SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[adb_quests]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[adb_quests](
	[id] [int] NOT NULL DEFAULT ((0)),
	[NextQuest] [int] NOT NULL DEFAULT ((0)),
	[Title] [varchar](255) NOT NULL DEFAULT ('No Quest Title'),
	[Zone] [int] NOT NULL DEFAULT ((0)),
	[Type] [int] NOT NULL DEFAULT ((0)),
	[Flags] [int] NOT NULL DEFAULT ((0)),
	[Level_Start] [tinyint] NOT NULL DEFAULT ((0)),
	[Level_Normal] [tinyint] NOT NULL DEFAULT ((60)),
	[Required_Quest] [int] NOT NULL DEFAULT ((0)),
	[Required_Race] [int] NOT NULL DEFAULT ((0)),
	[Required_Class] [int] NOT NULL DEFAULT ((0)),
	[Required_TradeSkill] [int] NOT NULL DEFAULT ((0)),
	[Required_Reputation1] [int] NOT NULL DEFAULT ((0)),
	[Required_Reputation1_Faction] [int] NOT NULL DEFAULT ((0)),
	[Required_Reputation2] [int] NOT NULL DEFAULT ((0)),
	[Required_Reputation2_Faction] [int] NOT NULL DEFAULT ((0)),
	[NPC_Start] [int] NOT NULL DEFAULT ((0)),
	[NPC_End] [int] NOT NULL DEFAULT ((0)),
	[Text_Objectives] [text] NOT NULL,
	[Text_Description] [text] NOT NULL,
	[Text_Incomplete] [text] NOT NULL,
	[Text_PreComplete] [text] NOT NULL,
	[Text_Complete] [text] NOT NULL,
	[QuestScript] [varchar](255) NOT NULL,
	[Reward_XP] [int] NOT NULL DEFAULT ((0)),
	[Reward_Gold] [int] NOT NULL DEFAULT ((0)),
	[Reward_Spell] [int] NOT NULL DEFAULT ((0)),
	[Reward_Reputation1] [int] NOT NULL DEFAULT ((0)),
	[Reward_Reputation1_Faction] [int] NOT NULL DEFAULT ((0)),
	[Reward_Reputation2] [int] NOT NULL DEFAULT ((0)),
	[Reward_Reputation2_Faction] [int] NOT NULL DEFAULT ((0)),
	[Reward_Item1] [int] NOT NULL DEFAULT ((0)),
	[Reward_Item1_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Reward_Item2] [int] NOT NULL DEFAULT ((0)),
	[Reward_Item2_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Reward_Item3] [int] NOT NULL DEFAULT ((0)),
	[Reward_Item3_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Reward_Item4] [int] NOT NULL DEFAULT ((0)),
	[Reward_Item4_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Reward_Item5] [int] NOT NULL DEFAULT ((0)),
	[Reward_Item5_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Reward_Item6] [int] NOT NULL DEFAULT ((0)),
	[Reward_Item6_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Reward_StaticItem1] [int] NOT NULL DEFAULT ((0)),
	[Reward_StaticItem1_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Reward_StaticItem2] [int] NOT NULL DEFAULT ((0)),
	[Reward_StaticItem2_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Reward_StaticItem3] [int] NOT NULL DEFAULT ((0)),
	[Reward_StaticItem3_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Reward_StaticItem4] [int] NOT NULL DEFAULT ((0)),
	[Reward_StaticItem4_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Objective_Kill1] [int] NOT NULL DEFAULT ((0)),
	[Objective_Kill1_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Objective_Kill2] [int] NOT NULL DEFAULT ((0)),
	[Objective_Kill2_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Objective_Kill3] [int] NOT NULL DEFAULT ((0)),
	[Objective_Kill3_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Objective_Kill4] [int] NOT NULL DEFAULT ((0)),
	[Objective_Kill4_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Objective_Item1] [int] NOT NULL DEFAULT ((0)),
	[Objective_Item1_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Objective_Item2] [int] NOT NULL DEFAULT ((0)),
	[Objective_Item2_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Objective_Item3] [int] NOT NULL DEFAULT ((0)),
	[Objective_Item3_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Objective_Item4] [int] NOT NULL DEFAULT ((0)),
	[Objective_Item4_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Objective_Deliver1] [int] NOT NULL DEFAULT ((0)),
	[Objective_Deliver1_Count] [tinyint] NOT NULL DEFAULT ((0)),
	[Objective_Gold] [int] NOT NULL DEFAULT ((0)),
	[Objective_Text1] [varchar](255) NOT NULL,
	[Objective_Text2] [varchar](255) NOT NULL,
	[Objective_Text3] [varchar](255) NOT NULL,
	[Objective_Text4] [varchar](255) NOT NULL,
 CONSTRAINT [PK_adb_quests] PRIMARY KEY CLUSTERED 
(
	[id] ASC
) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END