//////////////////////////////////////////////////////////
// DrNexus Amazing PlateArmors Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class AmazingPlateArmorsDrops
	{
		public static Loot[]AmazingPlateArmors = new Loot[]
		{
			new Loot( typeof( TruesilverBreastplate ), 45.504f )
				, new Loot( typeof( ValorousChestguard ), 48.741f )
				, new Loot( typeof( AlabasterBreastplate ), 25.947f )
				, new Loot( typeof( AlabasterPlateLeggings ), 35.366f )
				, new Loot( typeof( RevenantChestplate ), 40.462f )
				, new Loot( typeof( RevenantLeggings ), 46.036f )
				, new Loot( typeof( TemplarChestplate ), 25.956f )
				, new Loot( typeof( TemplarCrown ), 49.839f )
				, new Loot( typeof( TemplarLegplates ), 28.849f )
				, new Loot( typeof( TemplarPauldrons ), 49.472f )
				, new Loot( typeof( OverlordsChestplate ), 48.014f )
				, new Loot( typeof( HeavyLamellarChestpiece ), 37.118f )
				, new Loot( typeof( HeavyLamellarLeggings ), 39.801f )
				, new Loot( typeof( EmeraldBreastplate ), 18.979f )
				, new Loot( typeof( EmeraldHelm ), 44.056f )
				, new Loot( typeof( EmeraldLegplates ), 21.385f )
				, new Loot( typeof( EmeraldPauldrons ), 43.638f )
				, new Loot( typeof( ImbuedPlateArmor ), 10.657f )
				, new Loot( typeof( ImbuedPlateGreaves ), 44.253f )
				, new Loot( typeof( ImbuedPlateHelmet ), 41.246f )
				, new Loot( typeof( ImbuedPlateLeggings ), 13.318f )
				, new Loot( typeof( ImbuedPlatePauldrons ), 40.814f )
				, new Loot( typeof( CommandersBoots ), 37.401f )
				, new Loot( typeof( CommandersArmor ), 2.667999f )
				, new Loot( typeof( CommandersHelm ), 33.546f )
				, new Loot( typeof( CommandersLeggings ), 5.958998f )
				, new Loot( typeof( CommandersPauldrons ), 37.391f )
				, new Loot( typeof( HyperionGreaves ), 33.761f )
				, new Loot( typeof( HyperionHelm ), 29.656f )
				, new Loot( typeof( HyperionLegplates ), 1.146001f )
				, new Loot( typeof( HyperionPauldrons ), 29.124f )
				, new Loot( typeof( SilvershellLeggings ), 41.58f )
				, new Loot( typeof( CenturionLegplates ), 46.536f )
				, new Loot( typeof( AvenguardHelm ), 47.226f )
				, new Loot( typeof( WarriorsEmbrace ), 28.834f )
				, new Loot( typeof( WarforgedChestplate ), 31.722f )
				, new Loot( typeof( DarkIronPlate ), 2.857f )
				, new Loot( typeof( DarkIronShoulders ), 46.12f )
				, new Loot( typeof( SpiderfangCarapace ), 41.35f )
				, new Loot( typeof( CarapaceOfAnubshiah ), 22.019f )
				, new Loot( typeof( GolemSkullHelm ), 40.691f )
				, new Loot( typeof( ShalehuskBoots ), 31.336f )
				, new Loot( typeof( LavacrestLeggings ), 25.099f )
				, new Loot( typeof( BejeweledLegguards ), 38.273f )
				, new Loot( typeof( LegplatesOfTheEternalGuardian ), 17.717f )
				, new Loot( typeof( BoulderskinBreastplate ), 15.879f )
				, new Loot( typeof( ThoriumBoots ), 48.318f )
				, new Loot( typeof( ThoriumHelm ), 48.137f )
				, new Loot( typeof( ThoriumLeggings ), 13.118f )
				, new Loot( typeof( BattlechasersGreaves ), 42.968f )
				, new Loot( typeof( EbonsteelSpaulders ), 28.159f )
				, new Loot( typeof( DemonForgedBreastplate ), 16.797f )
				, new Loot( typeof( WhitesoulHelm ), 25.701f )
				, new Loot( typeof( BackusarianGauntlets ), 48.418f )
				, new Loot( typeof( BattlebornArmbraces ), 41.797f )
				, new Loot( typeof( SkullOfGyth ), 28.318f )
				, new Loot( typeof( HydralickArmor ), 28.291f )
				, new Loot( typeof( SapphironsScaleBoots ), 29.563f )
				, new Loot( typeof( StonegripGauntlets ), 47.866f )
				, new Loot( typeof( BrigamGirdle ), 41.791f )
				, new Loot( typeof( ReiverClaws ), 47.207f )
				, new Loot( typeof( SlamshotShoulders ), 28.976f )
				, new Loot( typeof( PlateOfTheShamanKing ), 4.575002f )
				, new Loot( typeof( RibsteelFootguards ), 19.652f )
				, new Loot( typeof( MasterCannoneerBoots ), 22.833f )
				, new Loot( typeof( SkulsColdEmbrace ), 9.119999f )
				, new Loot( typeof( WailingNightbanePauldrons ), 34.489f )
				, new Loot( typeof( HandcraftedMastersmithLeggings ), 8.627998f )
				, new Loot( typeof( HandcraftedMastersmithGirdle ), 40.063f )
				, new Loot( typeof( LavawalkerGreaves ), 34.254f )
				, new Loot( typeof( AcidEtchedPauldrons ), 35.948f )
				, new Loot( typeof( VigorsteelVambraces ), 44.974f )
				, new Loot( typeof( StoneformShoulders ), 18.163f )
				, new Loot( typeof( BoneclenchedGauntlets ), 47.195f )
				, new Loot( typeof( CorpselightGreaves ), 29.161f )
				, new Loot( typeof( StockadePauldrons ), 23.11f )
				, new Loot( typeof( DeathboneSabatons ), 36.412f )
				, new Loot( typeof( DeathboneLegguards ), 14.572f )
				, new Loot( typeof( SunscaleChestguard ), 42.642f )
				, new Loot( typeof( SunscaleLegplates ), 47.786f )
				, new Loot( typeof( VanguardBreastplate ), 18.977f )
				, new Loot( typeof( VanguardHeaddress ), 41.298f )
				, new Loot( typeof( VanguardLegplates ), 25.898f )
				, new Loot( typeof( VanguardPauldrons ), 47.384f )
				, new Loot( typeof( WarleadersShoulders ), 34.453f )
				, new Loot( typeof( JadeBreastplate ), 42.153f )
				, new Loot( typeof( LoftyBreastplate ), 29.842f )
				, new Loot( typeof( LoftyHelm ), 47.19f )
				, new Loot( typeof( LoftyLegguards ), 36.632f )
				, new Loot( typeof( HeroicArmor ), 7.257003f )
				, new Loot( typeof( HeroicGreaves ), 41.078f )
				, new Loot( typeof( HeroicSkullcap ), 40.572f )
				, new Loot( typeof( HeroicLegplates ), 16.487f )
				, new Loot( typeof( HeroicPauldrons ), 42.97f )
				, new Loot( typeof( BloodforgedChestpiece ), 48.491f )
				, new Loot( typeof( HighChiefsArmor ), 35.306f )
				, new Loot( typeof( HighChiefsLegguards ), 41.546f )
				, new Loot( typeof( GloriousBreastplate ), 10.994f )
				, new Loot( typeof( GloriousHeaddress ), 38.795f )
				, new Loot( typeof( GloriousLegplates ), 22.008f )
				, new Loot( typeof( GloriousShoulderPads ), 44.62f )
				, new Loot( typeof( GloriousSabatons ), 47.57f )
				, new Loot( typeof( ExaltedEpaulets ), 31.176f )
				, new Loot( typeof( LightforgeBoots ), 31.556f )
				, new Loot( typeof( LightforgeHelm ), 20.159f )
				, new Loot( typeof( LightforgeSpaulders ), 27.036f )
				, new Loot( typeof( HelmOfValor ), 18.95f )
				, new Loot( typeof( SpauldersOfValor ), 23.962f )
				, new Loot( typeof( BootsOfValor ), 27.32f )
				, new Loot( typeof( ElementalRockridgeLeggings ), 28.777f )
				, new Loot( typeof( HelmOfTheMountain ), 47.715f )
		};
	}
}
