namespace WorldServer
{
    using System;

    public enum EQUIPMENT_SLOT
    {
        EQUIPMENT_SLOT_BACK = 14,
        EQUIPMENT_SLOT_BODY = 3,
        EQUIPMENT_SLOT_CHEST = 4,
        EQUIPMENT_SLOT_END = 0x13,
        EQUIPMENT_SLOT_FEET = 7,
        EQUIPMENT_SLOT_FINGER1 = 10,
        EQUIPMENT_SLOT_FINGER2 = 11,
        EQUIPMENT_SLOT_HANDS = 9,
        EQUIPMENT_SLOT_HEAD = 0,
        EQUIPMENT_SLOT_LEGS = 6,
        EQUIPMENT_SLOT_MAINHAND = 15,
        EQUIPMENT_SLOT_NECK = 1,
        EQUIPMENT_SLOT_OFFHAND = 0x10,
        EQUIPMENT_SLOT_RANGED = 0x11,
        EQUIPMENT_SLOT_SHOULDERS = 2,
        EQUIPMENT_SLOT_START = 0,
        EQUIPMENT_SLOT_TABARD = 0x12,
        EQUIPMENT_SLOT_TRINKET1 = 12,
        EQUIPMENT_SLOT_TRINKET2 = 13,
        EQUIPMENT_SLOT_WAIST = 5,
        EQUIPMENT_SLOT_WRISTS = 8
    }
}

