namespace Server
{
    using System;

    public enum LightType
    {
        // Fields
        ArchedWindowEast = 0,
        ArchedWindowEastNoRay = 27,
        ArchedWindowSouth = 28,
        ArchedWindowSouthNoRay = 26,
        Circle150 = 2,
        Circle225 = 1,
        Circle300 = 29,
        DarkCircle300 = 36,
        DarkEast = 35,
        DarkNorthWest = 33,
        DarkSouth = 32,
        DarkSouthEast = 31,
        DarkSouthEast2 = 34,
        DecorationNorth = 16,
        DecorationNorthEast = 17,
        DecorationSouthWest = 20,
        DecorationWest = 19,
        DoorEast = 4,
        DoorOpenEast = 38,
        DoorOpenSouth = 37,
        DoorSouth = 3,
        EastBig = 7,
        EastSmall = 13,
        EastTiny = 18,
        Empty = 43,
        HoleEast = 48,
        HoleSouth = 47,
        Moongate = 49,
        NorthBig = 5,
        NorthBig2 = 53,
        NorthEastBig = 6,
        NorthEastSmall = 12,
        NorthSmall = 11,
        NorthWestBig = 30,
        NorthWestBig2 = 55,
        RectWindowEast = 25,
        RectWindowEastNoRay = 23,
        RectWindowSouth = 24,
        RectWindowSouthNoRay = 22,
        SkinnyWindowEast = 45,
        SkinnyWindowEastNoRay = 46,
        SkinnyWindowSouthNoRay = 44,
        SmallHoleEast = 52,
        SmallHoleSouth = 51,
        SouthBig = 10,
        SouthSmall = 15,
        SouthTiny = 21,
        SouthWestBig = 9,
        SquareWindowEast = 39,
        SquareWindowEastNoRay = 40,
        SquareWindowSouth = 41,
        SquareWindowSouthNoRay = 42,
        Strips = 50,
        WestBig = 8,
        WestBig2 = 54,
        WestSmall = 14
    }
}

