/*
MySQL Backup
Source Host:           localhost
Source Server Version: 4.1.8-nt
Source Database:       awowedb
Date:                  2006.07.29 13:59:07
*/

SET FOREIGN_KEY_CHECKS=0;
use awowedb;
#----------------------------
# Table structure for adb_quests
#----------------------------
CREATE TABLE `adb_quests` (
  `id` int(11) NOT NULL default '0',
  `NextQuest` int(11) NOT NULL default '0',
  `Title` varchar(255) NOT NULL default 'No Quest Title',
  `Zone` int(11) NOT NULL default '0',
  `Type` int(11) NOT NULL default '0',
  `Flags` int(11) NOT NULL default '0',
  `Level_Start` tinyint(3) unsigned NOT NULL default '0',
  `Level_Normal` tinyint(3) unsigned NOT NULL default '60',
  `Required_Quest` int(11) NOT NULL default '0',
  `Required_Race` int(11) NOT NULL default '0',
  `Required_Class` int(11) NOT NULL default '0',
  `Required_TradeSkill` int(11) NOT NULL default '0',
  `Required_Reputation1` int(11) NOT NULL default '0',
  `Required_Reputation1_Faction` int(11) NOT NULL default '0',
  `Required_Reputation2` int(11) NOT NULL default '0',
  `Required_Reputation2_Faction` int(11) NOT NULL default '0',
  `NPC_Start` int(11) NOT NULL default '0',
  `NPC_End` int(11) NOT NULL default '0',
  `Text_Objectives` text NOT NULL,
  `Text_Description` text NOT NULL,
  `Text_Incomplete` text NOT NULL,
  `Text_PreComplete` text NOT NULL,
  `Text_Complete` text NOT NULL,
  `QuestScript` varchar(255) NOT NULL default '',
  `Reward_XP` int(11) NOT NULL default '0',
  `Reward_Gold` int(11) NOT NULL default '0',
  `Reward_Spell` int(11) NOT NULL default '0',
  `Reward_Reputation1` int(11) NOT NULL default '0',
  `Reward_Reputation1_Faction` int(11) NOT NULL default '0',
  `Reward_Reputation2` int(11) NOT NULL default '0',
  `Reward_Reputation2_Faction` int(11) NOT NULL default '0',
  `Reward_Item1` int(11) NOT NULL default '0',
  `Reward_Item1_Count` tinyint(3) unsigned NOT NULL default '0',
  `Reward_Item2` int(11) NOT NULL default '0',
  `Reward_Item2_Count` tinyint(3) unsigned NOT NULL default '0',
  `Reward_Item3` int(11) NOT NULL default '0',
  `Reward_Item3_Count` tinyint(3) unsigned NOT NULL default '0',
  `Reward_Item4` int(11) NOT NULL default '0',
  `Reward_Item4_Count` tinyint(3) unsigned NOT NULL default '0',
  `Reward_Item5` int(11) NOT NULL default '0',
  `Reward_Item5_Count` tinyint(3) unsigned NOT NULL default '0',
  `Reward_Item6` int(11) NOT NULL default '0',
  `Reward_Item6_Count` tinyint(3) unsigned NOT NULL default '0',
  `Reward_StaticItem1` int(11) NOT NULL default '0',
  `Reward_StaticItem1_Count` tinyint(3) unsigned NOT NULL default '0',
  `Reward_StaticItem2` int(11) NOT NULL default '0',
  `Reward_StaticItem2_Count` tinyint(3) unsigned NOT NULL default '0',
  `Reward_StaticItem3` int(11) NOT NULL default '0',
  `Reward_StaticItem3_Count` tinyint(3) unsigned NOT NULL default '0',
  `Reward_StaticItem4` int(11) NOT NULL default '0',
  `Reward_StaticItem4_Count` tinyint(3) unsigned NOT NULL default '0',
  `Objective_Kill1` int(11) NOT NULL default '0',
  `Objective_Kill1_Count` tinyint(3) unsigned NOT NULL default '0',
  `Objective_Kill2` int(11) NOT NULL default '0',
  `Objective_Kill2_Count` tinyint(3) unsigned NOT NULL default '0',
  `Objective_Kill3` int(11) NOT NULL default '0',
  `Objective_Kill3_Count` tinyint(3) unsigned NOT NULL default '0',
  `Objective_Kill4` int(11) NOT NULL default '0',
  `Objective_Kill4_Count` tinyint(3) unsigned NOT NULL default '0',
  `Objective_Item1` int(11) NOT NULL default '0',
  `Objective_Item1_Count` tinyint(3) unsigned NOT NULL default '0',
  `Objective_Item2` int(11) NOT NULL default '0',
  `Objective_Item2_Count` tinyint(3) unsigned NOT NULL default '0',
  `Objective_Item3` int(11) NOT NULL default '0',
  `Objective_Item3_Count` tinyint(3) unsigned NOT NULL default '0',
  `Objective_Item4` int(11) NOT NULL default '0',
  `Objective_Item4_Count` tinyint(3) unsigned NOT NULL default '0',
  `Objective_Deliver1` int(11) NOT NULL default '0',
  `Objective_Deliver1_Count` tinyint(3) unsigned NOT NULL default '0',
  `Objective_Gold` int(11) NOT NULL default '0',
  `Objective_Text1` varchar(255) NOT NULL default '',
  `Objective_Text2` varchar(255) NOT NULL default '',
  `Objective_Text3` varchar(255) NOT NULL default '',
  `Objective_Text4` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
