using System;

namespace eWoW
{
	/// <summary>
	/// Const
	/// </summary>
	public class Const
	{
		public delegate void LogMessageHandler				(string message);
		//public event LogMessageHandler						LogMessageEvent;

		public static Random rand = new Random();

		static int  tick = 0;
		static int  tickLast = Environment.TickCount;
		public static int Tick 
		{
			get 
			{
				return tick;
			}
		}

		public static void SyncTick()
		{
			int t = Environment.TickCount;
			if(tickLast > t)
                tickLast = t;
			tick += Environment.TickCount - tickLast;
			tickLast = t;
		}

		public static uint GetTimeStamp()
		{
			DateTime n = DateTime.Now;

			return (uint)( n.Minute | (n.Hour<<6) | ((int)n.DayOfWeek << 11) | ((n.Day-1)<<14) | ((n.Year-2000)<<18) | ((n.Month-1)<<20) );
		}

		public static void Log(string from, string fmt, params object[] obs)
		{
			string str = String.Format(fmt, obs);
			Console.WriteLine("[{0} {1}] {2}", DateTime.Now.ToString("MM/dd hh:mm:ss.fff"), from, str);
		}

		public const ushort	UNIT_BLOCKS=16;
		public const ushort PLAYER_BLOCKS=42;
		public const int    UPDATE_DISTANCE=320;
		public const int    GUID_BITS=24;
		public const uint	SpawnPointEntry=99999999;
	}

	enum FriendsResult 
	{
		DB_ERROR             = 0x0,
		LIST_FULL            = 0x1,
		ONLINE               = 0x2,
		OFFLINE              = 0x3,
		NOT_FOUND            = 0x4,
		REMOVED              = 0x5,
		ADDED_ONLINE         = 0x6,
		ADDED_OFFLINE        = 0x7,
		ALREADY              = 0x8,
		SELF                 = 0x9,
		ENEMY                = 0xA,
		IGNORE_FULL          = 0xB, 
		IGNORE_SELF          = 0xC,
		IGNORE_NOT_FOUND     = 0xD,
		IGNORE_ALREADY       = 0xE,
		IGNORE_ADDED         = 0xF,
		IGNORE_REMOVED       = 0x10,
	};


	public enum TYPE : ushort
	{
		OBJECT			= 1,
		ITEM			= 2,
		CONTAINER		= 4,
		UNIT			= 8,
		PLAYER			= 16,
		GAMEOBJECT		= 32,
		DYNAMICOBJECT	= 64,
		CORPSE			= 128,
		AIGROUP			= 256,
		AREATRIGGER		= 512,
	};


	public enum ObjectTypesUpdateFields 
	{
		NONE				= 0,
		PLAYER				= 1,
		CREATURE			= 2, 
		SPAWNPOINT			= 3,
		ZONE				= 4,
		ACCOUNT				= 5,
		ITEM				= 6,
		ITEMTEMPLATE		= 7,
		CREATURETEMPLATE	= 8,
		CONTAINER			= 9,
		LOOTTABLE			= 10,
		PATHGROUP			= 11,
		GUILD				= 12,
		GAMEOBJECT			= 13,
		DYNAMICOBJECT		= 14,
		PARTY				= 15,
		TYPES				= 16,
	};

	public enum RACE
	{
		HUMAN				= 1,
		ORC					= 2,
		DWARF				= 3,
		NIGHT_ELF			= 4,
		UNDEAD				= 5,
		TAUREN				= 6,
		GNOME				= 7,
		TROLL				= 8,
		GOBLIN				= 9,
	}

	public enum CLASS
	{
		WARRIOR			= 1,
		PALADIN			= 2,
		HUNTER			= 3,
		ROGUE			= 4,
		PRIEST			= 5,
		SHAMAN			= 7,
		MAGE			= 8,
		WARLOCK			= 9,
		DRUID			= 0x0B,
	}

	public enum DamageTypeUpdateFields 
	{
		DMGTYPE_WEAPON				= 1,
		DMGTYPE_SPELL				= 2,
	};


	public enum GuildRankUpdateFields 
	{
		GM 				= 0,
		OFFICER 			= 1,
		VETERAN 			= 2,
		MEMBER 			= 3,
		INITIATE 			= 4,
	};

	public enum PartyRankUpdateFields 
	{
		PARTYRANK_LEADER 			= 0,
		PARTYRANK_MEMBER 			= 1,
		PARTYRANK_INVITE            = 1,
	};

	public enum SlotID : byte
	{
		HEAD			= 0,
		NECK			= 1,
		SHOULDERS		= 2,
		SHIRT			= 3,
		CHEST			= 4,
		WAIST			= 5,
		LEGS			= 6,
		FEET			= 7,
		WRISTS			= 8,
		HANDS			= 9,
		FINGERL		= 10,
		FINGERR		= 11,
		TRINKETL		= 12,
		TRINKETR		= 13,
		BACK			= 14,
		MAINHAND		= 15,
		OFFHAND		= 16,
		RANGED			= 17,
		TABARD			= 18,
		BAG1			= 19,
		BAG2			= 20,
		BAG3			= 21,
		BAG4			= 22,
		INBACKPACK		= 23,
		BANK			= 39,
		BANKBAGS		= 63,
		CHARACTER       = 255,
	};


	public enum WORN 
	{
		NONE			= 0,
		HEAD			= 1,
		NECK			= 2,
		SHOULDER		= 3,
		SHIRT			= 4,
		CHEST			= 5,
		WAIST			= 6,
		PANTS			= 7,
		BOOTS			= 8,
		BRACERS			= 9,
		HAND			= 10,
		FINGER			= 11,
		TRINKET			= 12,
		H1				= 13,
		SHIELD			= 14,
		RANGED			= 15,
		BACK			= 16,
		H2				= 17,
		JUNK			= 18,
		BAG				= 18,
		TABARD			= 19,
		ROBE			= 20,
		MAINHAND		= 21,
		OFFHAND			= 22,
		HELD			= 23,
		AMMO			= 24,
		THROWN			= 25,
		RANGEDRIGHT 	= 26,
		NUM_TYPES  		= 27,
	};

	public enum ItemType
	{
		CONSUMABLE		= 0x00,
		CONTAINER		= 0x01,
		WEAPON			= 0x02,
		ARMOR			= 0x04,
		ARMOUR			= 0x04,
		REAGENT			= 0x05,
		PROJECTILE		= 0x06,
		TRADEGOODS		= 0x07,
		BOOK			= 0x09,
		QUIVER			= 0x0B,
		QUEST			= 0x0C,
		KEY				= 0x0D,
		PERMANENT		= 0x0E,
		JUNK			= 0x0F,
		NUM_ITEMTYPES	= 0x10,
	};

	public enum WeaponSubtypeUpdateFields 
	{

		WEAPONSUBTYPE_ONEHANDAXE	= 0,
		WEAPONSUBTYPE_TWOHANDAXE	= 1,
		WEAPONSUBTYPE_BOW			= 2,
		WEAPONSUBTYPE_GUN			= 3,
		WEAPONSUBTYPE_ONEHANDBLUNT	= 4,
		WEAPONSUBTYPE_TWOHANDBLUNT	= 5,
		WEAPONSUBTYPE_POLEARM		= 6,
		WEAPONSUBTYPE_ONEHANDSWORD	= 7,
		WEAPONSUBTYPE_TWOHANDSWORD	= 8,
		WEAPONSUBTYPE_STAFF			= 10,
		WEAPONSUBTYPE_ONEHANDEXOTIC = 11,
		WEAPONSUBTYPE_TWOHANDEXOTIC = 12,
		WEAPONSUBTYPE_UNARMED		= 13,
		WEAPONSUBTYPE_GENERIC		= 14,
		WEAPONSUBTYPE_DAGGER		= 15,
		WEAPONSUBTYPE_THROWN		= 16,
		WEAPONSUBTYPE_SPEAR			= 17,
		WEAPONSUBTYPE_CROSSBOW		= 18,
		WEAPONSUBTYPE_WAND			= 19,
	};

	public enum ArmourSubtypeUpdateFields 
	{

		ARMOURSUBTYPE_GENERIC,
		ARMOURSUBTYPE_CLOTH,
		ARMOURSUBTYPE_LEATHER,
		ARMOURSUBTYPE_MAIL,
		ARMOURSUBTYPE_PLATE,
		ARMOURSUBTYPE_BUCKLER,
		ARMOURSUBTYPE_SHIELD,
	};

	public enum QuiverSubtypeUpdateFields 
	{

		QUIVERSUBTYPE_OBSOLETE,
		QUIVERSUBTYPE_BOLT,
		QUIVERSUBTYPE_ARROW,
		QUIVERSUBTYPE_AMMO,
	};

	public enum ProjectileSubtypeUpdateFields 
	{

		PROJECTILESUBTYPE_WAND,
		PROJECTILESUBTYPE_BOLT,
		PROJECTILESUBTYPE_ARROW,
		PROJECTILESUBTYPE_BULLET,
		PROJECTILESUBTYPE_THROWN,
	};


	public enum RegenerationUpdateFields 
	{

		PLAYER_REGEN_HPS		= 5,
		PLAYER_REGEN_MANA		= 5,
		CREATURE_REGEN_HPS		= 10,
		CREATURE_REGEN_MANA		= 10,
		CREATURE_REGEN_ENERGY   = 10,
	};

	public enum PlayerStatus
	{
		NORMAL	= 0x00,
		AFK		= 0x02,
		DEAD    = 0x10,
		REST    = 0x20
	};

	public enum NPCType
	{
		NONE			= 0x00,
		MERCHANT		= 0x01, 
		QUESTGIVER		= 0x02, 
		TAXI			= 0x04, 
		TRAINER			= 0x08, 
		BINDER			= 0x20, 
		BANKER			= 0x40, 
		PETITION		= 0x80,   
		TABARD			= 0x100,
	};

	public enum SheatheType
	{
		NONE,
		MAINHAND,
		OFFHAND,
		LARGEWEAPONLEFT,
		LARGEWEAPONRIGHT,
		HIPWEAPONLEFT,
		HIPWEAPONRIGHT,
		SHIELD,
		NUM_TYPES,
	};

	public enum UnitStandState
	{
		STANDING			= 0,
		SITTING			    = 1,
		SITTINGCHAIR		= 2,
		SLEEPING			= 3,
		SITTINGCHAIRLOW	    = 4,
		SITTINGCHAIRMEDIUM  = 5,
		SITTINGCHAIRHIGH	= 6,
		DEAD				= 7,
		KNEEL				= 8,
	};

	public enum CHAT : byte
	{
		SAY			            = 0x0,
		PARTY			        = 0x1,
		RAID                    = 0x2,
		GUILD			        = 0x3,
		OFFICER		            = 0x4,
		YELL                    = 0x5,
		WHISPER                 = 0x6,
		EMOTE			        = 0x7,
		TEXT_EMOTE		        = 0x8,
		SYSTEM			        = 0xa,
		MONSTER_SAY	            = 0xb,
		MONSTER_YELL	        = 0xc,
		MONSTER_EMOTE	        = 0xd,
		CHANNEL		            = 0xe,
		CHANNEL_JOIN	        = 0xf,
		CHANNEL_LEAVE	        = 0x10,
		CHANNEL_LIST	        = 0x11,
		CHANNEL_NOTICE          = 0x12,
		CHANNEL_NOTICE_USER     = 0x13,
		AFK		                = 0x14,
		DND		                = 0x15,
		COMBAT_LOG              = 0x16,
		IGNORED	                = 0x17,
		SKILL		            = 0x18,
		LOOT		            = 0x19,
	};

	public enum UnitMove : uint 
	{
		FORWARD				= 1,
		BACKWARD			= 2,
		STRAFE_LEFT			= 4,
		STRAFE_RIGHT		= 8,
		LEFT				= 0x10,
		RIGHT				= 0x20,
		PITCH_UP			=0x40,
		PITCH_DOWN			= 0x80,
		WALK				= 0x100,
		TIME_VALID			= 0x200,
		IMMOBILIZED			= 0x400,
		DONTCOLLIDE			= 0x800,
		REDIRECTED			= 0x1000,
		ROOTED				= 0x2000,
		FALLING				= 0x4000,
		FALLEN_FAR			= 0x8000,
		PENDING_STOP		= 0x10000,
		PENDING_UNSTRAFE	= 0x20000,
		PENDING_FALL		= 0x40000,
		PENDING_FORWARD		= 0x80000,
		PENDING_BACKWARD	= 0x100000,
		PENDING_STR_LEFT	= 0x200000,
		PENDING_STR_RGHT	= 0x400000,
		PEND_MOVE_MASK		= 0x180000,
		PEND_STRAFE_MASK	= 0x600000,
		PENDING_MASK		= 0x7f0000,
		MOVED				= 0x800000,
		SLIDING				= 0x1000000,
		SWIMMING			= 0x2000000,
		SPLINE_MOVER		= 0x4000000,
		SPEED_DIRTY			= 0x8000000,
		HALTED				= 0x10000000,
		NUDGE				= 0x20000000,
		FALL_MASK			= 0x100c000,
		LOCAL				= 0x80400000,
		MOVE_MASK			= 0x30000,
		TURN_MASK			= 0x300000,
		PITCH_MASK			= 0xc00000,
		STRAFE_MASK			= 0xc0000,
		MOTION_MASK			= 0xff0000,
		STOPPED_MASK		= 0x3100f,
	};

	public enum TradeStatusUpdateFields 
	{
		TRADE_STATUS_PLAYER_BUSY         =0x0,
		TRADE_STATUS_PROPOSED            =0x1,
		TRADE_STATUS_INITIATED           =0x2,
		TRADE_STATUS_CANCELLED           =0x3,
		TRADE_STATUS_ACCEPTED            =0x4,
		TRADE_STATUS_ALREADY_TRADING     =0x5,
		TRADE_STATUS_PLAYER_NOT_FOUND    =0x6,
		TRADE_STATUS_STATE_CHANGED       =0x7,
		TRADE_STATUS_COMPLETE            =0x8,
		TRADE_STATUS_UNACCEPTED          =0x9,
		TRADE_STATUS_TOO_FAR_AWAY        =0xA,
		TRADE_STATUS_WRONG_FACTION       =0xB,
		TRADE_STATUS_FAILED              =0xC,
		TRADE_STATUS_DEAD                =0xD,
		TRADE_STATUS_PETITION            =0xE,
		TRADE_STATUS_PLAYER_IGNORED      =0xF,
	};

	public enum CraftLevelUpdateFields 
	{
		CRAFT_NONE                       =0x0,
		CRAFT_OPTIMAL                    =0x1,
		CRAFT_MEDIUM                     =0x2,
		CRAFT_EASY                       =0x3,
		CRAFT_TRIVIAL                    =0x4,

	};

	public enum SpellTypeUpdateFields 
	{
		PLAYER_SPELL                     =0x0,
		PLAYER_ABILITY                   =0x1,
		PET_SPELL                        =0x2,
	};

	public enum TrainerServiceTypeUpdateFields 
	{
		TRAINER_SERVICE_AVAILABLE        =0x0,
		TRAINER_SERVICE_UNAVAILABLE      =0x1,
		TRAINER_SERVICE_USED             =0x2,
		TRAINER_SERVICE_NOT_SHOWN        =0x3,
		TRAINER_SERVICE_NEVER            =0x4,
		TRAINER_SERVICE_NO_PET           =0x5,
	};

	public enum TrainerTypeUpdateFields 
	{
		TRAINER_TYPE_GENERAL             =0x0,
		TRAINER_TYPE_TALENTS             =0x1,
		TRAINER_TYPE_TRADESKILLS         =0x2,
		TRAINER_TYPE_PET                 =0x3,
	};

	public enum SpellShadowUpdateFields 
	{
		SPELL_GOOD                       =0x0,
		SPELL_BAD                        =0x1,
		SPELL_NONE						 =0x3,
	};

	public enum ScriptEventUpdateFields 
	{
		UNIT_COMBAT               =0xB2,
		UNIT_SPELLMISS            =0xB3,
		UNIT_NAME_UPDATE          =0xB4,
		UNIT_PORTRAIT_UPDATE      =0xB5,
		UNIT_MODEL_CHANGED        =0xB6,
		UNIT_INVENTORY_CHANGED    =0xB7,
		ITEM_LOCK_CHANGED         =0xB8,
		PLAYER_XP_UPDATE          =0xB9,
		PLAYER_REGEN_DISABLED     =0xBA,
		PLAYER_REGEN_ENABLED      =0xBB,
		PLAYER_AURAS_CHANGED      =0xBC,
		PLAYER_ENTER_COMBAT       =0xBD,
		PLAYER_LEAVE_COMBAT       =0xBE,
		PLAYER_TARGET_CHANGED     =0xBF,
		PLAYER_PET_CHANGED        =0xC0,
		PLAYER_CONTROL_LOST       =0xC1,
		PLAYER_CONTROL_GAINED     =0xC2,
		PLAYER_LEVEL_UP           =0xC3,
		ZONE_CHANGED              =0xC4,
		MINIMAP_ZONE_CHANGED      =0xC5,
		MINIMAP_UPDATE_ZOOM       =0xC6,
		SCREENSHOT_SUCCEEDED      =0xC7,
		SCREENSHOT_FAILED         =0xC8,
		ACTIONBAR_SHOWGRID        =0xC9,
		ACTIONBAR_HIDEGRID        =0xCA,
		ACTIONBAR_PAGE_CHANGED    =0xCB,
		ACTIONBAR_SLOT_CHANGED    =0xCC,
		ACTIONBAR_UPDATE_STATE    =0xCD,
		ACTIONBAR_UPDATE_USABLE   =0xCE,
		ACTIONBAR_UPDATE_COOLDOWN =0xCF,
		UPDATE_BONUS_ACTIONBAR    =0xD0,
		PARTY_MEMBERS_CHANGED     =0xD1,
		PARTY_LEADER_CHANGED      =0xD2,
		PARTY_MEMBER_ENABLE       =0xD3,
		PARTY_MEMBER_DISABLE      =0xD4,
		PARTY_LOOT_METHOD_CHANGED =0xD5,
		SYSMSG                    =0xD6,
		UI_ERROR_MESSAGE          =0xD7,
		UI_INFO_MESSAGE           =0xD8,
		CHAT_MSG_SAY              =0xD9,
		CHAT_MSG_PARTY            =0xDA,
		CHAT_MSG_GUILD            =0xDB,
		CHAT_MSG_OFFICER          =0xDC,
		CHAT_MSG_YELL             =0xDD,
		CHAT_MSG_WHISPER          =0xDE,
		CHAT_MSG_WHISPER_INFORM   =0xDF,
		CHAT_MSG_EMOTE            =0xE0,
		CHAT_MSG_TEXT_EMOTE       =0xE1,
		CHAT_MSG_SYSTEM           =0xE2,
		CHAT_MSG_MONSTER_SAY      =0xE3,
		CHAT_MSG_MONSTER_YELL     =0xE4,
		CHAT_MSG_MONSTER_EMOTE    =0xE5,
		CHAT_MSG_CHANNEL          =0xE6,
		CHAT_MSG_CHANNEL_JOIN     =0xE7,
		CHAT_MSG_CHANNEL_LEAVE    =0xE8,
		CHAT_MSG_CHANNEL_LIST     =0xE9,
		CHAT_MSG_CHANNEL_NOTICE   =0xEA,
		CHAT_MSG_CHANNEL_NOTICE_USER =0xEB,
		CHAT_MSG_AFK              =0xEC,
		CHAT_MSG_DND              =0xED,
		CHAT_MSG_COMBAT_LOG       =0xEE,
		CHAT_MSG_IGNORED          =0xEF,
		CHAT_MSG_SKILL            =0xF0,
		CHAT_MSG_LOOT             =0xF1,
		LANGUAGE_LIST_CHANGED     =0xF2,
		TIME_PLAYED_MSG           =0xF3,
		SPELLS_CHANGED            =0xF4,
		CURRENT_SPELL_CAST_CHANGED =0xF5,
		SPELL_UPDATE_COOLDOWN     =0xF6,
		CHARACTER_POINTS_CHANGED  =0xF7,
		SKILL_LINES_CHANGED       =0xF8,
		ITEM_PUSH                 =0xF9,
		LOOT_OPENED               =0xFA,
		LOOT_SLOT_CLEARED         =0xFB,
		LOOT_CLOSED               =0xFC,
		PLAYER_ENTERING_WORLD     =0xFD,
		PLAYER_LEAVING_WORLD      =0xFE,
		PLAYER_ALIVE              =0xFF,
		PLAYER_DEAD               =0x100,
		PLAYER_CAMPING            =0x101,
		PLAYER_QUITING            =0x102,
		PLAYER_STAND              =0x103,
		PLAYER_SIT                =0x104,
		RESURRECT_REQUEST         =0x105,
		PARTY_INVITE_REQUEST      =0x106,
		PARTY_INVITE_CANCEL       =0x107,
		GUILD_INVITE_REQUEST      =0x108,
		GUILD_INVITE_CANCEL       =0x109,
		TRADE_REQUEST             =0x10A,
		TRADE_REQUEST_CANCEL      =0x10B,
		LOOT_BIND_CONFIRM         =0x10C,
		EQUIP_BIND_CONFIRM        =0x10D,
		AUTOEQUIP_BIND_CONFIRM    =0x10E,
		DELETE_ITEM_CONFIRM       =0x10F,
		CURSOR_UPDATE             =0x110,
		ITEM_TEXT_BEGIN           =0x111,
		ITEM_TEXT_TRANSLATION     =0x112,
		ITEM_TEXT_READY           =0x113,
		ITEM_TEXT_CLOSED          =0x114,
		QUEST_GREETING            =0x115,
		QUEST_DETAIL              =0x116,
		QUEST_PROGRESS            =0x117,
		QUEST_COMPLETE            =0x118,
		QUEST_FINISHED            =0x119,
		QUEST_ITEM_UPDATE         =0x11A,
		TAXIMAP_OPENED            =0x11B,
		TAXIMAP_CLOSED            =0x11C,
		QUEST_LOG_UPDATE          =0x11D,
		TRAINER_SHOW              =0x11E,
		TRAINER_UPDATE            =0x11F,
		TRAINER_CLOSED            =0x120,
		CVAR_UPDATE               =0x121,
		TRADE_SKILL_SHOW          =0x122,
		TRADE_SKILL_UPDATE        =0x123,
		TRADE_SKILL_CLOSE         =0x124,
		MERCHANT_SHOW             =0x125,
		MERCHANT_UPDATE           =0x126,
		MERCHANT_CLOSED           =0x127,
		TRADE_SHOW                =0x128,
		TRADE_CLOSED              =0x129,
		TRADE_UPDATE              =0x12A,
		TRADE_ACCEPT_UPDATE       =0x12B,
		TRADE_TARGET_ITEM_CHANGED =0x12C,
		TRADE_PLAYER_ITEM_CHANGED =0x12D,
		TRADE_MONEY_CHANGED       =0x12E,
		PLAYER_TRADE_MONEY        =0x12F,
		BAG_OPEN                  =0x130,
		BAG_UPDATE                =0x131,
		BAG_CLOSED                =0x132,
		BAG_UPDATE_COOLDOWN       =0x133,
		SOULSTONE_RECEIVED        =0x134,
		LOCALPLAYER_PET_RENAMED   =0x135,
		UNIT_ATTACK               =0x136,
		UNIT_DEFENSE              =0x137,
		PET_ATTACK_START          =0x138,
		PET_ATTACK_STOP           =0x139,
		UPDATE_MOUSEOVER_UNIT     =0x13A,
		SPELLCAST_START           =0x13B,
		SPELLCAST_STOP            =0x13C,
		SPELLCAST_FAILED          =0x13D,
		SPELLCAST_INTERRUPTED     =0x13E,
		SPELLCAST_DELAYED         =0x13F,
		SPELLCAST_CHANNEL_START   =0x140,
		SPELLCAST_CHANNEL_UPDATE  =0x141,
		CLEAR_TOOLTIP             =0x142,
		TOOLTIP_ADD_MONEY         =0x143,
		PLAYER_GUILD_UPDATE       =0x144,
		QUEST_ACCEPT_CONFIRM      =0x145,
		PLAYERBANKSLOTS_CHANGED   =0x146,
		BANKFRAME_OPENED          =0x147,
		BANKFRAME_CLOSED          =0x148,
		PLAYERBANKBAGSLOTS_CHANGED =0x149,
		FRIENDLIST_UPDATE         =0x14A,
		IGNORELIST_UPDATE         =0x14B,
		PLAYER_LOGOUT_FAILED      =0x14C,
		PET_BAR_UPDATE            =0x14D,
		PET_BAR_UPDATE_COOLDOWN   =0x14E,
		PET_BAR_SHOWGRID          =0x14F,
		PET_BAR_HIDEGRID          =0x150,
		MINIMAP_PING              =0x151,
		CHAT_MSG_COMBAT_LOG_ENEMY =0x152,
		CHAT_MSG_COMBAT_LOG_SELF  =0x153,
		CHAT_MSG_COMBAT_LOG_PARTY =0x154,
		CHAT_MSG_COMBAT_LOG_ERROR =0x155,
		CHAT_MSG_COMBAT_LOG_MISC_INFO =0x156,
		CRAFT_SHOW                =0x157,
		CRAFT_UPDATE              =0x158,
		CRAFT_CLOSE               =0x159,
		MIRROR_TIMER_START        =0x15A,
		MIRROR_TIMER_PAUSE        =0x15B,
		MIRROR_TIMER_STOP         =0x15C,
		WORLD_MAP_UPDATE          =0x15D,
		AUTOFOLLOW_BEGIN          =0x15E,
		AUTOFOLLOW_END            =0x15F,
		CINEMATIC_FADE            =0x160,
		CINEMATIC_START           =0x161,
		CINEMATIC_STOP            =0x162,
		UPDATE_FACTION            =0x163,
		CLOSE_WORLD_MAP           =0x164,
		OPEN_TABARD_FRAME         =0x165,
		CLOSE_TABARD_FRAME        =0x166,
		TABARD_CANSAVE_CHANGED    =0x167,
		SHOW_COMPARE_TOOLTIP      =0x168,
		GUILD_REGISTRAR_SHOW      =0x169,
		GUILD_REGISTRAR_CLOSED    =0x16A,
		DUEL_REQUESTED            =0x16B,
		DUEL_OUTOFBOUNDS          =0x16C,
		DUEL_INBOUNDS             =0x16D,
		DUEL_FINISHED             =0x16E,
		TUTORIAL_TRIGGER          =0x16F,
		PET_DISMISS_START         =0x170,
		UPDATE_BINDINGS           =0x171,
		UPDATE_SHAPESHIFT_FORMS   =0x172,
		WHO_LIST_UPDATE           =0x173,
		UPDATE_LFG                =0x174,
		PETITION_SHOW             =0x175,
		PETITION_CLOSED           =0x176,
	};

	public enum SpellTargetTypeUpdateFields 
	{
		CASTER               =0x0,
		UNIT                 =0x1,
		FRIENDLY             =0x2,
		ENEMY                =0x3,
		PARTY_MEMBER         =0x4,
		ITEM                 =0x5,
		LOCATION             =0x6,
		OBJECT               =0x7,
		PET                  =0x8,
		MAINHAND_ITEM        =0x9,
		OFFHAND_ITEM         =0xA,
		PARTY                =0xB,
		MULTIPLE_UNITS       =0xC,
		MULTIPLE_ENEMIES     =0xD,
		MULTIPLE_PARTY_MEMBERS =0xE,
		MASTER               =0xF,
	};

	public enum UnitSummonTypeUpdateFields 
	{
		UNIT_SUMMON_PET                  =0x0,
		UNIT_SUMMON_MINION               =0x1,
		UNIT_SUMMON_CHARM                =0x2,
		UNIT_SUMMON_GUARDIAN             =0x3,
		UNIT_SUMMON_CREATION             =0x4,
	};

	public enum SRectGridUpdateFields 
	{
		SRECTGRID_NAMEPLATES             =0x0,
		SRECTGRID_WORLDTEXT              =0x1,
	};

	public enum AIGroupActionUpdateFields 
	{
		AI_GROUP_SPAWN                   =0x0,
		AI_GROUP_IDLE                    =0x1,
		AI_GROUP_MOVETO                  =0x2,
		AI_GROUP_TELEPORT                =0x3,
		AI_GROUP_WANDER                  =0x4,
		AI_GROUP_WANDER_SPAWNRELATIVE_OBSOLETE =0x5,
		AI_GROUP_WANDER_AREA             =0x6,
		AI_GROUP_FOLLOW_GUID             =0x7,
		AI_GROUP_FOLLOW_PATH             =0x8,
		AI_GROUP_PATROL_LINE             =0x9,
		AI_GROUP_PATROL_CIRCLE           =0xA,
		AI_GROUP_GUARD_GUID              =0xB,
		AI_GROUP_GUARD_AREA              =0xC,
		AI_GROUP_SET_FORMATION           =0xD,
		AI_GROUP_UNIT_CHANGE_MODE_OBSOLETE =0xE,
		AI_GROUP_UNIT_SAY                =0xF,
		AI_GROUP_UNIT_CAST               =0x10,
		AI_GROUP_UNIT_ACTIVATE_OBJECT    =0x11,
		AI_GROUP_GENERATE_EVENT          =0x12,
		AI_GROUP_DESPAWN                 =0x13,
		AI_GROUP_SET_RADIUS_OBSOLETE     =0x14,
		AI_GROUP_SET_FACTION_OBSOLETE    =0x15,
		AI_GROUP_UNIT_SET_FACING         =0x16,
		AI_GROUP_UNIT_FACE_GUID          =0x17,
		AI_GROUP_UNIT_EMOTE              =0x18,
		AI_GROUP_MOVETO_GUID             =0x19,
		AI_GROUP_ATTACK_GUID             =0x1A,
		AI_GROUP_UNIT_MOUNT              =0x1B,
		AI_GROUP_UNIT_DISMOUNT           =0x1C,
		AI_GROUP_BEASTMASTER_ON          =0x1D,
		AI_GROUP_BEASTMASTER_OFF         =0x1E,
		AI_GROUP_UNIT_MODE               =0x1F,
		AI_GROUP_UNIT_MODE_RESET         =0x20,
		AI_GROUP_UNIT_FACTION            =0x21,
		AI_GROUP_UNIT_FACTION_RESET      =0x22,
		AI_GROUP_UNIT_RADIUS             =0x23,
		AI_GROUP_UNIT_RADIUS_RESET       =0x24,
		AI_GROUP_QUEST_COMPLETE          =0x25,
		AI_GROUP_UNIT_QUESTGIVER         =0x26,
		AI_GROUP_UNIT_TRAINER            =0x27,
		AI_GROUP_SPLINE_PATH             =0x28,
		AI_GROUP_PLAYER_ACTION           =0x29,
		AI_GROUP_RETURN_HOME             =0x2A,
		AI_GROUP_UNIT_SAY_RANDOM         =0x2B,
		AI_GROUP_UNIT_YELL               =0x2C,
		AI_GROUP_UNIT_YELL_RANDOM        =0x2D,
		AI_GROUP_UNIT_SET_ITEM_MAINHAND  =0x2E,
		AI_GROUP_UNIT_RESET_ITEM_MAINHAND =0x2F,
		AI_GROUP_UNIT_CHAT_EMOTE         =0x30,
		AI_GROUP_UNIT_CHAT_EMOTE_RANDOM  =0x31,
		AI_GROUP_UNIT_GENERATE_EVENT     =0x32,
		AI_GROUP_VENDOR_IDLE_OBSOLETE    =0x33,
		AI_GROUP_QUEST_FAILED            =0x34,
		AI_GROUP_UNIT_TRIGGERS           =0x35,
		AI_GROUP_UNIT_TRIGGERS_RESET     =0x36,
		AI_GROUP_UNIT_LEAVE_COMBAT       =0x37,
		AI_GROUP_IDLE_COMBAT_START       =0x38,
		AI_GROUP_IDLE_COMBAT_STOP        =0x39,
		AI_GROUP_UNIT_IMMUNEPC           =0x3A,
		AI_GROUP_UNIT_IMMUNEPC_RESET     =0x3B,
		AI_GROUP_UNIT_IMMUNENPC          =0x3C,
		AI_GROUP_UNIT_IMMUNENPC_RESET    =0x3D,
		AI_GROUP_UNIT_UNKILLABLE         =0x3E,
		AI_GROUP_UNIT_UNKILLABLE_RESET   =0x3F,
		AI_GROUP_UNIT_SPELLS             =0x40,
		AI_GROUP_UNIT_SPELLS_RESET       =0x41,
		AI_GROUP_REUSEME                 =0x42,
		AI_GROUP_UNIT_SEND_LOCAL_EVENT   =0x43,
		AI_GROUP_UNIT_BROADCAST_LOCAL_EVENT= 0x44,
		AI_GROUP_UNIT_FLEE               =0x45,
		AI_GROUP_UNIT_RETREAT            =0x46,
		AI_GROUP_OBJECT_CHAT_EMOTE       =0x47,
		AI_GROUP_OBJECT_CHAT_EMOTE_RANDOM =0x48,
		AI_GROUP_AVOID                   =0x49,
		AI_GROUP_AVOID_GUID              =0x4A,
		AI_GROUP_OBJECT_ACTIVATE         =0x4B,
		AI_GROUP_UNIT_ACTIVATE_OBJECTS   =0x4C,
		AI_GROUP_UNIT_STRINGID           =0x4D,
		AI_GROUP_UNIT_STRINGID_RESET     =0x4E,
		AI_GROUP_PERIODIC_EVENT          =0x4F,
		AI_GROUP_UNIT_SET_ITEM_OFFHAND   =0x50,
		AI_GROUP_UNIT_RESET_ITEM_OFFHAND =0x51,
		AI_GROUP_UNIT_SET_ITEM_RANGED    =0x52,
		AI_GROUP_UNIT_RESET_ITEM_RANGED  =0x53,
		AI_GROUP_UNIT_SHEATHE            =0x54,
		AI_GROUP_UNIT_UNSHEATHE          =0x55,
		AI_GROUP_UNIT_CANCEL_CAST        =0x56,
		AI_GROUP_UNIT_CANCEL_AURA        =0x57,
		AI_GROUP_UNIT_FINISH_CAST        =0x58,
		AI_GROUP_EMOTE_STATE             =0x59,
		AI_GROUP_UNIT_CALL_FOR_HELP      =0x5A,
		AI_GROUP_FLIGHT_PATH             =0x5B,
		AI_GROUP_UNIT_COMBAT_TRIGGER     =0x5C,
	};

	public enum WeaponParrySeqUpdateFields 
	{
		WEAPONPARRYSEQ_2HTIGHT           =0x0,
		WEAPONPARRYSEQ_2HLOOSE           =0x1,
		WEAPONPARRYSEQ_1H                =0x2,
		WEAPONPARRYSEQ_STAND             =0x3,
	};

	public enum WeaponReadySeqUpdateFields 
	{
		WEAPONREADYSEQ_2HTIGHT           =0x0,
		WEAPONREADYSEQ_2HLOOSE           =0x1,
		WEAPONREADYSEQ_1H                =0x2,
		WEAPONREADYSEQ_BOW               =0x3,
		WEAPONREADYSEQ_RIFLE             =0x4,
		WEAPONREADYSEQ_THROWN            =0x5,
	};

	public enum WeaponAttackSeqUpdateFields 
	{
		WEAPONATTACKSEQ_2HTIGHT          =0x0,
		WEAPONATTACKSEQ_2HLOOSE          =0x1,
		WEAPONATTACKSEQ_BOW              =0x2,
		WEAPONATTACKSEQ_1H               =0x3,
		WEAPONATTACKSEQ_RIFLE            =0x4,
		WEAPONATTACKSEQ_THROWN           =0x5,
	};

	public enum WhoSortTypeUpdateFields 
	{
		WHO_SORT_ZONE                    =0x0,
		WHO_SORT_LEVEL                   =0x1,
		WHO_SORT_CLASS                   =0x2,
		WHO_SORT_GROUP                   =0x3,
		WHO_SORT_NAME                    =0x4,
		WHO_SORT_RACE                    =0x5,
		WHO_SORT_GUILD                   =0x6,
	};

	public enum PartyStatusUpdateFields 
	{
		PARTY_STATUS_NOT_IN_PARTY        =0x0,
		PARTY_STATUS_IN_PARTY            =0x1,
		PARTY_STATUS_LFG                 =0x2,
	};

	public enum AttachSlotUpdateFields 
	{
		ATTACH_SHIELD                    =0x0,
		ATTACH_HANDR                     =0x1,
		ATTACH_HANDL                     =0x2,
		ATTACH_ELBOWR                    =0x3,
		ATTACH_ELBOWL                    =0x4,
		ATTACH_SHOULDERR                 =0x5,
		ATTACH_SHOULDERL                 =0x6,
		ATTACH_KNEER                     =0x7,
		ATTACH_KNEEL                     =0x8,
		ATTACH_HIPR                      =0x9,
		ATTACH_HIPL                      =0xA,
		ATTACH_HELM                      =0xB,
		ATTACH_BACK                      =0xC,
		ATTACH_SHOULDERFLAPR             =0xD,
		ATTACH_SHOULDERFLAPL             =0xE,
		ATTACH_TORSOBLOODFRONT           =0xF,
		ATTACH_TORSOBLOODBACK            =0x10,
		ATTACH_BREATH                    =0x11,
		ATTACH_PLAYERNAME                =0x12,
		ATTACH_UNITEFFECT_BASE           =0x13,
		ATTACH_UNITEFFECT_HEAD           =0x14,
		ATTACH_UNITEFFECT_SPELLLEFTHAND  =0x15,
		ATTACH_UNITEFFECT_SPELLRIGHTHAND =0x16,
		ATTACH_UNITEFFECT_SPECIAL1       =0x17,
		ATTACH_UNITEFFECT_SPECIAL2       =0x18,
		ATTACH_UNITEFFECT_SPECIAL3       =0x19,
		ATTACH_SHEATH_MAINHAND           =0x1A,
		ATTACH_SHEATH_OFFHAND            =0x1B,
		ATTACH_SHEATH_SHIELD             =0x1C,
		ATTACH_PLAYERNAMEMOUNTED         =0x1D,
		ATTACH_LARGEWEAPONLEFT           =0x1E,
		ATTACH_LARGEWEAPONRIGHT          =0x1F,
		ATTACH_HIPWEAPONLEFT             =0x20,
		ATTACH_HIPWEAPONRIGHT            =0x21,
		ATTACH_TORSOSPELL                =0x22,
		ATTACH_HANDARROW                 =0x23,
		ATTACH_NONE                      =-1,
	};

	public enum PowerType
	{
		MANA,
		RAGE,
		FOCUS,
		ENERGY,
		UNKNOWN,
	}


	public enum AnimState
	{
		NONE                  =0x0,
		DEAD                  =0x1,
		SPELL                 =0x2,
		IDLE                  =0x3,
		STOP                  =0x4,
		WALK                  =0x5,
		RUN                   =0x6,
		WALK_BACKWARDS        =0x7,
		STRAFE_WALK_LEFT      =0x8,
		STRAFE_WALK_RIGHT     =0x9,
		STRAFE_RUN_LEFT       =0xA,
		STRAFE_RUN_RIGHT      =0xB,
		DIAG_WALK_LEFT        =0xC,
		DIAG_WALK_RIGHT       =0xD,
		DIAG_RUN_LEFT         =0xE,
		DIAG_RUN_RIGHT        =0xF,
		DIAG_BACKWARDS_LEFT   =0x10,
		DIAG_BACKWARDS_RIGHT  =0x11,
		TURNING_LEFT          =0x12,
		TURNING_RIGHT         =0x13,
		SWIM_IDLE             =0x14,
		SWIM                  =0x15,
		SWIM_STRAFE_LEFT      =0x16,
		SWIM_STRAFE_RIGHT     =0x17,
		SWIM_BACKWARDS        =0x18,
		KNEEL                 =0x19,
		RISE                  =0x1A,
		WOUND                 =0x1B,
		CRITICALWOUND         =0x1C,
		STUN                  =0x1D,
		ATTACK_HIT            =0x1E,
		ATTACK_READY          =0x1F,
		ATTACK_MISS           =0x20,
		ATTACKOFF_HIT         =0x21,
		ATTACKOFF_MISS        =0x22,
		PARRY                 =0x23,
		DODGE                 =0x24,
		SPELLPRECAST          =0x25,
		SPELLCAST             =0x26,
		NPC_OBSOLETE          =0x27,
		BLOCK                 =0x28,
		JUMPING               =0x29,
		JUMP_LANDING          =0x2A,
		FALLING               =0x2B,
		LOOTBEGIN             =0x2C,
		LOOTEND               =0x2D,
		EMOTE                 =0x2E,
		SPELLIMPACT           =0x2F,
		MOUNTED               =0x30,
		SPECIALMOUNTANIM      =0x31,
		SITDOWN               =0x32,
		SITTING               =0x33,
		SITUP                 =0x34,
		SLEEPDOWN             =0x35,
		SLEEPING              =0x36,
		SLEEPUP               =0x37,
		SITCHAIRLOW           =0x38,
		SITCHAIRMEDIUM        =0x39,
		SITCHAIRHIGH          =0x3A,
		KNEELDOWN             =0x3B,
		KNEELING              =0x3C,
		KNEELUP               =0x3D,
		CHANNELSPELL          =0x3E,
		SPELLAURA             =0x3F,
	};

	public enum VirtualMonsterSlotUpdateFields 
	{
		VIRTUAL_MONSTER_SLOT_MAINHAND    =0x0,
		VIRTUAL_MONSTER_SLOT_OFFHAND     =0x1,
		VIRTUAL_MONSTER_SLOT_RANGED      =0x2,
	};

	public enum CombatMessageTypeUpdateFields 
	{
		COMBATMESSAGETYPE_NORMALHIT      =0x0,
		COMBATMESSAGETYPE_NORMALMISS     =0x1,
		COMBATMESSAGETYPE_NORMALBLOCK    =0x2,
		COMBATMESSAGETYPE_NORMALPARRY    =0x3,
		COMBATMESSAGETYPE_NORMALDODGE    =0x4,
		COMBATMESSAGETYPE_NORMALEVADE    =0x5,
		COMBATMESSAGETYPE_NORMALIMMUNE   =0x6,
	};

	public enum SpellVisualAttachUpdateFields 
	{
		SPELL_VISUAL_ATTACH_HEAD         =0x0,
		SPELL_VISUAL_ATTACH_CHEST        =0x1,
		SPELL_VISUAL_ATTACH_BASE         =0x2,
		SPELL_VISUAL_ATTACH_LEFT_HAND    =0x3,
		SPELL_VISUAL_ATTACH_RIGHT_HAND   =0x4,
		SPELL_VISUAL_ATTACH_BREATH       =0x5,
		SPELL_VISUAL_ATTACH_SPECIAL1     =0x6,
		SPELL_VISUAL_ATTACH_SPECIAL2     =0x7,
		SPELL_VISUAL_ATTACH_SPECIAL3     =0x8,
	};

	public enum TexComponentUpdateFields 
	{
		TEX_COMPONENT_SKIN               =0x1,
		TEX_COMPONENT_OBJECT_SKIN        =0x2,
		TEX_COMPONENT_WEAPON_BLADE       =0x3,
		TEX_COMPONENT_WEAPON_HANDLE      =0x4,
		TEX_COMPONENT_ENVIRONMENT        =0x5,
		TEX_COMPONENT_CHAR_HAIR          =0x6,
		TEX_COMPONENT_CHAR_FACIAL_HAIR   =0x7,
		TEX_COMPONENT_SKIN_EXTRA         =0x8,
		TEX_COMPONENT_UI_SKIN            =0x9,
		TEX_COMPONENT_TAUREN_MANE        =0xA,
		TEX_COMPONENT_MONSTER_1          =0xB,
		TEX_COMPONENT_MONSTER_2          =0xC,
		TEX_COMPONENT_MONSTER_3          =0xD,
		TEX_COMPONENT_ITEM_ICON          =0xE,
	};

	public enum ObjAttachUpdateFields 
	{
		OBJATTACH_HELMET                 =0x0,
		OBJATTACH_SHOULDERPAD            =0x1,
		OBJATTACH_MAINHAND               =0x2,
		OBJATTACH_OFFHAND                =0x3,
		OBJATTACH_RANGED                 =0x4,
		OBJATTACH_NUM                    =0x5,
	};

	public enum SheathAttachPointsUpdateFields 
	{
		SHEATHATTACH_NONE                =0x0,
		SHEATHATTACH_MAINHAND            =0x1,
		SHEATHATTACH_OFFHAND             =0x2,
		SHEATHATTACH_LARGEWEAPONLEFT     =0x3,
		SHEATHATTACH_LARGEWEAPONRIGHT    =0x4,
		SHEATHATTACH_HIPWEAPONLEFT       =0x5,
		SHEATHATTACH_HIPWEAPONRIGHT      =0x6,
		SHEATHATTACH_SHIELD              =0x7,
	};

	public enum WorldTextTypeUpdateFields 
	{
		WT_DAMAGE                        =0x0,
		WT_ABSORB                        =0x1,
		WT_CRIT                          =0x2,
		WT_HEALSPELL                     =0x3,
		WT_MISS                          =0x4,
		WT_XPGAIN                        =0x5,
		WT_QUEST                         =0x6,
	};

	public enum GameObjAnimStateUpdateFields 
	{
		ANIMSTATE_CLOSED                 =0x0,
		ANIMSTATE_OPENING                =0x1,
		ANIMSTATE_OPEN                   =0x2,
		ANIMSTATE_CLOSING                =0x3,
		ANIMSTATE_DESTROYING             =0x4,
		ANIMSTATE_DESTROYED              =0x5,
		ANIMSTATE_REBUILDING             =0x6,
		ANIMSTATE_FIRSTCUSTOM            =0x7,
		ANIMSTATE_CUSTOM0                =0x7,
		ANIMSTATE_CUSTOM1                =0x8,
		ANIMSTATE_CUSTOM2                =0x9,
		ANIMSTATE_CUSTOM3                =0xA,
	};

	public enum GuildEventUpdateFields 
	{
		GUILD_EVENT_PROMOTION            =0x0,
		GUILD_EVENT_DEMOTION             =0x1,
		GUILD_EVENT_MOTD                 =0x2,
		GUILD_EVENT_JOINED               =0x3,
		GUILD_EVENT_LEFT                 =0x4,
		GUILD_EVENT_REMOVED              =0x5,
		GUILD_EVENT_LEADER_IS            =0x6,
		GUILD_EVENT_LEADER_CHANGED       =0x7,
		GUILD_EVENT_DISBANDED            =0x8,
		GUILD_EVENT_TABARDCHANGE         =0x9,
	};

	public enum TaxiNodeTypeUpdateFields 
	{
		TAXINODE_NONE                    =0x0,
		TAXINODE_CURRENT                 =0x1,
		TAXINODE_REACHABLE               =0x2,
		TAXINODE_DISTANT                 =0x3,
	};

	public enum SpellFailedReason 
	{
		AFFECTING_COMBAT    =0x0,
		ALREADY_HAVE_CHARM  =0x1,
		ALREADY_HAVE_SUMMON =0x2,
		ALREADY_OPEN        =0x3,
		AURA_BOUNCED        =0x4,
		BAD_IMPLICIT_TARGETS =0x5,
		BAD_TARGETS         =0x6,
		CANT_BE_CHARMED     =0x7,
		CANT_STEALTH        =0x8,
		CASTER_AURASTATE    =0x9,
		CASTER_DEAD         =0xA,
		DONT_REPORT         =0xB,
		EQUIPPED_ITEM       =0xC,
		EQUIPPED_ITEM_CLASS =0xD,
		ERROR               =0xE,
		FIZZLE              =0xF,
		HUNGER_SATIATED     =0x10,
		INTERRUPTED         =0x11,
		INTERRUPTED_COMBAT  =0x12,
		ITEM_ALREADY_ENCHANTED= 0x13,
		ITEM_NOT_FOUND      =0x14,
		ITEM_NOT_READY      =0x15,
		LEVEL_REQUIREMENT   =0x16,
		LINE_OF_SIGHT       =0x17,
		LOWLEVEL            =0x18,
		LOW_CASTLEVEL       =0x19,
		MOVING              =0x1A,
		NEED_AMMO           =0x1B,
		NEED_AMMO_POUCH     =0x1C,
		NEED_EXOTIC_AMMO    =0x1D,
		NOPATH              =0x1E,
		NOTSTANDING         =0x1F,
		NOT_BEHIND          =0x20,
		NOT_BEHIND_OR_SIDE  =0x21,
		NOT_HERE            =0x22,
		NOT_KNOWN           =0x23,
		NOT_MOUNTED         =0x24,
		NOT_READY           =0x25,
		NOT_SHAPESHIFT      =0x26,
		NOT_TRADING         =0x27,
		NO_AMMO             =0x28,
		NO_CHARGES_REMAIN   =0x29,
		NO_ENDURANCE        =0x2A,
		NO_PET              =0x2B,
		NO_POWER            =0x2C,
		ONLY_ABOVEWATER     =0x2D,
		ONLY_DAYTIME        =0x2E,
		ONLY_INDOORS        =0x2F,
		ONLY_MOUNTED        =0x30,
		ONLY_NIGHTTIME      =0x31,
		ONLY_OUTDOORS       =0x32,
		ONLY_SHAPESHIFT     =0x33,
		ONLY_STEALTHED      =0x34,
		ONLY_UNDERWATER     =0x35,
		OUT_OF_RANGE        =0x36,
		PACIFIED            =0x37,
		REAGENTS            =0x38,
		REQUIRES_SPELL_FOCUS =0x39,
		SILENCED            =0x3A,
		SPELL_IN_PROGRESS   =0x3B,
		SPELL_LEARNED       =0x3C,
		SPELL_UNAVAILABLE   =0x3D,
		STUNNED             =0x3E,
		TARGETS_DEAD        =0x3F,
		TARGET_AFFECTING_COMBAT= 0x40,
		TARGET_AURASTATE    =0x41,
		TARGET_ENEMY        =0x42,
		TARGET_ENRAGED      =0x43,
		TARGET_FRIENDLY     =0x44,
		TARGET_IS_PLAYER    =0x45,
		TARGET_NOT_DEAD     =0x46,
		TARGET_NOT_IN_PARTY =0x47,
		TARGET_NO_POCKETS   =0x48,
		THIRST_SATIATED     =0x49,
		TOO_CLOSE           =0x4A,
		TOTEMS              =0x4B,
		TRY_AGAIN           =0x4C,
		UNIT_NOT_ATSIDE     =0x4D,
		UNIT_NOT_BEHIND     =0x4E,
		UNIT_NOT_INFRONT    =0x4F,
		NO_MOUNTS_ALLOWED   =0x50,
		CHEST_IN_USE        =0x51,
		NO_COMBO_POINTS     =0x52,
		TARGET_NOT_PLAYER   =0x53,
		TARGET_DUELING      =0x54,
		NOTUNSHEATHED       =0x55,
		NOT_FISHABLE        =0x56,
	};

	public enum GameObjTypeUpdateFields 
	{
		DOOR                        =0x0,
		BUTTON                      =0x1,
		QUESTGIVER                  =0x2,
		CHEST                       =0x3,
		BINDER                      =0x4,
		GENERIC                     =0x5,
		TRAP                        =0x6,
		CHAIR                       =0x7,
		SPELL_FOCUS                 =0x8,
		TEXT                        =0x9,
		GOOBER                      =0xA,
		TRANSPORT                   =0xB,
		AREADAMAGE                  =0xC,
		CAMERA                      =0xD,
		MAP_OBJECT                  =0xE,
		MO_TRANSPORT                =0xF,
		DUEL_ARBITER                =0x10,
		FISHINGNODE                 =0x11,
		RITUAL                      =0x12,
	};

	public enum PropUpdateFields 
	{
		TYPE                        =0x0,
		STARTOPEN                   =0x1,
		STARTDESTROYED              =0x2,
		AUTOCLOSE                   =0x3,
		LOCK                        =0x4,
		QUESTLISTID                 =0x5,
		CHESTLOOT                   =0x6,
		CHESTLOOTTIME               =0x7,
		CONSUMABLE                  =0x8,
		CHARGES                     =0x9,
		SPELL                       =0xA,
		CHAIRSLOTS                  =0xB,
		CHAIRHEIGHT                 =0xC,
		CHESTLOOTEDEVENT            =0xD,
		SPELLFOCUSTYPE              =0xE,
		TEXTID                      =0xF,
		TEXTLANGUAGE                =0x10,
		TEXTMATERIAL                =0x11,
		HIGHLIGHT                   =0x12,
		FLOATINGTOOLTIP             =0x13,
		QUESTID                     =0x14,
		EVENTID                     =0x15,
		CUSTOMANIM                  =0x16,
		COOLDOWN                    =0x17,
		RADIUS                      =0x18,
		CHESTMINRESTOCK             =0x19,
		CHESTMAXRESTOCK             =0x1A,
		DAMAGE_MIN                  =0x1B,
		DAMAGE_MAX                  =0x1C,
		DAMAGE_SCHOOL               =0x1D,
		LINKED_TRAP                 =0x1E,
		TRAP_LEVEL                  =0x1F,
		STARTDELAY                  =0x20,
		CAMERAID                    =0x21,
		CASTERS                     =0x22,
		TAXIPATHID1                 =0x23,
		TAXIPATHID2                 =0x24,
		MOVESPEED                   =0x25,
	};

	public enum ValueTypeUpdateFields 
	{
		VALUE_TYPE_TYPE                  =0x0,
		VALUE_TYPE_BOOL                  =0x1,
		VALUE_TYPE_INT                   =0x2,
		VALUE_TYPE_FLOAT                 =0x3,
		VALUE_TYPE_NAME                  =0x4,
		VALUE_TYPE_LOCK                  =0x5,
		VALUE_TYPE_QUESTGIVER            =0x6,
		VALUE_TYPE_LOOTTABLE             =0x7,
		VALUE_TYPE_SPELL                 =0x8,
		VALUE_TYPE_PAGETEXT              =0x9,
		VALUE_TYPE_PAGEMATERIAL          =0xA,
		VALUE_TYPE_TRAP                  =0xB,
		VALUE_TYPE_CAMERA                =0xC,
	};

	public enum GError
	{
		NONE                       = 0x0,
		CANT_EQUIP_LEVEL_I         = 0x1,  // need more level
		CANT_EQUIP_SKILL           = 0x2,
		WRONG_SLOT                 = 0x3,  // that item do not go that slot
		BAG_FULL                   = 0x4,  
		BAG_IN_BAG                 = 0x5,  // bag not empty
		AMMO_ONLY                  = 0x6,  
		PROFICIENCY_NEEDED         = 0x7,
		NOT_EQUIPPABLE             = 0x8,
		NEVER                      = 0x9,
		NEVER2                     = 0xA,
		WRONG_EQ_SLOT              = 0xb,
		TWOHAND                    = 0xc,
		DULEWIELD                  = 0xd,
		WRONG_SLOT2                = 0xe,
		WRONG_SLOT3                = 0xf,
		ITEM_TOO_MANY              = 0x10,

		NOT_A_BAG                  = 0x1d,


		ITEM_NOT_FOUND              =0x11,
		TOO_FEW_TO_SPLIT            =0x12,
		SPLIT_FAILED                =0x13,
		NOT_ENOUGH_GOLD             =0x14,

		NOT_OWNER                   =0x16,
		ONLY_ONE_QUIVER             =0x17,
		NO_BANK_SLOT                =0x18,
		NO_BANK_HERE                =0x19,
		ITEM_LOCKED                 =0x1A,
		HANDED_EQUIPPED             =0x1B,
		VENDOR_NOT_INTERESTED       =0x1C,
		VENDOR_HATES_YOU            =0x1D,
		VENDOR_SOLD_OUT             =0x1E,
		VENDOR_TOO_FAR              =0x1F,
		NOT_ENOUGH_MONEY            =0x20,
		RECEIVE_ITEM_S              =0x21,
		DROP_BOUND_ITEM             =0x22,
		TRADE_BOUND_ITEM            =0x23,
		TRADE_QUEST_ITEM            =0x24,
		TRADE_GROUND_ITEM           =0x25,
		TRADE_BAG                   =0x26,
		SPELL_FAILED_S              =0x27,
		ITEM_COOLDOWN               =0x28,
		POTION_COOLDOWN             =0x29,
		FOOD_COOLDOWN               =0x2A,
		SPELL_COOLDOWN              =0x2B,
		ABILITY_COOLDOWN            =0x2C,
		SPELL_ALREADY_KNOWN_S       =0x2D,
		SKILL_GAINED_S              =0x2E,
		SKILL_UP_SI                 =0x2F,
		LEARN_SPELL_S               =0x30,
		LEARN_ABILITY_S             =0x31,
		LEARN_RECIPE_S              =0x32,
		INVITE_PLAYER_S             =0x33,
		INVITED_TO_GROUP_S          =0x34,
		ALREADY_IN_GROUP_S          =0x35,
		PLAYER_BUSY_S               =0x36,
		NEW_LEADER_S                =0x37,
		NEW_LEADER_YOU              =0x38,
		LEFT_GROUP_S                =0x39,
		LEFT_GROUP_YOU              =0x3A,
		GROUP_DISBANDED             =0x3B,
		DECLINE_GROUP_S             =0x3C,
		JOINED_GROUP_S              =0x3D,
		UNINVITE_YOU                =0x3E,
		BAD_PLAYER_NAME_S           =0x3F,
		NOT_IN_GROUP                =0x40,
		TARGET_NOT_IN_GROUP_S       =0x41,
		GROUP_FULL                  =0x42,
		NOT_LEADER                  =0x43,
		PLAYER_DIED_S               =0x44,
		GUILD_CREATE_S              =0x45,
		GUILD_INVITE_S              =0x46,
		INVITED_TO_GUILD_SS         =0x47,
		ALREADY_IN_GUILD_S          =0x48,
		ALREADY_INVITED_TO_GUILD_S  =0x49,
		INVITED_TO_GUILD            =0x4A,
		ALREADY_IN_GUILD            =0x4B,
		GUILD_ACCEPT                =0x4C,
		GUILD_DECLINE_S             =0x4D,
		GUILD_PERMISSIONS           =0x4E,
		GUILD_JOIN_S                =0x4F,
		GUILD_FOUNDER_S             =0x50,
		GUILD_PROMOTE_SS            =0x51,
		GUILD_DEMOTE_SS             =0x52,
		GUILD_QUIT_S                =0x53,
		GUILD_LEAVE_S               =0x54,
		GUILD_REMOVE_SS             =0x55,
		GUILD_REMOVE_SELF           =0x56,
		GUILD_DISBAND_S             =0x57,
		GUILD_DISBAND_SELF          =0x58,
		GUILD_LEADER_S              =0x59,
		GUILD_LEADER_SELF           =0x5A,
		GUILD_MOTD_S                =0x5B,
		GUILD_PLAYER_NOT_FOUND_S    =0x5C,
		GUILD_PLAYER_NOT_IN_GUILD_S =0x5D,
		GUILD_PLAYER_NOT_IN_GUILD   =0x5E,
		GUILD_CANT_PROMOTE_S        =0x5F,
		GUILD_CANT_DEMOTE_S         =0x60,
		GUILD_NOT_IN_A_GUILD        =0x61,
		GUILD_INTERNAL              =0x62,
		GUILD_LEADER_IS_S           =0x63,
		GUILD_LEADER_CHANGED_SS     =0x64,
		GUILD_DISBANDED             =0x65,
		GUILD_NOT_ALLIED            =0x66,
		GUILD_LEADER_LEAVE          =0x67,
		GUILD_NAME_INVALID          =0x68,
		GUILD_NAME_EXISTS_S         =0x69,
		GUILD_ENTER_NAME            =0x6A,
		GUILD_NAME_TOO_SHORT        =0x6B,
		GUILD_NAME_MIXED_LANGUAGES  =0x6C,
		GUILD_NAME_PROFANE          =0x6D,
		GUILD_NAME_RESERVED         =0x6E,
		NO_GUILD_CHARTER            =0x6F,
		OUT_OF_RANGE                =0x70,
		PLAYER_DEAD                 =0x71,
		CLIENT_LOCKED_OUT           =0x72,
		KILLED_BY_S                 =0x73,
		LOOT_LOCKED                 =0x74,
		LOOT_TOO_FAR                =0x75,
		LOOT_DIDNT_KILL             =0x76,
		LOOT_BAD_FACING             =0x77,
		LOOT_NOTSTANDING            =0x78,
		LOOT_STUNNED                =0x79,
		LOOT_NO_UI                  =0x7A,
		QUEST_ACCEPTED_S            =0x7B,
		QUEST_COMPLETE_S            =0x7C,
		QUEST_FAILED_S              =0x7D,
		QUEST_FAILED_BAG_FULL_S     =0x7E,
		QUEST_FAILED_MAX_COUNT_S    =0x7F,
		QUEST_FAILED_LOW_LEVEL      =0x80,
		QUEST_FAILED_MISSING_ITEMS  =0x81,
		QUEST_REWARD_EXP_I          =0x82,
		QUEST_REWARD_ITEM_S         =0x83,
		QUEST_REWARD_MONEY_S        =0x84,
		QUEST_MUST_CHOOSE           =0x85,
		QUEST_LOG_FULL              =0x86,
		COMBAT_DAMAGE_SSI           =0x87,
		INSPECT_S                   =0x88,
		CANT_USE_ITEM               =0x89,
		MUST_EQUIP_ITEM             =0x8A,
		PASSIVE_ABILITY             =0x8B,
		HSKILLNOTFOUND              =0x8C,
		NO_ATTACK_TARGET            =0x8D,
		INVALID_ATTACK_TARGET       =0x8E,
		ATTACK_PACIFIED             =0x8F,
		ATTACK_DEAD                 =0x90,
		HUNGER_VERY_LOW             =0x91,
		HUNGER_LOW                  =0x92,
		HUNGER_MED                  =0x93,
		HUNGER_HIGH                 =0x94,
		HUNGER_SATIATED             =0x95,
		THIRST_VERY_LOW             =0x96,
		THIRST_LOW                  =0x97,
		THIRST_MED                  =0x98,
		THIRST_HIGH                 =0x99,
		THIRST_SATIATED             =0x9A,
		TAXISAMENODE                =0x9B,
		TAXINOSUCHPATH              =0x9C,
		TAXIUNSPECIFIEDSERVERERROR  =0x9D,
		TAXINOTENOUGHMONEY          =0x9E,
		TAXITOOFARAWAY              =0x9F,
		TAXINOVENDORNEARBY          =0xA0,
		TAXINOTVISITED              =0xA1,
		TAXIPLAYERBUSY              =0xA2,
		TAXIPLAYERALREADYMOUNTED    =0xA3,
		TAXIPLAYERSHAPESHIFTED      =0xA4,
		TAXIPLAYERMOVING            =0xA5,
		TAXINOPATHS                 =0xA6,
		NO_REPLY_TARGET             =0xA7,
		GENERIC_NO_TARGET           =0xA8,
		INITIATE_TRADE_S            =0xA9,
		TRADE_REQUEST_S             =0xAA,
		TRADE_TOO_FAR               =0xAB,
		TRADE_CANCELLED             =0xAC,
		TRADE_COMPLETE              =0xAD,
		TRADE_BAG_FULL              =0xAE,
		TRADE_TARGET_BAG_FULL       =0xAF,
		TRADE_MAX_COUNT_EXCEEDED    =0xB0,
		TRADE_TARGET_MAX_COUNT_EXCEEDED= 0xB1,
		MOUNT_INVALIDMOUNTEE        =0xB2,
		MOUNT_TOOFARAWAY            =0xB3,
		MOUNT_ALREADYMOUNTED        =0xB4,
		MOUNT_NOTMOUNTABLE          =0xB5,
		MOUNT_NOTYOURPET            =0xB6,
		MOUNT_OTHER                 =0xB7,
		MOUNT_LOOTING               =0xB8,
		MOUNT_RACECANTMOUNT         =0xB9,
		MOUNT_SHAPESHIFTED          =0xBA,
		DISMOUNT_NOPET              =0xBB,
		DISMOUNT_NOTMOUNTED         =0xBC,
		DISMOUNT_NOTYOURPET         =0xBD,
		SPELL_FAILED_TOTEMS         =0xBE,
		SPELL_FAILED_REAGENTS       =0xBF,
		SPELL_FAILED_EQUIPPED_ITEM  =0xC0,
		SPELL_FAILED_EQUIPPED_ITEM_CLASS_S= 0xC1,
		SPELL_FAILED_SHAPESHIFT_FORM_S =0xC2,
		BADATTACKFACING             =0xC3,
		BADATTACKPOS                =0xC4,
		CHEST_IN_USE                =0xC5,
		USE_CANT_OPEN               =0xC6,
		USE_LOCKED                  =0xC7,
		USE_LOCKED_WITH_ITEM_S      =0xC8,
		USE_LOCKED_WITH_SPELL_S     =0xC9,
		USE_LOCKED_WITH_SPELL_KNOWN_SI= 0xCA,
		USE_TOO_FAR                 =0xCB,
		USE_BAD_ANGLE               =0xCC,
		USE_OBJECT_MOVING           =0xCD,
		USE_SPELL_FOCUS             =0xCE,
		USE_DESTROYED               =0xCF,
		CANTATTACK_NOTSTANDING      =0xD0,
		SET_LOOT_FREEFORALL         =0xD1,
		SET_LOOT_ROUNDROBIN         =0xD2,
		SET_LOOT_MASTER             =0xD3,
		NEW_LOOT_MASTER_S           =0xD4,
		SPECIFY_MASTER_LOOTER       =0xD5,
		TAME_FAILED                 =0xD6,
		CHAT_WHILE_DEAD             =0xD7,
		NEWTAXIPATH                 =0xD8,
		NO_PET                      =0xD9,
		NOTYOURPET                  =0xDA,
		PET_NOT_RENAMEABLE          =0xDB,
		NULL_PETNAME                =0xDC,
		INVALID_PETNAME             =0xDD,
		QUEST_OBJECTIVE_COMPLETE_S  =0xDE,
		QUEST_UNKNOWN_COMPLETE      =0xDF,
		QUEST_ADD_KILL_SII          =0xE0,
		QUEST_ADD_FOUND_SII         =0xE1,
		QUEST_ADD_ITEM_SII          =0xE2,
		CANNOTCREATEDIRECTORY       =0xE3,
		CANNOTCREATEFILE            =0xE4,
		PLAYER_WRONG_FACTION        =0xE5,
		BANKSLOT_FAILED_TOO_MANY    =0xE6,
		BANKSLOT_INSUFFICIENT_FUNDS =0xE7,
		BANKSLOT_NOTBANKER          =0xE8,
		FRIEND_DB_ERROR             =0xE9,
		FRIEND_LIST_FULL            =0xEA,
		FRIEND_ADDED_S              =0xEB,
		FRIEND_ONLINE_S             =0xEC,
		FRIEND_OFFLINE_S            =0xED,
		FRIEND_NOT_FOUND            =0xEE,
		FRIEND_WRONG_FACTION        =0xEF,
		FRIEND_REMOVED_S            =0xF0,
		FRIEND_ERROR                =0xF1,
		FRIEND_ALREADY_S            =0xF2,
		FRIEND_SELF                 =0xF3,
		IGNORE_FULL                 =0xF4,
		IGNORE_SELF                 =0xF5,
		IGNORE_NOT_FOUND            =0xF6,
		IGNORE_ALREADY_S            =0xF7,
		IGNORE_ADDED_S              =0xF8,
		IGNORE_REMOVED_S            =0xF9,
		ONLY_ONE_BOLT               =0xFA,
		ONLY_ONE_AMMO               =0xFB,
		SPELL_FAILED_EQUIPPED_SPECIFIC_ITEM =0xFC,
		WRONG_BAG_TYPE_SUBCLASS     =0xFD,
		CANT_WRAP_STACKABLE         =0xFE,
		CANT_WRAP_EQUIPPED          =0xFF,
		CANT_WRAP_WRAPPED           =0x100,
		CANT_WRAP_BOUND             =0x101,
		CANT_WRAP_UNIQUE            =0x102,
		CANT_WRAP_BAGS              =0x103,
		OUT_OF_MANA                 =0x104,
		OUT_OF_RAGE                 =0x105,
		OUT_OF_FOCUS                =0x106,
		OUT_OF_ENERGY               =0x107,
		OUT_OF_HEALTH               =0x108,
		LOOT_GONE                   =0x109,
		MOUNT_FORCEDDISMOUNT        =0x10A,
		AUTOFOLLOW_TOO_FAR          =0x10B,
		UNIT_NOT_FOUND              =0x10C,
		INVALID_FOLLOW_TARGET       =0x10D,
		GUILDEMBLEM_SUCCESS         =0x10E,
		GUILDEMBLEM_INVALID_TABARD_COLORS =0x10F,
		GUILDEMBLEM_NOGUILD         =0x110,
		GUILDEMBLEM_COLORSPRESENT   =0x111,
		GUILDEMBLEM_NOTGUILDMASTER  =0x112,
		GUILDEMBLEM_NOTENOUGHMONEY  =0x113,
		GUILDEMBLEM_INVALIDVENDOR   =0x114,
		SPELL_OUT_OF_RANGE          =0x115,
		COMMAND_NEEDS_TARGET        =0x116,
		NOAMMO_S                    =0x117,
		TOOBUSYTOFOLLOW             =0x118,
		DUEL_REQUESTED              =0x119,
		DUEL_CANCELLED              =0x11A,
		DEATHBINDALREADYBOUND       =0x11B,
		NOEMOTEWHILERUNNING         =0x11C,
		ZONE_EXPLORED               =0x11D,
		ZONE_EXPLORED_XP            =0x11E,
		INVALID_ITEM_TARGET         =0x11F,
		IGNORING_YOU_S              =0x120,
		FISH_NOT_HOOKED             =0x121,
		FISH_ESCAPED                =0x122,
		SPELL_FAILED_NOTUNSHEATHED  =0x123,
		PETITION_SIGNED             =0x124,
		PETITION_ALREADY_SIGNED     =0x125,
		PETITION_IN_GUILD           =0x126,
		PETITION_CREATOR            =0x127,
		PETITION_NOT_ENOUGH_SIGNATURES =0x128,
	};

	public enum ObjectType
	{
		OBJECT                        =0x0,
		ITEM                          =0x1,
		CONTAINER                     =0x2,
		UNIT                          =0x3,
		PLAYER                        =0x4,
		GAMEOBJECT                    =0x5,
		DYNAMICOBJECT                 =0x6,
		CORPSE                        =0x7,
		AIGROUP                       =0x8,
		AREATRIGGER                   =0x9,
	};

	public enum QuestGiverUpdateFields 
	{
		QUEST_GIVER_NONE                 =0x0,
		QUEST_GIVER_TRIVIAL              =0x1,
		QUEST_GIVER_FUTURE               =0x2,
		QUEST_GIVER_REWARD               =0x3,
		QUEST_GIVER_QUEST                =0x4,
	};

	public enum ObjectAnimationUpdateFields 
	{
		ANIM_STAND                      = 0x0,
		ANIM_DEATH                      = 0x1,
		ANIM_SPELL                      = 0x2,
		ANIM_STOP                       = 0x3,
		ANIM_WALK                       = 0x4,
		ANIM_RUN                        = 0x5,
		ANIM_DEAD                       = 0x6,
		ANIM_RISE                       = 0x7,
		ANIM_STANDWOUND                 = 0x8,
		ANIM_COMBATWOUND                = 0x9,
		ANIM_COMBATCRITICAL             = 0xA,
		ANIM_SHUFFLE_LEFT               = 0xB,
		ANIM_SHUFFLE_RIGHT              = 0xC,
		ANIM_WALK_BACKWARDS             = 0xD,
		ANIM_STUN                       = 0xE,
		ANIM_HANDS_CLOSED               = 0xF,
		ANIM_ATTACKUNARMED               =0x10,
		ANIM_ATTACK1H                    =0x11,
		ANIM_ATTACK2HTIGHT               =0x12,
		ANIM_ATTACK2HLOOSE               =0x13,
		ANIM_PARRYUNARMED                =0x14,
		ANIM_PARRY1H                     =0x15,
		ANIM_PARRY2HTIGHT                =0x16,
		ANIM_PARRY2HLOOSE                =0x17,
		ANIM_PARRYSHIELD                 =0x18,
		ANIM_READYUNARMED                =0x19,
		ANIM_READY1H                     =0x1A,
		ANIM_READY2HTIGHT                =0x1B,
		ANIM_READY2HLOOSE                =0x1C,
		ANIM_READYBOW                    =0x1D,
		ANIM_DODGE                       =0x1E,
		ANIM_SPELLPRECAST                =0x1F,
		ANIM_SPELLCAST                   =0x20,
		ANIM_SPELLCASTAREA               =0x21,
		ANIM_NPCWELCOME                  =0x22,
		ANIM_NPCGOODBYE                  =0x23,
		ANIM_BLOCK                       =0x24,
		ANIM_JUMPSTART                   =0x25,
		ANIM_JUMP                        =0x26,
		ANIM_JUMPEND                     =0x27,
		ANIM_FALL                        =0x28,
		ANIM_SWIMIDLE                    =0x29,
		ANIM_SWIM                        =0x2A,
		ANIM_SWIM_LEFT                   =0x2B,
		ANIM_SWIM_RIGHT                  =0x2C,
		ANIM_SWIM_BACKWARDS              =0x2D,
		ANIM_ATTACKBOW                   =0x2E,
		ANIM_FIREBOW                     =0x2F,
		ANIM_READYRIFLE                  =0x30,
		ANIM_ATTACKRIFLE                 =0x31,
		ANIM_LOOT                        =0x32,
		ANIM_SPELL_PRECAST_DIRECTED      =0x33,
		ANIM_SPELL_PRECAST_OMNI          =0x34,
		ANIM_SPELL_CAST_DIRECTED         =0x35,
		ANIM_SPELL_CAST_OMNI             =0x36,
		ANIM_SPELL_BATTLEROAR            =0x37,
		ANIM_SPELL_READYABILITY          =0x38,
		ANIM_SPELL_SPECIAL1H             =0x39,
		ANIM_SPELL_SPECIAL2H             =0x3A,
		ANIM_SPELL_SHIELDBASH            =0x3B,
		ANIM_EMOTE_TALK                  =0x3C,
		ANIM_EMOTE_EAT                   =0x3D,
		ANIM_EMOTE_WORK                  =0x3E,
		ANIM_EMOTE_USE_STANDING          =0x3F,
		ANIM_EMOTE_EXCLAMATION           =0x40,
		ANIM_EMOTE_QUESTION              =0x41,
		ANIM_EMOTE_BOW                   =0x42,
		ANIM_EMOTE_WAVE                  =0x43,
		ANIM_EMOTE_CHEER                 =0x44,
		ANIM_EMOTE_DANCE                 =0x45,
		ANIM_EMOTE_LAUGH                 =0x46,
		ANIM_EMOTE_SLEEP                 =0x47,
		ANIM_EMOTE_SIT_GROUND            =0x48,
		ANIM_EMOTE_RUDE                  =0x49,
		ANIM_EMOTE_ROAR                  =0x4A,
		ANIM_EMOTE_KNEEL                 =0x4B,
		ANIM_EMOTE_KISS                  =0x4C,
		ANIM_EMOTE_CRY                   =0x4D,
		ANIM_EMOTE_CHICKEN               =0x4E,
		ANIM_EMOTE_BEG                   =0x4F,
		ANIM_EMOTE_APPLAUD               =0x50,
		ANIM_EMOTE_SHOUT                 =0x51,
		ANIM_EMOTE_FLEX                  =0x52,
		ANIM_EMOTE_SHY                   =0x53,
		ANIM_EMOTE_POINT                 =0x54,
		ANIM_ATTACK1HPIERCE              =0x55,
		ANIM_ATTACK2HLOOSEPIERCE         =0x56,
		ANIM_ATTACKOFF                   =0x57,
		ANIM_ATTACKOFFPIERCE             =0x58,
		ANIM_SHEATHE                     =0x59,
		ANIM_HIPSHEATHE                  =0x5A,
		ANIM_MOUNT                       =0x5B,
		ANIM_RUN_LEANRIGHT               =0x5C,
		ANIM_RUN_LEANLEFT                =0x5D,
		ANIM_MOUNT_SPECIAL               =0x5E,
		ANIM_KICK                        =0x5F,
		ANIM_SITDOWN                     =0x60,
		ANIM_SITTING                     =0x61,
		ANIM_SITUP                       =0x62,
		ANIM_SLEEPDOWN                   =0x63,
		ANIM_SLEEPING                    =0x64,
		ANIM_SLEEPUP                     =0x65,
		ANIM_SITCHAIRLOW                 =0x66,
		ANIM_SITCHAIRMEDIUM              =0x67,
		ANIM_SITCHAIRHIGH                =0x68,
		ANIM_LOADBOW                     =0x69,
		ANIM_LOADRIFLE                   =0x6A,
		ANIM_ATTACKTHROWN                =0x6B,
		ANIM_READYTHROWN                 =0x6C,
		ANIM_HOLDBOW                     =0x6D,
		ANIM_HOLDRIFLE                   =0x6E,
		ANIM_HOLDTHROWN                  =0x6F,
		ANIM_LOADTHROWN                  =0x70,
		ANIM_EMOTE_SALUTE                =0x71,
		ANIM_KNEELDOWN                   =0x72,
		ANIM_KNEELING                    =0x73,
		ANIM_KNEELUP                     =0x74,
		ANIM_ATTACKUNARMEDOFF            =0x75,
		ANIM_SPECIALUNARMED              =0x76,
		ANIM_STEALTHWALK                 =0x77,
		ANIM_STEALTHSTAND                =0x78,
		ANIM_KNOCKDOWN                   =0x79,
		ANIM_EATING                      =0x7A,
		ANIM_USESTANDINGLOOP             =0x7B,
		ANIM_CHANNELCASTDIRECTED         =0x7C,
		ANIM_CHANNELCASTOMNI             =0x7D,
		ANIM_WHIRLWIND                   =0x7E,
		ANIM_BIRTH                       =0x7F,
		ANIM_USESTANDINGSTART            =0x80,
		ANIM_USESTANDINGEND              =0x81,
		ANIM_HOWL                        =0x82,
		ANIM_DROWN                       =0x83,
		ANIM_DROWNED                     =0x84,
		ANIM_FISHINGCAST                 =0x85,
		ANIM_FISHINGLOOP                 =0x86,
	};

	public enum GameObjectAnimationsUpdateFields 
	{
		ANIM_GAMEOBJ_STAND               =0x0,
		ANIM_GAMEOBJ_CLOSED              =0x1,
		ANIM_GAMEOBJ_OPEN                =0x2,
		ANIM_GAMEOBJ_OPENED              =0x3,
		ANIM_GAMEOBJ_CLOSE               =0x4,
		ANIM_GAMEOBJ_DESTROY             =0x5,
		ANIM_GAMEOBJ_DESTROYED           =0x6,
		ANIM_GAMEOBJ_REBUILD             =0x7,
		ANIM_GAMEOBJ_CUSTOM0             =0x8,
		ANIM_GAMEOBJ_CUSTOM1             =0x9,
		ANIM_GAMEOBJ_CUSTOM2             =0xA,
		ANIM_GAMEOBJ_CUSTOM3             =0xB,
	};

	public enum EffectAnimationsUpdateFields 
	{
		ANIM_EFFECT_STAND                =0x0,
		ANIM_EFFECT_HOLD                 =0x1,
		ANIM_EFFECT_DECAY                =0x2,
		NUM_EFFECTANIMATIONS             =0x3,
	};

	public enum ItemAnimationsUpdateFields 
	{
		ANIM_ITEM_STAND                 = 0x0,
		ANIM_ITEM_INFLIGHT              = 0x1,
		ANIM_ITEM_BOWPULL               = 0x2,
		ANIM_ITEM_BOWRELEASE            = 0x3,
	};

	public enum NPCSoundUpdateFields 
	{
		NPCSOUND_HELLO                   =0x0,
		NPCSOUND_GOODBYE                 =0x1,
		NPCSOUND_PISSED                  =0x2,
		NPCSOUND_ACK                     =0x3,
	};

	public enum SpellCastUITypeUpdateFields 
	{
		SPELL_CAST_UI_NONE               =0x0,
		SPELL_CAST_UI_PET_TRAINING       =0x1,
		SPELL_CAST_UI_DISGUISES          =0x2,
		SPELL_CAST_UI_INSCRIBING         =0x3,
	};

	public enum BloodSpurtLocationUpdateFields 
	{
		BLOODSPURT_FRONT               =  0x0,
		BLOODSPURT_BACK                 = 0x1,
	};

	public enum UnitSoundTypeUpdateFields 
	{
		UNITSOUNDTYPE_EXERTION          = 0x0,
		UNITSOUNDTYPE_EXERTIONCRITICAL  = 0x1,
		UNITSOUNDTYPE_INJURY            = 0x2,
		UNITSOUNDTYPE_INJURYCRITICAL    = 0x3,
		UNITSOUNDTYPE_DEATH             = 0x4,
		UNITSOUNDTYPE_STUN              = 0x5,
		UNITSOUNDTYPE_STAND             = 0x6,
		UNITSOUNDTYPE_DEATHTHUD         = 0x7,
		UNITSOUNDTYPE_FOOTFALL          = 0x8,
		UNITSOUNDTYPE_AGGRO             = 0x9,
		UNITSOUNDTYPE_WINGFLAP          = 0xA,
		UNITSOUNDTYPE_ALERT             = 0xB,
		UNITSOUNDTYPE_INJURYCRUSHINGBLOW= 0xC,
		UNITSOUNDTYPE_WINGGLIDE         = 0xD,
		UNITSOUNDTYPE_JUMPSTART         = 0xE,
		UNITSOUNDTYPE_JUMPEND           = 0xF,
	};

	public enum EmoteSpecProcUpdateFields 
	{
		EMOTESPECPROC_NONE               =0x0,
		EMOTESPECPROC_STANDSTATEHANDLER  =0x1,
		EMOTESPECPROC_EMOTESTATEHANDLER  =0x2,
	};

	public enum UnitSexUpdateFields 
	{
		UNITSEX_MALE                     =0x0,
		UNITSEX_FEMALE                   =0x1,
		UNITSEX_NONE                     =0x2,
		UNITSEX_BOTH                     =0x3,
	};

	public enum WorldTextMissTypeUpdateFields 
	{
		WORLDTEXTMISS_EVADED            = 0x0,
		WORLDTEXTMISS_DODGED            = 0x1,
		WORLDTEXTMISS_PARRIED           = 0x2,
		WORLDTEXTMISS_BLOCKED           = 0x3,
		WORLDTEXTMISS_DEFLECTED         = 0x4,
		WORLDTEXTMISS_IMMUNE            = 0x5,
		WORLDTEXTMISS_TEMPIMMUNE        = 0x6,
		WORLDTEXTMISS_PHYSICAL          = 0x7,
		WORLDTEXTMISS_RESIST            = 0x8,
		WORLDTEXTMISS_ABSORBED          = 0x9,
	};

	public enum SheathReasonUpdateFields 
	{
		SHEATHE_PLAYEREXPLICIT          = 0x0,
		SHEATHE_SPELLS                  = 0x1,
		SHEATHE_STANDSTATE              = 0x2,
		SHEATHE_BASEANIM                = 0x3,
		SHEATHE_TORSOANIM               = 0x4,
		SHEATHE_RANGED                  = 0x5,
		SHEATHE_TALKEMOTE               = 0x6,
		SHEATHE_PRECAST                 = 0x7,
		SHEATHE_CHANNELLING             = 0x8,
	};

	public enum ItemSlotUpdateFields 
	{
		INVSLOT_HEAD                    = 0x0,
		INVSLOT_FIRST                   = 0x0,
		EQUIPPED_FIRST                  = 0x0,
		INVSLOT_NECK                    = 0x1,
		INVSLOT_SHOULDER                = 0x2,
		INVSLOT_BODY                    = 0x3,
		INVSLOT_CHEST                   = 0x4,
		INVSLOT_WAIST                   = 0x5,
		INVSLOT_LEGS                    = 0x6,
		INVSLOT_FEET                    = 0x7,
		INVSLOT_WRIST                   = 0x8,
		INVSLOT_HAND                    = 0x9,
		INVSLOT_FINGER1                 = 0xA,
		INVSLOT_FINGER2                 = 0xB,
		INVSLOT_TRINKET1                = 0xC,
		INVSLOT_TRINKET2                = 0xD,
		INVSLOT_BACK                    = 0xE,
		INVSLOT_MAINHAND                = 0xF,
		INVSLOT_OFFHAND                  =0x10,
		INVSLOT_RANGED                   =0x11,
		INVSLOT_TABARD                   =0x12,
		EQUIPPED_LAST                    =0x12,
		INVSLOT_BAG0                     =0x13,
		INVSLOT_BAGFIRST                 =0x13,
		INVSLOT_BAG1                     =0x14,
		INVSLOT_BAG2                     =0x15,
		INVSLOT_BAG3                     =0x16,
		INVSLOT_BAGLAST                  =0x16,
		INVSLOT_LAST                     =0x16,
		BACKPACK_SLOT00                  =0x17,
		BACKPACK_FIRST                   =0x17,
		BACKPACK_SLOT01                  =0x18,
		BACKPACK_SLOT02                  =0x19,
		BACKPACK_SLOT03                  =0x1A,
		BACKPACK_SLOT04                  =0x1B,
		BACKPACK_SLOT05                  =0x1C,
		BACKPACK_SLOT06                  =0x1D,
		BACKPACK_SLOT07                  =0x1E,
		BACKPACK_SLOT08                  =0x1F,
		BACKPACK_SLOT09                  =0x20,
		BACKPACK_SLOT10                  =0x21,
		BACKPACK_SLOT11                  =0x22,
		BACKPACK_SLOT12                  =0x23,
		BACKPACK_SLOT13                  =0x24,
		BACKPACK_SLOT14                  =0x25,
		BACKPACK_SLOT15                  =0x26,
		BACKPACK_LAST                    =0x26,
		BANKGENERIC_SLOT00               =0x27,
		BANKGENERIC_FIRST                =0x27,
		BANKGENERIC_SLOT01               =0x28,
		BANKGENERIC_SLOT02               =0x29,
		BANKGENERIC_SLOT03               =0x2A,
		BANKGENERIC_SLOT04               =0x2B,
		BANKGENERIC_SLOT05               =0x2C,
		BANKGENERIC_SLOT06               =0x2D,
		BANKGENERIC_SLOT07               =0x2E,
		BANKGENERIC_SLOT08               =0x2F,
		BANKGENERIC_SLOT09               =0x30,
		BANKGENERIC_SLOT10               =0x31,
		BANKGENERIC_SLOT11               =0x32,
		BANKGENERIC_SLOT12               =0x33,
		BANKGENERIC_SLOT13               =0x34,
		BANKGENERIC_SLOT14               =0x35,
		BANKGENERIC_SLOT15               =0x36,
		BANKGENERIC_SLOT16               =0x37,
		BANKGENERIC_SLOT17               =0x38,
		BANKGENERIC_SLOT18               =0x39,
		BANKGENERIC_SLOT19               =0x3A,
		BANKGENERIC_SLOT20               =0x3B,
		BANKGENERIC_SLOT21               =0x3C,
		BANKGENERIC_SLOT22               =0x3D,
		BANKGENERIC_SLOT23               =0x3E,
		BANKGENERIC_LAST                 =0x3E,
		BANKBAG_0                        =0x3F,
		BANKBAG_FIRST                    =0x3F,
		BANKBAG_1                        =0x40,
		BANKBAG_2                        =0x41,
		BANKBAG_3                        =0x42,
		BANKBAG_4                        =0x43,
		BANKBAG_5                        =0x44,
		BANKBAG_LAST                     =0x44,
		PLAYER_INVENTORY_SLOTS           =0x45,
		NUM_INVENTORY_SLOTS              =0x17,
		NUM_BAG_SLOTS                   = 0x4,
		MIN_BACKPACK_SLOTS               =0x10,
		BANK_NUM_GEMERIC_SLOTS           =0x18,
		NUM_BANKBAG_SLOTS               = 0x6,
		TOTAL_BAG_SLOTS                 = 0xA,
		INVENTORY_NONE                   =(-1),
	};

	public enum AffiliationUpdateFields 
	{
		AFFILIATION_YOURSELF            = 0x0,
		AFFILIATION_YOURPET             = 0x1,
		AFFILIATION_PARTYMEMBER         = 0x2,
		AFFILIATION_OTHER               = 0x3,
		AFFILIATION_YOURCONTROLLER      = 0x4,
	};

	public enum VictimStateUpdateFields 
	{
		VS_NONE                          =0x0,
		VS_WOUND                         =0x1,
		VS_DODGE                         =0x2,
		VS_PARRY                         =0x3,
		VS_INTERRUPT                     =0x4,
		VS_BLOCK                         =0x5,
		VS_EVADE                         =0x6,
		VS_IMMUNE                        =0x7,
		VS_DEFLECT                       =0x8,
	};

	public enum WeaponModeUpdateFields 
	{
		WEAPONMODE_NORMALMODE            =0x0,
		WEAPONMODE_SHEATHEDMODE          =0x1,
		WEAPONMODE_RANGEDMODE            =0x2,
	};

	public enum CombatHandUpdateFields 
	{
		COMBAT_MAINHAND                  =0x0,
		COMBAT_OFFHAND                   =0x1,
	};


	public enum ItemFlagUpdateFields : uint 
	{
		ITEM_FLAG_NO_PICKUP             = 0x1,
		ITEM_FLAG_CONJURED              = 0x2,
		ITEM_FLAG_HAS_LOOT              = 0x4,
		ITEM_FLAG_EXOTIC                = 0x8,
		ITEM_FLAG_DEPRECATED             =0x10,
		ITEM_FLAG_OBSOLETE               =0x20,
		ITEM_FLAG_PLAYERCAST             =0x40,
		ITEM_FLAG_NO_EQUIPCOOLDOWN       =0x80,
		ITEM_FLAG_INTBONUSINSTEAD        =0x100,
		ITEM_FLAG_IS_WRAPPER             =0x200,
		ITEM_FLAG_USES_RESOURCES         =0x400,
		ITEM_FLAG_MULTI_DROP             =0x800,
		ITEM_FLAG_BRIEFSPELLEFFECTS      =0x1000,
		ITEM_FLAG_PETITION               =0x2000,
		MAX_ITEM_FLAG                    =0x80008002,
		ITEM_FLAG_NUM                    =0xE,
	};

	public enum WeaponSwingSoundTypeUpdateFields 
	{
		WEAPONSWING_LIGHT               = 0x0,
		WEAPONSWING_MEDIUM              = 0x1,
		WEAPONSWING_HEAVY                =0x2,
	};

	public enum UnitEffectAttachPointUpdateFields 
	{
		UNITEFFECT_ATTACHBASE           = 0x0,
		UNITEFFECT_ATTACHHEAD           = 0x1,
		UNITEFFECT_ATTACHLEFTHAND       = 0x2,
		UNITEFFECT_ATTACHRIGHTHAND      = 0x3,
		UNITEFFECT_ATTACHNONE           = 0x4,
		UNITEFFECT_ATTACHBREATH         = 0x5,
		UNITEFFECT_ATTACHCHEST          = 0x6,
		UNITEFFECT_ATTACHSPECIAL1       = 0x7,
		UNITEFFECT_ATTACHSPECIAL2       = 0x8,
		UNITEFFECT_ATTACHSPECIAL3       = 0x9,
		UNITEFFECT_ATTACHCHESTBLOODBACK = 0xA,
		UNITEFFECT_ATTACHCHESTBLOODFRONT= 0xB,
	};

	public enum InteractionUpdateFields 
	{
		INTERACTICON_NONE               = 0x0,
		INTERACTICON_NORMAL             = 0x1,
		INTERACTICON_COMPLETION         = 0x2,
		INTERACTICON_FUTURE             = 0x3,
		INTERACTICON_TAXINODE           = 0x4,
		INTERACTICON_BINDER             = 0x5,
	};

	public enum UnitSpecialEffectUpdateFields 
	{
		SPECIALEFFECT_LOOTART           = 0x0,
		SPECIALEFFECT_LEVELUP           = 0x1,
		SPECIALEFFECT_FOOTSTEPSPRAYSNOW = 0x2,
		SPECIALEFFECT_FOOTSTEPSPRAYSNOWWALK =0x3,
		SPECIALEFFECT_FOOTSTEPDIRT      = 0x4,
		SPECIALEFFECT_FOOTSTEPDIRTWALK  = 0x5,
		SPECIALEFFECT_COLDBREATH        = 0x6,
		SPECIALEFFECT_UNDERWATERBUBBLES = 0x7,
		SPECIALEFFECT_COMBATBLOODSPURTFRONT= 0x8,
		SPECIALEFFECT_UNUSED            = 0x9,
		SPECIALEFFECT_COMBATBLOODSPURTBACK= 0xA,
		SPECIALEFFECT_HITSPLATPHYSICALSMALL= 0xB,
		SPECIALEFFECT_HITSPLATPHYSICALBIG= 0xC,
		SPECIALEFFECT_HITSPLATHOLYSMALL = 0xD,
		SPECIALEFFECT_HITSPLATHOLYBIG   = 0xE,
		SPECIALEFFECT_HITSPLATFIRESMALL = 0xF,
		SPECIALEFFECT_HITSPLATFIREBIG    =0x10,
		SPECIALEFFECT_HITSPLATNATURESMALL =0x11,
		SPECIALEFFECT_HITSPLATNATUREBIG  =0x12,
		SPECIALEFFECT_HITSPLATFROSTSMALL =0x13,
		SPECIALEFFECT_HITSPLATFROSTBIG   =0x14,
		SPECIALEFFECT_HITSPLATSHADOWSMALL =0x15,
		SPECIALEFFECT_HITSPLATSHADOWBIG  =0x16,
		SPECIALEFFECT_COMBATBLOODSPURTFRONTLARGE =0x17,
		SPECIALEFFECT_COMBATBLOODSPURTBACKLARGE =0x18,
		SPECIALEFFECT_FIZZLEPHYSICAL     =0x19,
		SPECIALEFFECT_FIZZLEHOLY         =0x1A,
		SPECIALEFFECT_FIZZLEFIRE         =0x1B,
		SPECIALEFFECT_FIZZLENATURE       =0x1C,
		SPECIALEFFECT_FIZZLEFROST        =0x1D,
		SPECIALEFFECT_FIZZLESHADOW       =0x1E,
		SPECIALEFFECT_COMBATBLOODSPURTGREENFRONT =0x1F,
		SPECIALEFFECT_COMBATBLOODSPURTGREENFRONTLARGE =0x20,
		SPECIALEFFECT_COMBATBLOODSPURTGREENBACK =0x21,
		SPECIALEFFECT_COMBATBLOODSPURTGREENBACKLARGE =0x22,
		SPECIALEFFECT_FOOTSTEPSPRAYWATER =0x23,
		SPECIALEFFECT_FOOTSTEPSPRAYWATERWALK =0x24,
		SPECIALEFFECT_CHARACTERSHAPESHIFT =0x25,
		SPECIALEFFECT_COMBATBLOODSPURTBLACKFRONT =0x26,
		SPECIALEFFECT_COMBATBLOODSPURTBLACKFRONTLARGE =0x27,
		SPECIALEFFECT_COMBATBLOODSPURTBLACKBACK =0x28,
		SPECIALEFFECT_COMBATBLOODSPURTBLACKBACKLARGE =0x29,
		SPECIALEFFECT_RES_EFFECT         =0x2A,
	};

	public enum ItemDFlagUpdateFields 
	{
		ITEM_DFLAG_BOUND                 =0x1,
		ITEM_DFLAG_TRANSLATED            =0x2,
		ITEM_DFLAG_UNLOCKED              =0x4,
		ITEM_DFLAG_WRAPPED               =0x8,
	};

	public enum AIReactionUpdateFields 
	{
		AI_REACT_ALERT                   =0x0,
		AI_REACT_FRIENDLY                =0x1,
		AI_REACT_HOSTILE                 =0x2,
		AI_REACT_AFRAID                  =0x3,
	};

	public enum UnitReactionUpdateFields 
	{
		UNIT_REACTION_HATED              =0x0,
		UNIT_REACTION_HOSTILE            =0x1,
		UNIT_REACTION_UNFRIENDLY         =0x2,
		UNIT_REACTION_NEUTRAL            =0x3,
		UNIT_REACTION_AMIABLE            =0x4,
		UNIT_REACTION_FRIENDLY           =0x5,
		UNIT_REACTION_REVERED            =0x6,
	};

	public enum MissTypeUpdateFields 
	{
		MISS_NONE                        =0x0,
		MISS_PHYSICAL                    =0x1,
		MISS_RESIST                      =0x2,
		MISS_IMMUNE                      =0x3,
		MISS_EVADED                      =0x4,
		MISS_DODGED                      =0x5,
		MISS_PARRIED                     =0x6,
		MISS_BLOCKED                     =0x7,
		MISS_TEMPIMMUNE                  =0x8,
		MISS_DEFLECTED                   =0x9,
	};

	public enum BagResponseUpdateFields 
	{
		BAG_OK                          = 0x0,
		BAG_LEVEL_MISMATCH              = 0x1,
		BAG_SKILL_MISMATCH              = 0x2,
		BAG_SLOT_MISMATCH               = 0x3,
		BAG_FULL                        = 0x4,
		BAG_NO_BAGS_IN_BAGS             = 0x5,
		BAG_AMMO_ONLY                   = 0x6,
		BAG_PROFICIENCY_NEEDED          = 0x7,
		BAG_NO_SLOTS_AVAILABLE          = 0x8,
		BAG_CLASS_NOTALLOWED            = 0x9,
		BAG_RACE_NOTALLOWED             = 0xA,
		BAG_2HWEAPON_ITEMEXISTSINOFFHAND= 0xB,
		BAG_2HWEAPONBEINGWIELDED        = 0xC,
		BAG_2HWEAPON_SKILLNOTFOUND      = 0xD,
		BAG_ITEM_CLASS_MISMATCH         = 0xE,
		BAG_ITEM_SUBTYPE_MISMATCH       = 0xF,
		BAG_ITEM_MAX_COUNT_EXCEEDED      =0x10,
		BAG_SLOT_NOT_EMPTY               =0x11,
		BAG_CANT_STACK                   =0x12,
		BAG_NOT_EQUIPPABLE               =0x13,
		BAG_CANT_SWAP                    =0x14,
		BAG_SLOT_EMPTY                   =0x15,
		BAG_ITEM_NOT_FOUND               =0x16,
		BAG_ITEM_ALREADY_BOUND           =0x17,
		BAG_DROP_TOO_FAR_AWAY            =0x18,
		BAG_ITEM_TOO_FEW_TO_SPLIT        =0x19,
		BAG_ITEM_SPLIT_FAILED            =0x1A,
		BAG_CANT_CAST_ENCHANTMENT        =0x1B,
		BAG_NOT_ENOUGH_GOLD              =0x1C,
		BAG_NOT_A_CONTAINER              =0x1D,
		BAG_NOT_EMPTY                    =0x1E,
		BAG_NOT_OWNER                    =0x1F,
		BAG_ONLY_ONE_QUIVER              =0x20,
		BAG_NOBANKSLOT                   =0x21,
		BAG_NOBANKHERE                   =0x22,
		BAG_ITEM_LOCKED                  =0x23,
		BAG_NOT_WHILE_DEAD               =0x24,
		BAG_CLIENT_LOCKED_OUT            =0x25,
		BAG_ERROR                        =0x26,
		BAG_ONLY_ONE_BOLT                =0x27,
		BAG_ONLY_ONE_AMMO                =0x28,
		BAG_CANT_WRAP_STACKABLE          =0x29,
		BAG_CANT_WRAP_EQUIPPED           =0x2A,
		BAG_CANT_WRAP_WRAPPED            =0x2B,
		BAG_CANT_WRAP_BOUND              =0x2C,
		BAG_CANT_WRAP_UNIQUE             =0x2D,
		BAG_CANT_WRAP_BAGS               =0x2E,
		BAG_LOOT_GONE                    =0x2F,
		BAG_INV_FULL                     =0x30,
		BAG_SOLD_OUT                     =0x31,
		BAG_DONT_LIKE_YOU                =0x32,
		BAG_UNKNOWN_ITEM                 =0x33,
		BAG_STACK_COUNT_EXCEEDED         =0x34,
		BAG_QUANTITY_ZERO                =0x35,
		BAG_DONT_HAVE_THAT_MANY          =0x36,
	};

	public enum VUIUpdateFields 
	{
		VUI_INVENTORYFULL               = 0x0,
		VUI_OUTOFAMMO                   = 0x1,
		VUI_NOEQUIP_LEVEL               = 0x2,
		VUI_NOEQUIP_EVER                = 0x3,
		VUI_BOUND_NODROP                = 0x4,
		VUI_ITEMCOOLING                 = 0x5,
		VUI_CANTDRINKMORE               = 0x6,
		VUI_CANTEATMORE                 = 0x7,
		VUI_CANTINVITE                  = 0x8,
		VUI_INVITEEBUSY                 = 0x9,
		VUI_TARGETTOOFAR                = 0xA,
		VUI_INVALIDTARGET               = 0xB,
		VUI_SPELLCOOLING                = 0xC,
		VUI_CANTLEARN_LEVEL             = 0xD,
		VUI_LOCKED                      = 0xE,
		VUI_NOMANA                      = 0xF,
		VUI_NOTWHILEDEAD                 =0x10,
		VUI_CANTLOOT                     =0x11,
		VUI_CANTCREATE                   =0x12,
		VUI_DECLINEGROUP                 =0x13,
		VUI_ALREADYINGROUP               =0x14,
		VUI_ALREADYINGUILD               =0x15,
		VUI_CANTAFFORDBANKSLOT           =0x16,
		VUI_TOOMANYBANKSLOTS             =0x17,
		VUI_CANTEAT_MOVING               =0x18,
		VUI_NOTABAG                      =0x19,
		VUI_CANTPUTBAG                   =0x1A,
		VUI_WRONGSLOT                    =0x1B,
		VUI_AMMOONLYINBAG                =0x1C,
		VUI_BAGFULL                      =0x1D,
		VUI_ITEMMAXCOUNT                 =0x1E,
		VUI_CANTLOOT_DIDNTKILL           =0x1F,
		VUI_CANTLOOT_WRONGFACING         =0x20,
		VUI_CANTLOOT_LOCKED              =0x21,
		VUI_CANTLOOT_NOTSTANDING         =0x22,
		VUI_CANTLOOT_TOOFAR              =0x23,
		VUI_CANTATTACKRONGDIRECTION      =0x24,
		VUI_CANTATTACK_NOTSTANDING       =0x25,
		VUI_CANTATTACK_NOTARGET          =0x26,
		VUI_NOTENOUGHGOLD                =0x27,
		VUI_NOTENOUGHMONEY               =0x28,
		VUI_CANTEQUIP2H_SKILL            =0x29,
		VUI_CANTEQUIP_2HEQUIPPED         =0x2A,
		VUI_CANTEQUIP2H_NOSKILL          =0x2B,
		VUI_NOTEQUIPPABLE                =0x2C,
		VUI_GENERICNOTARGET              =0x2D,
		VUI_CANTCAST_OUTOFRANGE          =0x2E,
		VUI_POTIONCOOLING                =0x2F,
		VUI_PROFICIENCYNEEDED            =0x30,
		VUI_MUSTEQUIPPITEM               =0x31,
		VUI_ABILITYCOOLING               =0x32,
		VUI_CANTUSEITEM                  =0x33,
		VUI_CHESTINUSE                   =0x34,
		VUI_FOODCOOLING                  =0x35,
		VUI_CANTTAXI_NOMONEY             =0x36,
		VUI_CANTUSELOCKED                =0x37,
		VUI_NOEQUIPSLOTAVAILABLE         =0x38,
		VUI_CANTUSETOOFAR                =0x39,
		VUI_CANTSWAP                     =0x3A,
		VUI_CANTTRADE_SOULBOUND          =0x3B,
		VUI_NOTOWNER                     =0x3C,
		VUI_ITEMLOCKED                   =0x3D,
		VUI_GUILDPERMISSIONS             =0x3E,
		VUI_NORAGE                       =0x3F,
		VUI_NOENERGY                     =0x40,
		VUI_NOFOCUS                      =0x41,
		NUM_VOCALUISOUNDS                =0x42,
		VUI_NONE                         =0x42,
	};


	public enum ObjectUpdateTypeUpdateFields 
	{
		UPDATE_PARTIAL                   =0x0,
		UPDATE_MOVEMENT                  =0x1,
		UPDATE_FULL                      =0x2,
		UPDATE_OUT_OF_RANGE              =0x3,
		UPDATE_IN_RANGE                  =0x4,
	};

	public enum UpdateWhenUpdateFields 
	{
		UPDATE_AFTER_PARENT              =(-1),
		UPDATE_WITH_PARENT               =0x0,
		UPDATE_BEFORE_PARENT             =0x1,
	};

	public enum InventoryTypeUpdateFields 
	{
		INDEX_NON_EQUIP_TYPE            = 0x0,
		INDEX_HEAD_TYPE                 = 0x1,
		INDEX_NECK_TYPE                 = 0x2,
		INDEX_SHOULDER_TYPE             = 0x3,
		INDEX_BODY_TYPE                 = 0x4,
		INDEX_CHEST_TYPE                = 0x5,
		INDEX_WAIST_TYPE                = 0x6,
		INDEX_LEGS_TYPE                 = 0x7,
		INDEX_FEET_TYPE                 = 0x8,
		INDEX_WRIST_TYPE                = 0x9,
		INDEX_HAND_TYPE                 = 0xA,
		INDEX_FINGER_TYPE               = 0xB,
		INDEX_TRINKET_TYPE              = 0xC,
		INDEX_WEAPON_TYPE               = 0xD,
		INDEX_SHIELD_TYPE               = 0xE,
		INDEX_RANGED_TYPE               = 0xF,
		INDEX_CLOAK_TYPE                 =0x10,
		INDEX_2HWEAPON_TYPE              =0x11,
		INDEX_BAG_TYPE                   =0x12,
		INDEX_TABARD_TYPE                =0x13,
		INDEX_ROBE_TYPE                  =0x14,
		INDEX_WEAPONMAINHAND_TYPE        =0x15,
		INDEX_WEAPONOFFHAND_TYPE         =0x16,
		INDEX_HOLDABLE_TYPE              =0x17,
		INDEX_AMMO_TYPE                  =0x18,
		INDEX_THROWN_TYPE                =0x19,
		INDEX_RANGEDRIGHT_TYPE           =0x1A,
		INDEX_NUMSLOTS                   =0x1B,
		INDEX_INVALID_INVENTORYTYPE      =0x1C,
	};

	public enum QuestStateUpdateFields 
	{
		QUEST_GREETING                   =0x0,
		QUEST_OFFER                      =0x1,
		QUEST_ACCEPTED                   =0x2,
		QUEST_REWARD                     =0x3,
	};

	public enum TradeskillLevelUpdateFields 
	{
		TRADESKILL_MEDIUM                =0x1,
		TRADESKILL_EASY                  =0x2,
		TRADESKILL_TRIVIAL               =0x3,
	};

	public enum LootMethodUpdateFields 
	{
		LOOT_METHOD_FREEFORALL           =0x0,
		LOOT_METHOD_ROUNDROBIN           =0x1,
		LOOT_METHOD_MASTERLOOTER         =0x2,
	}; 

	public enum TrackTypeUpdateFields 
	{
		TRACKTYPE_SPELLPRECAST           =0x0,
		TRACKTYPE_SPELLCHANNEL           =0x1,
		TRACKTYPE_FOLLOW                 =0x2,
	};

	

}
