
#ifndef WOWPYTHONSERVER_UPDATEMASKS_H
#define WOWPYTHONSERVER_UPDATEMASKS_H

#define UPDATE_BLOCKS 864

#define UNIT_BLOCKS 5
#define PLAYER_BLOCKS 27

//  List of Indices
//  Commented out fields basically are just placeholders showing how many bits between good Index enums

enum ObjectTypesUpdateFields {
	OBJ_NONE				= 0,
	OBJ_PLAYER				= 1,
	OBJ_CREATURE			= 2, 
	OBJ_SPAWNPOINT			= 3,
	OBJ_ZONE				= 4,
	OBJ_ACCOUNT				= 5,
	OBJ_ITEM				= 6,
	OBJ_ITEMTEMPLATE		= 7,
	OBJ_CREATURETEMPLATE	= 8,
	OBJ_CONTAINER			= 9,
	OBJ_LOOTTABLE			= 10,
	OBJ_PATHGROUP			= 11,
	OBJ_GUILD				= 12,
	OBJ_GAMEOBJECT			= 13,
	OBJ_DYNAMICOBJECT		= 14,
	OBJ_PARTY				= 15,
	OBJ_TYPES				= 16,
};

enum HighGuidUpdateFields {
	ITEMGUID_HIGH		= 0x40000000,
	CONTAINERGUID_HIGH  = 0x40000000,
	CREATUREGUID_HIGH   = 0xF0001000,
	PLAYERGUID_HIGH     = 0,
};

enum ObjectUpdateFields {
	OBJECT_START = 0,
	OBJECT_FIELD_GUID			= 0 + OBJECT_START,
	OBJECT_FIELD_TYPE			= 2 + OBJECT_START,
	OBJECT_FIELD_ENTRY			= 3 + OBJECT_START,
	OBJECT_FIELD_SCALE_X			= 4 + OBJECT_START,
	OBJECT_FIELD_PADDING			= 5 + OBJECT_START,
	OBJECT_END				= 6 + OBJECT_START,
};

enum ItemUpdateFields {
	ITEM_START = OBJECT_END,
	ITEM_FIELD_OWNER			= 0x00 + ITEM_START,
	ITEM_FIELD_CONTAINED			= 0x02 + ITEM_START,
	ITEM_FIELD_CREATOR			= 0x04 + ITEM_START,
	ITEM_FIELD_GIFTCREATOR			= 0x06 + ITEM_START,
	ITEM_FIELD_STACK_COUNT			= 0x08 + ITEM_START,
	ITEM_FIELD_DURATION			= 0x09 + ITEM_START,
	ITEM_FIELD_SPELL_CHARGES		= 0x0A + ITEM_START,
	ITEM_FIELD_FLAGS			= 0x0F + ITEM_START,
	ITEM_FIELD_ENCHANTMENT			= 0x10 + ITEM_START,
	ITEM_FIELD_PROPERTY_SEED		= 0x25 + ITEM_START,
	ITEM_FIELD_RANDOM_PROPERTIES_ID		= 0x26 + ITEM_START,
	ITEM_FIELD_ITEM_TEXT_ID			= 0x27 + ITEM_START,
	ITEM_DURABILITY				= 0x28 + ITEM_START,
	ITEM_MAXDURABILITY			= 0x29 + ITEM_START,
	ITEM_END				= 0x2A + ITEM_START,
		
};

enum ContainerUpdateFields {
	CONTAINER_START = ITEM_END,
	CONTAINER_FIELD_NUM_SLOTS		= 0x00 + CONTAINER_START,
	CONTAINER_ALIGN_PAD			= 0x01 + CONTAINER_START,
	CONTAINER_FIELD_SLOT_1			= 0x02 + CONTAINER_START,
	CONTAINER_END				= 0x2A + CONTAINER_START,	
};

enum UnitUpdateFields {
	UNIT_START = OBJECT_END,	
	UNIT_FIELD_CHARM			= 0x00 + UNIT_START, //2
	UNIT_FIELD_SUMMON			= 0x02 + UNIT_START, //2
	UNIT_FIELD_CHARMEDBY			= 0x04 + UNIT_START, //2
	UNIT_FIELD_SUMMONEDBY			= 0x06 + UNIT_START, //2
	UNIT_FIELD_CREATEDBY			= 0x08 + UNIT_START, //2
	UNIT_FIELD_TARGET			= 0x00A + UNIT_START, //2
	UNIT_FIELD_CHANNEL_OBJECT		= 0x00C + UNIT_START, //2
	UNIT_FIELD_HEALTH			= 0x00E + UNIT_START, //1
	UNIT_FIELD_POWER1			= 0x00F + UNIT_START, //1
	UNIT_FIELD_POWER2			= 0x010 + UNIT_START, //1
	UNIT_FIELD_POWER3			= 0x011 + UNIT_START, //1
	UNIT_FIELD_POWER4			= 0x012 + UNIT_START, //1
	UNIT_FIELD_POWER5			= 0x013 + UNIT_START, //1
	UNIT_FIELD_MAXHEALTH			= 0x014 + UNIT_START, //1
	UNIT_FIELD_MAXPOWER1			= 0x015 + UNIT_START, //1
	UNIT_FIELD_MAXPOWER2			= 0x016 + UNIT_START, //1
	UNIT_FIELD_MAXPOWER3			= 0x017 + UNIT_START, //1
	UNIT_FIELD_MAXPOWER4			= 0x018 + UNIT_START, //1
	UNIT_FIELD_MAXPOWER5			= 0x019 + UNIT_START, //1
	UNIT_FIELD_LEVEL			= 0x01A + UNIT_START, //1
	UNIT_FIELD_FACTIONTEMPLATE		= 0x01B + UNIT_START, //1
	UNIT_FIELD_BYTES_0			= 0x01C + UNIT_START, //1
	UNIT_VIRTUAL_ITEM_SLOT_DISPLAY		= 0x01D + UNIT_START, //3
	UNIT_VIRTUAL_ITEM_INFO			= 0x020 + UNIT_START, //6
	UNIT_FIELD_FLAGS			= 0x026 + UNIT_START, //1
	UNIT_FIELD_AURA		 		= 0x027 + UNIT_START, //38h
	UNIT_FIELD_AURALEVELS			= 0x05F + UNIT_START, //0Ah
	UNIT_FIELD_AURAAPPLICATIONS		= 0x069 + UNIT_START, //0Ah
	UNIT_FIELD_AURAFLAGS			= 0x073 + UNIT_START, //7
	UNIT_FIELD_AURASTATE			= 0x07A + UNIT_START, //1
	UNIT_FIELD_BASEATTACKTIME		= 0x07B + UNIT_START, //2
	UNIT_FIELD_BOUNDINGRADIUS		= 0x07D + UNIT_START, //1
	UNIT_FIELD_COMBATREACH			= 0x07E + UNIT_START, //1
	UNIT_FIELD_DISPLAYID			= 0x07F + UNIT_START, //1
	UNIT_FIELD_NATIVEDISPLAYID		= 0x080 + UNIT_START, //1
	UNIT_FIELD_MOUNTDISPLAYID		= 0x081 + UNIT_START, //1
	UNIT_FIELD_MINDAMAGE			= 0x082 + UNIT_START, //1
	UNIT_FIELD_MAXDAMAGE			= 0x083 + UNIT_START, //1
	UNIT_FIELD_BYTES_1			= 0x084 + UNIT_START, //1
	UNIT_FIELD_PETNUMBER			= 0x085 + UNIT_START, //1
	UNIT_FIELD_PET_NAME_TIMESTAMP		= 0x086 + UNIT_START, //1
	UNIT_FIELD_PETEXPERIENCE		= 0x087 + UNIT_START, //1
	UNIT_FIELD_PETNEXTLEVELEXP		= 0x088 + UNIT_START, //1
	UNIT_DYNAMIC_FLAGS			= 0x089 + UNIT_START, //1
	UNIT_CHANNEL_SPELL			= 0x08A + UNIT_START, //1
	UNIT_MOD_CAST_SPEED			= 0x08B + UNIT_START, //1
	UNIT_CREATED_BY_SPELL			= 0x08C + UNIT_START, //1
	UNIT_NPC_FLAGS		 		= 0x08D + UNIT_START, //1
	UNIT_NPC_EMOTESTATE			= 0x08E + UNIT_START, //1
	UNIT_TRAINING_POINTS			= 0x08F + UNIT_START, //1
	UNIT_FIELD_STAT0			= 0x090 + UNIT_START, //1
	UNIT_FIELD_STAT1			= 0x091 + UNIT_START, //1
	UNIT_FIELD_STAT2			= 0x092 + UNIT_START, //1
	UNIT_FIELD_STAT3			= 0x093 + UNIT_START, //1
	UNIT_FIELD_STAT4			= 0x094 + UNIT_START, //1
	UNIT_FIELD_RESISTANCES			= 0x095 + UNIT_START, //7
	UNIT_FIELD_ATTACKPOWER			= 0x09C + UNIT_START, //1
	UNIT_FIELD_BASE_MANA			= 0x09D + UNIT_START, //1	
	UNIT_ATTACK_POWER_MODS			= 0x09E + UNIT_START, //1	
	UNIT_FIELD_PADDING			= 0x09F + UNIT_START, //1	
	UNIT_END				= 0x0A0 + UNIT_START,
		
};

enum PlayerUpdateFields {

	PLAYER_START = UNIT_END,
	PLAYER_SELECTION			= 0x000 + PLAYER_START, //size 2        
	PLAYER_DUEL_ARBITER			= 0x002 + PLAYER_START, //size 2       
	PLAYER_GUILDID				= 0x004 + PLAYER_START, //size 1        
	PLAYER_GUILDRANK			= 0x005 + PLAYER_START, //size 1        
	PLAYER_BYTES				= 0x006 + PLAYER_START, //size 1        
	PLAYER_BYTES_2				= 0x007 + PLAYER_START, //size 1        
	PLAYER_BYTES_3				= 0x008 + PLAYER_START, //1        
	PLAYER_DUEL_TEAM			= 0x009 + PLAYER_START, //1        
	PLAYER_GUILD_TIMESTAMP			= 0x00A + PLAYER_START, //1        
	PLAYER_FIELD_PAD_0			= 0x00B + PLAYER_START, //1        
	PLAYER_FIELD_INV_SLOT_HEAD		= 0x00C + PLAYER_START, //2Eh        
	PLAYER_FIELD_PACK_SLOT_1		= 0x03A + PLAYER_START, //20h        
	PLAYER_FIELD_BANK_SLOT_1		= 0x05A + PLAYER_START, //30h       
	PLAYER_FIELD_BANKBAG_SLOT_1		= 0x08A + PLAYER_START, //0Ch        
	PLAYER_FIELD_VENDORBUYBACK_SLOT		= 0x096 + PLAYER_START, //2
	PLAYER_FARSIGHT				= 0x098 + PLAYER_START, //2
	PLAYER__FIELD_COMBO_TARGET		= 0x09A + PLAYER_START, //2
	PLAYER_FIELD_BUYBACK_NPC		= 0x09C + PLAYER_START, //2
	PLAYER_XP				= 0x09E + PLAYER_START, //1
	PLAYER_NEXT_LEVEL_XP			= 0x09F + PLAYER_START, //1
	PLAYER_SKILL_INFO_1_1			= 0x00A0 + PLAYER_START, //180
	PLAYER_QUEST_LOG_1_1			= 0x0220 + PLAYER_START, //3C
	PLAYER_CHARACTER_POINTS1		= 0x025C + PLAYER_START, //1
	PLAYER_CHARACTER_POINTS2		= 0x025D + PLAYER_START, //1
	PLAYER_TRACK_CREATURES			= 0x025E + PLAYER_START, //1
	PLAYER_TRACK_RESOURCES			= 0x025F + PLAYER_START, //1
	PLAYER_CHAT_FILTERS			= 0x0260 + PLAYER_START, //1
	PLAYER_BLOCK_PERCENTAGE			= 0x0261 + PLAYER_START, //1
	PLAYER_DODGE_PERCENTAGE			= 0x0262 + PLAYER_START, //1
	PLAYER_PARRY_PERCENTAGE			= 0x0263 + PLAYER_START, //1
	PLAYER_CRIT_PERCENTAGE			= 0x0264 + PLAYER_START, //1
	PLAYER_EXPLORED_ZONES_1			= 0x0265 + PLAYER_START, //20
	PLAYER_REST_STATE_EXPERIENCE		= 0x0285 + PLAYER_START, //1
	PLAYER_FIELD_COINAGE			= 0x0286 + PLAYER_START, //1
	PLAYER_FIELD_POSSTAT0			= 0x0287 + PLAYER_START, //1
	PLAYER_FIELD_POSSTAT1			= 0x0288 + PLAYER_START, //1
	PLAYER_FIELD_POSSTAT2			= 0x0289 + PLAYER_START, //1
	PLAYER_FIELD_POSSTAT3			= 0x028A + PLAYER_START, //1
	PLAYER_FIELD_POSSTAT4			= 0x028B + PLAYER_START, //1
	PLAYER_FIELD_NEGSTAT0			= 0x028C + PLAYER_START, //1
	PLAYER_FIELD_NEGSTAT1			= 0x028D + PLAYER_START, //1
	PLAYER_FIELD_NEGSTAT2			= 0x028E + PLAYER_START, //1
	PLAYER_FIELD_NEGSTAT3			= 0x028F + PLAYER_START, //1
	PLAYER_FIELD_NEGSTAT4			= 0x0290 + PLAYER_START, //1
	PLAYER_FIELD_RESISTANCEBUFFMODSPOSITIVE	= 0x0291 + PLAYER_START, //7
	PLAYER_FIELD_RESISTANCEBUFFMODSNEGATIVE	= 0x0298 + PLAYER_START, //7
	PLAYER_FIELD_MOD_DAMAGE_DONE_POS	= 0x029F + PLAYER_START, //7
	PLAYER_FIELD_MOD_DAMAGE_DONE_NEG	= 0x02A6 + PLAYER_START, //7
	PLAYER_FIELD_MOD_DAMAGE_DONE_PCT	= 0x02AD + PLAYER_START, //7
	PLAYER_FIELD_BYTES			= 0x02B4 + PLAYER_START, //1
	PLAYER_AMMO_ID				= 0x02B5 + PLAYER_START, //1
	PLAYER_FIELD_PVP_MEDALS			= 0x02B6 + PLAYER_START, //1
	PLAYER_FIELD_BUYBACK_ITEM_ID		= 0x02B7 + PLAYER_START, //1
	PLAYER_FIELD_BUYBACK_RANDOM_PROPERTIES_ID	= 0x02B8 + PLAYER_START, //1
	PLAYER_FIELD_BUYBACK_SEED		= 0x02B9 + PLAYER_START, //1
	PLAYER_FIELD_BUYBACK_PRICE		= 0x02BA + PLAYER_START, //1
	PLAYER_FIELD_PADDING			= 0x02BB + PLAYER_START, //1
	PLAYER_END				= 0x02BC + PLAYER_START,


};

enum GameObjectUpdateFields {
    GAMEOBJECT_START = OBJECT_END,
    GAMEOBJECT_DISPLAYID			= 0x00 + GAMEOBJECT_START, //1
    GAMEOBJECT_FLAGS				= 0x01 + GAMEOBJECT_START, //1
    GAMEOBJECT_ROTATION				= 0x02 + GAMEOBJECT_START, //4
    GAMEOBJECT_STATE				= 0x06 + GAMEOBJECT_START, //1
    GAMEOBJECT_TIMESTAMP			= 0x07 + GAMEOBJECT_START, //1
    GAMEOBJECT_POS_X				= 0x08 + GAMEOBJECT_START, //1
    GAMEOBJECT_POS_Y				= 0x09 + GAMEOBJECT_START, //1
    GAMEOBJECT_POS_Z				= 0x00A + GAMEOBJECT_START, //1
    GAMEOBJECT_FACING				= 0x00B + GAMEOBJECT_START, //1
    GAMEOBJECT_DYN_FLAGS			= 0x00C + GAMEOBJECT_START, //1
    GAMEOBJECT_FACTION				= 0x00D + GAMEOBJECT_START, //1
    GAMEOBJECT_TYPE_ID				= 0x00E + GAMEOBJECT_START, //1
    GAMEOBJECT_LEVEL				= 0x00F + GAMEOBJECT_START, //1
    GAMEOBJECT_END				= 0x010 + GAMEOBJECT_START,
	
};

enum DynamicObjectUpdateFields {
    DYNAMICOBJECT_START = GAMEOBJECT_END,
    DYNAMICOBJECT_CASTER			= 0x00 + DYNAMICOBJECT_START,
    DYNAMICOBJECT_BYTES				= 0x02 + DYNAMICOBJECT_START,
    DYNAMICOBJECT_SPELLID			= 0x03 + DYNAMICOBJECT_START,
    DYNAMICOBJECT_RADIUS			= 0x04 + DYNAMICOBJECT_START,
    DYNAMICOBJECT_POS_X				= 0x05 + DYNAMICOBJECT_START,
    DYNAMICOBJECT_POS_Y				= 0x06 + DYNAMICOBJECT_START,
    DYNAMICOBJECT_POS_Z				= 0x07 + DYNAMICOBJECT_START,
    DYNAMICOBJECT_FACING			= 0x08 + DYNAMICOBJECT_START,
    DYNAMICOBJECT_PAD				= 0x09 + DYNAMICOBJECT_START,
    DYNAMICOBJECT_END				= 0x0A + DYNAMICOBJECT_START,
	
};

enum CorpseUpdateFields {
    CORPSE_START = GAMEOBJECT_END,
    CORPSE_FIELD_OWNER				= 0x00 + CORPSE_START,
    CORPSE_FIELD_FACING				= 0x02 + CORPSE_START,
    CORPSE_FIELD_POS_X				= 0x03 + CORPSE_START,
    CORPSE_FIELD_POS_Y				= 0x04 + CORPSE_START,
    CORPSE_FIELD_POS_Z				= 0x05 + CORPSE_START,
    CORPSE_FIELD_DISPLAY_ID			= 0x06 + CORPSE_START,
    CORPSE_FIELD_ITEM0				= 0x07 + CORPSE_START,
    CORPSE_FIELD_ITEM1				= 0x08 + CORPSE_START,
    CORPSE_FIELD_ITEM2				= 0x09 + CORPSE_START,
    CORPSE_FIELD_ITEM3				= 0x0A + CORPSE_START,
    CORPSE_FIELD_ITEM4				= 0x0B + CORPSE_START,
    CORPSE_FIELD_ITEM5				= 0x0C + CORPSE_START,
    CORPSE_FIELD_BYTES_1			= 0x1A + CORPSE_START,
    CORPSE_FIELD_BYTES_2			= 0x1B + CORPSE_START,
    CORPSE_FIELD_GUILD				= 0x1C + CORPSE_START,
    CORPSE_FIELD_FLAGS				= 0x1D + CORPSE_START,
};

enum RaceUpdateFields {
	RACE_HUMAN				= 1,
	RACE_ORC				= 2,
	RACE_DWARF				= 3,
	RACE_NIGHTELF			= 4,
	RACE_UNDEAD				= 5,
	RACE_TAUREN				= 6,
	RACE_GNOME				= 7,
	RACE_TROLL				= 8,
	RACE_GOBLIN				= 9,
};

enum ClassUpdateFields {
	CLASS_WARRIOR			= 1,
	CLASS_PALADIN			= 2,
	CLASS_HUNTER			= 3,
	CLASS_ROGUE				= 4,
	CLASS_PRIEST			= 5,
	CLASS_SHAMAN			= 7,
	CLASS_MAGE				= 8,
	CLASS_WARLOCK			= 9,		
	CLASS_DRUID				= 0x0B,
};
/*
#define DEFAULT_PLAYER_RUN_SPEED 		7.0f
#define DEFAULT_PLAYER_WALK_SPEED 		2.5f
#define DEFAULT_PLAYER_SWIM_SPEED 		4.7222223f
#define DEFAULT_PLAYER_TURN_RATE 		3.141593f


#define SAYDIST					(25.0f)
#define EMOTEDIST				(25.0f)
#define YELLDIST				(50.0f)
#define SPELLDIST				(25.0f)
#define ATTACKDIST				(25.0f)
#define WHODIST					(200.0f)
*/

enum DamageTypeUpdateFields {
	DMGTYPE_WEAPON				= 1,
	DMGTYPE_SPELL				= 2,
};

enum ChatUpdateFields {
	CHAT_SAY				= 0,
	CHAT_PARTY				= 1,
	CHAT_GUILD				= 2,
	CHAT_OFFICER			= 3,
	CHAT_YELL				= 4,
	CHAT_WHISPER			= 5,
	CHAT_EMOTE				= 7,
	CHAT_MOTD				= 9,
	CHAT_AFK				= 19,
	CHAT_DND				= 20,
};

enum GuildRankUpdateFields {
	GUILDRANK_GM 				= 0,
	GUILDRANK_OFFICER 			= 1,
	GUILDRANK_VETERAN 			= 2,
	GUILDRANK_MEMBER 			= 3,
	GUILDRANK_INITIATE 			= 4,
};

enum PartyRankUpdateFields {
	PARTYRANK_LEADER 			= 0,
	PARTYRANK_MEMBER 			= 1,
	PARTYRANK_INVITE            = 1,
};

enum SlotUpdateFields {
	SLOT_HEAD			= 0,
	SLOT_NECK			= 1,
	SLOT_SHOULDERS		= 2,
	SLOT_SHIRT			= 3,
	SLOT_CHEST			= 4,
	SLOT_WAIST			= 5,
	SLOT_LEGS			= 6,
	SLOT_FEET			= 7,
	SLOT_WRISTS			= 8,
	SLOT_HANDS			= 9,
	SLOT_FINGERL		= 10,
	SLOT_FINGERR		= 11,
	SLOT_TRINKETL		= 12,
	SLOT_TRINKETR		= 13,
	SLOT_BACK			= 14,
	SLOT_MAINHAND		= 15,
	SLOT_OFFHAND		= 16,
	SLOT_RANGED			= 17,
	SLOT_TABARD			= 18,
	SLOT_BAG1			= 19,
	SLOT_BAG2			= 20,
	SLOT_BAG3			= 21,
	SLOT_BAG4			= 22,
	SLOT_INBACKPACK		= 23,
	SLOT_BANK			= 39,
	SLOT_BANKBAGS		= 63,
};

enum WORN {
	WORN_NONE			= 0,
	WORN_HEAD			= 1,
	WORN_NECK			= 2,
	WORN_SHOULDER		= 3,
	WORN_SHIRT			= 4,
	WORN_CHEST			= 5,
	WORN_WAIST			= 6,
	WORN_PANTS			= 7,
	WORN_BOOTS			= 8,
	WORN_BRACERS		= 9,
	WORN_HAND			= 10,
	WORN_FINGER			= 11,
	WORN_TRINKET		= 12,
	WORN_1H				= 13,
	WORN_SHIELD			= 14,
	WORN_RANGED			= 15,
	WORN_BACK			= 16,
	WORN_2H				= 17,
	WORN_JUNK			= 18,
	WORN_BAG			= 18,
	WORN_TABARD			= 19,
	WORN_ROBE			= 20,
	WORN_MAINHAND		= 21,
	WORN_OFFHAND		= 22,
	WORN_HELD			= 23,
	WORN_AMMO			= 24,
	WORN_THROWN			= 25,
	WORN_RANGEDRIGHT 	= 26,
	WORN_NUM_TYPES  	= 27,
};

enum ItemTypeUpdateFields {
	ITEMTYPE_CONSUMABLE		= 0x00,
	ITEMTYPE_CONTAINER		= 0x01,
	ITEMTYPE_WEAPON			= 0x02,
	ITEMTYPE_ARMOR			= 0x04,
	ITEMTYPE_ARMOUR			= 0x04,
	ITEMTYPE_REAGENT		= 0x05,
	ITEMTYPE_PROJECTILE		= 0x06,
	ITEMTYPE_TRADEGOODS		= 0x07,
	ITEMTYPE_BOOK			= 0x09,
	ITEMTYPE_QUIVER			= 0x0B,
	ITEMTYPE_QUEST			= 0x0C,
	ITEMTYPE_KEY			= 0x0D,
	ITEMTYPE_PERMANENT		= 0x0E,
	ITEMTYPE_JUNK			= 0x0F,
	NUM_ITEMTYPES			= 0x10,
};

enum WeaponSubtypeUpdateFields {

	WEAPONSUBTYPE_ONEHANDAXE = 0,
	WEAPONSUBTYPE_TWOHANDAXE = 1,
	WEAPONSUBTYPE_BOW = 2,
	WEAPONSUBTYPE_GUN = 3,
	WEAPONSUBTYPE_ONEHANDBLUNT = 4,
	WEAPONSUBTYPE_TWOHANDBLUNT = 5,
	WEAPONSUBTYPE_POLEARM = 6,
	WEAPONSUBTYPE_ONEHANDSWORD = 7,
	WEAPONSUBTYPE_TWOHANDSWORD = 8,
	WEAPONSUBTYPE_STAFF = 10,
	WEAPONSUBTYPE_ONEHANDEXOTIC = 11,
	WEAPONSUBTYPE_TWOHANDEXOTIC = 12,
	WEAPONSUBTYPE_UNARMED = 13,
	WEAPONSUBTYPE_GENERIC = 14,
	WEAPONSUBTYPE_DAGGER = 15,
	WEAPONSUBTYPE_THROWN = 16,
	WEAPONSUBTYPE_SPEAR = 17,
	WEAPONSUBTYPE_CROSSBOW = 18,
	WEAPONSUBTYPE_WAND = 19,
};

enum ArmourSubtypeUpdateFields {

	ARMOURSUBTYPE_GENERIC,
	ARMOURSUBTYPE_CLOTH,
	ARMOURSUBTYPE_LEATHER,
	ARMOURSUBTYPE_MAIL,
	ARMOURSUBTYPE_PLATE,
	ARMOURSUBTYPE_BUCKLER,
	ARMOURSUBTYPE_SHIELD,
};

enum QuiverSubtypeUpdateFields {

	QUIVERSUBTYPE_OBSOLETE,
	QUIVERSUBTYPE_BOLT,
	QUIVERSUBTYPE_ARROW,
	QUIVERSUBTYPE_AMMO,
};

enum ProjectileSubtypeUpdateFields {

	PROJECTILESUBTYPE_WAND,
	PROJECTILESUBTYPE_BOLT,
	PROJECTILESUBTYPE_ARROW,
	PROJECTILESUBTYPE_BULLET,
	PROJECTILESUBTYPE_THROWN,
};

enum SheatheTypeUpdateFields {

	SHEATHETYPE_NONE,
	SHEATHETYPE_MAINHAND,
	SHEATHETYPE_OFFHAND,
	SHEATHETYPE_LARGEWEAPONLEFT,
	SHEATHETYPE_LARGEWEAPONRIGHT,
	SHEATHETYPE_HIPWEAPONLEFT,
	SHEATHETYPE_HIPWEAPONRIGHT,
	SHEATHETYPE_SHIELD,
	SHEATHETYPE_NUM_TYPES,
};

enum RegenerationUpdateFields {

	PLAYER_REGEN_HPS		= 5,
	PLAYER_REGEN_MANA		= 5,
	CREATURE_REGEN_HPS		= 10,
	CREATURE_REGEN_MANA		= 10,
	CREATURE_REGEN_ENERGY   = 10,
};

enum StatusUpdateFields {
	STATUS_NORMAL	= 0x00,
	STATUS_AFK		= 0x04,
	STATUS_DND		= 0x08,
	STATUS_GM		= 0x10,
};

enum NPCTypeUpdateFields {
	NPCTYPE_NONE			= 0x00,
	NPCTYPE_MERCHANT		= 0x01, 
	NPCTYPE_QUESTGIVER		= 0x02, 
	NPCTYPE_TAXI			= 0x04, 
	NPCTYPE_TRAINER			= 0x08, 
	NPCTYPE_BINDER			= 0x20, 
	NPCTYPE_BANKER			= 0x40, 
	NPCTYPE_PETITION		= 0x80,   
	NPCTYPE_TABARD			= 0x100,
};

enum UnitStandStateUpdateFields {
	UNIT_STANDING			= 0,
	UNIT_SITTING			= 1,
	UNIT_SITTINGCHAIR		= 2,
	UNIT_SLEEPING			= 3,
	UNIT_SITTINGCHAIRLOW	= 4,
	UNIT_SITTINGCHAIRMEDIUM = 5,
	UNIT_SITTINGCHAIRHIGH	= 6,
	UNIT_DEAD				= 7,
	UNIT_KNEEL				= 8,
};

enum ChairStateUpdateFields {
	UNIT_NUMSTANDSTATES		= 9,
	UNIT_NUMCHAIRSTATES		= 3,
	UNIT_FIRSTCHAIRSIT		= 4,
	UNIT_LASTCHAIRSIT		= 6,
};

enum UnitMoveFlagUpdateFields {
	MOVEFLAG_FORWARD = 1,
  	MOVEFLAG_BACKWARD = 2,
 	MOVEFLAG_STRAFE_LEFT = 4,
 	MOVEFLAG_STRAFE_RIGHT = 8,
 	MOVEFLAG_LEFT = 0x10,
 	MOVEFLAG_RIGHT = 0x20,
 	MOVEFLAG_PITCH_UP =0x40,
 	MOVEFLAG_PITCH_DOWN = 0x80,
 	MOVEFLAG_WALK = 0x100,
 	MOVEFLAG_TIME_VALID = 0x200,
 	MOVEFLAG_IMMOBILIZED = 0x400,
 	MOVEFLAG_DONTCOLLIDE = 0x800,
 	MOVEFLAG_REDIRECTED = 0x1000,
 	MOVEFLAG_ROOTED = 0x2000,
 	MOVEFLAG_FALLING = 0x4000,
 	MOVEFLAG_FALLEN_FAR = 0x8000,
 	MOVEFLAG_PENDING_STOP = 0x10000,
 	MOVEFLAG_PENDING_UNSTRAFE = 0x20000,
 	MOVEFLAG_PENDING_FALL = 0x40000,
 	MOVEFLAG_PENDING_FORWARD = 0x80000,
 	MOVEFLAG_PENDING_BACKWARD = 0x100000,
 	MOVEFLAG_PENDING_STR_LEFT = 0x200000,
 	MOVEFLAG_PENDING_STR_RGHT = 0x400000,
 	MOVEFLAG_PEND_MOVE_MASK   = 0x180000,
 	MOVEFLAG_PEND_STRAFE_MASK = 0x600000,
 	MOVEFLAG_PENDING_MASK     = 0x7f0000,
 	MOVEFLAG_MOVED            = 0x800000,
 	MOVEFLAG_SLIDING      = 0x1000000,
 	MOVEFLAG_SWIMMING     = 0x2000000,
 	MOVEFLAG_SPLINE_MOVER = 0x4000000,
 	MOVEFLAG_SPEED_DIRTY  = 0x8000000,
 	MOVEFLAG_HALTED       = 0x10000000,
 	MOVEFLAG_NUDGE        = 0x20000000,
 	MOVEFLAG_FALL_MASK    = 0x100c000,
 	MOVEFLAG_LOCAL        = 0x80400000,
 	MOVEFLAG_MOVE_MASK        = 0x30000,
 	MOVEFLAG_TURN_MASK        = 0x300000,
 	MOVEFLAG_PITCH_MASK       = 0xc00000,
 	MOVEFLAG_STRAFE_MASK      = 0xc0000,
 	MOVEFLAG_MOTION_MASK      = 0xff0000,
 	MOVEFLAG_STOPPED_MASK     = 0x3100f,
};

enum TradeStatusUpdateFields {
 TRADE_STATUS_PLAYER_BUSY         =0x0,
 TRADE_STATUS_PROPOSED            =0x1,
 TRADE_STATUS_INITIATED           =0x2,
 TRADE_STATUS_CANCELLED           =0x3,
 TRADE_STATUS_ACCEPTED            =0x4,
 TRADE_STATUS_ALREADY_TRADING     =0x5,
 TRADE_STATUS_PLAYER_NOT_FOUND    =0x6,
 TRADE_STATUS_STATE_CHANGED       =0x7,
 TRADE_STATUS_COMPLETE            =0x8,
 TRADE_STATUS_UNACCEPTED          =0x9,
 TRADE_STATUS_TOO_FAR_AWAY        =0xA,
 TRADE_STATUS_WRONG_FACTION       =0xB,
 TRADE_STATUS_FAILED              =0xC,
 TRADE_STATUS_DEAD                =0xD,
 TRADE_STATUS_PETITION            =0xE,
 TRADE_STATUS_PLAYER_IGNORED      =0xF,
};

enum CraftLevelUpdateFields {
 CRAFT_NONE                       =0x0,
 CRAFT_OPTIMAL                    =0x1,
 CRAFT_MEDIUM                     =0x2,
 CRAFT_EASY                       =0x3,
 CRAFT_TRIVIAL                    =0x4,
};
#define NUM_CRAFT_CATEGORIES             0x5

enum SpellTypeUpdateFields {
 PLAYER_SPELL                     =0x0,
 PLAYER_ABILITY                   =0x1,
 PET_SPELL                        =0x2,
};
#define NUM_SPELL_TYPES                  0x3

enum TrainerServiceTypeUpdateFields {
 TRAINER_SERVICE_AVAILABLE        =0x0,
 TRAINER_SERVICE_UNAVAILABLE      =0x1,
 TRAINER_SERVICE_USED             =0x2,
 TRAINER_SERVICE_NOT_SHOWN        =0x3,
 TRAINER_SERVICE_NEVER            =0x4,
 TRAINER_SERVICE_NO_PET           =0x5,
};
#define NUM_TRAINER_SERVICE_TYPES        0x6

enum TrainerTypeUpdateFields {
 TRAINER_TYPE_GENERAL             =0x0,
 TRAINER_TYPE_TALENTS             =0x1,
 TRAINER_TYPE_TRADESKILLS         =0x2,
 TRAINER_TYPE_PET                 =0x3,
};
#define NUM_TRAINER_TYPES                0x4

enum SpellShadowUpdateFields {
 SPELL_GOOD                       =0x0,
 SPELL_BAD                        =0x1,
 SPELL_NONE						  =0x3,
};
#define NUM_SPELL_SHADOWS                0x2

enum ScriptEventUpdateFields {
 SCRIPT_UNIT_COMBAT               =0xB2,
 SCRIPT_UNIT_SPELLMISS            =0xB3,
 SCRIPT_UNIT_NAME_UPDATE          =0xB4,
 SCRIPT_UNIT_PORTRAIT_UPDATE      =0xB5,
 SCRIPT_UNIT_MODEL_CHANGED        =0xB6,
 SCRIPT_UNIT_INVENTORY_CHANGED    =0xB7,
 SCRIPT_ITEM_LOCK_CHANGED         =0xB8,
 SCRIPT_PLAYER_XP_UPDATE          =0xB9,
 SCRIPT_PLAYER_REGEN_DISABLED     =0xBA,
 SCRIPT_PLAYER_REGEN_ENABLED      =0xBB,
 SCRIPT_PLAYER_AURAS_CHANGED      =0xBC,
 SCRIPT_PLAYER_ENTER_COMBAT       =0xBD,
 SCRIPT_PLAYER_LEAVE_COMBAT       =0xBE,
 SCRIPT_PLAYER_TARGET_CHANGED     =0xBF,
 SCRIPT_PLAYER_PET_CHANGED        =0xC0,
 SCRIPT_PLAYER_CONTROL_LOST       =0xC1,
 SCRIPT_PLAYER_CONTROL_GAINED     =0xC2,
 SCRIPT_PLAYER_LEVEL_UP           =0xC3,
 SCRIPT_ZONE_CHANGED              =0xC4,
 SCRIPT_MINIMAP_ZONE_CHANGED      =0xC5,
 SCRIPT_MINIMAP_UPDATE_ZOOM       =0xC6,
 SCRIPT_SCREENSHOT_SUCCEEDED      =0xC7,
 SCRIPT_SCREENSHOT_FAILED         =0xC8,
 SCRIPT_ACTIONBAR_SHOWGRID        =0xC9,
 SCRIPT_ACTIONBAR_HIDEGRID        =0xCA,
 SCRIPT_ACTIONBAR_PAGE_CHANGED    =0xCB,
 SCRIPT_ACTIONBAR_SLOT_CHANGED    =0xCC,
 SCRIPT_ACTIONBAR_UPDATE_STATE    =0xCD,
 SCRIPT_ACTIONBAR_UPDATE_USABLE   =0xCE,
 SCRIPT_ACTIONBAR_UPDATE_COOLDOWN =0xCF,
 SCRIPT_UPDATE_BONUS_ACTIONBAR    =0xD0,
 SCRIPT_PARTY_MEMBERS_CHANGED     =0xD1,
 SCRIPT_PARTY_LEADER_CHANGED      =0xD2,
 SCRIPT_PARTY_MEMBER_ENABLE       =0xD3,
 SCRIPT_PARTY_MEMBER_DISABLE      =0xD4,
 SCRIPT_PARTY_LOOT_METHOD_CHANGED =0xD5,
 SCRIPT_SYSMSG                    =0xD6,
 SCRIPT_UI_ERROR_MESSAGE          =0xD7,
 SCRIPT_UI_INFO_MESSAGE           =0xD8,
 SCRIPT_CHAT_MSG_SAY              =0xD9,
 SCRIPT_CHAT_MSG_PARTY            =0xDA,
 SCRIPT_CHAT_MSG_GUILD            =0xDB,
 SCRIPT_CHAT_MSG_OFFICER          =0xDC,
 SCRIPT_CHAT_MSG_YELL             =0xDD,
 SCRIPT_CHAT_MSG_WHISPER          =0xDE,
 SCRIPT_CHAT_MSG_WHISPER_INFORM   =0xDF,
 SCRIPT_CHAT_MSG_EMOTE            =0xE0,
 SCRIPT_CHAT_MSG_TEXT_EMOTE       =0xE1,
 SCRIPT_CHAT_MSG_SYSTEM           =0xE2,
 SCRIPT_CHAT_MSG_MONSTER_SAY      =0xE3,
 SCRIPT_CHAT_MSG_MONSTER_YELL     =0xE4,
 SCRIPT_CHAT_MSG_MONSTER_EMOTE    =0xE5,
 SCRIPT_CHAT_MSG_CHANNEL          =0xE6,
 SCRIPT_CHAT_MSG_CHANNEL_JOIN     =0xE7,
 SCRIPT_CHAT_MSG_CHANNEL_LEAVE    =0xE8,
 SCRIPT_CHAT_MSG_CHANNEL_LIST     =0xE9,
 SCRIPT_CHAT_MSG_CHANNEL_NOTICE   =0xEA,
 SCRIPT_CHAT_MSG_CHANNEL_NOTICE_USER =0xEB,
 SCRIPT_CHAT_MSG_AFK              =0xEC,
 SCRIPT_CHAT_MSG_DND              =0xED,
 SCRIPT_CHAT_MSG_COMBAT_LOG       =0xEE,
 SCRIPT_CHAT_MSG_IGNORED          =0xEF,
 SCRIPT_CHAT_MSG_SKILL            =0xF0,
 SCRIPT_CHAT_MSG_LOOT             =0xF1,
 SCRIPT_LANGUAGE_LIST_CHANGED     =0xF2,
 SCRIPT_TIME_PLAYED_MSG           =0xF3,
 SCRIPT_SPELLS_CHANGED            =0xF4,
 SCRIPT_CURRENT_SPELL_CAST_CHANGED =0xF5,
 SCRIPT_SPELL_UPDATE_COOLDOWN     =0xF6,
 SCRIPT_CHARACTER_POINTS_CHANGED  =0xF7,
 SCRIPT_SKILL_LINES_CHANGED       =0xF8,
 SCRIPT_ITEM_PUSH                 =0xF9,
 SCRIPT_LOOT_OPENED               =0xFA,
 SCRIPT_LOOT_SLOT_CLEARED         =0xFB,
 SCRIPT_LOOT_CLOSED               =0xFC,
 SCRIPT_PLAYER_ENTERING_WORLD     =0xFD,
 SCRIPT_PLAYER_LEAVING_WORLD      =0xFE,
 SCRIPT_PLAYER_ALIVE              =0xFF,
 SCRIPT_PLAYER_DEAD               =0x100,
 SCRIPT_PLAYER_CAMPING            =0x101,
 SCRIPT_PLAYER_QUITING            =0x102,
 SCRIPT_PLAYER_STAND              =0x103,
 SCRIPT_PLAYER_SIT                =0x104,
 SCRIPT_RESURRECT_REQUEST         =0x105,
 SCRIPT_PARTY_INVITE_REQUEST      =0x106,
 SCRIPT_PARTY_INVITE_CANCEL       =0x107,
 SCRIPT_GUILD_INVITE_REQUEST      =0x108,
 SCRIPT_GUILD_INVITE_CANCEL       =0x109,
 SCRIPT_TRADE_REQUEST             =0x10A,
 SCRIPT_TRADE_REQUEST_CANCEL      =0x10B,
 SCRIPT_LOOT_BIND_CONFIRM         =0x10C,
 SCRIPT_EQUIP_BIND_CONFIRM        =0x10D,
 SCRIPT_AUTOEQUIP_BIND_CONFIRM    =0x10E,
 SCRIPT_DELETE_ITEM_CONFIRM       =0x10F,
 SCRIPT_CURSOR_UPDATE             =0x110,
 SCRIPT_ITEM_TEXT_BEGIN           =0x111,
 SCRIPT_ITEM_TEXT_TRANSLATION     =0x112,
 SCRIPT_ITEM_TEXT_READY           =0x113,
 SCRIPT_ITEM_TEXT_CLOSED          =0x114,
 SCRIPT_QUEST_GREETING            =0x115,
 SCRIPT_QUEST_DETAIL              =0x116,
 SCRIPT_QUEST_PROGRESS            =0x117,
 SCRIPT_QUEST_COMPLETE            =0x118,
 SCRIPT_QUEST_FINISHED            =0x119,
 SCRIPT_QUEST_ITEM_UPDATE         =0x11A,
 SCRIPT_TAXIMAP_OPENED            =0x11B,
 SCRIPT_TAXIMAP_CLOSED            =0x11C,
 SCRIPT_QUEST_LOG_UPDATE          =0x11D,
 SCRIPT_TRAINER_SHOW              =0x11E,
 SCRIPT_TRAINER_UPDATE            =0x11F,
 SCRIPT_TRAINER_CLOSED            =0x120,
 SCRIPT_CVAR_UPDATE               =0x121,
 SCRIPT_TRADE_SKILL_SHOW          =0x122,
 SCRIPT_TRADE_SKILL_UPDATE        =0x123,
 SCRIPT_TRADE_SKILL_CLOSE         =0x124,
 SCRIPT_MERCHANT_SHOW             =0x125,
 SCRIPT_MERCHANT_UPDATE           =0x126,
 SCRIPT_MERCHANT_CLOSED           =0x127,
 SCRIPT_TRADE_SHOW                =0x128,
 SCRIPT_TRADE_CLOSED              =0x129,
 SCRIPT_TRADE_UPDATE              =0x12A,
 SCRIPT_TRADE_ACCEPT_UPDATE       =0x12B,
 SCRIPT_TRADE_TARGET_ITEM_CHANGED =0x12C,
 SCRIPT_TRADE_PLAYER_ITEM_CHANGED =0x12D,
 SCRIPT_TRADE_MONEY_CHANGED       =0x12E,
 SCRIPT_PLAYER_TRADE_MONEY        =0x12F,
 SCRIPT_BAG_OPEN                  =0x130,
 SCRIPT_BAG_UPDATE                =0x131,
 SCRIPT_BAG_CLOSED                =0x132,
 SCRIPT_BAG_UPDATE_COOLDOWN       =0x133,
 SCRIPT_SOULSTONE_RECEIVED        =0x134,
 SCRIPT_LOCALPLAYER_PET_RENAMED   =0x135,
 SCRIPT_UNIT_ATTACK               =0x136,
 SCRIPT_UNIT_DEFENSE              =0x137,
 SCRIPT_PET_ATTACK_START          =0x138,
 SCRIPT_PET_ATTACK_STOP           =0x139,
 SCRIPT_UPDATE_MOUSEOVER_UNIT     =0x13A,
 SCRIPT_SPELLCAST_START           =0x13B,
 SCRIPT_SPELLCAST_STOP            =0x13C,
 SCRIPT_SPELLCAST_FAILED          =0x13D,
 SCRIPT_SPELLCAST_INTERRUPTED     =0x13E,
 SCRIPT_SPELLCAST_DELAYED         =0x13F,
 SCRIPT_SPELLCAST_CHANNEL_START   =0x140,
 SCRIPT_SPELLCAST_CHANNEL_UPDATE  =0x141,
 SCRIPT_CLEAR_TOOLTIP             =0x142,
 SCRIPT_TOOLTIP_ADD_MONEY         =0x143,
 SCRIPT_PLAYER_GUILD_UPDATE       =0x144,
 SCRIPT_QUEST_ACCEPT_CONFIRM      =0x145,
 SCRIPT_PLAYERBANKSLOTS_CHANGED   =0x146,
 SCRIPT_BANKFRAME_OPENED          =0x147,
 SCRIPT_BANKFRAME_CLOSED          =0x148,
 SCRIPT_PLAYERBANKBAGSLOTS_CHANGED =0x149,
 SCRIPT_FRIENDLIST_UPDATE         =0x14A,
 SCRIPT_IGNORELIST_UPDATE         =0x14B,
 SCRIPT_PLAYER_LOGOUT_FAILED      =0x14C,
 SCRIPT_PET_BAR_UPDATE            =0x14D,
 SCRIPT_PET_BAR_UPDATE_COOLDOWN   =0x14E,
 SCRIPT_PET_BAR_SHOWGRID          =0x14F,
 SCRIPT_PET_BAR_HIDEGRID          =0x150,
 SCRIPT_MINIMAP_PING              =0x151,
 SCRIPT_CHAT_MSG_COMBAT_LOG_ENEMY =0x152,
 SCRIPT_CHAT_MSG_COMBAT_LOG_SELF  =0x153,
 SCRIPT_CHAT_MSG_COMBAT_LOG_PARTY =0x154,
 SCRIPT_CHAT_MSG_COMBAT_LOG_ERROR =0x155,
 SCRIPT_CHAT_MSG_COMBAT_LOG_MISC_INFO =0x156,
 SCRIPT_CRAFT_SHOW                =0x157,
 SCRIPT_CRAFT_UPDATE              =0x158,
 SCRIPT_CRAFT_CLOSE               =0x159,
 SCRIPT_MIRROR_TIMER_START        =0x15A,
 SCRIPT_MIRROR_TIMER_PAUSE        =0x15B,
 SCRIPT_MIRROR_TIMER_STOP         =0x15C,
 SCRIPT_WORLD_MAP_UPDATE          =0x15D,
 SCRIPT_AUTOFOLLOW_BEGIN          =0x15E,
 SCRIPT_AUTOFOLLOW_END            =0x15F,
 SCRIPT_CINEMATIC_FADE            =0x160,
 SCRIPT_CINEMATIC_START           =0x161,
 SCRIPT_CINEMATIC_STOP            =0x162,
 SCRIPT_UPDATE_FACTION            =0x163,
 SCRIPT_CLOSE_WORLD_MAP           =0x164,
 SCRIPT_OPEN_TABARD_FRAME         =0x165,
 SCRIPT_CLOSE_TABARD_FRAME        =0x166,
 SCRIPT_TABARD_CANSAVE_CHANGED    =0x167,
 SCRIPT_SHOW_COMPARE_TOOLTIP      =0x168,
 SCRIPT_GUILD_REGISTRAR_SHOW      =0x169,
 SCRIPT_GUILD_REGISTRAR_CLOSED    =0x16A,
 SCRIPT_DUEL_REQUESTED            =0x16B,
 SCRIPT_DUEL_OUTOFBOUNDS          =0x16C,
 SCRIPT_DUEL_INBOUNDS             =0x16D,
 SCRIPT_DUEL_FINISHED             =0x16E,
 SCRIPT_TUTORIAL_TRIGGER          =0x16F,
 SCRIPT_PET_DISMISS_START         =0x170,
 SCRIPT_UPDATE_BINDINGS           =0x171,
 SCRIPT_UPDATE_SHAPESHIFT_FORMS   =0x172,
 SCRIPT_WHO_LIST_UPDATE           =0x173,
 SCRIPT_UPDATE_LFG                =0x174,
 SCRIPT_PETITION_SHOW             =0x175,
 SCRIPT_PETITION_CLOSED           =0x176,
};
#define NUM_SCRIPTEVENTS                 0x177

enum SpellTargetTypeUpdateFields {
 TARGET_TYPE_CASTER               =0x0,
 TARGET_TYPE_UNIT                 =0x1,
 TARGET_TYPE_FRIENDLY             =0x2,
 TARGET_TYPE_ENEMY                =0x3,
 TARGET_TYPE_PARTY_MEMBER         =0x4,
 TARGET_TYPE_ITEM                 =0x5,
 TARGET_TYPE_LOCATION             =0x6,
 TARGET_TYPE_OBJECT               =0x7,
 TARGET_TYPE_PET                  =0x8,
 TARGET_TYPE_MAINHAND_ITEM        =0x9,
 TARGET_TYPE_OFFHAND_ITEM         =0xA,
 TARGET_TYPE_PARTY                =0xB,
 TARGET_TYPE_MULTIPLE_UNITS       =0xC,
 TARGET_TYPE_MULTIPLE_ENEMIES     =0xD,
 TARGET_TYPE_MULTIPLE_PARTY_MEMBERS =0xE,
 TARGET_TYPE_MASTER               =0xF,
};
#define NUM_SPELL_TARGET_TYPES           0x10

enum UnitSummonTypeUpdateFields {
 UNIT_SUMMON_PET                  =0x0,
 UNIT_SUMMON_MINION               =0x1,
 UNIT_SUMMON_CHARM                =0x2,
 UNIT_SUMMON_GUARDIAN             =0x3,
 UNIT_SUMMON_CREATION             =0x4,
};
#define NUM_UNIT_SUMMON_TYPES            0x5

enum SRectGridUpdateFields {
 SRECTGRID_NAMEPLATES             =0x0,
 SRECTGRID_WORLDTEXT              =0x1,
};
#define NUM_SRECTGRIDS                   0x2

enum AIGroupActionUpdateFields {
 AI_GROUP_SPAWN                   =0x0,
 AI_GROUP_IDLE                    =0x1,
 AI_GROUP_MOVETO                  =0x2,
 AI_GROUP_TELEPORT                =0x3,
 AI_GROUP_WANDER                  =0x4,
 AI_GROUP_WANDER_SPAWNRELATIVE_OBSOLETE =0x5,
 AI_GROUP_WANDER_AREA             =0x6,
 AI_GROUP_FOLLOW_GUID             =0x7,
 AI_GROUP_FOLLOW_PATH             =0x8,
 AI_GROUP_PATROL_LINE             =0x9,
 AI_GROUP_PATROL_CIRCLE           =0xA,
 AI_GROUP_GUARD_GUID              =0xB,
 AI_GROUP_GUARD_AREA              =0xC,
 AI_GROUP_SET_FORMATION           =0xD,
 AI_GROUP_UNIT_CHANGE_MODE_OBSOLETE =0xE,
 AI_GROUP_UNIT_SAY                =0xF,
 AI_GROUP_UNIT_CAST               =0x10,
 AI_GROUP_UNIT_ACTIVATE_OBJECT    =0x11,
 AI_GROUP_GENERATE_EVENT          =0x12,
 AI_GROUP_DESPAWN                 =0x13,
 AI_GROUP_SET_RADIUS_OBSOLETE     =0x14,
 AI_GROUP_SET_FACTION_OBSOLETE    =0x15,
 AI_GROUP_UNIT_SET_FACING         =0x16,
 AI_GROUP_UNIT_FACE_GUID          =0x17,
 AI_GROUP_UNIT_EMOTE              =0x18,
 AI_GROUP_MOVETO_GUID             =0x19,
 AI_GROUP_ATTACK_GUID             =0x1A,
 AI_GROUP_UNIT_MOUNT              =0x1B,
 AI_GROUP_UNIT_DISMOUNT           =0x1C,
 AI_GROUP_BEASTMASTER_ON          =0x1D,
 AI_GROUP_BEASTMASTER_OFF         =0x1E,
 AI_GROUP_UNIT_MODE               =0x1F,
 AI_GROUP_UNIT_MODE_RESET         =0x20,
 AI_GROUP_UNIT_FACTION            =0x21,
 AI_GROUP_UNIT_FACTION_RESET      =0x22,
 AI_GROUP_UNIT_RADIUS             =0x23,
 AI_GROUP_UNIT_RADIUS_RESET       =0x24,
 AI_GROUP_QUEST_COMPLETE          =0x25,
 AI_GROUP_UNIT_QUESTGIVER         =0x26,
 AI_GROUP_UNIT_TRAINER            =0x27,
 AI_GROUP_SPLINE_PATH             =0x28,
 AI_GROUP_PLAYER_ACTION           =0x29,
 AI_GROUP_RETURN_HOME             =0x2A,
 AI_GROUP_UNIT_SAY_RANDOM         =0x2B,
 AI_GROUP_UNIT_YELL               =0x2C,
 AI_GROUP_UNIT_YELL_RANDOM        =0x2D,
 AI_GROUP_UNIT_SET_ITEM_MAINHAND  =0x2E,
 AI_GROUP_UNIT_RESET_ITEM_MAINHAND =0x2F,
 AI_GROUP_UNIT_CHAT_EMOTE         =0x30,
 AI_GROUP_UNIT_CHAT_EMOTE_RANDOM  =0x31,
 AI_GROUP_UNIT_GENERATE_EVENT     =0x32,
 AI_GROUP_VENDOR_IDLE_OBSOLETE    =0x33,
 AI_GROUP_QUEST_FAILED            =0x34,
 AI_GROUP_UNIT_TRIGGERS           =0x35,
 AI_GROUP_UNIT_TRIGGERS_RESET     =0x36,
 AI_GROUP_UNIT_LEAVE_COMBAT       =0x37,
 AI_GROUP_IDLE_COMBAT_START       =0x38,
 AI_GROUP_IDLE_COMBAT_STOP        =0x39,
 AI_GROUP_UNIT_IMMUNEPC           =0x3A,
 AI_GROUP_UNIT_IMMUNEPC_RESET     =0x3B,
 AI_GROUP_UNIT_IMMUNENPC          =0x3C,
 AI_GROUP_UNIT_IMMUNENPC_RESET    =0x3D,
 AI_GROUP_UNIT_UNKILLABLE         =0x3E,
 AI_GROUP_UNIT_UNKILLABLE_RESET   =0x3F,
 AI_GROUP_UNIT_SPELLS             =0x40,
 AI_GROUP_UNIT_SPELLS_RESET       =0x41,
 AI_GROUP_REUSEME                 =0x42,
 AI_GROUP_UNIT_SEND_LOCAL_EVENT   =0x43,
 AI_GROUP_UNIT_BROADCAST_LOCAL_EVENT= 0x44,
 AI_GROUP_UNIT_FLEE               =0x45,
 AI_GROUP_UNIT_RETREAT            =0x46,
 AI_GROUP_OBJECT_CHAT_EMOTE       =0x47,
 AI_GROUP_OBJECT_CHAT_EMOTE_RANDOM =0x48,
 AI_GROUP_AVOID                   =0x49,
 AI_GROUP_AVOID_GUID              =0x4A,
 AI_GROUP_OBJECT_ACTIVATE         =0x4B,
 AI_GROUP_UNIT_ACTIVATE_OBJECTS   =0x4C,
 AI_GROUP_UNIT_STRINGID           =0x4D,
 AI_GROUP_UNIT_STRINGID_RESET     =0x4E,
 AI_GROUP_PERIODIC_EVENT          =0x4F,
 AI_GROUP_UNIT_SET_ITEM_OFFHAND   =0x50,
 AI_GROUP_UNIT_RESET_ITEM_OFFHAND =0x51,
 AI_GROUP_UNIT_SET_ITEM_RANGED    =0x52,
 AI_GROUP_UNIT_RESET_ITEM_RANGED  =0x53,
 AI_GROUP_UNIT_SHEATHE            =0x54,
 AI_GROUP_UNIT_UNSHEATHE          =0x55,
 AI_GROUP_UNIT_CANCEL_CAST        =0x56,
 AI_GROUP_UNIT_CANCEL_AURA        =0x57,
 AI_GROUP_UNIT_FINISH_CAST        =0x58,
 AI_GROUP_EMOTE_STATE             =0x59,
 AI_GROUP_UNIT_CALL_FOR_HELP      =0x5A,
 AI_GROUP_FLIGHT_PATH             =0x5B,
 AI_GROUP_UNIT_COMBAT_TRIGGER     =0x5C,
};
#define NUM_AI_GROUP_ACTIONS             0x5D

enum WeaponParrySeqUpdateFields {
 WEAPONPARRYSEQ_2HTIGHT           =0x0,
 WEAPONPARRYSEQ_2HLOOSE           =0x1,
 WEAPONPARRYSEQ_1H                =0x2,
 WEAPONPARRYSEQ_STAND             =0x3,
};
#define NUM_WEAPONPARRYSEQS              0x4

enum WeaponReadySeqUpdateFields {
 WEAPONREADYSEQ_2HTIGHT           =0x0,
 WEAPONREADYSEQ_2HLOOSE           =0x1,
 WEAPONREADYSEQ_1H                =0x2,
 WEAPONREADYSEQ_BOW               =0x3,
 WEAPONREADYSEQ_RIFLE             =0x4,
 WEAPONREADYSEQ_THROWN            =0x5,
};
#define NUM_WEAPONREADYSEQS              0x6

enum WeaponAttackSeqUpdateFields {
 WEAPONATTACKSEQ_2HTIGHT          =0x0,
 WEAPONATTACKSEQ_2HLOOSE          =0x1,
 WEAPONATTACKSEQ_BOW              =0x2,
 WEAPONATTACKSEQ_1H               =0x3,
 WEAPONATTACKSEQ_RIFLE            =0x4,
 WEAPONATTACKSEQ_THROWN           =0x5,
};
#define NUM_WEAPONATTACKSEQS             0x6

enum WhoSortTypeUpdateFields {
 WHO_SORT_ZONE                    =0x0,
 WHO_SORT_LEVEL                   =0x1,
 WHO_SORT_CLASS                   =0x2,
 WHO_SORT_GROUP                   =0x3,
 WHO_SORT_NAME                    =0x4,
 WHO_SORT_RACE                    =0x5,
 WHO_SORT_GUILD                   =0x6,
};
#define NUM_WHO_SORT_TYPES               0x7

enum PartyStatusUpdateFields {
 PARTY_STATUS_NOT_IN_PARTY        =0x0,
 PARTY_STATUS_IN_PARTY            =0x1,
 PARTY_STATUS_LFG                 =0x2,
};

enum AttachSlotUpdateFields {
 ATTACH_SHIELD                    =0x0,
 ATTACH_HANDR                     =0x1,
 ATTACH_HANDL                     =0x2,
 ATTACH_ELBOWR                    =0x3,
 ATTACH_ELBOWL                    =0x4,
 ATTACH_SHOULDERR                 =0x5,
 ATTACH_SHOULDERL                 =0x6,
 ATTACH_KNEER                     =0x7,
 ATTACH_KNEEL                     =0x8,
 ATTACH_HIPR                      =0x9,
 ATTACH_HIPL                      =0xA,
 ATTACH_HELM                      =0xB,
 ATTACH_BACK                      =0xC,
 ATTACH_SHOULDERFLAPR             =0xD,
 ATTACH_SHOULDERFLAPL             =0xE,
 ATTACH_TORSOBLOODFRONT           =0xF,
 ATTACH_TORSOBLOODBACK            =0x10,
 ATTACH_BREATH                    =0x11,
 ATTACH_PLAYERNAME                =0x12,
 ATTACH_UNITEFFECT_BASE           =0x13,
 ATTACH_UNITEFFECT_HEAD           =0x14,
 ATTACH_UNITEFFECT_SPELLLEFTHAND  =0x15,
 ATTACH_UNITEFFECT_SPELLRIGHTHAND =0x16,
 ATTACH_UNITEFFECT_SPECIAL1       =0x17,
 ATTACH_UNITEFFECT_SPECIAL2       =0x18,
 ATTACH_UNITEFFECT_SPECIAL3       =0x19,
 ATTACH_SHEATH_MAINHAND           =0x1A,
 ATTACH_SHEATH_OFFHAND            =0x1B,
 ATTACH_SHEATH_SHIELD             =0x1C,
 ATTACH_PLAYERNAMEMOUNTED         =0x1D,
 ATTACH_LARGEWEAPONLEFT           =0x1E,
 ATTACH_LARGEWEAPONRIGHT          =0x1F,
 ATTACH_HIPWEAPONLEFT             =0x20,
 ATTACH_HIPWEAPONRIGHT            =0x21,
 ATTACH_TORSOSPELL                =0x22,
 ATTACH_HANDARROW                 =0x23,
 ATTACH_NONE                      =-1,
};
#define NUM_ATTACH_SLOTS                 0x24

enum AnimStateUpdateFields {
 ANIM_STATE_NONE                  =0x0,
 ANIM_STATE_DEAD                  =0x1,
 ANIM_STATE_SPELL                 =0x2,
 ANIM_STATE_IDLE                  =0x3,
 ANIM_STATE_STOP                  =0x4,
 ANIM_STATE_WALK                  =0x5,
 ANIM_STATE_RUN                   =0x6,
 ANIM_STATE_WALK_BACKWARDS        =0x7,
 ANIM_STATE_STRAFE_WALK_LEFT      =0x8,
 ANIM_STATE_STRAFE_WALK_RIGHT     =0x9,
 ANIM_STATE_STRAFE_RUN_LEFT       =0xA,
 ANIM_STATE_STRAFE_RUN_RIGHT      =0xB,
 ANIM_STATE_DIAG_WALK_LEFT        =0xC,
 ANIM_STATE_DIAG_WALK_RIGHT       =0xD,
 ANIM_STATE_DIAG_RUN_LEFT         =0xE,
 ANIM_STATE_DIAG_RUN_RIGHT        =0xF,
 ANIM_STATE_DIAG_BACKWARDS_LEFT   =0x10,
 ANIM_STATE_DIAG_BACKWARDS_RIGHT  =0x11,
 ANIM_STATE_TURNING_LEFT          =0x12,
 ANIM_STATE_TURNING_RIGHT         =0x13,
 ANIM_STATE_SWIM_IDLE             =0x14,
 ANIM_STATE_SWIM                  =0x15,
 ANIM_STATE_SWIM_STRAFE_LEFT      =0x16,
 ANIM_STATE_SWIM_STRAFE_RIGHT     =0x17,
 ANIM_STATE_SWIM_BACKWARDS        =0x18,
 ANIM_STATE_KNEEL                 =0x19,
 ANIM_STATE_RISE                  =0x1A,
 ANIM_STATE_WOUND                 =0x1B,
 ANIM_STATE_CRITICALWOUND         =0x1C,
 ANIM_STATE_STUN                  =0x1D,
 ANIM_STATE_ATTACK_HIT            =0x1E,
 ANIM_STATE_ATTACK_READY          =0x1F,
 ANIM_STATE_ATTACK_MISS           =0x20,
 ANIM_STATE_ATTACKOFF_HIT         =0x21,
 ANIM_STATE_ATTACKOFF_MISS        =0x22,
 ANIM_STATE_PARRY                 =0x23,
 ANIM_STATE_DODGE                 =0x24,
 ANIM_STATE_SPELLPRECAST          =0x25,
 ANIM_STATE_SPELLCAST             =0x26,
 ANIM_STATE_NPC_OBSOLETE          =0x27,
 ANIM_STATE_BLOCK                 =0x28,
 ANIM_STATE_JUMPING               =0x29,
 ANIM_STATE_JUMP_LANDING          =0x2A,
 ANIM_STATE_FALLING               =0x2B,
 ANIM_STATE_LOOTBEGIN             =0x2C,
 ANIM_STATE_LOOTEND               =0x2D,
 ANIM_STATE_EMOTE                 =0x2E,
 ANIM_STATE_SPELLIMPACT           =0x2F,
 ANIM_STATE_MOUNTED               =0x30,
 ANIM_STATE_SPECIALMOUNTANIM      =0x31,
 ANIM_STATE_SITDOWN               =0x32,
 ANIM_STATE_SITTING               =0x33,
 ANIM_STATE_SITUP                 =0x34,
 ANIM_STATE_SLEEPDOWN             =0x35,
 ANIM_STATE_SLEEPING              =0x36,
 ANIM_STATE_SLEEPUP               =0x37,
 ANIM_STATE_SITCHAIRLOW           =0x38,
 ANIM_STATE_SITCHAIRMEDIUM        =0x39,
 ANIM_STATE_SITCHAIRHIGH          =0x3A,
 ANIM_STATE_KNEELDOWN             =0x3B,
 ANIM_STATE_KNEELING              =0x3C,
 ANIM_STATE_KNEELUP               =0x3D,
 ANIM_STATE_CHANNELSPELL          =0x3E,
 ANIM_STATE_SPELLAURA             =0x3F,
};
#define NUM_ANIMSTATES                   0x40
#define ANIM_STATE_FIRST_STRAFE          0x8
#define ANIM_STATE_LAST_STRAFE           0x11
#define INVALID_ANIM_STATE               (-1)

enum VirtualMonsterSlotUpdateFields {
 VIRTUAL_MONSTER_SLOT_MAINHAND    =0x0,
 VIRTUAL_MONSTER_SLOT_OFFHAND     =0x1,
 VIRTUAL_MONSTER_SLOT_RANGED      =0x2,
};
#define NUM_VIRTUAL_MONSTER_SLOTS        0x3

enum CombatMessageTypeUpdateFields {
 COMBATMESSAGETYPE_NORMALHIT      =0x0,
 COMBATMESSAGETYPE_NORMALMISS     =0x1,
 COMBATMESSAGETYPE_NORMALBLOCK    =0x2,
 COMBATMESSAGETYPE_NORMALPARRY    =0x3,
 COMBATMESSAGETYPE_NORMALDODGE    =0x4,
 COMBATMESSAGETYPE_NORMALEVADE    =0x5,
 COMBATMESSAGETYPE_NORMALIMMUNE   =0x6,
};
#define NUM_COMBATMESSAGETYPES           0x7
#define COMBATMESSAGETYPE_UNKNOWN        (-1)

enum SpellVisualAttachUpdateFields {
 SPELL_VISUAL_ATTACH_HEAD         =0x0,
 SPELL_VISUAL_ATTACH_CHEST        =0x1,
 SPELL_VISUAL_ATTACH_BASE         =0x2,
 SPELL_VISUAL_ATTACH_LEFT_HAND    =0x3,
 SPELL_VISUAL_ATTACH_RIGHT_HAND   =0x4,
 SPELL_VISUAL_ATTACH_BREATH       =0x5,
 SPELL_VISUAL_ATTACH_SPECIAL1     =0x6,
 SPELL_VISUAL_ATTACH_SPECIAL2     =0x7,
 SPELL_VISUAL_ATTACH_SPECIAL3     =0x8,
};
#define NUM_SPELL_VISUAL_ATTACH          0x9

enum TexComponentUpdateFields {
 TEX_COMPONENT_SKIN               =0x1,
 TEX_COMPONENT_OBJECT_SKIN        =0x2,
 TEX_COMPONENT_WEAPON_BLADE       =0x3,
 TEX_COMPONENT_WEAPON_HANDLE      =0x4,
 TEX_COMPONENT_ENVIRONMENT        =0x5,
 TEX_COMPONENT_CHAR_HAIR          =0x6,
 TEX_COMPONENT_CHAR_FACIAL_HAIR   =0x7,
 TEX_COMPONENT_SKIN_EXTRA         =0x8,
 TEX_COMPONENT_UI_SKIN            =0x9,
 TEX_COMPONENT_TAUREN_MANE        =0xA,
 TEX_COMPONENT_MONSTER_1          =0xB,
 TEX_COMPONENT_MONSTER_2          =0xC,
 TEX_COMPONENT_MONSTER_3          =0xD,
 TEX_COMPONENT_ITEM_ICON          =0xE,
};
#define NUM_REPLACEABLE_MATERIAL_IDS     0xF

enum ObjAttachUpdateFields {
 OBJATTACH_HELMET                 =0x0,
 OBJATTACH_SHOULDERPAD            =0x1,
 OBJATTACH_MAINHAND               =0x2,
 OBJATTACH_OFFHAND                =0x3,
 OBJATTACH_RANGED                 =0x4,
 OBJATTACH_NUM                    =0x5,
};

enum SheathAttachPointsUpdateFields {
 SHEATHATTACH_NONE                =0x0,
 SHEATHATTACH_MAINHAND            =0x1,
 SHEATHATTACH_OFFHAND             =0x2,
 SHEATHATTACH_LARGEWEAPONLEFT     =0x3,
 SHEATHATTACH_LARGEWEAPONRIGHT    =0x4,
 SHEATHATTACH_HIPWEAPONLEFT       =0x5,
 SHEATHATTACH_HIPWEAPONRIGHT      =0x6,
 SHEATHATTACH_SHIELD              =0x7,
};
#define SHEATHATTACH_NUM_SAVESSHEATHATTACHPOINTS 0x8

enum WorldTextTypeUpdateFields {
 WT_DAMAGE                        =0x0,
 WT_ABSORB                        =0x1,
 WT_CRIT                          =0x2,
 WT_HEALSPELL                     =0x3,
 WT_MISS                          =0x4,
 WT_XPGAIN                        =0x5,
 WT_QUEST                         =0x6,
};
#define NUM_WORLDTEXTTYPES               0x7

enum GameObjAnimStateUpdateFields {
 ANIMSTATE_CLOSED                 =0x0,
 ANIMSTATE_OPENING                =0x1,
 ANIMSTATE_OPEN                   =0x2,
 ANIMSTATE_CLOSING                =0x3,
 ANIMSTATE_DESTROYING             =0x4,
 ANIMSTATE_DESTROYED              =0x5,
 ANIMSTATE_REBUILDING             =0x6,
 ANIMSTATE_FIRSTCUSTOM            =0x7,
 ANIMSTATE_CUSTOM0                =0x7,
 ANIMSTATE_CUSTOM1                =0x8,
 ANIMSTATE_CUSTOM2                =0x9,
 ANIMSTATE_CUSTOM3                =0xA,
};
#define NUM_GAMEOBJ_ANIMSTATES           0xB

enum GuildEventUpdateFields {
 GUILD_EVENT_PROMOTION            =0x0,
 GUILD_EVENT_DEMOTION             =0x1,
 GUILD_EVENT_MOTD                 =0x2,
 GUILD_EVENT_JOINED               =0x3,
 GUILD_EVENT_LEFT                 =0x4,
 GUILD_EVENT_REMOVED              =0x5,
 GUILD_EVENT_LEADER_IS            =0x6,
 GUILD_EVENT_LEADER_CHANGED       =0x7,
 GUILD_EVENT_DISBANDED            =0x8,
 GUILD_EVENT_TABARDCHANGE         =0x9,
};

enum TaxiNodeTypeUpdateFields {
 TAXINODE_NONE                    =0x0,
 TAXINODE_CURRENT                 =0x1,
 TAXINODE_REACHABLE               =0x2,
 TAXINODE_DISTANT                 =0x3,
};
#define TAXINODE_NUMTAXINODES            0x4

enum SpellFailedReason {
 SPELL_FAILED_AFFECTING_COMBAT    =0x0,
 SPELL_FAILED_ALREADY_HAVE_CHARM  =0x1,
 SPELL_FAILED_ALREADY_HAVE_SUMMON =0x2,
 SPELL_FAILED_ALREADY_OPEN        =0x3,
 SPELL_FAILED_AURA_BOUNCED        =0x4,
 SPELL_FAILED_BAD_IMPLICIT_TARGETS =0x5,
 SPELL_FAILED_BAD_TARGETS         =0x6,
 SPELL_FAILED_CANT_BE_CHARMED     =0x7,
 SPELL_FAILED_CANT_STEALTH        =0x8,
 SPELL_FAILED_CASTER_AURASTATE    =0x9,
 SPELL_FAILED_CASTER_DEAD         =0xA,
 SPELL_FAILED_DONT_REPORT         =0xB,
 SPELL_FAILED_EQUIPPED_ITEM       =0xC,
 SPELL_FAILED_EQUIPPED_ITEM_CLASS =0xD,
 SPELL_FAILED_ERROR               =0xE,
 SPELL_FAILED_FIZZLE              =0xF,
 SPELL_FAILED_HUNGER_SATIATED     =0x10,
 SPELL_FAILED_INTERRUPTED         =0x11,
 SPELL_FAILED_INTERRUPTED_COMBAT  =0x12,
 SPELL_FAILED_ITEM_ALREADY_ENCHANTED= 0x13,
 SPELL_FAILED_ITEM_NOT_FOUND      =0x14,
 SPELL_FAILED_ITEM_NOT_READY      =0x15,
 SPELL_FAILED_LEVEL_REQUIREMENT   =0x16,
 SPELL_FAILED_LINE_OF_SIGHT       =0x17,
 SPELL_FAILED_LOWLEVEL            =0x18,
 SPELL_FAILED_LOW_CASTLEVEL       =0x19,
 SPELL_FAILED_MOVING              =0x1A,
 SPELL_FAILED_NEED_AMMO           =0x1B,
 SPELL_FAILED_NEED_AMMO_POUCH     =0x1C,
 SPELL_FAILED_NEED_EXOTIC_AMMO    =0x1D,
 SPELL_FAILED_NOPATH              =0x1E,
 SPELL_FAILED_NOTSTANDING         =0x1F,
 SPELL_FAILED_NOT_BEHIND          =0x20,
 SPELL_FAILED_NOT_BEHIND_OR_SIDE  =0x21,
 SPELL_FAILED_NOT_HERE            =0x22,
 SPELL_FAILED_NOT_KNOWN           =0x23,
 SPELL_FAILED_NOT_MOUNTED         =0x24,
 SPELL_FAILED_NOT_READY           =0x25,
 SPELL_FAILED_NOT_SHAPESHIFT      =0x26,
 SPELL_FAILED_NOT_TRADING         =0x27,
 SPELL_FAILED_NO_AMMO             =0x28,
 SPELL_FAILED_NO_CHARGES_REMAIN   =0x29,
 SPELL_FAILED_NO_ENDURANCE        =0x2A,
 SPELL_FAILED_NO_PET              =0x2B,
 SPELL_FAILED_NO_POWER            =0x2C,
 SPELL_FAILED_ONLY_ABOVEWATER     =0x2D,
 SPELL_FAILED_ONLY_DAYTIME        =0x2E,
 SPELL_FAILED_ONLY_INDOORS        =0x2F,
 SPELL_FAILED_ONLY_MOUNTED        =0x30,
 SPELL_FAILED_ONLY_NIGHTTIME      =0x31,
 SPELL_FAILED_ONLY_OUTDOORS       =0x32,
 SPELL_FAILED_ONLY_SHAPESHIFT     =0x33,
 SPELL_FAILED_ONLY_STEALTHED      =0x34,
 SPELL_FAILED_ONLY_UNDERWATER     =0x35,
 SPELL_FAILED_OUT_OF_RANGE        =0x36,
 SPELL_FAILED_PACIFIED            =0x37,
 SPELL_FAILED_REAGENTS            =0x38,
 SPELL_FAILED_REQUIRES_SPELL_FOCUS =0x39,
 SPELL_FAILED_SILENCED            =0x3A,
 SPELL_FAILED_SPELL_IN_PROGRESS   =0x3B,
 SPELL_FAILED_SPELL_LEARNED       =0x3C,
 SPELL_FAILED_SPELL_UNAVAILABLE   =0x3D,
 SPELL_FAILED_STUNNED             =0x3E,
 SPELL_FAILED_TARGETS_DEAD        =0x3F,
 SPELL_FAILED_TARGET_AFFECTING_COMBAT= 0x40,
 SPELL_FAILED_TARGET_AURASTATE    =0x41,
 SPELL_FAILED_TARGET_ENEMY        =0x42,
 SPELL_FAILED_TARGET_ENRAGED      =0x43,
 SPELL_FAILED_TARGET_FRIENDLY     =0x44,
 SPELL_FAILED_TARGET_IS_PLAYER    =0x45,
 SPELL_FAILED_TARGET_NOT_DEAD     =0x46,
 SPELL_FAILED_TARGET_NOT_IN_PARTY =0x47,
 SPELL_FAILED_TARGET_NO_POCKETS   =0x48,
 SPELL_FAILED_THIRST_SATIATED     =0x49,
 SPELL_FAILED_TOO_CLOSE           =0x4A,
 SPELL_FAILED_TOTEMS              =0x4B,
 SPELL_FAILED_TRY_AGAIN           =0x4C,
 SPELL_FAILED_UNIT_NOT_ATSIDE     =0x4D,
 SPELL_FAILED_UNIT_NOT_BEHIND     =0x4E,
 SPELL_FAILED_UNIT_NOT_INFRONT    =0x4F,
 SPELL_FAILED_NO_MOUNTS_ALLOWED   =0x50,
 SPELL_FAILED_CHEST_IN_USE        =0x51,
 SPELL_FAILED_NO_COMBO_POINTS     =0x52,
 SPELL_FAILED_TARGET_NOT_PLAYER   =0x53,
 SPELL_FAILED_TARGET_DUELING      =0x54,
 SPELL_FAILED_NOTUNSHEATHED       =0x55,
 SPELL_FAILED_NOT_FISHABLE        =0x56,
};
#define SPELL_FAILED_NUMREASONS          0x57

enum GameObjTypeUpdateFields {
 TYPE_DOOR                        =0x0,
 TYPE_BUTTON                      =0x1,
 TYPE_QUESTGIVER                  =0x2,
 TYPE_CHEST                       =0x3,
 TYPE_BINDER                      =0x4,
 TYPE_GENERIC                     =0x5,
 TYPE_TRAP                        =0x6,
 TYPE_CHAIR                       =0x7,
 TYPE_SPELL_FOCUS                 =0x8,
 TYPE_TEXT                        =0x9,
 TYPE_GOOBER                      =0xA,
 TYPE_TRANSPORT                   =0xB,
 TYPE_AREADAMAGE                  =0xC,
 TYPE_CAMERA                      =0xD,
 TYPE_MAP_OBJECT                  =0xE,
 TYPE_MO_TRANSPORT                =0xF,
 TYPE_DUEL_ARBITER                =0x10,
 TYPE_FISHINGNODE                 =0x11,
 TYPE_RITUAL                      =0x12,
};
#define NUM_GAMEOBJECT_TYPE              0x13

enum PropUpdateFields {
 PROP_TYPE                        =0x0,
 PROP_STARTOPEN                   =0x1,
 PROP_STARTDESTROYED              =0x2,
 PROP_AUTOCLOSE                   =0x3,
 PROP_LOCK                        =0x4,
 PROP_QUESTLISTID                 =0x5,
 PROP_CHESTLOOT                   =0x6,
 PROP_CHESTLOOTTIME               =0x7,
 PROP_CONSUMABLE                  =0x8,
 PROP_CHARGES                     =0x9,
 PROP_SPELL                       =0xA,
 PROP_CHAIRSLOTS                  =0xB,
 PROP_CHAIRHEIGHT                 =0xC,
 PROP_CHESTLOOTEDEVENT            =0xD,
 PROP_SPELLFOCUSTYPE              =0xE,
 PROP_TEXTID                      =0xF,
 PROP_TEXTLANGUAGE                =0x10,
 PROP_TEXTMATERIAL                =0x11,
 PROP_HIGHLIGHT                   =0x12,
 PROP_FLOATINGTOOLTIP             =0x13,
 PROP_QUESTID                     =0x14,
 PROP_EVENTID                     =0x15,
 PROP_CUSTOMANIM                  =0x16,
 PROP_COOLDOWN                    =0x17,
 PROP_RADIUS                      =0x18,
 PROP_CHESTMINRESTOCK             =0x19,
 PROP_CHESTMAXRESTOCK             =0x1A,
 PROP_DAMAGE_MIN                  =0x1B,
 PROP_DAMAGE_MAX                  =0x1C,
 PROP_DAMAGE_SCHOOL               =0x1D,
 PROP_LINKED_TRAP                 =0x1E,
 PROP_TRAP_LEVEL                  =0x1F,
 PROP_STARTDELAY                  =0x20,
 PROP_CAMERAID                    =0x21,
 PROP_CASTERS                     =0x22,
 PROP_TAXIPATHID1                 =0x23,
 PROP_TAXIPATHID2                 =0x24,
 PROP_MOVESPEED                   =0x25,
};
#define NUM_PROP                         0x26

enum ValueTypeUpdateFields {
 VALUE_TYPE_TYPE                  =0x0,
 VALUE_TYPE_BOOL                  =0x1,
 VALUE_TYPE_INT                   =0x2,
 VALUE_TYPE_FLOAT                 =0x3,
 VALUE_TYPE_NAME                  =0x4,
 VALUE_TYPE_LOCK                  =0x5,
 VALUE_TYPE_QUESTGIVER            =0x6,
 VALUE_TYPE_LOOTTABLE             =0x7,
 VALUE_TYPE_SPELL                 =0x8,
 VALUE_TYPE_PAGETEXT              =0x9,
 VALUE_TYPE_PAGEMATERIAL          =0xA,
 VALUE_TYPE_TRAP                  =0xB,
 VALUE_TYPE_CAMERA                =0xC,
};
#define NUM_VALUE_TYPE                   0xD

enum GerrUpdateFields {
 GERR_INV_FULL                   = 0x0,
 GERR_CANT_EQUIP_LEVEL_I         = 0x1,
 GERR_CANT_EQUIP_SKILL           = 0x2,
 GERR_CANT_EQUIP_EVER            = 0x3,
 GERR_PROFICIENCY_NEEDED         = 0x4,
 GERR_WRONG_SLOT                 = 0x5,
 GERR_BAG_FULL                   = 0x6,
 GERR_DESTROY_NONEMPTY_BAG       = 0x7,
 GERR_BAG_IN_BAG                 = 0x8,
 GERR_AMMO_ONLY                  = 0x9,
 GERR_NO_SLOT_AVAILABLE          = 0xA,
 GERR_WRONG_BAG_TYPE             = 0xB,
 GERR_ITEM_MAX_COUNT             = 0xC,
 GERR_NOT_EQUIPPABLE             = 0xD,
 GERR_CANT_STACK                 = 0xE,
 GERR_CANT_SWAP                  = 0xF,
 GERR_SLOT_EMPTY                  =0x10,
 GERR_ITEM_NOT_FOUND              =0x11,
 GERR_TOO_FEW_TO_SPLIT            =0x12,
 GERR_SPLIT_FAILED                =0x13,
 GERR_NOT_ENOUGH_GOLD             =0x14,
 GERR_NOT_A_BAG                   =0x15,
 GERR_NOT_OWNER                   =0x16,
 GERR_ONLY_ONE_QUIVER             =0x17,
 GERR_NO_BANK_SLOT                =0x18,
 GERR_NO_BANK_HERE                =0x19,
 GERR_ITEM_LOCKED                 =0x1A,
 GERR_2HANDED_EQUIPPED            =0x1B,
 GERR_VENDOR_NOT_INTERESTED       =0x1C,
 GERR_VENDOR_HATES_YOU            =0x1D,
 GERR_VENDOR_SOLD_OUT             =0x1E,
 GERR_VENDOR_TOO_FAR              =0x1F,
 GERR_NOT_ENOUGH_MONEY            =0x20,
 GERR_RECEIVE_ITEM_S              =0x21,
 GERR_DROP_BOUND_ITEM             =0x22,
 GERR_TRADE_BOUND_ITEM            =0x23,
 GERR_TRADE_QUEST_ITEM            =0x24,
 GERR_TRADE_GROUND_ITEM           =0x25,
 GERR_TRADE_BAG                   =0x26,
 GERR_SPELL_FAILED_S              =0x27,
 GERR_ITEM_COOLDOWN               =0x28,
 GERR_POTION_COOLDOWN             =0x29,
 GERR_FOOD_COOLDOWN               =0x2A,
 GERR_SPELL_COOLDOWN              =0x2B,
 GERR_ABILITY_COOLDOWN            =0x2C,
 GERR_SPELL_ALREADY_KNOWN_S       =0x2D,
 GERR_SKILL_GAINED_S              =0x2E,
 GERR_SKILL_UP_SI                 =0x2F,
 GERR_LEARN_SPELL_S               =0x30,
 GERR_LEARN_ABILITY_S             =0x31,
 GERR_LEARN_RECIPE_S              =0x32,
 GERR_INVITE_PLAYER_S             =0x33,
 GERR_INVITED_TO_GROUP_S          =0x34,
 GERR_ALREADY_IN_GROUP_S          =0x35,
 GERR_PLAYER_BUSY_S               =0x36,
 GERR_NEW_LEADER_S                =0x37,
 GERR_NEW_LEADER_YOU              =0x38,
 GERR_LEFT_GROUP_S                =0x39,
 GERR_LEFT_GROUP_YOU              =0x3A,
 GERR_GROUP_DISBANDED             =0x3B,
 GERR_DECLINE_GROUP_S             =0x3C,
 GERR_JOINED_GROUP_S              =0x3D,
 GERR_UNINVITE_YOU                =0x3E,
 GERR_BAD_PLAYER_NAME_S           =0x3F,
 GERR_NOT_IN_GROUP                =0x40,
 GERR_TARGET_NOT_IN_GROUP_S       =0x41,
 GERR_GROUP_FULL                  =0x42,
 GERR_NOT_LEADER                  =0x43,
 GERR_PLAYER_DIED_S               =0x44,
 GERR_GUILD_CREATE_S              =0x45,
 GERR_GUILD_INVITE_S              =0x46,
 GERR_INVITED_TO_GUILD_SS         =0x47,
 GERR_ALREADY_IN_GUILD_S          =0x48,
 GERR_ALREADY_INVITED_TO_GUILD_S  =0x49,
 GERR_INVITED_TO_GUILD            =0x4A,
 GERR_ALREADY_IN_GUILD            =0x4B,
 GERR_GUILD_ACCEPT                =0x4C,
 GERR_GUILD_DECLINE_S             =0x4D,
 GERR_GUILD_PERMISSIONS           =0x4E,
 GERR_GUILD_JOIN_S                =0x4F,
 GERR_GUILD_FOUNDER_S             =0x50,
 GERR_GUILD_PROMOTE_SS            =0x51,
 GERR_GUILD_DEMOTE_SS             =0x52,
 GERR_GUILD_QUIT_S                =0x53,
 GERR_GUILD_LEAVE_S               =0x54,
 GERR_GUILD_REMOVE_SS             =0x55,
 GERR_GUILD_REMOVE_SELF           =0x56,
 GERR_GUILD_DISBAND_S             =0x57,
 GERR_GUILD_DISBAND_SELF          =0x58,
 GERR_GUILD_LEADER_S              =0x59,
 GERR_GUILD_LEADER_SELF           =0x5A,
 GERR_GUILD_MOTD_S                =0x5B,
 GERR_GUILD_PLAYER_NOT_FOUND_S    =0x5C,
 GERR_GUILD_PLAYER_NOT_IN_GUILD_S =0x5D,
 GERR_GUILD_PLAYER_NOT_IN_GUILD   =0x5E,
 GERR_GUILD_CANT_PROMOTE_S        =0x5F,
 GERR_GUILD_CANT_DEMOTE_S         =0x60,
 GERR_GUILD_NOT_IN_A_GUILD        =0x61,
 GERR_GUILD_INTERNAL              =0x62,
 GERR_GUILD_LEADER_IS_S           =0x63,
 GERR_GUILD_LEADER_CHANGED_SS     =0x64,
 GERR_GUILD_DISBANDED             =0x65,
 GERR_GUILD_NOT_ALLIED            =0x66,
 GERR_GUILD_LEADER_LEAVE          =0x67,
 GERR_GUILD_NAME_INVALID          =0x68,
 GERR_GUILD_NAME_EXISTS_S         =0x69,
 GERR_GUILD_ENTER_NAME            =0x6A,
 GERR_GUILD_NAME_TOO_SHORT        =0x6B,
 GERR_GUILD_NAME_MIXED_LANGUAGES  =0x6C,
 GERR_GUILD_NAME_PROFANE          =0x6D,
 GERR_GUILD_NAME_RESERVED         =0x6E,
 GERR_NO_GUILD_CHARTER            =0x6F,
 GERR_OUT_OF_RANGE                =0x70,
 GERR_PLAYER_DEAD                 =0x71,
 GERR_CLIENT_LOCKED_OUT           =0x72,
 GERR_KILLED_BY_S                 =0x73,
 GERR_LOOT_LOCKED                 =0x74,
 GERR_LOOT_TOO_FAR                =0x75,
 GERR_LOOT_DIDNT_KILL             =0x76,
 GERR_LOOT_BAD_FACING             =0x77,
 GERR_LOOT_NOTSTANDING            =0x78,
 GERR_LOOT_STUNNED                =0x79,
 GERR_LOOT_NO_UI                  =0x7A,
 GERR_QUEST_ACCEPTED_S            =0x7B,
 GERR_QUEST_COMPLETE_S            =0x7C,
 GERR_QUEST_FAILED_S              =0x7D,
 GERR_QUEST_FAILED_BAG_FULL_S     =0x7E,
 GERR_QUEST_FAILED_MAX_COUNT_S    =0x7F,
 GERR_QUEST_FAILED_LOW_LEVEL      =0x80,
 GERR_QUEST_FAILED_MISSING_ITEMS  =0x81,
 GERR_QUEST_REWARD_EXP_I          =0x82,
 GERR_QUEST_REWARD_ITEM_S         =0x83,
 GERR_QUEST_REWARD_MONEY_S        =0x84,
 GERR_QUEST_MUST_CHOOSE           =0x85,
 GERR_QUEST_LOG_FULL              =0x86,
 GERR_COMBAT_DAMAGE_SSI           =0x87,
 GERR_INSPECT_S                   =0x88,
 GERR_CANT_USE_ITEM               =0x89,
 GERR_MUST_EQUIP_ITEM             =0x8A,
 GERR_PASSIVE_ABILITY             =0x8B,
 GERR_2HSKILLNOTFOUND             =0x8C,
 GERR_NO_ATTACK_TARGET            =0x8D,
 GERR_INVALID_ATTACK_TARGET       =0x8E,
 GERR_ATTACK_PACIFIED             =0x8F,
 GERR_ATTACK_DEAD                 =0x90,
 GERR_HUNGER_VERY_LOW             =0x91,
 GERR_HUNGER_LOW                  =0x92,
 GERR_HUNGER_MED                  =0x93,
 GERR_HUNGER_HIGH                 =0x94,
 GERR_HUNGER_SATIATED             =0x95,
 GERR_THIRST_VERY_LOW             =0x96,
 GERR_THIRST_LOW                  =0x97,
 GERR_THIRST_MED                  =0x98,
 GERR_THIRST_HIGH                 =0x99,
 GERR_THIRST_SATIATED             =0x9A,
 GERR_TAXISAMENODE                =0x9B,
 GERR_TAXINOSUCHPATH              =0x9C,
 GERR_TAXIUNSPECIFIEDSERVERERROR  =0x9D,
 GERR_TAXINOTENOUGHMONEY          =0x9E,
 GERR_TAXITOOFARAWAY              =0x9F,
 GERR_TAXINOVENDORNEARBY          =0xA0,
 GERR_TAXINOTVISITED              =0xA1,
 GERR_TAXIPLAYERBUSY              =0xA2,
 GERR_TAXIPLAYERALREADYMOUNTED    =0xA3,
 GERR_TAXIPLAYERSHAPESHIFTED      =0xA4,
 GERR_TAXIPLAYERMOVING            =0xA5,
 GERR_TAXINOPATHS                 =0xA6,
 GERR_NO_REPLY_TARGET             =0xA7,
 GERR_GENERIC_NO_TARGET           =0xA8,
 GERR_INITIATE_TRADE_S            =0xA9,
 GERR_TRADE_REQUEST_S             =0xAA,
 GERR_TRADE_TOO_FAR               =0xAB,
 GERR_TRADE_CANCELLED             =0xAC,
 GERR_TRADE_COMPLETE              =0xAD,
 GERR_TRADE_BAG_FULL              =0xAE,
 GERR_TRADE_TARGET_BAG_FULL       =0xAF,
 GERR_TRADE_MAX_COUNT_EXCEEDED    =0xB0,
 GERR_TRADE_TARGET_MAX_COUNT_EXCEEDED= 0xB1,
 GERR_MOUNT_INVALIDMOUNTEE        =0xB2,
 GERR_MOUNT_TOOFARAWAY            =0xB3,
 GERR_MOUNT_ALREADYMOUNTED        =0xB4,
 GERR_MOUNT_NOTMOUNTABLE          =0xB5,
 GERR_MOUNT_NOTYOURPET            =0xB6,
 GERR_MOUNT_OTHER                 =0xB7,
 GERR_MOUNT_LOOTING               =0xB8,
 GERR_MOUNT_RACECANTMOUNT         =0xB9,
 GERR_MOUNT_SHAPESHIFTED          =0xBA,
 GERR_DISMOUNT_NOPET              =0xBB,
 GERR_DISMOUNT_NOTMOUNTED         =0xBC,
 GERR_DISMOUNT_NOTYOURPET         =0xBD,
 GERR_SPELL_FAILED_TOTEMS         =0xBE,
 GERR_SPELL_FAILED_REAGENTS       =0xBF,
 GERR_SPELL_FAILED_EQUIPPED_ITEM  =0xC0,
 GERR_SPELL_FAILED_EQUIPPED_ITEM_CLASS_S= 0xC1,
 GERR_SPELL_FAILED_SHAPESHIFT_FORM_S =0xC2,
 GERR_BADATTACKFACING             =0xC3,
 GERR_BADATTACKPOS                =0xC4,
 GERR_CHEST_IN_USE                =0xC5,
 GERR_USE_CANT_OPEN               =0xC6,
 GERR_USE_LOCKED                  =0xC7,
 GERR_USE_LOCKED_WITH_ITEM_S      =0xC8,
 GERR_USE_LOCKED_WITH_SPELL_S     =0xC9,
 GERR_USE_LOCKED_WITH_SPELL_KNOWN_SI= 0xCA,
 GERR_USE_TOO_FAR                 =0xCB,
 GERR_USE_BAD_ANGLE               =0xCC,
 GERR_USE_OBJECT_MOVING           =0xCD,
 GERR_USE_SPELL_FOCUS             =0xCE,
 GERR_USE_DESTROYED               =0xCF,
 GERR_CANTATTACK_NOTSTANDING      =0xD0,
 GERR_SET_LOOT_FREEFORALL         =0xD1,
 GERR_SET_LOOT_ROUNDROBIN         =0xD2,
 GERR_SET_LOOT_MASTER             =0xD3,
 GERR_NEW_LOOT_MASTER_S           =0xD4,
 GERR_SPECIFY_MASTER_LOOTER       =0xD5,
 GERR_TAME_FAILED                 =0xD6,
 GERR_CHAT_WHILE_DEAD             =0xD7,
 GERR_NEWTAXIPATH                 =0xD8,
 GERR_NO_PET                      =0xD9,
 GERR_NOTYOURPET                  =0xDA,
 GERR_PET_NOT_RENAMEABLE          =0xDB,
 GERR_NULL_PETNAME                =0xDC,
 GERR_INVALID_PETNAME             =0xDD,
 GERR_QUEST_OBJECTIVE_COMPLETE_S  =0xDE,
 GERR_QUEST_UNKNOWN_COMPLETE      =0xDF,
 GERR_QUEST_ADD_KILL_SII          =0xE0,
 GERR_QUEST_ADD_FOUND_SII         =0xE1,
 GERR_QUEST_ADD_ITEM_SII          =0xE2,
 GERR_CANNOTCREATEDIRECTORY       =0xE3,
 GERR_CANNOTCREATEFILE            =0xE4,
 GERR_PLAYER_WRONG_FACTION        =0xE5,
 GERR_BANKSLOT_FAILED_TOO_MANY    =0xE6,
 GERR_BANKSLOT_INSUFFICIENT_FUNDS =0xE7,
 GERR_BANKSLOT_NOTBANKER          =0xE8,
 GERR_FRIEND_DB_ERROR             =0xE9,
 GERR_FRIEND_LIST_FULL            =0xEA,
 GERR_FRIEND_ADDED_S              =0xEB,
 GERR_FRIEND_ONLINE_S             =0xEC,
 GERR_FRIEND_OFFLINE_S            =0xED,
 GERR_FRIEND_NOT_FOUND            =0xEE,
 GERR_FRIEND_WRONG_FACTION        =0xEF,
 GERR_FRIEND_REMOVED_S            =0xF0,
 GERR_FRIEND_ERROR                =0xF1,
 GERR_FRIEND_ALREADY_S            =0xF2,
 GERR_FRIEND_SELF                 =0xF3,
 GERR_IGNORE_FULL                 =0xF4,
 GERR_IGNORE_SELF                 =0xF5,
 GERR_IGNORE_NOT_FOUND            =0xF6,
 GERR_IGNORE_ALREADY_S            =0xF7,
 GERR_IGNORE_ADDED_S              =0xF8,
 GERR_IGNORE_REMOVED_S            =0xF9,
 GERR_ONLY_ONE_BOLT               =0xFA,
 GERR_ONLY_ONE_AMMO               =0xFB,
 GERR_SPELL_FAILED_EQUIPPED_SPECIFIC_ITEM =0xFC,
 GERR_WRONG_BAG_TYPE_SUBCLASS     =0xFD,
 GERR_CANT_WRAP_STACKABLE         =0xFE,
 GERR_CANT_WRAP_EQUIPPED          =0xFF,
 GERR_CANT_WRAP_WRAPPED           =0x100,
 GERR_CANT_WRAP_BOUND             =0x101,
 GERR_CANT_WRAP_UNIQUE            =0x102,
 GERR_CANT_WRAP_BAGS              =0x103,
 GERR_OUT_OF_MANA                 =0x104,
 GERR_OUT_OF_RAGE                 =0x105,
 GERR_OUT_OF_FOCUS                =0x106,
 GERR_OUT_OF_ENERGY               =0x107,
 GERR_OUT_OF_HEALTH               =0x108,
 GERR_LOOT_GONE                   =0x109,
 GERR_MOUNT_FORCEDDISMOUNT        =0x10A,
 GERR_AUTOFOLLOW_TOO_FAR          =0x10B,
 GERR_UNIT_NOT_FOUND              =0x10C,
 GERR_INVALID_FOLLOW_TARGET       =0x10D,
 GERR_GUILDEMBLEM_SUCCESS         =0x10E,
 GERR_GUILDEMBLEM_INVALID_TABARD_COLORS =0x10F,
 GERR_GUILDEMBLEM_NOGUILD         =0x110,
 GERR_GUILDEMBLEM_COLORSPRESENT   =0x111,
 GERR_GUILDEMBLEM_NOTGUILDMASTER  =0x112,
 GERR_GUILDEMBLEM_NOTENOUGHMONEY  =0x113,
 GERR_GUILDEMBLEM_INVALIDVENDOR   =0x114,
 GERR_SPELL_OUT_OF_RANGE          =0x115,
 GERR_COMMAND_NEEDS_TARGET        =0x116,
 GERR_NOAMMO_S                    =0x117,
 GERR_TOOBUSYTOFOLLOW             =0x118,
 GERR_DUEL_REQUESTED              =0x119,
 GERR_DUEL_CANCELLED              =0x11A,
 GERR_DEATHBINDALREADYBOUND       =0x11B,
 GERR_NOEMOTEWHILERUNNING         =0x11C,
 GERR_ZONE_EXPLORED               =0x11D,
 GERR_ZONE_EXPLORED_XP            =0x11E,
 GERR_INVALID_ITEM_TARGET         =0x11F,
 GERR_IGNORING_YOU_S              =0x120,
 GERR_FISH_NOT_HOOKED             =0x121,
 GERR_FISH_ESCAPED                =0x122,
 GERR_SPELL_FAILED_NOTUNSHEATHED  =0x123,
 GERR_PETITION_SIGNED             =0x124,
 GERR_PETITION_ALREADY_SIGNED     =0x125,
 GERR_PETITION_IN_GUILD           =0x126,
 GERR_PETITION_CREATOR            =0x127,
 GERR_PETITION_NOT_ENOUGH_SIGNATURES =0x128,
 GERR_NONE                        =0x129,
};
#define GERR_NUM_TYPES                   0x129

enum ObjectTypeUpdateFields {
 ID_OBJECT                        =0x0,
 ID_ITEM                          =0x1,
 ID_CONTAINER                     =0x2,
 ID_UNIT                          =0x3,
 ID_PLAYER                        =0x4,
 ID_GAMEOBJECT                    =0x5,
 ID_DYNAMICOBJECT                 =0x6,
 ID_CORPSE                        =0x7,
 ID_AIGROUP                       =0x8,
 ID_AREATRIGGER                   =0x9,
};
#define NUM_CLIENT_OBJECT_TYPES          0x8
#define NUM_OBJECT_TYPES                 0xA

enum HeirTypeUpdateFields {
 HIER_TYPE_OBJECT                 =0x1,
 HIER_TYPE_ITEM                   =0x3,
 HIER_TYPE_CONTAINER              =0x7,
 HIER_TYPE_UNIT                   =0x9,
 HIER_TYPE_PLAYER                 =0x19,
 HIER_TYPE_GAMEOBJECT             =0x21,
 HIER_TYPE_DYNAMICOBJECT          =0x41,
 HIER_TYPE_CORPSE                 =0x81,
 HIER_TYPE_AIGROUP                =0x101,
 HIER_TYPE_AREATRIGGER            =0x201,
};

enum QuestGiverUpdateFields {
 QUEST_GIVER_NONE                 =0x0,
 QUEST_GIVER_TRIVIAL              =0x1,
 QUEST_GIVER_FUTURE               =0x2,
 QUEST_GIVER_REWARD               =0x3,
 QUEST_GIVER_QUEST                =0x4,
};
#define QUEST_GIVER_NUMITEMS             0x5

enum ObjectAnimationUpdateFields {
 ANIM_STAND                      = 0x0,
 ANIM_DEATH                      = 0x1,
 ANIM_SPELL                      = 0x2,
 ANIM_STOP                       = 0x3,
 ANIM_WALK                       = 0x4,
 ANIM_RUN                        = 0x5,
 ANIM_DEAD                       = 0x6,
 ANIM_RISE                       = 0x7,
 ANIM_STANDWOUND                 = 0x8,
 ANIM_COMBATWOUND                = 0x9,
 ANIM_COMBATCRITICAL             = 0xA,
 ANIM_SHUFFLE_LEFT               = 0xB,
 ANIM_SHUFFLE_RIGHT              = 0xC,
 ANIM_WALK_BACKWARDS             = 0xD,
 ANIM_STUN                       = 0xE,
 ANIM_HANDS_CLOSED               = 0xF,
 ANIM_ATTACKUNARMED               =0x10,
 ANIM_ATTACK1H                    =0x11,
 ANIM_ATTACK2HTIGHT               =0x12,
 ANIM_ATTACK2HLOOSE               =0x13,
 ANIM_PARRYUNARMED                =0x14,
 ANIM_PARRY1H                     =0x15,
 ANIM_PARRY2HTIGHT                =0x16,
 ANIM_PARRY2HLOOSE                =0x17,
 ANIM_PARRYSHIELD                 =0x18,
 ANIM_READYUNARMED                =0x19,
 ANIM_READY1H                     =0x1A,
 ANIM_READY2HTIGHT                =0x1B,
 ANIM_READY2HLOOSE                =0x1C,
 ANIM_READYBOW                    =0x1D,
 ANIM_DODGE                       =0x1E,
 ANIM_SPELLPRECAST                =0x1F,
 ANIM_SPELLCAST                   =0x20,
 ANIM_SPELLCASTAREA               =0x21,
 ANIM_NPCWELCOME                  =0x22,
 ANIM_NPCGOODBYE                  =0x23,
 ANIM_BLOCK                       =0x24,
 ANIM_JUMPSTART                   =0x25,
 ANIM_JUMP                        =0x26,
 ANIM_JUMPEND                     =0x27,
 ANIM_FALL                        =0x28,
 ANIM_SWIMIDLE                    =0x29,
 ANIM_SWIM                        =0x2A,
 ANIM_SWIM_LEFT                   =0x2B,
 ANIM_SWIM_RIGHT                  =0x2C,
 ANIM_SWIM_BACKWARDS              =0x2D,
 ANIM_ATTACKBOW                   =0x2E,
 ANIM_FIREBOW                     =0x2F,
 ANIM_READYRIFLE                  =0x30,
 ANIM_ATTACKRIFLE                 =0x31,
 ANIM_LOOT                        =0x32,
 ANIM_SPELL_PRECAST_DIRECTED      =0x33,
 ANIM_SPELL_PRECAST_OMNI          =0x34,
 ANIM_SPELL_CAST_DIRECTED         =0x35,
 ANIM_SPELL_CAST_OMNI             =0x36,
 ANIM_SPELL_BATTLEROAR            =0x37,
 ANIM_SPELL_READYABILITY          =0x38,
 ANIM_SPELL_SPECIAL1H             =0x39,
 ANIM_SPELL_SPECIAL2H             =0x3A,
 ANIM_SPELL_SHIELDBASH            =0x3B,
 ANIM_EMOTE_TALK                  =0x3C,
 ANIM_EMOTE_EAT                   =0x3D,
 ANIM_EMOTE_WORK                  =0x3E,
 ANIM_EMOTE_USE_STANDING          =0x3F,
 ANIM_EMOTE_EXCLAMATION           =0x40,
 ANIM_EMOTE_QUESTION              =0x41,
 ANIM_EMOTE_BOW                   =0x42,
 ANIM_EMOTE_WAVE                  =0x43,
 ANIM_EMOTE_CHEER                 =0x44,
 ANIM_EMOTE_DANCE                 =0x45,
 ANIM_EMOTE_LAUGH                 =0x46,
 ANIM_EMOTE_SLEEP                 =0x47,
 ANIM_EMOTE_SIT_GROUND            =0x48,
 ANIM_EMOTE_RUDE                  =0x49,
 ANIM_EMOTE_ROAR                  =0x4A,
 ANIM_EMOTE_KNEEL                 =0x4B,
 ANIM_EMOTE_KISS                  =0x4C,
 ANIM_EMOTE_CRY                   =0x4D,
 ANIM_EMOTE_CHICKEN               =0x4E,
 ANIM_EMOTE_BEG                   =0x4F,
 ANIM_EMOTE_APPLAUD               =0x50,
 ANIM_EMOTE_SHOUT                 =0x51,
 ANIM_EMOTE_FLEX                  =0x52,
 ANIM_EMOTE_SHY                   =0x53,
 ANIM_EMOTE_POINT                 =0x54,
 ANIM_ATTACK1HPIERCE              =0x55,
 ANIM_ATTACK2HLOOSEPIERCE         =0x56,
 ANIM_ATTACKOFF                   =0x57,
 ANIM_ATTACKOFFPIERCE             =0x58,
 ANIM_SHEATHE                     =0x59,
 ANIM_HIPSHEATHE                  =0x5A,
 ANIM_MOUNT                       =0x5B,
 ANIM_RUN_LEANRIGHT               =0x5C,
 ANIM_RUN_LEANLEFT                =0x5D,
 ANIM_MOUNT_SPECIAL               =0x5E,
 ANIM_KICK                        =0x5F,
 ANIM_SITDOWN                     =0x60,
 ANIM_SITTING                     =0x61,
 ANIM_SITUP                       =0x62,
 ANIM_SLEEPDOWN                   =0x63,
 ANIM_SLEEPING                    =0x64,
 ANIM_SLEEPUP                     =0x65,
 ANIM_SITCHAIRLOW                 =0x66,
 ANIM_SITCHAIRMEDIUM              =0x67,
 ANIM_SITCHAIRHIGH                =0x68,
 ANIM_LOADBOW                     =0x69,
 ANIM_LOADRIFLE                   =0x6A,
 ANIM_ATTACKTHROWN                =0x6B,
 ANIM_READYTHROWN                 =0x6C,
 ANIM_HOLDBOW                     =0x6D,
 ANIM_HOLDRIFLE                   =0x6E,
 ANIM_HOLDTHROWN                  =0x6F,
 ANIM_LOADTHROWN                  =0x70,
 ANIM_EMOTE_SALUTE                =0x71,
 ANIM_KNEELDOWN                   =0x72,
 ANIM_KNEELING                    =0x73,
 ANIM_KNEELUP                     =0x74,
 ANIM_ATTACKUNARMEDOFF            =0x75,
 ANIM_SPECIALUNARMED              =0x76,
 ANIM_STEALTHWALK                 =0x77,
 ANIM_STEALTHSTAND                =0x78,
 ANIM_KNOCKDOWN                   =0x79,
 ANIM_EATING                      =0x7A,
 ANIM_USESTANDINGLOOP             =0x7B,
 ANIM_CHANNELCASTDIRECTED         =0x7C,
 ANIM_CHANNELCASTOMNI             =0x7D,
 ANIM_WHIRLWIND                   =0x7E,
 ANIM_BIRTH                       =0x7F,
 ANIM_USESTANDINGSTART            =0x80,
 ANIM_USESTANDINGEND              =0x81,
 ANIM_HOWL                        =0x82,
 ANIM_DROWN                       =0x83,
 ANIM_DROWNED                     =0x84,
 ANIM_FISHINGCAST                 =0x85,
 ANIM_FISHINGLOOP                 =0x86,
};
#define NUM_OBJECTANIMATIONS             0x87
#define RESET_ANIMATION_INDICES0         (-1)

enum GameObjectAnimationsUpdateFields {
 ANIM_GAMEOBJ_STAND               =0x0,
 ANIM_GAMEOBJ_CLOSED              =0x1,
 ANIM_GAMEOBJ_OPEN                =0x2,
 ANIM_GAMEOBJ_OPENED              =0x3,
 ANIM_GAMEOBJ_CLOSE               =0x4,
 ANIM_GAMEOBJ_DESTROY             =0x5,
 ANIM_GAMEOBJ_DESTROYED           =0x6,
 ANIM_GAMEOBJ_REBUILD             =0x7,
 ANIM_GAMEOBJ_CUSTOM0             =0x8,
 ANIM_GAMEOBJ_CUSTOM1             =0x9,
 ANIM_GAMEOBJ_CUSTOM2             =0xA,
 ANIM_GAMEOBJ_CUSTOM3             =0xB,
};
#define NUM_GAMEOBJECTANIMATIONS         0xC
#define FIRST_GAMEOBJECTANIMATION        0x87
#define RESET_ANIMATION_INDICES1         (-1)

enum EffectAnimationsUpdateFields {
 ANIM_EFFECT_STAND                =0x0,
 ANIM_EFFECT_HOLD                 =0x1,
 ANIM_EFFECT_DECAY                =0x2,
 NUM_EFFECTANIMATIONS             =0x3,
};
#define FIRST_EFFECTANIMATION            0x93
#define RESET_ANIMATION_INDICES2         (-1)

enum ItemAnimationsUpdateFields {
 ANIM_ITEM_STAND                 = 0x0,
 ANIM_ITEM_INFLIGHT              = 0x1,
 ANIM_ITEM_BOWPULL               = 0x2,
 ANIM_ITEM_BOWRELEASE            = 0x3,
};
#define NUM_ITEMANIMATIONS               0x4
#define FIRST_ITEMANIMATION              0x96
#define RESET_ANIMATION_INDICES3         (-1)
#define INVALID_ANIMATION                (-1)

enum NPCSoundUpdateFields {
 NPCSOUND_HELLO                   =0x0,
 NPCSOUND_GOODBYE                 =0x1,
 NPCSOUND_PISSED                  =0x2,
 NPCSOUND_ACK                     =0x3,
};
#define NUM_NPCSOUNDS                    0x4

enum SpellCastUITypeUpdateFields {
 SPELL_CAST_UI_NONE               =0x0,
 SPELL_CAST_UI_PET_TRAINING       =0x1,
 SPELL_CAST_UI_DISGUISES          =0x2,
 SPELL_CAST_UI_INSCRIBING         =0x3,
};
#define NUM_SPELL_CAST_UI_TYPES          0x4

enum BloodSpurtLocationUpdateFields {
 BLOODSPURT_FRONT               =  0x0,
 BLOODSPURT_BACK                 = 0x1,
};
#define NUM_BLOODSPURTLOCATIONS          0x2

enum UnitSoundTypeUpdateFields {
 UNITSOUNDTYPE_EXERTION          = 0x0,
 UNITSOUNDTYPE_EXERTIONCRITICAL  = 0x1,
 UNITSOUNDTYPE_INJURY            = 0x2,
 UNITSOUNDTYPE_INJURYCRITICAL    = 0x3,
 UNITSOUNDTYPE_DEATH             = 0x4,
 UNITSOUNDTYPE_STUN              = 0x5,
 UNITSOUNDTYPE_STAND             = 0x6,
 UNITSOUNDTYPE_DEATHTHUD         = 0x7,
 UNITSOUNDTYPE_FOOTFALL          = 0x8,
 UNITSOUNDTYPE_AGGRO             = 0x9,
 UNITSOUNDTYPE_WINGFLAP          = 0xA,
 UNITSOUNDTYPE_ALERT             = 0xB,
 UNITSOUNDTYPE_INJURYCRUSHINGBLOW= 0xC,
 UNITSOUNDTYPE_WINGGLIDE         = 0xD,
 UNITSOUNDTYPE_JUMPSTART         = 0xE,
 UNITSOUNDTYPE_JUMPEND           = 0xF,
};
#define NUM_UNITSOUNDTYPES               0x10

enum EmoteSpecProcUpdateFields {
 EMOTESPECPROC_NONE               =0x0,
 EMOTESPECPROC_STANDSTATEHANDLER  =0x1,
 EMOTESPECPROC_EMOTESTATEHANDLER  =0x2,
};
#define EMOTESPECPROC_NUMSPECPROCS       0x3

enum UnitSexUpdateFields {
 UNITSEX_MALE                     =0x0,
 UNITSEX_FEMALE                   =0x1,
 UNITSEX_NONE                     =0x2,
 UNITSEX_BOTH                     =0x3,
};
#define UNITSEX_LAST                     0x3

enum WorldTextMissTypeUpdateFields {
 WORLDTEXTMISS_EVADED            = 0x0,
 WORLDTEXTMISS_DODGED            = 0x1,
 WORLDTEXTMISS_PARRIED           = 0x2,
 WORLDTEXTMISS_BLOCKED           = 0x3,
 WORLDTEXTMISS_DEFLECTED         = 0x4,
 WORLDTEXTMISS_IMMUNE            = 0x5,
 WORLDTEXTMISS_TEMPIMMUNE        = 0x6,
 WORLDTEXTMISS_PHYSICAL          = 0x7,
 WORLDTEXTMISS_RESIST            = 0x8,
 WORLDTEXTMISS_ABSORBED          = 0x9,
};
#define WORLDTEXTMISS_NUMTYPES           0xA

enum SheathReasonUpdateFields {
 SHEATHE_PLAYEREXPLICIT          = 0x0,
 SHEATHE_SPELLS                  = 0x1,
 SHEATHE_STANDSTATE              = 0x2,
 SHEATHE_BASEANIM                = 0x3,
 SHEATHE_TORSOANIM               = 0x4,
 SHEATHE_RANGED                  = 0x5,
 SHEATHE_TALKEMOTE               = 0x6,
 SHEATHE_PRECAST                 = 0x7,
 SHEATHE_CHANNELLING             = 0x8,
};
#define SHEATHE_NUMREASONS               0x9

enum ItemSlotUpdateFields {
 INVSLOT_HEAD                    = 0x0,
 INVSLOT_FIRST                   = 0x0,
 EQUIPPED_FIRST                  = 0x0,
 INVSLOT_NECK                    = 0x1,
 INVSLOT_SHOULDER                = 0x2,
 INVSLOT_BODY                    = 0x3,
 INVSLOT_CHEST                   = 0x4,
 INVSLOT_WAIST                   = 0x5,
 INVSLOT_LEGS                    = 0x6,
 INVSLOT_FEET                    = 0x7,
 INVSLOT_WRIST                   = 0x8,
 INVSLOT_HAND                    = 0x9,
 INVSLOT_FINGER1                 = 0xA,
 INVSLOT_FINGER2                 = 0xB,
 INVSLOT_TRINKET1                = 0xC,
 INVSLOT_TRINKET2                = 0xD,
 INVSLOT_BACK                    = 0xE,
 INVSLOT_MAINHAND                = 0xF,
 INVSLOT_OFFHAND                  =0x10,
 INVSLOT_RANGED                   =0x11,
 INVSLOT_TABARD                   =0x12,
 EQUIPPED_LAST                    =0x12,
 INVSLOT_BAG0                     =0x13,
 INVSLOT_BAGFIRST                 =0x13,
 INVSLOT_BAG1                     =0x14,
 INVSLOT_BAG2                     =0x15,
 INVSLOT_BAG3                     =0x16,
 INVSLOT_BAGLAST                  =0x16,
 INVSLOT_LAST                     =0x16,
 BACKPACK_SLOT00                  =0x17,
 BACKPACK_FIRST                   =0x17,
 BACKPACK_SLOT01                  =0x18,
 BACKPACK_SLOT02                  =0x19,
 BACKPACK_SLOT03                  =0x1A,
 BACKPACK_SLOT04                  =0x1B,
 BACKPACK_SLOT05                  =0x1C,
 BACKPACK_SLOT06                  =0x1D,
 BACKPACK_SLOT07                  =0x1E,
 BACKPACK_SLOT08                  =0x1F,
 BACKPACK_SLOT09                  =0x20,
 BACKPACK_SLOT10                  =0x21,
 BACKPACK_SLOT11                  =0x22,
 BACKPACK_SLOT12                  =0x23,
 BACKPACK_SLOT13                  =0x24,
 BACKPACK_SLOT14                  =0x25,
 BACKPACK_SLOT15                  =0x26,
 BACKPACK_LAST                    =0x26,
 BANKGENERIC_SLOT00               =0x27,
 BANKGENERIC_FIRST                =0x27,
 BANKGENERIC_SLOT01               =0x28,
 BANKGENERIC_SLOT02               =0x29,
 BANKGENERIC_SLOT03               =0x2A,
 BANKGENERIC_SLOT04               =0x2B,
 BANKGENERIC_SLOT05               =0x2C,
 BANKGENERIC_SLOT06               =0x2D,
 BANKGENERIC_SLOT07               =0x2E,
 BANKGENERIC_SLOT08               =0x2F,
 BANKGENERIC_SLOT09               =0x30,
 BANKGENERIC_SLOT10               =0x31,
 BANKGENERIC_SLOT11               =0x32,
 BANKGENERIC_SLOT12               =0x33,
 BANKGENERIC_SLOT13               =0x34,
 BANKGENERIC_SLOT14               =0x35,
 BANKGENERIC_SLOT15               =0x36,
 BANKGENERIC_SLOT16               =0x37,
 BANKGENERIC_SLOT17               =0x38,
 BANKGENERIC_SLOT18               =0x39,
 BANKGENERIC_SLOT19               =0x3A,
 BANKGENERIC_SLOT20               =0x3B,
 BANKGENERIC_SLOT21               =0x3C,
 BANKGENERIC_SLOT22               =0x3D,
 BANKGENERIC_SLOT23               =0x3E,
 BANKGENERIC_LAST                 =0x3E,
 BANKBAG_0                        =0x3F,
 BANKBAG_FIRST                    =0x3F,
 BANKBAG_1                        =0x40,
 BANKBAG_2                        =0x41,
 BANKBAG_3                        =0x42,
 BANKBAG_4                        =0x43,
 BANKBAG_5                        =0x44,
 BANKBAG_LAST                     =0x44,
 PLAYER_INVENTORY_SLOTS           =0x45,
 NUM_INVENTORY_SLOTS              =0x17,
 NUM_BAG_SLOTS                   = 0x4,
 MIN_BACKPACK_SLOTS               =0x10,
 BANK_NUM_GEMERIC_SLOTS           =0x18,
 NUM_BANKBAG_SLOTS               = 0x6,
 TOTAL_BAG_SLOTS                 = 0xA,
 INVENTORY_NONE                   =(-1),
};

enum AffiliationUpdateFields {
 AFFILIATION_YOURSELF            = 0x0,
 AFFILIATION_YOURPET             = 0x1,
 AFFILIATION_PARTYMEMBER         = 0x2,
 AFFILIATION_OTHER               = 0x3,
 AFFILIATION_YOURCONTROLLER      = 0x4,
};
#define AFFILIATION_NUMAFFILIATIONS      0x5

enum VictimStateUpdateFields {
 VS_NONE                          =0x0,
 VS_WOUND                         =0x1,
 VS_DODGE                         =0x2,
 VS_PARRY                         =0x3,
 VS_INTERRUPT                     =0x4,
 VS_BLOCK                         =0x5,
 VS_EVADE                         =0x6,
 VS_IMMUNE                        =0x7,
 VS_DEFLECT                       =0x8,
};
#define NUM_VICTIMSTATES                 0x9

enum WeaponModeUpdateFields {
 WEAPONMODE_NORMALMODE            =0x0,
 WEAPONMODE_SHEATHEDMODE          =0x1,
 WEAPONMODE_RANGEDMODE            =0x2,
};
#define WEAPONMODE_NUMMODES              0x3

enum CombatHandUpdateFields {
 COMBAT_MAINHAND                  =0x0,
 COMBAT_OFFHAND                   =0x1,
};
#define NUMHANDS                         0x2


enum ItemFlagUpdateFields {
 ITEM_FLAG_NO_PICKUP             = 0x1,
 ITEM_FLAG_CONJURED              = 0x2,
 ITEM_FLAG_HAS_LOOT              = 0x4,
 ITEM_FLAG_EXOTIC                = 0x8,
 ITEM_FLAG_DEPRECATED             =0x10,
 ITEM_FLAG_OBSOLETE               =0x20,
 ITEM_FLAG_PLAYERCAST             =0x40,
 ITEM_FLAG_NO_EQUIPCOOLDOWN       =0x80,
 ITEM_FLAG_INTBONUSINSTEAD        =0x100,
 ITEM_FLAG_IS_WRAPPER             =0x200,
 ITEM_FLAG_USES_RESOURCES         =0x400,
 ITEM_FLAG_MULTI_DROP             =0x800,
 ITEM_FLAG_BRIEFSPELLEFFECTS      =0x1000,
 ITEM_FLAG_PETITION               =0x2000,
 MAX_ITEM_FLAG                    =0x80008002,
 ITEM_FLAG_NUM                    =0xE,
};

enum WeaponSwingSoundTypeUpdateFields {
 WEAPONSWING_LIGHT               = 0x0,
 WEAPONSWING_MEDIUM              = 0x1,
 WEAPONSWING_HEAVY                =0x2,
};
#define NUM_WEAPONSWINGSOUNDTYPES        0x3
#define WEAPONSWING_UNUSED               (-1)

enum UnitEffectAttachPointUpdateFields {
 UNITEFFECT_ATTACHBASE           = 0x0,
 UNITEFFECT_ATTACHHEAD           = 0x1,
 UNITEFFECT_ATTACHLEFTHAND       = 0x2,
 UNITEFFECT_ATTACHRIGHTHAND      = 0x3,
 UNITEFFECT_ATTACHNONE           = 0x4,
 UNITEFFECT_ATTACHBREATH         = 0x5,
 UNITEFFECT_ATTACHCHEST          = 0x6,
 UNITEFFECT_ATTACHSPECIAL1       = 0x7,
 UNITEFFECT_ATTACHSPECIAL2       = 0x8,
 UNITEFFECT_ATTACHSPECIAL3       = 0x9,
 UNITEFFECT_ATTACHCHESTBLOODBACK = 0xA,
 UNITEFFECT_ATTACHCHESTBLOODFRONT= 0xB,
};
#define NUM_UNITEFFECTATTACHPOINTS       0xC
#define UNITEFFECT_INVALID               (-1)

enum InteractionUpdateFields {
 INTERACTICON_NONE               = 0x0,
 INTERACTICON_NORMAL             = 0x1,
 INTERACTICON_COMPLETION         = 0x2,
 INTERACTICON_FUTURE             = 0x3,
 INTERACTICON_TAXINODE           = 0x4,
 INTERACTICON_BINDER             = 0x5,
};
#define INTERACTICON_NUMITEMS            0x6

enum UnitSpecialEffectUpdateFields {
 SPECIALEFFECT_LOOTART           = 0x0,
 SPECIALEFFECT_LEVELUP           = 0x1,
 SPECIALEFFECT_FOOTSTEPSPRAYSNOW = 0x2,
 SPECIALEFFECT_FOOTSTEPSPRAYSNOWWALK =0x3,
 SPECIALEFFECT_FOOTSTEPDIRT      = 0x4,
 SPECIALEFFECT_FOOTSTEPDIRTWALK  = 0x5,
 SPECIALEFFECT_COLDBREATH        = 0x6,
 SPECIALEFFECT_UNDERWATERBUBBLES = 0x7,
 SPECIALEFFECT_COMBATBLOODSPURTFRONT= 0x8,
 SPECIALEFFECT_UNUSED            = 0x9,
 SPECIALEFFECT_COMBATBLOODSPURTBACK= 0xA,
 SPECIALEFFECT_HITSPLATPHYSICALSMALL= 0xB,
 SPECIALEFFECT_HITSPLATPHYSICALBIG= 0xC,
 SPECIALEFFECT_HITSPLATHOLYSMALL = 0xD,
 SPECIALEFFECT_HITSPLATHOLYBIG   = 0xE,
 SPECIALEFFECT_HITSPLATFIRESMALL = 0xF,
 SPECIALEFFECT_HITSPLATFIREBIG    =0x10,
 SPECIALEFFECT_HITSPLATNATURESMALL =0x11,
 SPECIALEFFECT_HITSPLATNATUREBIG  =0x12,
 SPECIALEFFECT_HITSPLATFROSTSMALL =0x13,
 SPECIALEFFECT_HITSPLATFROSTBIG   =0x14,
 SPECIALEFFECT_HITSPLATSHADOWSMALL =0x15,
 SPECIALEFFECT_HITSPLATSHADOWBIG  =0x16,
 SPECIALEFFECT_COMBATBLOODSPURTFRONTLARGE =0x17,
 SPECIALEFFECT_COMBATBLOODSPURTBACKLARGE =0x18,
 SPECIALEFFECT_FIZZLEPHYSICAL     =0x19,
 SPECIALEFFECT_FIZZLEHOLY         =0x1A,
 SPECIALEFFECT_FIZZLEFIRE         =0x1B,
 SPECIALEFFECT_FIZZLENATURE       =0x1C,
 SPECIALEFFECT_FIZZLEFROST        =0x1D,
 SPECIALEFFECT_FIZZLESHADOW       =0x1E,
 SPECIALEFFECT_COMBATBLOODSPURTGREENFRONT =0x1F,
 SPECIALEFFECT_COMBATBLOODSPURTGREENFRONTLARGE =0x20,
 SPECIALEFFECT_COMBATBLOODSPURTGREENBACK =0x21,
 SPECIALEFFECT_COMBATBLOODSPURTGREENBACKLARGE =0x22,
 SPECIALEFFECT_FOOTSTEPSPRAYWATER =0x23,
 SPECIALEFFECT_FOOTSTEPSPRAYWATERWALK =0x24,
 SPECIALEFFECT_CHARACTERSHAPESHIFT =0x25,
 SPECIALEFFECT_COMBATBLOODSPURTBLACKFRONT =0x26,
 SPECIALEFFECT_COMBATBLOODSPURTBLACKFRONTLARGE =0x27,
 SPECIALEFFECT_COMBATBLOODSPURTBLACKBACK =0x28,
 SPECIALEFFECT_COMBATBLOODSPURTBLACKBACKLARGE =0x29,
 SPECIALEFFECT_RES_EFFECT         =0x2A,
};
#define NUM_UNITEFFECTSPECIALS           0x2B
#define SPECIALEFFECT_NONE               (-1)

enum ItemDFlagUpdateFields {
 ITEM_DFLAG_BOUND                 =0x1,
 ITEM_DFLAG_TRANSLATED            =0x2,
 ITEM_DFLAG_UNLOCKED              =0x4,
 ITEM_DFLAG_WRAPPED               =0x8,
};

enum AIReactionUpdateFields {
 AI_REACT_ALERT                   =0x0,
 AI_REACT_FRIENDLY                =0x1,
 AI_REACT_HOSTILE                 =0x2,
 AI_REACT_AFRAID                  =0x3,
};
#define NUM_AI_REACTIONS                 0x4

enum UnitReactionUpdateFields {
 UNIT_REACTION_HATED              =0x0,
 UNIT_REACTION_HOSTILE            =0x1,
 UNIT_REACTION_UNFRIENDLY         =0x2,
 UNIT_REACTION_NEUTRAL            =0x3,
 UNIT_REACTION_AMIABLE            =0x4,
 UNIT_REACTION_FRIENDLY           =0x5,
 UNIT_REACTION_REVERED            =0x6,
};
#define NUM_UNIT_REACTIONS               0x7

enum MissTypeUpdateFields {
 MISS_NONE                        =0x0,
 MISS_PHYSICAL                    =0x1,
 MISS_RESIST                      =0x2,
 MISS_IMMUNE                      =0x3,
 MISS_EVADED                      =0x4,
 MISS_DODGED                      =0x5,
 MISS_PARRIED                     =0x6,
 MISS_BLOCKED                     =0x7,
 MISS_TEMPIMMUNE                  =0x8,
 MISS_DEFLECTED                   =0x9,
};
#define MISS_NUMMISSTYPES                0xA

enum BagResponseUpdateFields {
 BAG_OK                          = 0x0,
 BAG_LEVEL_MISMATCH              = 0x1,
 BAG_SKILL_MISMATCH              = 0x2,
 BAG_SLOT_MISMATCH               = 0x3,
 BAG_FULL                        = 0x4,
 BAG_NO_BAGS_IN_BAGS             = 0x5,
 BAG_AMMO_ONLY                   = 0x6,
 BAG_PROFICIENCY_NEEDED          = 0x7,
 BAG_NO_SLOTS_AVAILABLE          = 0x8,
 BAG_CLASS_NOTALLOWED            = 0x9,
 BAG_RACE_NOTALLOWED             = 0xA,
 BAG_2HWEAPON_ITEMEXISTSINOFFHAND= 0xB,
 BAG_2HWEAPONBEINGWIELDED        = 0xC,
 BAG_2HWEAPON_SKILLNOTFOUND      = 0xD,
 BAG_ITEM_CLASS_MISMATCH         = 0xE,
 BAG_ITEM_SUBTYPE_MISMATCH       = 0xF,
 BAG_ITEM_MAX_COUNT_EXCEEDED      =0x10,
 BAG_SLOT_NOT_EMPTY               =0x11,
 BAG_CANT_STACK                   =0x12,
 BAG_NOT_EQUIPPABLE               =0x13,
 BAG_CANT_SWAP                    =0x14,
 BAG_SLOT_EMPTY                   =0x15,
 BAG_ITEM_NOT_FOUND               =0x16,
 BAG_ITEM_ALREADY_BOUND           =0x17,
 BAG_DROP_TOO_FAR_AWAY            =0x18,
 BAG_ITEM_TOO_FEW_TO_SPLIT        =0x19,
 BAG_ITEM_SPLIT_FAILED            =0x1A,
 BAG_CANT_CAST_ENCHANTMENT        =0x1B,
 BAG_NOT_ENOUGH_GOLD              =0x1C,
 BAG_NOT_A_CONTAINER              =0x1D,
 BAG_NOT_EMPTY                    =0x1E,
 BAG_NOT_OWNER                    =0x1F,
 BAG_ONLY_ONE_QUIVER              =0x20,
 BAG_NOBANKSLOT                   =0x21,
 BAG_NOBANKHERE                   =0x22,
 BAG_ITEM_LOCKED                  =0x23,
 BAG_NOT_WHILE_DEAD               =0x24,
 BAG_CLIENT_LOCKED_OUT            =0x25,
 BAG_ERROR                        =0x26,
 BAG_ONLY_ONE_BOLT                =0x27,
 BAG_ONLY_ONE_AMMO                =0x28,
 BAG_CANT_WRAP_STACKABLE          =0x29,
 BAG_CANT_WRAP_EQUIPPED           =0x2A,
 BAG_CANT_WRAP_WRAPPED            =0x2B,
 BAG_CANT_WRAP_BOUND              =0x2C,
 BAG_CANT_WRAP_UNIQUE             =0x2D,
 BAG_CANT_WRAP_BAGS               =0x2E,
 BAG_LOOT_GONE                    =0x2F,
 BAG_INV_FULL                     =0x30,
 BAG_SOLD_OUT                     =0x31,
 BAG_DONT_LIKE_YOU                =0x32,
 BAG_UNKNOWN_ITEM                 =0x33,
 BAG_STACK_COUNT_EXCEEDED         =0x34,
 BAG_QUANTITY_ZERO                =0x35,
 BAG_DONT_HAVE_THAT_MANY          =0x36,
};

enum VUIUpdateFields {
 VUI_INVENTORYFULL               = 0x0,
 VUI_OUTOFAMMO                   = 0x1,
 VUI_NOEQUIP_LEVEL               = 0x2,
 VUI_NOEQUIP_EVER                = 0x3,
 VUI_BOUND_NODROP                = 0x4,
 VUI_ITEMCOOLING                 = 0x5,
 VUI_CANTDRINKMORE               = 0x6,
 VUI_CANTEATMORE                 = 0x7,
 VUI_CANTINVITE                  = 0x8,
 VUI_INVITEEBUSY                 = 0x9,
 VUI_TARGETTOOFAR                = 0xA,
 VUI_INVALIDTARGET               = 0xB,
 VUI_SPELLCOOLING                = 0xC,
 VUI_CANTLEARN_LEVEL             = 0xD,
 VUI_LOCKED                      = 0xE,
 VUI_NOMANA                      = 0xF,
 VUI_NOTWHILEDEAD                 =0x10,
 VUI_CANTLOOT                     =0x11,
 VUI_CANTCREATE                   =0x12,
 VUI_DECLINEGROUP                 =0x13,
 VUI_ALREADYINGROUP               =0x14,
 VUI_ALREADYINGUILD               =0x15,
 VUI_CANTAFFORDBANKSLOT           =0x16,
 VUI_TOOMANYBANKSLOTS             =0x17,
 VUI_CANTEAT_MOVING               =0x18,
 VUI_NOTABAG                      =0x19,
 VUI_CANTPUTBAG                   =0x1A,
 VUI_WRONGSLOT                    =0x1B,
 VUI_AMMOONLYINBAG                =0x1C,
 VUI_BAGFULL                      =0x1D,
 VUI_ITEMMAXCOUNT                 =0x1E,
 VUI_CANTLOOT_DIDNTKILL           =0x1F,
 VUI_CANTLOOT_WRONGFACING         =0x20,
 VUI_CANTLOOT_LOCKED              =0x21,
 VUI_CANTLOOT_NOTSTANDING         =0x22,
 VUI_CANTLOOT_TOOFAR              =0x23,
 VUI_CANTATTACKRONGDIRECTION      =0x24,
 VUI_CANTATTACK_NOTSTANDING       =0x25,
 VUI_CANTATTACK_NOTARGET          =0x26,
 VUI_NOTENOUGHGOLD                =0x27,
 VUI_NOTENOUGHMONEY               =0x28,
 VUI_CANTEQUIP2H_SKILL            =0x29,
 VUI_CANTEQUIP_2HEQUIPPED         =0x2A,
 VUI_CANTEQUIP2H_NOSKILL          =0x2B,
 VUI_NOTEQUIPPABLE                =0x2C,
 VUI_GENERICNOTARGET              =0x2D,
 VUI_CANTCAST_OUTOFRANGE          =0x2E,
 VUI_POTIONCOOLING                =0x2F,
 VUI_PROFICIENCYNEEDED            =0x30,
 VUI_MUSTEQUIPPITEM               =0x31,
 VUI_ABILITYCOOLING               =0x32,
 VUI_CANTUSEITEM                  =0x33,
 VUI_CHESTINUSE                   =0x34,
 VUI_FOODCOOLING                  =0x35,
 VUI_CANTTAXI_NOMONEY             =0x36,
 VUI_CANTUSELOCKED                =0x37,
 VUI_NOEQUIPSLOTAVAILABLE         =0x38,
 VUI_CANTUSETOOFAR                =0x39,
 VUI_CANTSWAP                     =0x3A,
 VUI_CANTTRADE_SOULBOUND          =0x3B,
 VUI_NOTOWNER                     =0x3C,
 VUI_ITEMLOCKED                   =0x3D,
 VUI_GUILDPERMISSIONS             =0x3E,
 VUI_NORAGE                       =0x3F,
 VUI_NOENERGY                     =0x40,
 VUI_NOFOCUS                      =0x41,
 NUM_VOCALUISOUNDS                =0x42,
 VUI_NONE                         =0x42,
};

#define DYNAMIC_OBJECT_PORTAL            0x0
#define DYNAMIC_OBJECT_AREA_SPELL        0x1
#define DYNAMIC_OBJECT_FARSIGHT_FOCUS    0x2
#define PLAYER_NORMAL                    0x0
#define PLAYER_BOT                       0x1

enum ObjectUpdateTypeUpdateFields {
 UPDATE_PARTIAL                   =0x0,
 UPDATE_MOVEMENT                  =0x1,
 UPDATE_FULL                      =0x2,
 UPDATE_OUT_OF_RANGE              =0x3,
 UPDATE_IN_RANGE                  =0x4,
};

enum UpdateWhenUpdateFields {
 UPDATE_AFTER_PARENT              =(-1),
 UPDATE_WITH_PARENT               =0x0,
 UPDATE_BEFORE_PARENT             =0x1,
};

enum InventoryTypeUpdateFields {
 INDEX_NON_EQUIP_TYPE            = 0x0,
 INDEX_HEAD_TYPE                 = 0x1,
 INDEX_NECK_TYPE                 = 0x2,
 INDEX_SHOULDER_TYPE             = 0x3,
 INDEX_BODY_TYPE                 = 0x4,
 INDEX_CHEST_TYPE                = 0x5,
 INDEX_WAIST_TYPE                = 0x6,
 INDEX_LEGS_TYPE                 = 0x7,
 INDEX_FEET_TYPE                 = 0x8,
 INDEX_WRIST_TYPE                = 0x9,
 INDEX_HAND_TYPE                 = 0xA,
 INDEX_FINGER_TYPE               = 0xB,
 INDEX_TRINKET_TYPE              = 0xC,
 INDEX_WEAPON_TYPE               = 0xD,
 INDEX_SHIELD_TYPE               = 0xE,
 INDEX_RANGED_TYPE               = 0xF,
 INDEX_CLOAK_TYPE                 =0x10,
 INDEX_2HWEAPON_TYPE              =0x11,
 INDEX_BAG_TYPE                   =0x12,
 INDEX_TABARD_TYPE                =0x13,
 INDEX_ROBE_TYPE                  =0x14,
 INDEX_WEAPONMAINHAND_TYPE        =0x15,
 INDEX_WEAPONOFFHAND_TYPE         =0x16,
 INDEX_HOLDABLE_TYPE              =0x17,
 INDEX_AMMO_TYPE                  =0x18,
 INDEX_THROWN_TYPE                =0x19,
 INDEX_RANGEDRIGHT_TYPE           =0x1A,
 INDEX_NUMSLOTS                   =0x1B,
 INDEX_INVALID_INVENTORYTYPE      =0x1C,
};

enum QuestStateUpdateFields {
 QUEST_GREETING                   =0x0,
 QUEST_OFFER                      =0x1,
 QUEST_ACCEPTED                   =0x2,
 QUEST_REWARD                     =0x3,
};
#define QUEST_STATE_NUM_TYPES            0x4

enum TradeskillLevelUpdateFields {
 TRADESKILL_MEDIUM                =0x1,
 TRADESKILL_EASY                  =0x2,
 TRADESKILL_TRIVIAL               =0x3,
};
#define NUM_TRADESKILL_CATEGORIES        0x4

enum LootMethodUpdateFields {
 LOOT_METHOD_FREEFORALL           =0x0,
 LOOT_METHOD_ROUNDROBIN           =0x1,
 LOOT_METHOD_MASTERLOOTER         =0x2,
}; 
#define LOOT_METHOD_MAX                  0x3

enum TrackTypeUpdateFields {
 TRACKTYPE_SPELLPRECAST           =0x0,
 TRACKTYPE_SPELLCHANNEL           =0x1,
 TRACKTYPE_FOLLOW                 =0x2,
};
#define TRACKTYPE_NUMTRACKTYPES          0x3

struct UpdateMask {
    uint8 count;
    uint16 length;
    uint32 * updateMask;

    inline void setBit( const uint32 index ) {
        ( (uint8 *)updateMask )[ index >> 3 ] |= 1 << ( index & 0x7 );
    }
	inline void unSetBit( const uint32 index ) {
		( (uint8 *)updateMask )[ index >> 3 ] &= (0xff ^ (1 <<  ( index & 0x7 ) ) );
	}
    void setCount(int newcount) { 
        clear( );
        count = newcount;
        length = count*4;
        updateMask = new uint32[count];
        memset(updateMask, 0, length);
    }

    void clear(){
        if (updateMask){
            delete [] updateMask;
            updateMask = 0;
        }

        count = 0;
        length = 0;
    }

    UpdateMask( ) : updateMask( 0 ), count( 0 ), length( 0 ) { }
    ~UpdateMask( ) { clear( ); }
};


#endif

