using System;
using Server.Items;
using System.Collections;
using Server;


///////////////////////////////////////////
namespace Server
{
	public class KoboldDrops
	{
		public static Loot[] KoboldVermin = new Loot[] {  new Loot( typeof( CopperOre ), 0.01f )
														   , new Loot( typeof( RefreshingSpringWater ), 6.65f )
														   , new Loot( typeof( RoughStone ), 0.02f )
														   , new Loot( typeof( ShinyRedApple ), 13.18f )
														   , new Loot( typeof( SmallBlackPouch ), 0.10f )
														   , new Loot( typeof( SmallBluePouch ), 0.10f )
														   , new Loot( typeof( SmallBrownPouch ), 0.10f )
														   , new Loot( typeof( SmallGreenPouch ), 0.10f )
														   , new Loot( typeof( SmallRedPouch ), 0.11f )
														   , new Loot( typeof( BatteredBuckler ), 1.29f )
														   , new Loot( typeof( BentLargeShield ), 1.25f )
														   , new Loot( typeof( FlimsyChainBelt ), 1.03f )
														   , new Loot( typeof( FlimsyChainBoots ), 1.09f )
														   , new Loot( typeof( FlimsyChainBracers ), 1.15f )
														   , new Loot( typeof( FlimsyChainCloak ), 1.16f )
														   , new Loot( typeof( FlimsyChainGloves ), 1.06f )
														   , new Loot( typeof( FlimsyChainPants ), 0.98f )
														   , new Loot( typeof( FlimsyChainVest ), 0.94f )
														   , new Loot( typeof( FrayedBelt ), 1.44f )
														   , new Loot( typeof( FrayedBracers ), 1.40f )
														   , new Loot( typeof( FrayedCloak ), 1.49f )
														   , new Loot( typeof( FrayedGloves ), 1.62f )
														   , new Loot( typeof( FrayedPants ), 1.46f )
														   , new Loot( typeof( FrayedRobe ), 1.55f )
														   , new Loot( typeof( FrayedShoes ), 1.39f )
														   , new Loot( typeof( MeltedCandle ), 29.89f )
														   , new Loot( typeof( RaggedCloak ), 1.27f )
														   , new Loot( typeof( RaggedLeatherBelt ), 1.25f )
														   , new Loot( typeof( RaggedLeatherBoots ), 1.27f )
														   , new Loot( typeof( RaggedLeatherBracers ), 1.26f )
														   , new Loot( typeof( RaggedLeatherGloves ), 1.33f )
														   , new Loot( typeof( RaggedLeatherPants ), 1.30f )
														   , new Loot( typeof( RaggedLeatherVest ), 1.40f )
													   };
		public static Loot[] KoboldWorker = new Loot[] {  new Loot( typeof( CopperOre ), 0.01f )
														   , new Loot( typeof( RefreshingSpringWater ), 6.47f )
														   , new Loot( typeof( RoughStone ), 0.01f )
														   , new Loot( typeof( ShinyRedApple ), 13.35f )
														   , new Loot( typeof( SmallBlackPouch ), 0.10f )
														   , new Loot( typeof( SmallBluePouch ), 0.09f )
														   , new Loot( typeof( SmallBrownPouch ), 0.09f )
														   , new Loot( typeof( SmallGreenPouch ), 0.10f )
														   , new Loot( typeof( SmallRedPouch ), 0.10f )
														   , new Loot( typeof( BatteredBuckler ), 1.28f )
														   , new Loot( typeof( BentLargeShield ), 1.25f )
														   , new Loot( typeof( FlimsyChainBelt ), 1.00f )
														   , new Loot( typeof( FlimsyChainBoots ), 0.99f )
														   , new Loot( typeof( FlimsyChainBracers ), 1.03f )
														   , new Loot( typeof( FlimsyChainCloak ), 1.07f )
														   , new Loot( typeof( FlimsyChainGloves ), 1.07f )
														   , new Loot( typeof( FlimsyChainPants ), 1.01f )
														   , new Loot( typeof( FlimsyChainVest ), 1.03f )
														   , new Loot( typeof( FrayedBelt ), 1.49f )
														   , new Loot( typeof( FrayedBracers ), 1.49f )
														   , new Loot( typeof( FrayedCloak ), 1.49f )
														   , new Loot( typeof( FrayedGloves ), 1.52f )
														   , new Loot( typeof( FrayedPants ), 1.51f )
														   , new Loot( typeof( FrayedRobe ), 1.49f )
														   , new Loot( typeof( FrayedShoes ), 1.39f )
														   , new Loot( typeof( MeltedCandle ), 29.43f )
														   , new Loot( typeof( RaggedCloak ), 1.28f )
														   , new Loot( typeof( RaggedLeatherBelt ), 1.28f )
														   , new Loot( typeof( RaggedLeatherBoots ), 1.22f )
														   , new Loot( typeof( RaggedLeatherBracers ), 1.29f )
														   , new Loot( typeof( RaggedLeatherGloves ), 1.34f )
														   , new Loot( typeof( RaggedLeatherPants ), 1.34f )
														   , new Loot( typeof( RaggedLeatherVest ), 1.43f )
													   };
		public static Loot[] KoboldTunneler = new Loot[] {  new Loot( typeof( Malachite ), 0.24f )
															 , new Loot( typeof( PatternFineLeatherGloves ), 0.01f )
															 , new Loot( typeof( PatternRedLinenRobe ), 0.07f )
															 , new Loot( typeof( PlansCopperChainVest ), 0.07f )
															 , new Loot( typeof( PlansGemmedCopperGauntlets ), 0.01f )
															 , new Loot( typeof( RecipeSwiftnessPotion ), 0.01f )
															 , new Loot( typeof( SchematicMechanicalSquirrel ), 0.01f )
															 , new Loot( typeof( Tigerseye ), 0.07f )
															 , new Loot( typeof( CopperOre ), 2.41f )
															 , new Loot( typeof( GoldDust ), 20.71f )
															 , new Loot( typeof( KoboldMiningShovel ), 3.89f )
															 , new Loot( typeof( LargeCandle ), 95.15f )
															 , new Loot( typeof( LightLeather ), 0.01f )
															 , new Loot( typeof( LinenCloth ), 28.89f )
															 , new Loot( typeof( RefreshingSpringWater ), 3.65f )
															 , new Loot( typeof( RoughStone ), 2.31f )
															 , new Loot( typeof( ScrollOfProtection ), 0.71f )
															 , new Loot( typeof( ScrollOfSpirit ), 0.75f )
															 , new Loot( typeof( ShinyRedApple ), 7.37f )
															 , new Loot( typeof( Silverleaf ), 0.01f )
															 , new Loot( typeof( SmallBlackPouch ), 0.08f )
															 , new Loot( typeof( SmallBluePouch ), 0.07f )
															 , new Loot( typeof( SmallBrownPouch ), 0.06f )
															 , new Loot( typeof( SmallGreenPouch ), 0.07f )
															 , new Loot( typeof( SmallRedPouch ), 0.08f )
															 , new Loot( typeof( ToughJerky ), 0.01f )
															 , new Loot( typeof( BatteredBuckler ), 0.62f )
															 , new Loot( typeof( BeatenBattleAxe ), 0.28f )
															 , new Loot( typeof( BentLargeShield ), 0.60f )
															 , new Loot( typeof( CarpentersMallet ), 0.25f )
															 , new Loot( typeof( CrackedBuckler ), 0.16f )
															 , new Loot( typeof( CrackedShortbow ), 0.25f )
															 , new Loot( typeof( CrackedSledge ), 0.26f )
															 , new Loot( typeof( CrudeBastardSword ), 0.27f )
															 , new Loot( typeof( FeebleSword ), 0.27f )
															 , new Loot( typeof( FlimsyChainBelt ), 0.49f )
															 , new Loot( typeof( FlimsyChainBoots ), 0.50f )
															 , new Loot( typeof( FlimsyChainBracers ), 0.50f )
															 , new Loot( typeof( FlimsyChainCloak ), 0.56f )
															 , new Loot( typeof( FlimsyChainGloves ), 0.55f )
															 , new Loot( typeof( FlimsyChainPants ), 0.51f )
															 , new Loot( typeof( FlimsyChainVest ), 0.49f )
															 , new Loot( typeof( FrayedBelt ), 0.71f )
															 , new Loot( typeof( FrayedBracers ), 0.68f )
															 , new Loot( typeof( FrayedCloak ), 0.75f )
															 , new Loot( typeof( FrayedGloves ), 0.73f )
															 , new Loot( typeof( FrayedPants ), 0.78f )
															 , new Loot( typeof( FrayedRobe ), 0.76f )
															 , new Loot( typeof( FrayedShoes ), 0.67f )
															 , new Loot( typeof( LooseChainBelt ), 0.14f )
															 , new Loot( typeof( LooseChainBoots ), 0.14f )
															 , new Loot( typeof( LooseChainBracers ), 0.15f )
															 , new Loot( typeof( LooseChainCloak ), 0.18f )
															 , new Loot( typeof( LooseChainGloves ), 0.15f )
															 , new Loot( typeof( LooseChainPants ), 0.14f )
															 , new Loot( typeof( LooseChainVest ), 0.15f )
															 , new Loot( typeof( PatchworkArmor ), 0.23f )
															 , new Loot( typeof( PatchworkBelt ), 0.22f )
															 , new Loot( typeof( PatchworkBracers ), 0.22f )
															 , new Loot( typeof( PatchworkCloak ), 0.23f )
															 , new Loot( typeof( PatchworkGloves ), 0.20f )
															 , new Loot( typeof( PatchworkPants ), 0.24f )
															 , new Loot( typeof( PatchworkShoes ), 0.20f )
															 , new Loot( typeof( RaggedCloak ), 0.68f )
															 , new Loot( typeof( RaggedLeatherBelt ), 0.65f )
															 , new Loot( typeof( RaggedLeatherBoots ), 0.60f )
															 , new Loot( typeof( RaggedLeatherBracers ), 0.65f )
															 , new Loot( typeof( RaggedLeatherGloves ), 0.66f )
															 , new Loot( typeof( RaggedLeatherPants ), 0.70f )
															 , new Loot( typeof( RaggedLeatherVest ), 0.71f )
															 , new Loot( typeof( RustCoveredBlunderbuss ), 0.26f )
															 , new Loot( typeof( RustyHatchet ), 0.29f )
															 , new Loot( typeof( SharpenedLetterOpener ), 0.26f )
															 , new Loot( typeof( WitheredStaff ), 0.30f )
															 , new Loot( typeof( WornHideCloak ), 0.18f )
															 , new Loot( typeof( WornLargeShield ), 0.18f )
															 , new Loot( typeof( WornLeatherBelt ), 0.19f )
															 , new Loot( typeof( WornLeatherBoots ), 0.19f )
															 , new Loot( typeof( WornLeatherBracers ), 0.20f )
															 , new Loot( typeof( WornLeatherGloves ), 0.20f )
															 , new Loot( typeof( WornLeatherPants ), 0.19f )
															 , new Loot( typeof( WornLeatherVest ), 0.19f )
														 };
		public static Loot[] KoboldMiner = new Loot[] { new Loot( typeof( FormulaEnchantChestMinorMana ), 0.01f)
														  , new Loot( typeof( Malachite ), 0.43f)
														  , new Loot( typeof( NotchedShortsword ), 0.03f)
														  , new Loot( typeof( PatternFineLeatherBoots ), 0.01f)
														  , new Loot( typeof( PatternFineLeatherGloves ), 0.01f)
														  , new Loot( typeof( PatternRedLinenRobe ), 0.17f)
														  , new Loot( typeof( PatternRedLinenVest ), 0.01f)
														  , new Loot( typeof( PatternRuggedLeatherPants ), 0.01f)
														  , new Loot( typeof( PatternWhiteLeatherJerkin ), 0.01f)
														  , new Loot( typeof( PlansCopperChainVest ), 0.14f)
														  , new Loot( typeof( PlansGemmedCopperGauntlets ), 0.01f)
														  , new Loot( typeof( RecipeSwiftnessPotion ), 0.01f)
														  , new Loot( typeof( SchematicMechanicalSquirrel ), 0.01f)
														  , new Loot( typeof( SeveringAxe ), 0.01f)
														  , new Loot( typeof( Tigerseye ), 0.15f)
														  , new Loot( typeof( TrainingSword ), 0.01f)
														  , new Loot( typeof( Beatstick ), 0.04f)
														  , new Loot( typeof( BillyClub ), 0.03f)
														  , new Loot( typeof( CadetsBow ), 0.06f)
														  , new Loot( typeof( CopperOre ), 1.5f)
														  , new Loot( typeof(FineScimitar ), 0.05f)
														  , new Loot( typeof( GoldDust ), 7.9f)
														  , new Loot( typeof( HuntingRifle ), 0.03f)
														  , new Loot( typeof( KoboldMiningMallet ), 3.91f)
														  , new Loot( typeof( LargeCandle ), 90.51f)
														  , new Loot( typeof( LightLeather ), 0.01f)
														  , new Loot( typeof( LinenCloth ), 29.03f)
														  , new Loot( typeof( LongBoStaff ), 0.04f)
														  , new Loot( typeof( LumberjackAxe ), 0.03f)
														  , new Loot( typeof( MinorHealingPotion ), 2.26f)
														  , new Loot( typeof( Peacebloom ), 0.01f)
														  , new Loot( typeof( PelletRifle ), 0.1f)
														  , new Loot( typeof( PracticeSword ), 0.1f)
														  , new Loot( typeof( RecipeElixirOfMinorAgility ), 0.01f)
														  , new Loot( typeof( RefreshingSpringWater ), 3.7f)
														  , new Loot( typeof( RoughStone ), 1.51f)
														  , new Loot( typeof( ScrollOfProtection ), 0.71f)
														  , new Loot( typeof( ScrollOfSpirit ), 0.68f)
														  , new Loot( typeof( ShinyRedApple ), 6.96f)
														  , new Loot( typeof( Silverleaf ), 0.01f)
														  , new Loot( typeof( SimpleDagger ), 0.05f)
														  , new Loot( typeof( SmallBlackPouch ), 0.04f)
														  , new Loot( typeof( SmallBluePouch ), 0.03f)
														  , new Loot( typeof( SmallBrownPouch ), 0.05f)
														  , new Loot( typeof( SmallGreenPouch ), 0.05f)
														  , new Loot( typeof( SmallRedPouch ), 0.04f)
														  , new Loot( typeof( WoodChopper ), 0.04f)
														  , new Loot( typeof( BeatenBattleAxe ), 0.58f)
														  , new Loot( typeof( CarpentersMallet ), 0.55f)
														  , new Loot( typeof( CrackedBuckler ), 0.4f)
														  , new Loot( typeof( CrackedShortbow ), 0.53f)
														  , new Loot( typeof( CrackedSledge ), 0.52f)
														  , new Loot( typeof( CrudeBastardSword ), 0.52f)
														  , new Loot( typeof(FeebleSword ), 0.51f)
														  , new Loot( typeof( LooseChainBelt ), 0.28f)
														  , new Loot( typeof( LooseChainBoots ), 0.3f)
														  , new Loot( typeof( LooseChainBracers ), 0.3f)
														  , new Loot( typeof( LooseChainCloak ), 0.33f)
														  , new Loot( typeof( LooseChainGloves ), 0.34f)
														  , new Loot( typeof( LooseChainPants ), 0.29f)
														  , new Loot( typeof( LooseChainVest ), 0.27f)
														  , new Loot( typeof( PatchworkArmor ), 0.48f)
														  , new Loot( typeof( PatchworkBelt ), 0.42f)
														  , new Loot( typeof( PatchworkBracers ), 0.39f)
														  , new Loot( typeof( PatchworkCloak ), 0.43f)
														  , new Loot( typeof( PatchworkGloves ), 0.46f)
														  , new Loot( typeof( PatchworkPants ), 0.51f)
														  , new Loot( typeof( PatchworkShoes ), 0.39f)
														  , new Loot( typeof( RustCoveredBlunderbuss ), 0.57f)
														  , new Loot( typeof( RustyHatchet ), 0.61f)
														  , new Loot( typeof( SharpenedLetterOpener ), 0.6f)
														  , new Loot( typeof( WitheredStaff ), 0.58f)
														  , new Loot( typeof( WornHideCloak ), 0.39f)
														  , new Loot( typeof( WornLargeShield ), 0.36f)
														  , new Loot( typeof( WornLeatherBelt ), 0.4f)
														  , new Loot( typeof( WornLeatherBoots ), 0.4f)
														  , new Loot( typeof( WornLeatherBracers ), 0.43f)
														  , new Loot( typeof( WornLeatherGloves ), 0.37f)
														  , new Loot( typeof( WornLeatherPants ), 0.42f)
														  , new Loot( typeof( WornLeatherVest ), 0.33f)
													  };
		public static Loot[] KoboldLaborer= new Loot[] {  new Loot( typeof( MinorHealingPotion ), 0.1f )
														   , new Loot( typeof( RefreshingSpringWater ), 7.3f )
														   , new Loot( typeof( ShinyRedApple ), 15.5f )
														   , new Loot( typeof( SmallBlackPouch ), 0.10f )
														   , new Loot( typeof( SmallBluePouch ), 0.09f )
														   , new Loot( typeof( SmallBrownPouch ), 0.09f )
														   , new Loot( typeof( SmallRedPouch ), 0.10f )
														   , new Loot( typeof( SmallWoodenHammer ), 1.0f )
														   , new Loot( typeof( ToughJerky ), 0.2f )
														   , new Loot( typeof( BatteredBuckler ), 1.40f )
														   , new Loot( typeof( BentLargeShield ), 1.3f )
														   , new Loot( typeof( DrySaltLick ), 0.3f )
														   , new Loot( typeof( FlimsyChainBelt ), 1.0f )
														   , new Loot( typeof( FlimsyChainBoots ), 1.0f )
														   , new Loot( typeof( FlimsyChainBracers ), 1.1f )
														   , new Loot( typeof( FlimsyChainCloak ), 1.1f )
														   , new Loot( typeof( FlimsyChainGloves ), 1.0f )
														   , new Loot( typeof( FlimsyChainPants ), 1.1f )
														   , new Loot( typeof( FlimsyChainVest ), 1.0f )
														   , new Loot( typeof( FrayedBelt ), 1.5f )
														   , new Loot( typeof( FrayedBracers ), 1.51f )
														   , new Loot( typeof( FrayedCloak ), 1.6f )
														   , new Loot( typeof( FrayedGloves ), 1.39f )
														   , new Loot( typeof( FrayedPants ), 1.6f )
														   , new Loot( typeof( FrayedRobe), 1.5f )
														   , new Loot( typeof( FrayedShoes ), 1.5f )
														   , new Loot( typeof( MeltedCandle ), 33.8f )
														   , new Loot( typeof( RaggedCloak ), 1.29f )
														   , new Loot( typeof( RaggedLeatherBelt ), 1.4f )
														   , new Loot( typeof( RaggedLeatherBoots ), 1.4f )
														   , new Loot( typeof( RaggedLeatherBracers ), 1.2f )
														   , new Loot( typeof( RaggedLeatherGloves ), 1.5f )															, new Loot( typeof( RaggedLeatherPants ), 1.2f )
														   , new Loot( typeof( RaggedLeatherVest ), 1.3f )
													   };
		public static Loot[] KoboldGeomancer= new Loot[] {  new Loot( typeof( Malachite ), 2.3f )
															 , new Loot( typeof( PatternRedLinenRobe ), 0.2f )
															 , new Loot( typeof( PatternWhiteLeatherJerkin ), 0.1f )
															 , new Loot( typeof( PlansCopperChainVest ), 0.10f )
															 , new Loot( typeof( SilverBar ), 0.1f )
															 , new Loot( typeof( Tigerseye ), 0.7f )
															 , new Loot( typeof( Beatstick ), 0.3f )
															 , new Loot( typeof( BillyClub ), 0.1f )
															 , new Loot( typeof( ToughJerky ), 0.2f )
															 , new Loot( typeof( CopperOre ), 0.30f )
															 , new Loot( typeof( FlangedMace ), 0.1f )
															 , new Loot( typeof( ForestMushroomCap ), 0.2f )
															 , new Loot( typeof( GoldDust ), 3.1f )
															 , new Loot( typeof( HuntingRifle ), 0.1f )
															 , new Loot( typeof( KoboldExcavationPick ), 2.6f )
															 , new Loot( typeof( LargeCandle ), 90.9f )
															 , new Loot( typeof( LightLeather ), 0.1f )
															 , new Loot( typeof( LinenCloth ), 48.1f )
															 , new Loot( typeof( LongBoStaff ), 0.3f )
															 , new Loot( typeof( LumberjackAxe ), 0.1f )
															 , new Loot( typeof( MagicCandle ), 21.0f )
															 , new Loot( typeof( MinorHealingPotion ), 2.2f )
															 , new Loot( typeof( Peacebloom ), 0.1f )
															 , new Loot( typeof( PelletRifle ), 0.1f )
															 , new Loot( typeof( RefreshingSpringWater), 4.3f )
															 , new Loot( typeof( RoughStone ), 0.2f )
															 , new Loot( typeof( ScrollOfProtection ), 0.6f )
															 , new Loot( typeof( ScrollOfSpirit ), 0.8f )
															 , new Loot( typeof( ShinyRedApple ), 7.5f )
															 , new Loot( typeof( Silverleaf ), 0.1f )
															 , new Loot( typeof( SmallBlackPouch ), 0.2f )
															 , new Loot( typeof( ToughJerky ), 0.1f )																, new Loot( typeof( WoodChopper ), 0.2f )
															 , new Loot( typeof( BeatenBattleAxe ), 0.5f )
															 , new Loot( typeof( CarpentersMallet ), 0.4f )
															 , new Loot( typeof( CrackedBuckler ), 0.4f )
															 , new Loot( typeof( CrackedShortbow ), 0.6f )
															 , new Loot( typeof( CrackedSledge ), 0.7f )
															 , new Loot( typeof( CrudeBastardSword ), 1.8f )
															 , new Loot( typeof( FeebleSword ), 0.6f )
															 , new Loot( typeof( LooseChainBelt ), 0.2f )
															 , new Loot( typeof( LooseChainBoots ), 0.3f )
															 , new Loot( typeof( LooseChainBracers ), 0.3f )
															 , new Loot( typeof( LooseChainCloak ), 0.3f )
															 , new Loot( typeof( LooseChainGloves), 0.2f )
															 , new Loot( typeof( LooseChainPants), 0.1f )
															 , new Loot( typeof( LooseChainVest), 0.3f )
															 , new Loot( typeof( PatchworkArmor), 0.5f )
															 , new Loot( typeof( PatchworkBelt), 0.3f )
															 , new Loot( typeof( PatchworkBracers), 0.6f )
															 , new Loot( typeof( PatchworkCloak), 0.3f )
															 , new Loot( typeof( PatchworkGloves), 0.6f )
															 , new Loot( typeof( PatchworkPants), 0.6f )
															 , new Loot( typeof( PatchworkShoes), 0.3f )
															 , new Loot( typeof( RustCoveredBlunderbuss), 0.7f )
															 , new Loot( typeof( RustyHatchet), 0.9f )
															 , new Loot( typeof( SharpenedLetterOpener), 0.7f )
															 , new Loot( typeof( WitheredStaff), 0.7f )
															 , new Loot( typeof( WornHideCloak), 0.4f )
															 , new Loot( typeof( WornLargeShield), 0.4f )
															 , new Loot( typeof( WornLeatherBelt), 0.5f )
															 , new Loot( typeof( WornLeatherBoots), 0.3f )
															 , new Loot( typeof( WornLeatherBracers), 0.4f )
															 , new Loot( typeof( WornLeatherGloves), 0.3f )
															 , new Loot( typeof( WornLeatherPants), 0.5f )
															 , new Loot( typeof( WornLeatherVest), 0.4f )
														 };
		public static Loot[] KoboldDigger= new Loot[] {  new Loot( typeof( BurntLeatherVest ), 0.2f )
														  , new Loot( typeof( FireWand ), 0.2f )
														  , new Loot( typeof( HeavyShortbow ), 0.1f )
														  , new Loot( typeof( HuntingBow ), 0.1f )
														  , new Loot( typeof( JourneymansVest ), 0.1f )
														  , new Loot( typeof( Malachite ), 0.1f )
														  , new Loot( typeof( PatternFineLeatherBoots), 0.1f )
														  //								, new Loot( typeof( PioneerTrousersOfTheEagle), 0.1f )
														  //								, new Loot( typeof( PioneerTunicOfTheMonkey), 3.1f )
														  , new Loot( typeof( HuntingRifle ), 0.1f )
														  //								, new Loot( typeof( PriestsMaceOfPower), 0.1f )
														  , new Loot( typeof( Shadowgem), 0.1f )
														  //								, new Loot( typeof( SimpleBritchesOfTheEagle), 0.1f )
														  , new Loot( typeof( WarriorsTunic), 0.1f )
														  , new Loot( typeof( BardsCloak), 0.1f )
														  , new Loot( typeof( CadetBelt), 0.1f )
														  , new Loot( typeof( CadetBoots), 0.1f )
														  , new Loot( typeof( CadetBracers), 0.1f )
														  , new Loot( typeof( CadetCloak), 0.1f )
														  , new Loot( typeof( CadetGauntlets), 0.1f )
														  , new Loot( typeof( CoarseStone), 2.4f )
														  , new Loot( typeof( CopperOre), 4.0f )
														  , new Loot( typeof( GypsyBands), 0.1f )
														  , new Loot( typeof( GypsyGloves), 0.1f )
														  , new Loot( typeof( GypsySandals), 0.1f )
														  , new Loot( typeof( GypsySash), 0.2f )
														  , new Loot( typeof( HaunchOfMeat), 0.1f )
														  , new Loot( typeof( HuntingBelt), 0.1f )																		, new Loot( typeof( HuntingBoots), 0.1f )
														  , new Loot( typeof( HuntingBracers), 0.1f )
														  , new Loot( typeof( HuntingCloak ), 0.1f )
														  , new Loot( typeof( IceColdMilk), 2.3f )
														  , new Loot( typeof( InfantryBoots), 0.1f )
														  , new Loot( typeof( InfantryGauntlets), 0.1f )
														  , new Loot( typeof( LesserHealingPotion), 1.2f )
														  , new Loot( typeof( LinenCloth), 70.9f )
														  , new Loot( typeof( MinorManaPotion), 0.9f )
														  , new Loot( typeof( PioneerBoots), 0.1f )
														  , new Loot( typeof( PioneerGloves), 0.1f )
														  , new Loot( typeof( RecipeCookedCrabClaw), 0.1f )
														  , new Loot( typeof( RecipeElixirOfMinorAgility), 0.1f )
														  , new Loot( typeof( RedLeatherBag), 0.01f )
														  , new Loot( typeof( RoughStone), 0.6f )
														  , new Loot( typeof( ScrollOfIntellect), 0.2f )
														  , new Loot( typeof( ScrollOfProtection), 0.3f )
														  , new Loot( typeof( ScrollOfSpirit), 0.2f )
														  , new Loot( typeof( ScrollOfStamina), 0.2f )
														  , new Loot( typeof( SimpleBands), 0.1f )
														  , new Loot( typeof( SimpleCape), 0.1f )
														  , new Loot( typeof( SimpleCord), 0.1f )
														  , new Loot( typeof( SimpleGloves), 0.1f )
														  , new Loot( typeof( SimpleShoes), 0.2f )
														  , new Loot( typeof( SpellbinderBelt), 0.1f )
														  , new Loot( typeof( SpellbinderBoots), 0.1f )
														  , new Loot( typeof( SpellbinderBracers), 0.1f )
														  , new Loot( typeof( SpellbinderCloak), 0.1f )
														  , new Loot( typeof( SpellbinderGloves), 0.1f )
														  , new Loot( typeof( TelAbimBanana), 4.7f )
														  , new Loot( typeof( TinOre), 1.6f )
														  , new Loot( typeof( VeteranBracers), 0.01f )
														  , new Loot( typeof( VeteranCloak), 0.1f )
														  , new Loot( typeof( VeteranGirdle), 0.1f )
														  , new Loot( typeof( WhiteLeatherBag), 0.01f )
														  , new Loot( typeof( CalicoBelt), 0.3f )
														  , new Loot( typeof( CalicoBracers), 0.3f )
														  , new Loot( typeof( CalicoCloak), 0.3f )
														  , new Loot( typeof( CalicoGloves), 0.3f )
														  , new Loot( typeof( CalicoPants), 0.3f )
														  , new Loot( typeof( CalicoShoes), 0.3f )
														  , new Loot( typeof( CalicoTunic), 0.3f )
														  , new Loot( typeof( CheapBlunderbuss), 0.4f )
														  , new Loot( typeof( CommonersSword), 0.4f )
														  , new Loot( typeof( CrudeBattleAxe), 0.5f )
														  , new Loot( typeof( FeebleShortbow), 0.6f )
														  , new Loot( typeof( FishermanKnife), 0.5f )
														  , new Loot( typeof( GnawedBone), 0.1f )
														  , new Loot( typeof( HeavyHammer), 0.4f )
														  , new Loot( typeof( OldGreatsword), 0.3f )
														  , new Loot( typeof( RoughWoodenStaff), 0.5f )
														  , new Loot( typeof( RustyWarhammer), 0.4f )
														  , new Loot( typeof( WarpedCloak), 0.3f )
														  , new Loot( typeof( WarpedLeatherBelt), 0.3f )
														  , new Loot( typeof( WarpedLeatherBoots), 0.2f )
														  , new Loot( typeof( WarpedLeatherBracers), 0.3f )
														  , new Loot( typeof( WarpedLeatherGloves), 0.3f )
														  , new Loot( typeof( WarpedLeatherPants), 0.4f )
														  , new Loot( typeof( WarpedLeatherVest), 0.2f )
														  , new Loot( typeof( WoodenBuckler), 0.3f )
														  , new Loot( typeof( WoodenShield), 0.3f )
														  , new Loot( typeof( WornCloak), 0.2f )
														  , new Loot( typeof( WornHatchet), 0.5f )
														  , new Loot( typeof( WornMailBelt), 0.3f )
														  , new Loot( typeof( WornMailBoots), 0.2f )
														  , new Loot( typeof( WornMailBracers), 0.3f )
														  , new Loot( typeof( WornMailGloves), 0.2f )
														  , new Loot( typeof( WornMailPants), 0.3f )
														  , new Loot( typeof( WornMailVest), 0.2f )
													  };								

		public static Loot[] TunnelRatKobold= new Loot[] {  new Loot( typeof( DisciplesGloves), 1.72f )
															 , new Loot( typeof( GreenLeatherBag), 1.72f )
															 , new Loot( typeof( IceColdMilk), 5.17f )
															 , new Loot( typeof( LinenCloth), 98.28f )
															 , new Loot( typeof( MinorManaPotion), 5.17f )
															 , new Loot( typeof( RecipeElixirOfMinorAgility), 3.45f )
															 , new Loot( typeof( TelAbimBanana), 6.90f )
															 , new Loot( typeof( TunnelRatEar), 5.17f )																		, new Loot( typeof( CalicoPants), 1.72f )																		, new Loot( typeof( CalicoShoes), 3.45f )
															 , new Loot( typeof( CalicoTunic), 1.72f )
															 , new Loot( typeof( CheapBlunderbuss), 1.72f )
															 , new Loot( typeof( WornHatchet), 1.72f )
															 , new Loot( typeof( WornMailBoots), 3.45f )
															 , new Loot( typeof( WornMailGloves), 1.72f )		
														 };								
		public static Loot[] Goldtooth= new Loot[] {new Loot( typeof( HuntingBow), 0.0548607f ) 
,new Loot( typeof( Malachite), 0.394997f ) 
,new Loot( typeof( NotchedShortsword), 0.109721f ) 
,new Loot( typeof( PatternFineLeatherBoots), 0.0219443f ) 
,new Loot( typeof( PatternRedLinenRobe), 0.142638f ) 
,new Loot( typeof( PatternRedLinenVest), 0.0219443f ) 
,new Loot( typeof( PatternWhiteLeatherJerkin), 0.0219443f ) 
,new Loot( typeof( PlansCopperChainVest), 0.0768049f ) 
,new Loot( typeof( ScalpingTomahawk), 0.0658328f ) 
,new Loot( typeof( SeveringAxe), 0.0219443f ) 
,new Loot( typeof( Tigerseye), 0.109721f ) 
,new Loot( typeof( TrainingSword), 0.0548607f ) 
,new Loot( typeof( Beatstick), 0.241387f ) 
,new Loot( typeof( BernicesNecklace), 37.415f ) 
,new Loot( typeof( BillyClub), 0.109721f ) 
,new Loot( typeof( CopperOre), 2.30415f ) 
,new Loot( typeof( DarnassianBleu), 0.0219443f ) 
,new Loot( typeof( FlangedMace), 0.131666f ) 
,new Loot( typeof( ForestMushroomCap), 0.0219443f ) 
,new Loot( typeof( GoldDust), 14.7136f ) 
,new Loot( typeof( HuntingRifle), 0.109721f ) 
,new Loot( typeof( LargeCandle), 10.1931f ) 
,new Loot( typeof( LightLeather), 0.0219443f ) 
,new Loot( typeof( LinenCloth), 27.3645f ) 
,new Loot( typeof( LongBoStaff), 0.230415f ) 
,new Loot( typeof( LumberjackAxe), 0.142638f ) 
,new Loot( typeof( MinorHealingPotion), 2.16151f ) 
,new Loot( typeof( PelletRifle), 0.0219443f ) 
,new Loot( typeof( PracticeSword), 0.120693f ) 
,new Loot( typeof( RefreshingSpringWater), 3.46719f ) 
,new Loot( typeof( RoughStone), 2.29318f ) 
,new Loot( typeof( ScrollOfProtection), 0.6693f ) 
,new Loot( typeof( ScrollOfSpirit), 0.570551f ) 
,new Loot( typeof( ShinyRedApple), 7.26355f ) 
,new Loot( typeof( SmallBlackPouch), 0.0329164f ) 
,new Loot( typeof( SmallBluePouch), 0.0438885f ) 
,new Loot( typeof( SmallBrownPouch), 0.0329164f ) 
,new Loot( typeof( SmallGreenPouch), 0.0438885f ) 
,new Loot( typeof( SmallRedPouch), 0.0438885f ) 
,new Loot( typeof( ToughJerky), 0.0329164f ) 
,new Loot( typeof( WoodChopper), 0.175554f ) 
,new Loot( typeof( AGoldTooth), 9.447f ) 
,new Loot( typeof( BeatenBattleAxe), 0.581523f ) 
,new Loot( typeof( CarpentersMallet), 0.581523f ) 
,new Loot( typeof( CrackedBuckler), 0.329164f ) 
,new Loot( typeof( CrackedShortbow), 0.460829f ) 
,new Loot( typeof( CrackedSledge), 0.548607f ) 
,new Loot( typeof( CrudeBastardSword), 0.394997f ) 
,new Loot( typeof( FeebleSword), 0.460829f ) 
,new Loot( typeof( LooseChainBelt), 0.263331f ) 
,new Loot( typeof( LooseChainBoots), 0.230415f ) 
,new Loot( typeof( LooseChainBracers), 0.373052f ) 
,new Loot( typeof( LooseChainCloak), 0.416941f ) 
,new Loot( typeof( LooseChainGloves), 0.405969f ) 
,new Loot( typeof( LooseChainPants), 0.285275f ) 
,new Loot( typeof( LooseChainVest), 0.318192f ) 
,new Loot( typeof( PatchworkArmor), 0.460829f ) 
,new Loot( typeof( PatchworkBelt), 0.427913f ) 
,new Loot( typeof( PatchworkBracers), 0.394997f ) 
,new Loot( typeof( PatchworkCloak), 0.416941f ) 
,new Loot( typeof( PatchworkGloves), 0.438885f ) 
,new Loot( typeof( PatchworkPants), 0.329164f ) 
,new Loot( typeof( PatchworkShoes), 0.427913f ) 
,new Loot( typeof( RustCoveredBlunderbuss), 0.493746f ) 
,new Loot( typeof( RustyHatchet), 0.680272f ) 
,new Loot( typeof( SharpenedLetterOpener), 0.537634f ) 
,new Loot( typeof( WitheredStaff), 0.482774f ) 
,new Loot( typeof( WornHideCloak), 0.460829f ) 
,new Loot( typeof( WornLargeShield), 0.329164f ) 
,new Loot( typeof( WornLeatherBelt), 0.394997f ) 
,new Loot( typeof( WornLeatherBoots), 0.36208f ) 
,new Loot( typeof( WornLeatherBracers), 0.373052f ) 
,new Loot( typeof( WornLeatherGloves), 0.416941f ) 
,new Loot( typeof( WornLeatherPants), 0.340136f ) 
,new Loot( typeof( WornLeatherVest), 0.241387f ) 
};								

	}
}
