//////////////////////////////////////////////////////////
// DrNexus Beginners MiscelenaousItems Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class BeginnersMiscelenaousItemsDrops
	{
		public static Loot[]BeginnersMiscelenaousItems = new Loot[]
		{
			new Loot( typeof( RoughVultureFeathers ), 31.37255f )
				, new Loot( typeof( MeltedCandle ), 92.15686f )
				, new Loot( typeof( SnappedSpiderLimb ), 50.98039f )
				, new Loot( typeof( TheStoryOfMorganLadimore ), 95f )
				, new Loot( typeof( ForestSpiderWebbing ), 60.78432f )
				, new Loot( typeof( DirtyTroggCloth ), 60.78432f )
				, new Loot( typeof( BrokenBoarTusk ), 50.98039f )
				, new Loot( typeof( RabbitsFoot ), 25.49019f )
				, new Loot( typeof( BrokenArrow ), 90.19608f )
				, new Loot( typeof( CrackedEggShells ), 62.74509f )
				, new Loot( typeof( DiscoloredFang ), 50.98039f )
				, new Loot( typeof( RuinedPelt ), 60.78432f )
				, new Loot( typeof( BrokenScorpidLeg ), 31.37255f )
				, new Loot( typeof( StoneArrowhead ), 21.56863f )
				, new Loot( typeof( SquashedRabbitCarcass ), 41.17647f )
				, new Loot( typeof( UnconsciousDigRat ), 95f )
				, new Loot( typeof( ASackOfCoins ), 95f )
				, new Loot( typeof( CovertOpsPack ), 95f )
				, new Loot( typeof( JournalPage ), 92.15686f )
				, new Loot( typeof( GuildCharter ), 95f )
				, new Loot( typeof( _10PoundMudSnapper ), 33.33333f )
				, new Loot( typeof( _12PoundMudSnapper ), 21.56863f )
				, new Loot( typeof( _15PoundMudSnapper ), 5.882353f )
				, new Loot( typeof( OldSkull ), 41.17647f )
				, new Loot( typeof( BatteredChest ), 21.56863f )
				, new Loot( typeof( PracticeLock ), 1.960784f )
				, new Loot( typeof( ASmallContainerOfGems ), 95f )
				, new Loot( typeof( Hearthstone ), 95f )
				, new Loot( typeof( BrokenFang ), 50.98039f )
				, new Loot( typeof( ChippedClaw ), 68.62746f )
				, new Loot( typeof( PluckedFeather ), 60.78432f )
				, new Loot( typeof( SplinteredTusk ), 50.98039f )
				, new Loot( typeof( SeveredPincer ), 50.98039f )
				, new Loot( typeof( StickyIchor ), 41.17647f )
				, new Loot( typeof( BugEye ), 60.78432f )
				, new Loot( typeof( BrokenDragonmawShinbone ), 95f )
				, new Loot( typeof( TazansSatchel ), 95f )
				, new Loot( typeof( ChestOfContainmentCoffers ), 95f )
				, new Loot( typeof( BloodstainedJournal ), 95f )
				, new Loot( typeof( CertificateOfThievery ), 95f )
				, new Loot( typeof( FlareGun ), 95f )
				, new Loot( typeof( FizzulesWhistle ), 95f )
				, new Loot( typeof( SampleOfZanzilsAlteredMixture ), 95f )
				, new Loot( typeof( ParrotDroppings ), 95f )
				, new Loot( typeof( LargeRuffledFeather ), 95f )
				, new Loot( typeof( MutilatedRatCarcass ), 95f )
				, new Loot( typeof( SparklematicWrappedBox ), 1.960784f )
				, new Loot( typeof( ABulgingCoinPurse ), 95f )
				, new Loot( typeof( TradersSatchel ), 95f )
				, new Loot( typeof( KovicsTradingSatchel ), 5.882353f )
				, new Loot( typeof( HoardOfTheBlackDragonflight ), 95f )
				, new Loot( typeof( BlackDragonflightMolt ), 95f )
				, new Loot( typeof( KumshasJunk ), 95f )
				, new Loot( typeof( CrystallizedNote ), 95f )
				, new Loot( typeof( AMangledJournal ), 95f )
				, new Loot( typeof( GnomeEngineersRenewalGift ), 95f )
				, new Loot( typeof( TorwasPouch ), 95f )
				, new Loot( typeof( FelSalve ), 95f )
				, new Loot( typeof( ADingyFannyPack ), 95f )
				, new Loot( typeof( CenarionCircleCache ), 1.960784f )
				, new Loot( typeof( PackageOfEmptyOozeContainers ), 95f )
				, new Loot( typeof( BagOfEmptyOozeContainers ), 95f )
				, new Loot( typeof( KumishasJunk ), 95f )
				, new Loot( typeof( WinnasKittenCarrier ), 95f )
				, new Loot( typeof( ZerglingLeash ), 95f )
				, new Loot( typeof( PandaCollar ), 95f )
				, new Loot( typeof( DiabloStone ), 95f )
				, new Loot( typeof( DampNote ), 95f )
				, new Loot( typeof( BatteredJunkbox ), 95f )
				, new Loot( typeof( HeavyJunkbox ), 95f )
				, new Loot( typeof( FeralasAhi ), 95f )
				, new Loot( typeof( LightFeather ), 41.17647f )
				, new Loot( typeof( ShinyFishScales ), 41.17647f )
				, new Loot( typeof( FishOil ), 41.17647f )
				, new Loot( typeof( Mistletoe ), 80.39216f )
				, new Loot( typeof( SmokywoodPasturesSampler ), 95f )
				, new Loot( typeof( WinterVeilDisguiseKit ), 95f )
				, new Loot( typeof( SmokywoodPasturesGiftPack ), 95f )
				, new Loot( typeof( TheFeastOfWinterVeil ), 95f )
		};
	}
}
