//////////////////////////////////////////////////////////
// DrNexus Low LeatherArmors Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class LowLeatherArmorsDrops
	{
		public static Loot[]LowLeatherArmors = new Loot[]
		{
			new Loot( typeof( LayeredTunic ), 88f )
				, new Loot( typeof( DwarvenLeatherPants ), 88f )
				, new Loot( typeof( DirtyLeatherVest ), 87.6f )
				, new Loot( typeof( DirtyLeatherPants ), 88f )
				, new Loot( typeof( IceCoveredBracers ), 41.4f )
				, new Loot( typeof( RoughLeatherBoots ), 47.2f )
				, new Loot( typeof( RoughLeatherGloves ), 64.8f )
				, new Loot( typeof( RoughLeatherPants ), 29.2f )
				, new Loot( typeof( RoughLeatherVest ), 29f )
				, new Loot( typeof( WeatherWornBoots ), 47.6f )
				, new Loot( typeof( GnollKindredBracers ), 12.6f )
				, new Loot( typeof( LionStampedGloves ), 81f )
				, new Loot( typeof( WornLeatherBoots ), 80.4f )
				, new Loot( typeof( WornLeatherBracers ), 81.6f )
				, new Loot( typeof( WornLeatherPants ), 81.2f )
				, new Loot( typeof( WornLeatherVest ), 62.4f )
				, new Loot( typeof( WarpedLeatherBelt ), 39.6f )
				, new Loot( typeof( WarpedLeatherBracers ), 67.6f )
				, new Loot( typeof( WarpedLeatherGloves ), 49f )
				, new Loot( typeof( WarpedLeatherVest ), 40.2f )
				, new Loot( typeof( PatchedLeatherGloves ), 10f )
				, new Loot( typeof( RoughLeatherBelt ), 63.2f )
				, new Loot( typeof( RoughLeatherBracers ), 63f )
				, new Loot( typeof( WhiteWolfGloves ), 64f )
				, new Loot( typeof( LumberjackJerkin ), 45.8f )
				, new Loot( typeof( CrackedLeatherPants ), 88.2f )
				, new Loot( typeof( CrackedLeatherVest ), 88f )
				, new Loot( typeof( PatchedPants ), 24.6f )
				, new Loot( typeof( HandstitchedLeatherBoots ), 70.6f )
				, new Loot( typeof( HandstitchedLeatherPants ), 28.4f )
				, new Loot( typeof( SturdyLeatherBracers ), 63.6f )
				, new Loot( typeof( BatteredLeatherHarness ), 24.6f )
				, new Loot( typeof( BatteredLeatherBelt ), 62.2f )
				, new Loot( typeof( BatteredLeatherPants ), 31.4f )
				, new Loot( typeof( BatteredLeatherBoots ), 48.2f )
				, new Loot( typeof( BatteredLeatherBracers ), 65.4f )
				, new Loot( typeof( BatteredLeatherGloves ), 65.4f )
				, new Loot( typeof( BurntLeatherBoots ), 58.4f )
				, new Loot( typeof( BurntLeatherGloves ), 63.8f )
				, new Loot( typeof( DrivingGloves ), 72f )
				, new Loot( typeof( BurntHideBracers ), 39.4f )
				, new Loot( typeof( BurntLeatherBracers ), 81f )
				, new Loot( typeof( HuntingBracers ), 12.4f )
				, new Loot( typeof( ZombieSkinLeggings ), 87f )
				, new Loot( typeof( TribalBoots ), 11.2f )
				, new Loot( typeof( TribalBracers ), 63.6f )
				, new Loot( typeof( TribalGloves ), 40.6f )
				, new Loot( typeof( CeremonialLeatherBracers ), 29.4f )
				, new Loot( typeof( GrayFurBooties ), 58.6f )
				, new Loot( typeof( ZombieSkinBracers ), 80.4f )
				, new Loot( typeof( ZombieSkinBoots ), 70f )
				, new Loot( typeof( TillersVest ), 9.799999f )
				, new Loot( typeof( WeatheredBelt ), 42.4f )
				, new Loot( typeof( HandstitchedLeatherBelt ), 65.2f )
				, new Loot( typeof( EmbossedLeatherGloves ), 28.6f )
				, new Loot( typeof( BurntLeatherBelt ), 73.6f )
				, new Loot( typeof( TribalBelt ), 64.4f )
				, new Loot( typeof( HuntingBelt ), 28.8f )
				, new Loot( typeof( CeremonialLeatherBelt ), 13.4f )
				, new Loot( typeof( RainwalkerBoots ), 78.2f )
				, new Loot( typeof( WoodlandTunic ), 87f )
				, new Loot( typeof( DustCoveredLeggings ), 87.4f )
				, new Loot( typeof( SandrunnerWristguards ), 79.6f )
				, new Loot( typeof( LightScorpidArmor ), 41.8f )
				, new Loot( typeof( VeiledGrips ), 63.6f )
				, new Loot( typeof( TigerHideBoots ), 10.2f )
				, new Loot( typeof( SquealersBelt ), 86.2f )
				, new Loot( typeof( DoubleLayeredGloves ), 80f )
				, new Loot( typeof( BoundHarness ), 9.200001f )
				, new Loot( typeof( RoughHewnKodoLeggings ), 45.8f )
				, new Loot( typeof( PlainsHunterWristguards ), 64.4f )
				, new Loot( typeof( CanopyLeggings ), 87f )
				, new Loot( typeof( FeralBracers ), 86.39999f )
				, new Loot( typeof( IvyCuffs ), 27.4f )
				, new Loot( typeof( AnimalSkinBelt ), 80.2f )
				, new Loot( typeof( SewingGloves ), 80f )
				, new Loot( typeof( HandstitchedLeatherVest ), 60f )
				, new Loot( typeof( NomadicVest ), 87f )
				, new Loot( typeof( RattyOldBelt ), 63f )
				, new Loot( typeof( LitheBoots ), 45.6f )
				, new Loot( typeof( PioneerBelt ), 64.2f )
				, new Loot( typeof( PioneerBoots ), 29.8f )
				, new Loot( typeof( PioneerBracers ), 64f )
				, new Loot( typeof( PioneerGloves ), 52.8f )
				, new Loot( typeof( HandstitchedLeatherBracers ), 71.6f )
				, new Loot( typeof( LightLeatherBracers ), 15.8f )
				, new Loot( typeof( CushionedBoots ), 12.4f )
				, new Loot( typeof( GypsySash ), 42.6f )
				, new Loot( typeof( GypsySandals ), 13.4f )
				, new Loot( typeof( GypsyBands ), 42.2f )
				, new Loot( typeof( GypsyGloves ), 26.8f )
				, new Loot( typeof( ScavengerTunic ), 88f )
				, new Loot( typeof( PrimalBelt ), 80f )
				, new Loot( typeof( PrimalBoots ), 57.6f )
				, new Loot( typeof( PrimalBands ), 71.8f )
				, new Loot( typeof( PrimalMitts ), 62.8f )
				, new Loot( typeof( LupineCuffs ), 14f )
				, new Loot( typeof( GrizzlyBracers ), 54.6f )
				, new Loot( typeof( GrizzlyGloves ), 13.6f )
				, new Loot( typeof( GrizzlyBelt ), 52.6f )
		};
	}
}
