//////////////////////////////////////////////////////////
// DrNexus Low MiscelenaousItems Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class LowMiscelenaousItemsDrops
	{
		public static Loot[]LowMiscelenaousItems = new Loot[]
		{
			new Loot( typeof( DullFrenzyScale ), 30f )
				, new Loot( typeof( BuzzardBeak ), 15f )
				, new Loot( typeof( ChippedBoarTusk ), 69f )
				, new Loot( typeof( ProwlerTeeth ), 82.8f )
				, new Loot( typeof( ShinySeashell ), 85f )
				, new Loot( typeof( PoundOfFlesh ), 34f )
				, new Loot( typeof( AGoldTooth ), 77f )
				, new Loot( typeof( GnollSpittle ), 83f )
				, new Loot( typeof( BuzzardTalon ), 43f )
				, new Loot( typeof( TrollSweat ), 43f )
				, new Loot( typeof( AzuredeepShards ), 31.2f )
				, new Loot( typeof( ChunkOfFlesh ), 88f )
				, new Loot( typeof( LargeBoarTusk ), 44f )
				, new Loot( typeof( ThreshadonAmbergris ), 49f )
				, new Loot( typeof( BloodyBearPaw ), 65f )
				, new Loot( typeof( FineSand ), 19f )
				, new Loot( typeof( ThickSpiderHair ), 45f )
				, new Loot( typeof( ChippedBearTooth ), 85f )
				, new Loot( typeof( LargeBearTooth ), 62f )
				, new Loot( typeof( RuinedDragonhide ), 20f )
				, new Loot( typeof( SmallClaw ), 40f )
				, new Loot( typeof( TinyFang ), 60f )
				, new Loot( typeof( PartiallyDigestedMeat ), 81f )
				, new Loot( typeof( FracturedCanine ), 61f )
				, new Loot( typeof( SharpCanine ), 18f )
				, new Loot( typeof( VultureTalon ), 35f )
				, new Loot( typeof( RoughCrocoliskScale ), 35f )
				, new Loot( typeof( LargeSlimyBone ), 44f )
				, new Loot( typeof( DecomposedBoot ), 24f )
				, new Loot( typeof( ExtinguishedTorch ), 55f )
				, new Loot( typeof( SlimyIchor ), 15f )
				, new Loot( typeof( FamiliarFang ), 45f )
				, new Loot( typeof( FamiliarClaw ), 35f )
				, new Loot( typeof( GryphonFeatherQuill ), 76f )
				, new Loot( typeof( FineParchment ), 81f )
				, new Loot( typeof( BrokenWand ), 89f )
				, new Loot( typeof( BuzzardFeather ), 89f )
				, new Loot( typeof( LegendsOfTheGurubashiVolume3 ), 80f )
				, new Loot( typeof( CrumpledNote ), 81f )
				, new Loot( typeof( RippedNote ), 79f )
				, new Loot( typeof( TornNote ), 73f )
				, new Loot( typeof( OrnateBronzeLockbox ), 60f )
				, new Loot( typeof( HeavyBronzeLockbox ), 44f )
				, new Loot( typeof( IronLockbox ), 30f )
				, new Loot( typeof( StrongIronLockbox ), 12f )
				, new Loot( typeof( CrackedBill ), 77f )
				, new Loot( typeof( RuffledFeather ), 66.99999f )
				, new Loot( typeof( DullKodoTooth ), 89f )
				, new Loot( typeof( KodoHornFragment ), 55f )
				, new Loot( typeof( SmallLeatherCollar ), 73f )
				, new Loot( typeof( DryScorpidEye ), 24f )
				, new Loot( typeof( DryHardenedBarnacle ), 88f )
				, new Loot( typeof( CleanFishbones ), 63f )
				, new Loot( typeof( SlimyBone ), 89f )
				, new Loot( typeof( BloodyLeatherBoot ), 37f )
				, new Loot( typeof( BrokenBloodstainedBow ), 55f )
				, new Loot( typeof( BrokenSpear ), 31f )
				, new Loot( typeof( SeveredTalon ), 23f )
				, new Loot( typeof( BrokenWishbone ), 19f )
				, new Loot( typeof( LargeFlatTooth ), 43f )
				, new Loot( typeof( FineLooseHair ), 5.000001f )
				, new Loot( typeof( SteelArrowhead ), 6f )
				, new Loot( typeof( SmallRaptorTooth ), 6f )
				, new Loot( typeof( SmallFurryPaw ), 26f )
				, new Loot( typeof( SilithidIchor ), 24f )
				, new Loot( typeof( CatFigurine ), 88f )
				, new Loot( typeof( GlowingCatFigurine ), 88f )
				, new Loot( typeof( ChewToy ), 85f )
				, new Loot( typeof( FoldedHandkerchief ), 84f )
				, new Loot( typeof( DrySaltLick ), 78f )
				, new Loot( typeof( PrimitiveRockTool ), 82f )
				, new Loot( typeof( EmptyWallet ), 61f )
				, new Loot( typeof( GnawedBone ), 74f )
				, new Loot( typeof( BentSpoon ), 70f )
				, new Loot( typeof( PieceOfCoral ), 61f )
				, new Loot( typeof( LuckyCharm ), 42f )
				, new Loot( typeof( SmallPocketWatch ), 30f )
				, new Loot( typeof( ScratchingStick ), 24f )
				, new Loot( typeof( BrokenMirror ), 47f )
				, new Loot( typeof( BeadyEyeStalk ), 43f )
				, new Loot( typeof( SmallBarnacledClam ), 88f )
				, new Loot( typeof( ThickShelledClam ), 83f )
				, new Loot( typeof( BrokenAntler ), 16f )
				, new Loot( typeof( HatchedEggSac ), 82f )
				, new Loot( typeof( StickySpiderWebbing ), 49f )
				, new Loot( typeof( RockChip ), 11f )
				, new Loot( typeof( AFrayedKnot ), 82f )
				, new Loot( typeof( DriedBatBlood ), 73f )
				, new Loot( typeof( PatchOfBatHair ), 77f )
				, new Loot( typeof( OldTeamstersSkull ), 40f )
				, new Loot( typeof( DampDiaryPageDay4 ), 80f )
				, new Loot( typeof( DampDiaryPageDay87 ), 80f )
				, new Loot( typeof( DampDiaryPageDay512 ), 80f )
				, new Loot( typeof( MessageInABottle ), 88f )
				, new Loot( typeof( _17PoundCatfish ), 20f )
				, new Loot( typeof( DentedCrate ), 80f )
				, new Loot( typeof( WaterloggedCrate ), 60f )
				, new Loot( typeof( SmallChest ), 60f )
				, new Loot( typeof( SmallLockedChest ), 20f )
				, new Loot( typeof( BrittleMolting ), 29.6f )
				, new Loot( typeof( BlackWhelpScale ), 80f )
				, new Loot( typeof( RedWhelpScale ), 20f )
				, new Loot( typeof( BigMouthClam ), 63f )
				, new Loot( typeof( PuncturedDewGland ), 75f )
				, new Loot( typeof( EmptyDewGland ), 63f )
				, new Loot( typeof( GadgetzanWaterCoCarePackage ), 45f )
				, new Loot( typeof( TrollTribalNecklace ), 48.4f )
				, new Loot( typeof( PiratesFootlocker ), 20f )
				, new Loot( typeof( CrustedBandages ), 69f )
				, new Loot( typeof( CrackedPottery ), 62f )
				, new Loot( typeof( BrokenObsidianClub ), 58f )
				, new Loot( typeof( BrokenBasiliskTeeth ), 44f )
				, new Loot( typeof( BrokenBatFang ), 36f )
				, new Loot( typeof( TornBearPelt ), 13f )
				, new Loot( typeof( _42PoundRedgill ), 52f )
				, new Loot( typeof( _34PoundRedgill ), 60f )
				, new Loot( typeof( SmallBrownWrappedPackage ), 80f )
				, new Loot( typeof( BrokenLock ), 78f )
				, new Loot( typeof( PaddedLining ), 88f )
		};
	}
}
