//////////////////////////////////////////////////////////
// DrNexus Low MailArmors Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class LowMailArmorsDrops
	{
		public static Loot[]LowMailArmors = new Loot[]
		{
			new Loot( typeof( BrassStuddedBracers ), 55.6f )
				, new Loot( typeof( StormwindChainGloves ), 58f )
				, new Loot( typeof( WornMailBelt ), 51.4f )
				, new Loot( typeof( WornMailBoots ), 7.800001f )
				, new Loot( typeof( WornMailBracers ), 26.4f )
				, new Loot( typeof( WornMailGloves ), 60.6f )
				, new Loot( typeof( WornMailPants ), 10.2f )
				, new Loot( typeof( LacedMailBracers ), 2.600002f )
				, new Loot( typeof( FrostmaneChainVest ), 85.6f )
				, new Loot( typeof( TarnishedChainVest ), 85f )
				, new Loot( typeof( TarnishedChainLeggings ), 85f )
				, new Loot( typeof( TarnishedChainBoots ), 88.6f )
				, new Loot( typeof( RustedChainVest ), 84.6f )
				, new Loot( typeof( RustedChainLeggings ), 84.6f )
				, new Loot( typeof( RustedChainBoots ), 88.2f )
				, new Loot( typeof( LightMailArmor ), 17.4f )
				, new Loot( typeof( LightMailBelt ), 58.8f )
				, new Loot( typeof( LightMailLeggings ), 16.8f )
				, new Loot( typeof( LightMailBoots ), 35.6f )
				, new Loot( typeof( LightMailBracers ), 57f )
				, new Loot( typeof( LightMailGloves ), 57f )
				, new Loot( typeof( LightChainArmor ), 13.2f )
				, new Loot( typeof( LightChainBelt ), 56.6f )
				, new Loot( typeof( LightChainLeggings ), 12.6f )
				, new Loot( typeof( LightChainBoots ), 34f )
				, new Loot( typeof( LightChainBracers ), 56.2f )
				, new Loot( typeof( LightChainGloves ), 56f )
				, new Loot( typeof( RoyalFrostmaneGirdle ), 44.8f )
				, new Loot( typeof( LooseChainBelt ), 83.6f )
				, new Loot( typeof( LooseChainBoots ), 66.8f )
				, new Loot( typeof( LooseChainBracers ), 71.2f )
				, new Loot( typeof( LooseChainGloves ), 88.8f )
				, new Loot( typeof( LooseChainPants ), 68.2f )
				, new Loot( typeof( LooseChainVest ), 41.4f )
				, new Loot( typeof( OutfitterBoots ), 89.2f )
				, new Loot( typeof( CopperChainBelt ), 43.6f )
				, new Loot( typeof( CopperChainPants ), 33f )
				, new Loot( typeof( CopperBracers ), 83f )
				, new Loot( typeof( MountaineerChestpiece ), 67.6f )
				, new Loot( typeof( WarriorsBoots ), 33.8f )
				, new Loot( typeof( WarriorsGloves ), 66.2f )
				, new Loot( typeof( SiegeBrigadeVest ), 12.6f )
				, new Loot( typeof( VeteranBracers ), 10.6f )
				, new Loot( typeof( WarriorsBracers ), 66.2f )
				, new Loot( typeof( RuggedMailVest ), 84.6f )
				, new Loot( typeof( BattleChainBracers ), 66.99999f )
				, new Loot( typeof( BattleChainGloves ), 44f )
				, new Loot( typeof( BrackwaterBracers ), 29.4f )
				, new Loot( typeof( PerrinesBoots ), 51.6f )
				, new Loot( typeof( ClaspedBelt ), 76.2f )
				, new Loot( typeof( CryptwalkerBoots ), 65.2f )
				, new Loot( typeof( CopperChainBoots ), 51f )
				, new Loot( typeof( RunedCopperGauntlets ), 28.6f )
				, new Loot( typeof( WarriorsGirdle ), 76.2f )
				, new Loot( typeof( BattleChainGirdle ), 58.2f )
				, new Loot( typeof( BattlewornChainLeggings ), 85.6f )
				, new Loot( typeof( JaggedChainVest ), 84.8f )
				, new Loot( typeof( WideMetalGirdle ), 76.60001f )
				, new Loot( typeof( LightweightBoots ), 32.6f )
				, new Loot( typeof( FortifiedBindings ), 58f )
				, new Loot( typeof( CliffRunnerBoots ), 36f )
				, new Loot( typeof( TrackingBoots ), 88.2f )
				, new Loot( typeof( MossCoveredGauntlets ), 58.8f )
				, new Loot( typeof( ShackledGirdle ), 45.8f )
				, new Loot( typeof( GraystoneBracers ), 76.8f )
				, new Loot( typeof( ColdSteelGauntlets ), 76.60001f )
				, new Loot( typeof( IronwroughtBracers ), 30.4f )
				, new Loot( typeof( InfantryBoots ), 12.8f )
				, new Loot( typeof( InfantryBracers ), 55.4f )
				, new Loot( typeof( InfantryBelt ), 55.2f )
				, new Loot( typeof( InfantryGauntlets ), 45.6f )
				, new Loot( typeof( CadetBelt ), 27.2f )
				, new Loot( typeof( CadetBracers ), 26.6f )
				, new Loot( typeof( CadetGauntlets ), 7.4f )
				, new Loot( typeof( RoughCopperVest ), 67.8f )
				, new Loot( typeof( PaintedChainLeggings ), 85.39999f )
				, new Loot( typeof( BarkmailVest ), 85.39999f )
				, new Loot( typeof( RoamersLeggings ), 85.8f )
				, new Loot( typeof( ChargersBelt ), 66.6f )
				, new Loot( typeof( ChargersBoots ), 34.4f )
				, new Loot( typeof( ChargersBindings ), 76.2f )
				, new Loot( typeof( ChargersHandwraps ), 56f )
				, new Loot( typeof( WarTornGirdle ), 15.6f )
				, new Loot( typeof( WarTornBands ), 45.8f )
				, new Loot( typeof( WarTornHandgrips ), 31.6f )
		};
	}
}
