//////////////////////////////////////////////////////////
// DrNexus Low PrimMaterials Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class LowPrimMaterialsDrops
	{
		public static Loot[]LowPrimMaterials = new Loot[]
		{
			new Loot( typeof( StormwindSeasoningSalts ), 84f )
				, new Loot( typeof( GoretuskLiver ), 88f )
				, new Loot( typeof( StringyVultureMeat ), 86f )
				, new Loot( typeof( MurlocEye ), 87f )
				, new Loot( typeof( GoretuskSnout ), 78f )
				, new Loot( typeof( Malachite ), 88f )
				, new Loot( typeof( LightHide ), 60f )
				, new Loot( typeof( Mageroyal ), 84f )
				, new Loot( typeof( FlaskOfOil ), 80f )
				, new Loot( typeof( Tigerseye ), 20f )
				, new Loot( typeof( FistSizedSpinneret ), 55f )
				, new Loot( typeof( LeanWolfFlank ), 80.8f )
				, new Loot( typeof( ToughCondorMeat ), 37f )
				, new Loot( typeof( CrispSpiderMeat ), 60f )
				, new Loot( typeof( MurlocFin ), 77f )
				, new Loot( typeof( SmallVenomSac ), 34f )
				, new Loot( typeof( GreatGoretuskSnout ), 60f )
				, new Loot( typeof( LightLeather ), 88f )
				, new Loot( typeof( MediumLeather ), 60f )
				, new Loot( typeof( FineThread ), 80f )
				, new Loot( typeof( Earthroot ), 84f )
				, new Loot( typeof( Briarthorn ), 80f )
				, new Loot( typeof( Swiftthistle ), 88f )
				, new Loot( typeof( Bruiseweed ), 80f )
				, new Loot( typeof( LinenCloth ), 89f )
				, new Loot( typeof( WoolCloth ), 73f )
				, new Loot( typeof( GreenDye ), 80f )
				, new Loot( typeof( BoarRibs ), 88f )
				, new Loot( typeof( TinOre ), 80f )
				, new Loot( typeof( SilverOre ), 40f )
				, new Loot( typeof( CoarseStone ), 88f )
				, new Loot( typeof( HeavyStone ), 52f )
				, new Loot( typeof( BronzeBar ), 60f )
				, new Loot( typeof( SilverBar ), 20f )
				, new Loot( typeof( HeavySharpeningStone ), 68f )
				, new Loot( typeof( WeakFlux ), 80f )
				, new Loot( typeof( CrocoliskMeat ), 87f )
				, new Loot( typeof( MaidensAnguish ), 80f )
				, new Loot( typeof( TormentVine ), 60f )
				, new Loot( typeof( BoltOfWoolenCloth ), 20f )
				, new Loot( typeof( DiscoloredWorgHeart ), 73f )
				, new Loot( typeof( BoarIntestines ), 85f )
				, new Loot( typeof( BearMeat ), 88f )
				, new Loot( typeof( SpiderIchor ), 87f )
				, new Loot( typeof( HeavyWeightstone ), 68f )
				, new Loot( typeof( IncendiciteOre ), 75f )
				, new Loot( typeof( WildSteelbloom ), 60f )
				, new Loot( typeof( Kingsblood ), 76f )
				, new Loot( typeof( Liferoot ), 40f )
				, new Loot( typeof( GraveMoss ), 80f )
				, new Loot( typeof( LeadedVial ), 60f )
				, new Loot( typeof( HeavyGrindingStone ), 20f )
				, new Loot( typeof( TinBar ), 72f )
				, new Loot( typeof( TenderCrocoliskMeat ), 80f )
				, new Loot( typeof( RaptorEgg ), 43f )
				, new Loot( typeof( TurtleMeat ), 30f )
				, new Loot( typeof( SoothingSpices ), 68f )
				, new Loot( typeof( BigBearMeat ), 64f )
				, new Loot( typeof( LionMeat ), 56f )
				, new Loot( typeof( Wintersbite ), 20f )
				, new Loot( typeof( Stranglekelp ), 20f )
				, new Loot( typeof( SteelBar ), 52f )
				, new Loot( typeof( CuredLightHide ), 12f )
				, new Loot( typeof( GrayDye ), 30f )
				, new Loot( typeof( GiantClamMeat ), 43f )
				, new Loot( typeof( ThinKodoLeather ), 80f )
				, new Loot( typeof( Deathweed ), 80f )
				, new Loot( typeof( ThunderLizardTail ), 77f )
				, new Loot( typeof( StagMeat ), 76f )
				, new Loot( typeof( ClamMeat ), 87f )
				, new Loot( typeof( TangyClamMeat ), 82f )
				, new Loot( typeof( SharpClaw ), 64f )
				, new Loot( typeof( LargeFang ), 40f )
				, new Loot( typeof( SlimyMurlocScale ), 40f )
				, new Loot( typeof( CopperRod ), 75.2f )
				, new Loot( typeof( RunedCopperRod ), 75.2f )
				, new Loot( typeof( RunedSilverRod ), 75.2f )
				, new Loot( typeof( CrimsonLotus ), 60f )
				, new Loot( typeof( FishScale ), 89f )
				, new Loot( typeof( SolidStone ), 20f )
				, new Loot( typeof( SolidSharpeningStone ), 68f )
				, new Loot( typeof( SolidWeightstone ), 68f )
				, new Loot( typeof( ZestyClamMeat ), 60f )
				, new Loot( typeof( TurtleScale ), 20f )
				, new Loot( typeof( ArthasTears ), 24f )
				, new Loot( typeof( Sungrass ), 52f )
				, new Loot( typeof( EssenceOfAgony ), 60f )
				, new Loot( typeof( DustOfDeterioration ), 80f )
				, new Loot( typeof( MysteryMeat ), 30f )
				, new Loot( typeof( RaptorFlesh ), 30f )
				, new Loot( typeof( TigerMeat ), 30f )
				, new Loot( typeof( RedWolfMeat ), 30f )
				, new Loot( typeof( HeavyKodoMeat ), 10f )
				, new Loot( typeof( WhiteSpiderMeat ), 10f )
				, new Loot( typeof( TenderCrabMeat ), 10f )
				, new Loot( typeof( DenseSharpeningStone ), 40f )
				, new Loot( typeof( DenseWeightstone ), 40f )
				, new Loot( typeof( Dreamfoil ), 20f )
				, new Loot( typeof( GoldenSansam ), 20f )
				, new Loot( typeof( SilverSkeletonKey ), 60f )
		};
	}
}
