//	Script made by kolkoo - 07/07/05 06:02:09

using System;
using Server.Items;
using HelperTools;

namespace Server
{

	public class LargeBatteredChest : BaseChest
	{
		public LargeBatteredChest()
		{
			DefaultModel = 75293;
			BaseTreasure tempTreasure = new BaseTreasure( 
				new Loot[] { 
							   new Loot( typeof( Tigerseye ),	1.63f	),
				/*			   new Loot( typeof( MossAgate ), 0.70f ),
							   new Loot( typeof( Shadowgem	 ), 3.27f ),
							   new Loot( typeof( NorthernShortsword ), 1.44f ),
							   new Loot( typeof( SergeantsWarhammer ), 1.45f	),
							   new Loot( typeof( PatternFineLeatherBoots	), 0.20f ),
							   new Loot( typeof( PatternWhiteLeatherJerkin ), 0.26f ),
							   new Loot( typeof( PatternFineLeatherGloves ), 0.29f ),
							   new Loot( typeof( PatternDarkLeatherTunic ), 0.58f ),
							   new Loot( typeof( RecipeSwiftnessPotion ), 0.22f	 ),
							   new Loot( typeof( PatternGrayWoolenRobe	 ), 0.11f ),
							   new Loot( typeof( SilverOre ), 1.98f ),
							   new Loot( typeof( PlansRunedCopperBreastplate ), 0.69f ),
							   new Loot( typeof( PlansSilveredBronzeShoulders	), 0.14f ),
							   new Loot( typeof( PlansDeadlyBronzePoniard ), 0.13f ),
							   new Loot( typeof( SpellbinderVest ), 0.58f	),
							   new Loot( typeof( SpellbinderPants ), 1.70f	),
							   new Loot( typeof( HuntingTunic ), 1.04f ),
							   new Loot( typeof( HuntingPants ), 1.47f ),
							   new Loot( typeof( VeteranArmor ), 1.30f  ),
							   new Loot( typeof( SeersPants ), 1.07f	),
							   new Loot( typeof( SeersBoots ), 1.21f ),
							   new Loot( typeof( SeersGloves	 ), 1.55f ),
							   new Loot( typeof( InscribedLeatherPants ), 0.91f	),
							   new Loot( typeof( InscribedLeatherBoots),	1.33f	),
							   new Loot( typeof( InscribedLeatherGloves), 1.07f	 ),
							   new Loot( typeof( BurnishedGloves ), 0.78f ),
							   new Loot( typeof( HuntersMuzzleLoader ),	1.47f	),
							   new Loot( typeof( HookDagger ), 1.28f ),
							   new Loot( typeof( BarbaricBattleAxe	), 1.41f ),
							   new Loot( typeof( EdgedBastardSword ), 1.53f ),
							   new Loot( typeof( InscribedLeatherBracers ), 1.04f ),
							   new Loot( typeof( BurnishedBracers ), 0.91f ),
							   new Loot( typeof( PlansGemmedCopperGauntlets ), 0.21f ),
							   new Loot( typeof( SeersCuffs ), 1.27f ),
							   new Loot( typeof( BurnishedShield ), 0.33f	),
							   new Loot( typeof( PatternGreenWoolenBag ), 0.61f ),
							   new Loot( typeof( PatternHillmansLeatherVest ),	0.63f	),
							   new Loot( typeof( PatternHillmansBelt ), 0.13f ),
							   new Loot( typeof( PatternRedWoolenBoots ), 0.64f ),
							   new Loot( typeof( PatternHeavyWoolenCloak ), 0.65f ),
							   new Loot( typeof( PatternReinforcedWoolenShoulders ), 0.12f ),
							   new Loot( typeof( PatternPhoenixGloves ),	0.12f	),
							   new Loot( typeof( PatternPhoenixPants ), 0.10f ),
							   new Loot( typeof( SchematicMechanicalSquirrel ), 0.21f ),
							   new Loot( typeof( SchematicSmallSeaforiumCharge ), 0.63f ),
							   new Loot( typeof( SchematicShadowGoggles ), 0.12f ),
							   new Loot( typeof( MercSword ), 1.35f ),
							   new Loot( typeof( WarKnife ),	1.46f	),
							   new Loot( typeof( MedicineStaff), 1.52f ),
							   new Loot( typeof( BurnishedCloak ),	1.10f	),
							   new Loot( typeof( BurnishedGirdle),	0.81f	),
							   new Loot( typeof( SeersBelt ),	1.56f	),
							   new Loot( typeof( InscribedCloak ),	1.57f	),
							   new Loot( typeof( OpaqueWand ), 1.24f ),
							   new Loot( typeof( BlazingWand ), 1.55f ),
							   new Loot( typeof( PlansSilveredBronzeBreastplate ), 0.11f ),
							   new Loot( typeof( PatternFineLeatherPants ), 0.11f ),
							   new Loot( typeof( PatternRedLinenVest ), 0.26f	),
							   new Loot( typeof( FormulaEnchantChestMinorMana ), 0.23f ),
							   new Loot( typeof( FormulaEnchantBracerMinorSpirit), 0.65f ),
							   new Loot( typeof( FormulaEnchantBracerMinorStrength	 ), 0.56f ),
							   new Loot( typeof( FormulaEnchantWeaponMinorBeastslayer ), 0.61f	 ),
							   new Loot( typeof( FormulaEnchantBracerLesserSpirit ),	0.13f	),
							   new Loot( typeof( SeersCape ), 1.08f	),
							   new Loot( typeof( InscribedLeatherBelt ), 1.09f ),
							   new Loot( typeof( InscribedBuckler ), 0.68f ),
							   new Loot( typeof( PatternStylishBlueShirt ), 0.11f ),
							   new Loot( typeof( PatternStylishGreenShirt	), 0.12f ),
							   new Loot( typeof( SpellbinderRobe ),	0.60f	),
							   new Loot( typeof( WillowVest ), 0.62f ),
							   new Loot( typeof( WillowRobe	 ), 0.55f ),
							   new Loot( typeof( WillowBelt ), 1.83f ),
							   new Loot( typeof( WillowPants ), 1.76f ),
							   new Loot( typeof( WillowGloves ), 1.62f ),
							   new Loot( typeof( SoldiersArmor ), 1.16f ),
							   new Loot( typeof( SoldiersLeggings ), 0.86f ),
							   new Loot( typeof( SoldiersGauntlets ), 0.92f ),
							   new Loot( typeof( SoldiersGirdle ), 1.30f ),
							   new Loot( typeof( SoldiersBoots ), 0.88f ),
							   new Loot( typeof( BardsTunic ), 0.93f ),
							   new Loot( typeof( BardsTrousers ), 1.51f ),
							   new Loot( typeof( BardsGloves ), 1.06f ),
							   new Loot( typeof( BardsBoots ), 1.30f ),
							   new Loot( typeof( BardsBuckler ), 0.64f ),
							   new Loot( typeof( SoldiersShield ), 0.69f ),
							   new Loot( typeof( ShimmeringBracers ), 1.21f ),
							   new Loot( typeof( DefenderCloak ), 0.82f ),
							   new Loot( typeof( ScoutingCloak ), 0.91f ),
							   new Loot( typeof( SchematicEZThroDynamite ), 0.53f ),
							   new Loot( typeof( PatternRuggedLeatherPants ),	0.24f	),
							   new Loot( typeof( WillowBranch ), 0.34f ),
							   new Loot( typeof( SeersFineStein ), 0.33f ),
							   new Loot( typeof( BanditCinch	 ), 1.03f ),
							   new Loot( typeof( BanditBoots	 ), 0.97f  ),
							   new Loot( typeof( BanditBracers ), 1.01f ),
							   new Loot( typeof( BanditBuckler ), 0.38f ),
							   new Loot( typeof( BanditCloak	), 1.38f ),
							   new Loot( typeof( BanditGloves ), 0.96f ),
							   new Loot( typeof( RaidersChestpiece	), 0.93f ),
							   new Loot( typeof( RaidersBoots ), 0.95f ),
							   new Loot( typeof( RaidersBracers ), 0.87f ),
							   new Loot( typeof( RaidersCloak ), 1.18f ),
							   new Loot( typeof( RaidersGauntlets ), 0.89f	 ),
							   new Loot( typeof( RaidersBelt ), 1.26f ),
							   new Loot( typeof( RaidersLegguards ), 0.76f ),
							   new Loot( typeof( RaidersShield ), 0.31f ),
							   new Loot( typeof( PatternColorfulKilt ), 0.11f ),
							   new Loot( typeof( FormulaEnchant2HWeaponLesserSpirit ), 0.09f ),
							   new Loot( typeof( FormulaEnchantCloakMinorAgility ), 0.09f	),
							   new Loot( typeof( FormulaEnchantShieldLesserProtection ), 0.13f ),
							   new Loot( typeof( QuartzRing ), 0.50f ),
							   new Loot( typeof( LeadBand ), 0.61f	),
							   new Loot( typeof( BuccaneersBracers ), 1.13f ),
							   new Loot( typeof( BuccaneersCape ), 1.24f	),
							   new Loot( typeof( BuccaneersGloves	), 1.14f ),
							   new Loot( typeof( BuccaneersCord ), 1.03f	),
							   new Loot( typeof( BuccaneersBoots ), 1.39f	 ),
							   new Loot( typeof( RaiderShortsword	), 1.38f ),
							   new Loot( typeof( BarbedClub	), 1.50f ),
							   new Loot( typeof( GleamingClaymore ), 1.32f ),
							   new Loot( typeof( TwinbladedAxe ), 1.34f	),
							   new Loot( typeof( SpellbinderOrb ), 0.62f	),
							   new Loot( typeof( DalaranSharp ), 13.00f	),
							   new Loot( typeof( Silverleaf ),	4.85f	),
							   new Loot( typeof( LightHide ),	5.24f	),
							   new Loot( typeof( Mageroyal ), 4.68f	),
							   new Loot( typeof( BlueLeatherBag ),	1.32f	),
							   new Loot( typeof( LesserHealingPotion ), 19.54f	 ),
							   new Loot( typeof( IceColdMilk	 ),29.24f  ),
							   new Loot( typeof( HaunchofMeat ), 12.85f	 ),
							   new Loot( typeof( LightLeather ), 28.10f  ),
							   new Loot( typeof( Peacebloom	), 4.99f  ),
							   new Loot( typeof( Earthroot ), 5.13f  ),
							   new Loot( typeof( Briarthorn ),  5.11f	 ),
							   new Loot( typeof( Swiftthistle ), 4.69f  ),
							   new Loot( typeof( Bruiseweed ), 4.89f  ),
							   new Loot( typeof( MinorManaPotion	), 20.62f  ),
							   new Loot( typeof( RecipeElixirofMinorAgility ), 0.24f  ),
							   new Loot( typeof( LinenCloth ), 12.76f  ),
							   new Loot( typeof( WoolCloth ), 5.74f  ),
							   new Loot( typeof( RedLeatherBag ), 1.41f  ),
							   new Loot( typeof( CopperOre ), 7.20f	 ),
							   new Loot( typeof( TinOre ), 7.99f  ),
							   new Loot( typeof( RoughStone	 ), 7.97f  ),
							   new Loot( typeof( CoarseStone	 ), 7.66f  ),
							   new Loot( typeof( BoltofLinenCloth ), 13.90f  ),
							   new Loot( typeof( RecipeMinorMagicResistancePotion ), 0.10f  ),
							   new Loot( typeof( RecipeElixirofPoisonResistance ), 0.08f  ),
							   new Loot( typeof( TelAbimBanana ),	12.88f ),
							   new Loot( typeof( FreshlyBakedBread ), 12.07f  ),
							   new Loot( typeof( RedspeckledMushroom ), 12.86f  ),
							   new Loot( typeof( GreenLeatherBag ), 1.47f  ),
							   new Loot( typeof( WhiteLeatherBag ), 1.30f  ),
							   new Loot( typeof( LacedMailBelt ), 0.81f ),
							   new Loot( typeof( LacedMailBoots ), 0.78f	 ),
							   new Loot( typeof( LacedMailBracers	), 0.80f ),
							   new Loot( typeof( LacedCloak ), 0.76f ),
							   new Loot( typeof( LacedMailGloves ), 0.88f  ),
							   new Loot( typeof( LacedMailPants ),	0.74f	 ),
							   new Loot( typeof( LacedMailShoulderpads ), 0.74f ),
							   new Loot( typeof( LacedMailVest ), 0.73f  ),
							   new Loot( typeof( CanvasShoes ), 1.02f  ),
							   new Loot( typeof( CanvasCloak ), 1.05f  ),
							   new Loot( typeof( CanvasGloves ), 1.07f  ),
							   new Loot( typeof( CanvasPants	 ), 1.13f  ),
							   new Loot( typeof( CanvasShoulderpads ), 0.90f ),
							   new Loot( typeof( CanvasVest ),  1.07f  ),
							   new Loot( typeof( PatchedLeatherBelt ), 0.94f  ),
							   new Loot( typeof( PatchedLeatherBoots ), 0.90f  ),
							   new Loot( typeof( PatchedLeatherBracers ), 1.02f	 ),
							   new Loot( typeof( PatchedCloak ), 0.94f  ),
							   new Loot( typeof( PatchedLeatherGloves ),	1.01f	 ),
							   new Loot( typeof( PatchedLeatherPants ), 0.95f  ),
							   new Loot( typeof( PatchedLeatherShoulderpads ), 0.92f ),
							   new Loot( typeof( PatchedLeatherJerkin ), 0.88f  ),
							   new Loot( typeof( BluntClaymore ), 1.54f  ),
							   new Loot( typeof( ShorthandledBattleAxe ), 1.64f	 ),
							   new Loot( typeof( ChippedQuarterstaff ), 1.69f  ),
							   new Loot( typeof( BatteredMallet ),	1.61f	 ),
							   new Loot( typeof( OrnamentalMace ), 1.76f	 ),
							   new Loot( typeof( UnbalancedAxe ),	1.51f	 ),
							   new Loot( typeof( StockShortsword ), 1.58f	 ),
							   new Loot( typeof( SimpleBuckler ),	1.14f	 ),
							   new Loot( typeof( RectangularShield	 ), 0.92f ),
							   new Loot( typeof( SmallDagger ), 1.74f  ),
							   new Loot( typeof( LightHuntingBow	), 1.50f  ),
							   new Loot( typeof( DirtyBlunderbuss ), 1.68f  ),
							   new Loot( typeof( CanvasBelt ),  1.27f ),*/
							   new Loot( typeof( CanvasBracers ), 1.15f  )

						   },
				100.0f );
			Loots = new BaseTreasure[] { tempTreasure };
			Charge = 1;//	one use before vanishing
		}
		public override bool OnUse( Mobile from )
		{
			return base.OnUse( from );
		}

		public override bool OnRelease( Mobile from )
		{
			return base.OnRelease( from );
		}
	}
} 