using System;

namespace WoWDaemon.Common
{

	#region enum CMSG
	public enum CMSG : int
	{
		// 1.3.0 opcodes
		
		NULL_ACTION                           =0x0000,
		BOOTME                                =0x0001,
		DBLOOKUP                              =0x0002,
		QUERY_OBJECT_POSITION                 =0x0004,
		QUERY_OBJECT_ROTATION                 =0x0006,
		WORLD_TELEPORT                        =0x0008,
		TELEPORT_TO_UNIT                      =0x0009,
		ZONE_MAP                              =0x000A,
		DEBUG_CHANGECELLZONE                  =0x000C,
		EMBLAZON_TABARD_OBSOLETE              =0x000D,
		UNEMBLAZON_TABARD_OBSOLETE            =0x000E,
		RECHARGE                              =0x000F,
		LEARN_SPELL                           =0x0010,
		CREATEMONSTER                         =0x0011,
		DESTROYMONSTER                        =0x0012,
		CREATEITEM                            =0x0013,
		CREATEGAMEOBJECT                      =0x0014,
		MAKEMONSTERATTACKME                   =0x0015,
		MAKEMONSTERATTACKGUID                 =0x0016,
		ENABLEDEBUGCOMBATLOGGING_OBSOLETE     =0x0017,
		FORCEACTION                           =0x0018,
		FORCEACTIONONOTHER                    =0x0019,
		FORCEACTIONSHOW                       =0x001A,
		UNDRESSPLAYER                         =0x0020,
		BEASTMASTER                           =0x0021,
		GODMODE                               =0x0022,
		CHEAT_SETMONEY                        =0x0024,
		LEVEL_CHEAT                           =0x0025,
		PET_LEVEL_CHEAT                       =0x0026,
		LEVELUP_CHEAT_OBSOLETE                =0x0027,
		COOLDOWN_CHEAT                        =0x0028,
		USE_SKILL_CHEAT                       =0x0029,
		FLAG_QUEST                            =0x002A,
		FLAG_QUEST_FINISH                     =0x002B,
		CLEAR_QUEST                           =0x002C,
		SEND_EVENT                            =0x002D,
		DEBUG_AISTATE                         =0x002E,
		DISABLE_PVP_CHEAT                     =0x0030,
		ADVANCE_SPAWN_TIME                    =0x0031,
		PVP_PORT_OBSOLETE                     =0x0032,
		AUTH_SRP6_BEGIN                       =0x0033,
		AUTH_SRP6_PROOF                       =0x0034,
		AUTH_SRP6_RECODE                      =0x0035,
		CHAR_CREATE                           =0x0036,
		CHAR_ENUM                             =0x0037,
		CHAR_DELETE                           =0x0038,
		PLAYER_LOGIN                          =0x003D,
		GAMETIME_SET                          =0x0044,
		GAMESPEED_SET                         =0x0046,
		SERVERTIME                            =0x0048,
		PLAYER_LOGOUT                         =0x004A,
		LOGOUT_REQUEST                        =0x004B,
		LOGOUT_CANCEL                         =0x004E,
		NAME_QUERY                            =0x0050,
		PET_NAME_QUERY                        =0x0052,
		GUILD_QUERY                           =0x0054,
		ITEM_QUERY_SINGLE                     =0x0056,
		ITEM_QUERY_MULTIPLE                   =0x0057,
		PAGE_TEXT_QUERY                       =0x005A,
		QUEST_QUERY                           =0x005C,
		GAMEOBJECT_QUERY                      =0x005E,
		CREATURE_QUERY                        =0x0060,
		WHO                                   =0x0062,
		WHOIS                                 =0x0064,
		FRIEND_LIST                           =0x0066,
		ADD_FRIEND                            =0x0069,
		DEL_FRIEND                            =0x006A,
		ADD_IGNORE                            =0x006C,
		DEL_IGNORE                            =0x006D,
		GROUP_INVITE                          =0x006E,
		GROUP_CANCEL                          =0x0070,
		GROUP_ACCEPT                          =0x0072,
		GROUP_DECLINE                         =0x0073,
		GROUP_UNINVITE                        =0x0075,
		GROUP_UNINVITE_GUID                   =0x0076,
		GROUP_SET_LEADER                      =0x0078,
		LOOT_METHOD                           =0x007A,
		GROUP_DISBAND                         =0x007B,
		_UPDATE_GROUP_MEMBERS                 =0x0080,
		GUILD_CREATE                          =0x0081,
		GUILD_INVITE                          =0x0082,
		GUILD_ACCEPT                          =0x0084,
		GUILD_DECLINE                         =0x0085,
		GUILD_INFO                            =0x0087,
		GUILD_ROSTER                          =0x0089,
		GUILD_PROMOTE                         =0x008B,
		GUILD_DEMOTE                          =0x008C,
		GUILD_LEAVE                           =0x008D,
		GUILD_REMOVE                          =0x008E,
		GUILD_DISBAND                         =0x008F,
		GUILD_LEADER                          =0x0090,
		GUILD_MOTD                            =0x0091,
		UPDATE_GUILD                          =0x0094,
		MESSAGECHAT                           =0x0095,
		JOIN_CHANNEL                          =0x0097,
		LEAVE_CHANNEL                         =0x0098,
		CHANNEL_LIST                          =0x009A,
		CHANNEL_PASSWORD                      =0x009C,
		CHANNEL_SET_OWNER                     =0x009D,
		CHANNEL_OWNER                         =0x009E,
		CHANNEL_MODERATOR                     =0x009F,
		CHANNEL_UNMODERATOR                   =0x00A0,
		CHANNEL_MUTE                          =0x00A1,
		CHANNEL_UNMUTE                        =0x00A2,
		CHANNEL_INVITE                        =0x00A3,
		CHANNEL_KICK                          =0x00A4,
		CHANNEL_BAN                           =0x00A5,
		CHANNEL_UNBAN                         =0x00A6,
		CHANNEL_ANNOUNCEMENTS                 =0x00A7,
		CHANNEL_MODERATE                      =0x00A8,
		USE_ITEM                              =0x00AB,
		OPEN_ITEM                             =0x00AC,
		READ_ITEM                             =0x00AD,
		GAMEOBJ_USE                           =0x00B1,
		GAMEOBJ_CHAIR_USE_OBSOLETE            =0x00B2,
		AREATRIGGER                           =0x00B4,
		MOVE_START_FORWARD                    =0x00B5,
		MOVE_START_BACKWARD                   =0x00B6,
		MOVE_STOP                             =0x00B7,
		MOVE_START_STRAFE_LEFT                =0x00B8,
		MOVE_START_STRAFE_RIGHT               =0x00B9,
		MOVE_STOP_STRAFE                      =0x00BA,
		MOVE_JUMP                             =0x00BB,
		MOVE_START_TURN_LEFT                  =0x00BC,
		MOVE_START_TURN_RIGHT                 =0x00BD,
		MOVE_STOP_TURN                        =0x00BE,
		MOVE_START_PITCH_UP                   =0x00BF,
		MOVE_START_PITCH_DOWN                 =0x00C0,
		MOVE_STOP_PITCH                       =0x00C1,
		MOVE_SET_RUN_MODE                     =0x00C2,
		MOVE_SET_WALK_MODE                    =0x00C3,
		MOVE_TOGGLE_LOGGING                   =0x00C4,
		MOVE_TELEPORT                         =0x00C5,
		MOVE_TELEPORT_CHEAT                   =0x00C6,
		MOVE_TELEPORT_ACK                     =0x00C7,
		MOVE_TOGGLE_FALL_LOGGING              =0x00C8,
		MOVE_FALL_LAND                        =0x00C9,
		MOVE_START_SWIM                       =0x00CA,
		MOVE_STOP_SWIM                        =0x00CB,
		MOVE_SET_RUN_SPEED_CHEAT              =0x00CC,
		MOVE_SET_RUN_SPEED                    =0x00CD,
		MOVE_SET_RUN_BACK_SPEED_CHEAT         =0x00CE,
		MOVE_SET_RUN_BACK_SPEED               =0x00CF,
		MOVE_SET_WALK_SPEED_CHEAT             =0x00D0,
		MOVE_SET_WALK_SPEED                   =0x00D1,
		MOVE_SET_SWIM_SPEED_CHEAT             =0x00D2,
		MOVE_SET_SWIM_SPEED                   =0x00D3,
		MOVE_SET_SWIM_BACK_SPEED_CHEAT        =0x00D4,
		MOVE_SET_SWIM_BACK_SPEED              =0x00D5,
		MOVE_SET_ALL_SPEED_CHEAT              =0x00D6,
		MOVE_SET_TURN_RATE_CHEAT              =0x00D7,
		MOVE_SET_TURN_RATE                    =0x00D8,
		MOVE_TOGGLE_COLLISION_CHEAT           =0x00D9,
		MOVE_SET_FACING                       =0x00DA,
		MOVE_SET_PITCH                        =0x00DB,
		MOVE_WORLDPORT_ACK                    =0x00DC,
		MOVE_SET_RAW_POSITION_ACK             =0x00E0,
		MOVE_SET_RAW_POSITION                 =0x00E1,
		FORCE_RUN_SPEED_CHANGE_ACK            =0x00E3,
		FORCE_RUN_BACK_SPEED_CHANGE_ACK       =0x00E5,
		FORCE_SWIM_SPEED_CHANGE_ACK           =0x00E7,
		FORCE_MOVE_ROOT_ACK                   =0x00E9,
		FORCE_MOVE_UNROOT_ACK                 =0x00EB,
		MOVE_ROOT                             =0x00EC,
		MOVE_UNROOT                           =0x00ED,
		MOVE_HEARTBEAT                        =0x00EE,
		MOVE_KNOCK_BACK_ACK                   =0x00F0,
		MOVE_KNOCK_BACK                       =0x00F1,
		MOVE_HOVER_ACK                        =0x00F6,
		MOVE_HOVER                            =0x00F7,
		TRIGGER_CINEMATIC_CHEAT               =0x00F8,
		OPENING_CINEMATIC                     =0x00F9,
		NEXT_CINEMATIC_CAMERA                 =0x00FB,
		COMPLETE_CINEMATIC                    =0x00FC,
		TUTORIAL_FLAG                         =0x00FE,
		TUTORIAL_CLEAR                        =0x00FF,
		TUTORIAL_RESET                        =0x0100,
		STANDSTATECHANGE                      =0x0101,
		EMOTE                                 =0x0102,
		TEXT_EMOTE                            =0x0104,
		AUTOEQUIP_GROUND_ITEM                 =0x0106,
		AUTOSTORE_GROUND_ITEM                 =0x0107,
		AUTOSTORE_LOOT_ITEM                   =0x0108,
		STORE_LOOT_IN_SLOT                    =0x0109,
		AUTOEQUIP_ITEM                        =0x010A,
		AUTOSTORE_BAG_ITEM                    =0x010B,
		SWAP_ITEM                             =0x010C,
		SWAP_INV_ITEM                         =0x010D,
		SPLIT_ITEM                            =0x010E,
		PICKUP_ITEM                           =0x010F,
		DROP_ITEM                             =0x0110,
		DESTROYITEM                           =0x0111,
		INSPECT                               =0x0114,
		INITIATE_TRADE                        =0x0116,
		BEGIN_TRADE                           =0x0117,
		BUSY_TRADE                            =0x0118,
		IGNORE_TRADE                          =0x0119,
		ACCEPT_TRADE                          =0x011A,
		UNACCEPT_TRADE                        =0x011B,
		CANCEL_TRADE                          =0x011C,
		SET_TRADE_ITEM                        =0x011D,
		CLEAR_TRADE_ITEM                      =0x011E,
		SET_TRADE_GOLD                        =0x011F,
		SET_FACTION_ATWAR                     =0x0125,
		SET_FACTION_CHEAT                     =0x0126,
		SET_ACTION_BUTTON                     =0x0128,
		NEW_SPELL_SLOT                        =0x012D,
		CAST_SPELL                            =0x012E,
		CANCEL_CAST                           =0x012F,
		CANCEL_AURA                           =0x0136,
		CHANNEL_START                         =0x0139,
		CHANNEL_UPDATE                        =0x013A,
		CANCEL_CHANNELLING                    =0x013B,
		SET_SELECTION                         =0x013D,
		SET_TARGET                            =0x013E,
		UNUSED                                =0x013F,
		UNUSED2                               =0x0140,
		ATTACKSWING                           =0x0141,
		ATTACKSTOP                            =0x0142,
		SHEATHE_OBSOLETE                      =0x0152,
		SAVE_PLAYER                           =0x0153,
		SETDEATHBINDPOINT                     =0x0154,
		GETDEATHBINDZONE                      =0x0156,
		REPOP_REQUEST                         =0x015A,
		RESURRECT_RESPONSE                    =0x015C,
		LOOT                                  =0x015D,
		LOOT_MONEY                            =0x015E,
		LOOT_RELEASE                          =0x015F,
		DUEL_ACCEPTED                         =0x016C,
		DUEL_CANCELLED                        =0x016D,
		MOUNTSPECIAL_ANIM                     =0x0171,
		PET_SET_ACTION                        =0x0174,
		PET_ACTION                            =0x0175,
		PET_ABANDON                           =0x0176,
		PET_RENAME                            =0x0177,
		PET_CAST_SPELL_OBSOLETE               =0x017A,
		GOSSIP_HELLO                          =0x017B,
		GOSSIP_SELECT_OPTION                  =0x017C,
		NPC_TEXT_QUERY                        =0x017F,
		QUESTGIVER_STATUS_QUERY               =0x0182,
		QUESTGIVER_HELLO                      =0x0184,
		QUESTGIVER_QUERY_QUEST                =0x0186,
		QUESTGIVER_QUEST_AUTOLAUNCH           =0x0187,
		QUESTGIVER_ACCEPT_QUEST               =0x0189,
		QUESTGIVER_COMPLETE_QUEST             =0x018A,
		QUESTGIVER_REQUEST_REWARD             =0x018C,
		QUESTGIVER_CHOOSE_REWARD              =0x018E,
		QUESTGIVER_CANCEL                     =0x0190,
		QUESTLOG_SWAP_QUEST                   =0x0193,
		QUESTLOG_REMOVE_QUEST                 =0x0194,
		QUEST_CONFIRM_ACCEPT                  =0x019B,
		PUSHQUESTTOPARTY                      =0x019D,
		LIST_INVENTORY                        =0x019E,
		SELL_ITEM                             =0x01A0,
		BUY_ITEM                              =0x01A2,
		BUY_ITEM_IN_SLOT                      =0x01A3,
		TAXICLEARALLNODES                     =0x01A6,
		TAXIENABLEALLNODES                    =0x01A7,
		TAXISHOWNODES                         =0x01A8,
		TAXINODE_STATUS_QUERY                 =0x01AA,
		TAXIQUERYAVAILABLENODES               =0x01AC,
		ACTIVATETAXI                          =0x01AD,
		TRAINER_LIST                          =0x01B0,
		TRAINER_BUY_SPELL                     =0x01B2,
		BINDER_ACTIVATE                       =0x01B5,
		BANKER_ACTIVATE                       =0x01B7,
		BUY_BANK_SLOT                         =0x01B9,
		PETITION_SHOWLIST                     =0x01BB,
		PETITION_BUY                          =0x01BD,
		PETITION_SHOW_SIGNATURES              =0x01BE,
		PETITION_SIGN                         =0x01C0,
		PETITION_DECLINE                      =0x01C2,
		OFFER_PETITION                        =0x01C3,
		TURN_IN_PETITION                      =0x01C4,
		PETITION_QUERY                        =0x01C6,
		BUG                                   =0x01CA,
		PLAYED_TIME                           =0x01CC,
		QUERY_TIME                            =0x01CE,
		SPLIT_MONEY                           =0x01D1,
		RECLAIM_CORPSE                        =0x01D2,
		WRAP_ITEM                             =0x01D3,
		MINIMAP_PING                          =0x01D5,
		SET_SKILL_CHEAT                       =0x01D8,
		PING                                  =0x01DC,
		SETSHEATHED                           =0x01E0,
		PLAYER_MACRO                          =0x01E3,
		GHOST                                 =0x01E5,
		GM_INVIS                              =0x01E6,
		SCREENSHOT                            =0x01E7,
		GM_BIND_OTHER                         =0x01E8,
		GM_SUMMON                             =0x01E9,
		AUTH_SESSION                          =0x01ED,
		GM_SHOWLABEL                          =0x01EF,
		ADD_DYNAMIC_TARGET                    =0x01F0,
		SAVE_GUILD_EMBLEM                     =0x01F1,
		TABARDVENDOR_ACTIVATE                 =0x01F2,
		ZONEUPDATE                            =0x01F4,
		GM_SET_SECURITY_GROUP                 =0x01F9,
		GM_NUKE                               =0x01FA,
		RANDOM_ROLL                           =0x01FB,
		RWHOIS                                =0x01FD,
		LOOKING_FOR_GROUP                     =0x01FF,
		SET_LOOKING_FOR_GROUP                 =0x0200,
		UNLEARN_SPELL                         =0x0201,
		UNLEARN_SKILL                         =0x0202,
		DECHARGE                              =0x0204,
		GMTICKET_CREATE                       =0x0205,
		GMTICKET_UPDATETEXT                   =0x0207,
		REQUEST_ACCOUNT_DATA                  =0x020A,
		UPDATE_ACCOUNT_DATA                   =0x020B,
		GM_TEACH                              =0x020F,
		GM_CREATE_ITEM_TARGET                 =0x0210,
		GMTICKET_GETTICKET                    =0x0211,
		UNLEARN_TALENTS                       =0x0213,
		CORPSE_QUERY                          =0x0216,
		GMTICKET_DELETETICKET                 =0x0217,
		GMTICKET_SYSTEMSTATUS                 =0x021A,
		SPIRIT_HEALER_ACTIVATE                =0x021C,
		SET_STAT_CHEAT                        =0x021D,
		SKILL_BUY_STEP                        =0x021F,
		SKILL_BUY_RANK                        =0x0220,
		XP_CHEAT                              =0x0221,
		CHARACTER_POINT_CHEAT                 =0x0223,
		CHAT_IGNORED                          =0x0225,
		GM_VISION                             =0x0226,
		SERVER_COMMAND                        =0x0227,
		GM_SILENCE                            =0x0228,
		GM_REVEALTO                           =0x0229,
		GM_RESURRECT                          =0x022A,
		GM_SUMMONMOB                          =0x022B,
		GM_MOVECORPSE                         =0x022C,
		GM_FREEZE                             =0x022D,
		GM_UBERINVIS                          =0x022E,
		GM_REQUEST_PLAYER_INFO                =0x022F,
		GUILD_RANK                            =0x0231,
		GUILD_ADD_RANK                        =0x0232,
		GUILD_DEL_RANK                        =0x0233,
		GUILD_SET_PUBLIC_NOTE                 =0x0234,
		GUILD_SET_OFFICER_NOTE                =0x0235,
		CLEAR_EXPLORATION                     =0x0237,
		SEND_MAIL                             =0x0238,
		GET_MAIL_LIST                         =0x023A,
		BATTLEFIELD_LIST                      =0x023C,
		BATTLEFIELD_JOIN                      =0x023E,
		TAXICLEARNODE                         =0x0241,
		TAXIENABLENODE                        =0x0242,
		ITEM_TEXT_QUERY                       =0x0243,
		MAIL_TAKE_MONEY                       =0x0245,
		MAIL_TAKE_ITEM                        =0x0246,
		MAIL_MARK_AS_READ                     =0x0247,
		MAIL_RETURN_TO_SENDER                 =0x0248,
		MAIL_DELETE                           =0x0249,
		MAIL_CREATE_TEXT_ITEM                 =0x024A,
		LEARN_TALENT                          =0x0251,
		ENABLE_PVP                            =0x0253,
		AUCTION_HELLO                         =0x0255,
		AUCTION_SELL_ITEM                     =0x0256,
		AUCTION_REMOVE_ITEM                   =0x0257,
		AUCTION_LIST_ITEMS                    =0x0258,
		AUCTION_LIST_OWNER_ITEMS              =0x0259,
		AUCTION_PLACE_BID                     =0x025A,
		AUCTION_LIST_BIDDER_ITEMS             =0x0264,
		SET_AMMO                              =0x0268,
		SET_ACTIVE_MOVER                      =0x026A,
		PET_CANCEL_AURA                       =0x026B,
		PLAYER_AI_CHEAT                       =0x026C,
		CANCEL_AUTO_REPEAT_SPELL              =0x026D,
		GM_ACCOUNT_ONLINE                     =0x026E,
		LIST_STABLED_PETS                     =0x026F,
		STABLE_PET                            =0x0270,
		UNSTABLE_PET                          =0x0271,
		BUY_STABLE_SLOT                       =0x0272,
		STABLE_REVIVE_PET                     =0x0274,
		STABLE_SWAP_PET                       =0x0275,
		QUEST_PUSH_RESULT                     =0x0276,
		REQUEST_PET_INFO                      =0x0279,
		FAR_SIGHT                             =0x027A,
		ENABLE_DAMAGE_LOG                     =0x027D,
		GROUP_CHANGE_SUB_GROUP                =0x027E,
		GROUP_SWAP_SUB_GROUP                  =0x0280,
		RESET_FACTION_CHEAT                   =0x0281,
		AUTOSTORE_BANK_ITEM                   =0x0282,
		AUTOBANK_ITEM                         =0x0283,
		QUERY_NEXT_MAIL_TIME                  =0x0284,
		SET_DURABILITY_CHEAT                  =0x0287,
		SET_PVP_RANK_CHEAT                    =0x0288,
		ADD_PVP_MEDAL_CHEAT                   =0x0289,
		DEL_PVP_MEDAL_CHEAT                   =0x028A,
		SET_PVP_TITLE                         =0x028B,
		GROUP_RAID_CONVERT                    =0x028E,
		GROUP_ASSISTANT_LEADER                =0x028F,
		BUYBACK_ITEM                          =0x0290,
		GMTICKETSYSTEM_TOGGLE                 =0x0292,
		CANCEL_GROWTH_AURA                    =0x0293,
		LOOT_ROLL                             =0x0298,
		LOOT_MASTER_GIVE                      =0x029B,
		REPAIR_ITEM                           =0x02A0,
		TALENT_WIPE_CONFIRM                   =0x02A2,
		SUMMON_RESPONSE                       =0x02A4,
		MOVE_TOGGLE_GRAVITY_CHEAT             =0x02A5,
		MOVE_FEATHER_FALL                     =0x02A8,
		MOVE_WATER_WALK                       =0x02A9,
		SERVER_BROADCAST                      =0x02AA,
		SELF_RES                              =0x02AB,
		RUN_SCRIPT                            =0x02AD,
		TOGGLE_HELM							  =0x02B9,
		TOGGLE_CLOAK						  =0x02BA,
		SET_EXPLORATION						  =0x02BE,
		SET_ACTIONBAR_TOGGLES				  =0x02BF,
		DELETE_GUILD_CHARTER 				  =0x02C0,
		PETITION_RENAME						  =0x02C1,
		ITEM_NAME_QUERY						  =0x02C4,
		
		MAX	=0x400,

		//MAX,
	}

	#endregion

	#region enum SMSG
	public enum SMSG : short
	{
		// 1.3.0 opcodes
		NULL_ACTION                           =0x0000,
		DBLOOKUP                              =0x0003,
		QUERY_OBJECT_POSITION                 =0x0005,
		QUERY_OBJECT_ROTATION                 =0x0007,
		ZONE_MAP                              =0x000B,
		FORCEACTIONSHOW                       =0x001B,
		ATTACKERSTATEUPDATEDEBUGINFO_OBSOLETE =0x001C,
		DEBUGINFOSPELL_OBSOLETE               =0x001D,
		DEBUGINFOSPELLMISS_OBSOLETE           =0x001E,
		DEBUG_PLAYER_RANGE_OBSOLETE           =0x001F,
		GODMODE                               =0x0023,
		DEBUG_AISTATE                         =0x002F,
		AUTH_SRP6_RESPONSE                    =0x0039,
		CHAR_CREATE                           =0x003A,
		CHAR_ENUM                             =0x003B,
		CHAR_DELETE                           =0x003C,
		NEW_WORLD                             =0x003E,
		TRANSFER_PENDING                      =0x003F,
		TRANSFER_ABORTED                      =0x0040,
		CHARACTER_LOGIN_FAILED                =0x0041,
		LOGIN_SETTIMESPEED                    =0x0042,
		GAMETIME_UPDATE                       =0x0043,
		GAMETIME_SET                          =0x0045,
		GAMESPEED_SET                         =0x0047,
		SERVERTIME                            =0x0049,
		LOGOUT_RESPONSE                       =0x004C,
		LOGOUT_COMPLETE                       =0x004D,
		LOGOUT_CANCEL_ACK                     =0x004F,
		NAME_QUERY_RESPONSE                   =0x0051,
		PET_NAME_QUERY_RESPONSE               =0x0053,
		GUILD_QUERY_RESPONSE                  =0x0055,
		ITEM_QUERY_SINGLE_RESPONSE            =0x0058,
		ITEM_QUERY_MULTIPLE_RESPONSE          =0x0059,
		PAGE_TEXT_QUERY_RESPONSE              =0x005B,
		QUEST_QUERY_RESPONSE                  =0x005D,
		GAMEOBJECT_QUERY_RESPONSE             =0x005F,
		CREATURE_QUERY_RESPONSE               =0x0061,
		WHO                                   =0x0063,
		WHOIS                                 =0x0065,
		FRIEND_LIST                           =0x0067,
		FRIEND_STATUS                         =0x0068,
		IGNORE_LIST                           =0x006B,
		GROUP_INVITE                          =0x006F,
		GROUP_CANCEL                          =0x0071,
		GROUP_DECLINE                         =0x0074,
		GROUP_UNINVITE                        =0x0077,
		GROUP_SET_LEADER                      =0x0079,
		GROUP_DESTROYED                       =0x007C,
		GROUP_LIST                            =0x007D,
		PARTY_MEMBER_STATS                    =0x007E,
		PARTY_COMMAND_RESULT                  =0x007F,
		_UPDATE_GROUP_MEMBERS                 =0x0080,
		GUILD_INVITE                          =0x0083,
		GUILD_DECLINE                         =0x0086,
		GUILD_INFO                            =0x0088,
		GUILD_ROSTER                          =0x008A,
		GUILD_EVENT                           =0x0092,
		GUILD_COMMAND_RESULT                  =0x0093,
		_UPDATE_GUILD                         =0x0094,
		MESSAGECHAT                           =0x0096,
		CHANNEL_NOTIFY                        =0x0099,
		CHANNEL_LIST                          =0x009B,
		UPDATE_OBJECT                         =0x00A9,
		DESTROY_OBJECT                        =0x00AA,
		READ_ITEM_OK                          =0x00AE,
		READ_ITEM_FAILED                      =0x00AF,
		ITEM_COOLDOWN                         =0x00B0,
		GAMEOBJECT_CUSTOM_ANIM                =0x00B3,
		MOVE_START_FORWARD                    =0x00B5,
		MOVE_START_BACKWARD                   =0x00B6,
		MOVE_STOP                             =0x00B7,
		MOVE_START_STRAFE_LEFT                =0x00B8,
		MOVE_START_STRAFE_RIGHT               =0x00B9,
		MOVE_STOP_STRAFE                      =0x00BA,
		MOVE_JUMP                             =0x00BB,
		MOVE_START_TURN_LEFT                  =0x00BC,
		MOVE_START_TURN_RIGHT                 =0x00BD,
		MOVE_STOP_TURN                        =0x00BE,
		MOVE_START_PITCH_UP                   =0x00BF,
		MOVE_START_PITCH_DOWN                 =0x00C0,
		MOVE_STOP_PITCH                       =0x00C1,
		MOVE_SET_RUN_MODE                     =0x00C2,
		MOVE_SET_WALK_MODE                    =0x00C3,
		MOVE_TOGGLE_LOGGING                   =0x00C4,
		MOVE_TELEPORT                         =0x00C5,
		MOVE_TELEPORT_CHEAT                   =0x00C6,
		MOVE_TELEPORT_ACK                     =0x00C7,
		MOVE_TOGGLE_FALL_LOGGING              =0x00C8,
		MOVE_FALL_LAND                        =0x00C9,
		MOVE_START_SWIM                       =0x00CA,
		MOVE_STOP_SWIM                        =0x00CB,
		MOVE_SET_RUN_SPEED_CHEAT              =0x00CC,
		MOVE_SET_RUN_SPEED                    =0x00CD,
		MOVE_SET_RUN_BACK_SPEED_CHEAT         =0x00CE,
		MOVE_SET_RUN_BACK_SPEED               =0x00CF,
		MOVE_SET_WALK_SPEED_CHEAT             =0x00D0,
		MOVE_SET_WALK_SPEED                   =0x00D1,
		MOVE_SET_SWIM_SPEED_CHEAT             =0x00D2,
		MOVE_SET_SWIM_SPEED                   =0x00D3,
		MOVE_SET_SWIM_BACK_SPEED_CHEAT        =0x00D4,
		MOVE_SET_SWIM_BACK_SPEED              =0x00D5,
		MOVE_SET_ALL_SPEED_CHEAT              =0x00D6,
		MOVE_SET_TURN_RATE_CHEAT              =0x00D7,
		MOVE_SET_TURN_RATE                    =0x00D8,
		MOVE_TOGGLE_COLLISION_CHEAT           =0x00D9,
		MOVE_SET_FACING                       =0x00DA,
		MOVE_SET_PITCH                        =0x00DB,
		MOVE_WORLDPORT_ACK                    =0x00DC,
		MONSTER_MOVE                          =0x00DD,
		MOVE_WATER_WALK                       =0x00DE,
		MOVE_LAND_WALK                        =0x00DF,
		MOVE_SET_RAW_POSITION_ACK             =0x00E0,
		FORCE_RUN_SPEED_CHANGE                =0x00E2,
		FORCE_RUN_BACK_SPEED_CHANGE           =0x00E4,
		FORCE_SWIM_SPEED_CHANGE               =0x00E6,
		FORCE_MOVE_ROOT                       =0x00E8,
		FORCE_MOVE_UNROOT                     =0x00EA,
		MOVE_ROOT                             =0x00EC,
		MOVE_UNROOT                           =0x00ED,
		MOVE_HEARTBEAT                        =0x00EE,
		MOVE_KNOCK_BACK                       =0x00EF,
		MOVE_FEATHER_FALL                     =0x00F2,
		MOVE_NORMAL_FALL                      =0x00F3,
		MOVE_SET_HOVER                        =0x00F4,
		MOVE_UNSET_HOVER                      =0x00F5,
		MOVE_HOVER                            =0x00F7,
		TRIGGER_CINEMATIC                     =0x00FA,
		TUTORIAL_FLAGS                        =0x00FD,
		EMOTE                                 =0x0103,
		TEXT_EMOTE                            =0x0105,
		INVENTORY_CHANGE_FAILURE              =0x0112,
		OPEN_CONTAINER                        =0x0113,
		INSPECT                               =0x0115,
		TRADE_STATUS                          =0x0120,
		TRADE_STATUS_EXTENDED                 =0x0121,
		INITIALIZE_FACTIONS                   =0x0122,
		SET_FACTION_VISIBLE                   =0x0123,
		SET_FACTION_STANDING                  =0x0124,
		SET_PROFICIENCY                       =0x0127,
		ACTION_BUTTONS                        =0x0129,
		INITIAL_SPELLS                        =0x012A,
		LEARNED_SPELL                         =0x012B,
		SUPERCEDED_SPELL                      =0x012C,
		CAST_RESULT                           =0x0130,
		SPELL_START                           =0x0131,
		SPELL_GO                              =0x0132,
		SPELL_FAILURE                         =0x0133,
		SPELL_COOLDOWN                        =0x0134,
		COOLDOWN_EVENT                        =0x0135,
		UPDATE_AURA_DURATION                  =0x0137,
		PET_CAST_FAILED                       =0x0138,
		CHANNEL_START                         =0x0139,
		CHANNEL_UPDATE                        =0x013A,
		AI_REACTION                           =0x013C,
		ATTACKSTART                           =0x0143,
		ATTACKSTOP                            =0x0144,
		ATTACKSWING_NOTINRANGE                =0x0145,
		ATTACKSWING_BADFACING                 =0x0146,
		ATTACKSWING_NOTSTANDING               =0x0147,
		ATTACKSWING_DEADTARGET                =0x0148,
		ATTACKSWING_CANT_ATTACK               =0x0149,
		ATTACKERSTATEUPDATE                   =0x014A,
		VICTIMSTATEUPDATE_OBSOLETE            =0x014B,
		DAMAGE_DONE_OBSOLETE                  =0x014C,
		DAMAGE_TAKEN_OBSOLETE                 =0x014D,
		CANCEL_COMBAT                         =0x014E,
		PLAYER_COMBAT_XP_GAIN_OBSOLETE        =0x014F,
		HEALSPELL_ON_PLAYER_OBSOLETE          =0x0150,
		HEALSPELL_ON_PLAYERS_PET_OBSOLETE     =0x0151,
		BINDPOINTUPDATE                       =0x0155,
		BINDZONEREPLY                         =0x0157,
		PLAYERBOUND                           =0x0158,
		DEATH_NOTIFY_OBSOLETE                 =0x0159,
		RESURRECT_REQUEST                     =0x015B,
		LOOT_RESPONSE                         =0x0160,
		LOOT_RELEASE_RESPONSE                 =0x0161,
		LOOT_REMOVED                          =0x0162,
		LOOT_MONEY_NOTIFY                     =0x0163,
		LOOT_ITEM_NOTIFY                      =0x0164,
		LOOT_CLEAR_MONEY                      =0x0165,
		ITEM_PUSH_RESULT                      =0x0166,
		DUEL_REQUESTED                        =0x0167,
		DUEL_OUTOFBOUNDS                      =0x0168,
		DUEL_INBOUNDS                         =0x0169,
		DUEL_COMPLETE                         =0x016A,
		DUEL_WINNER                           =0x016B,
		MOUNTRESULT                           =0x016E,
		DISMOUNTRESULT                        =0x016F,
		PUREMOUNT_CANCELLED_OBSOLETE          =0x0170,
		MOUNTSPECIAL_ANIM                     =0x0172,
		PET_TAME_FAILURE                      =0x0173,
		PET_NAME_INVALID                      =0x0178,
		PET_SPELLS                            =0x0179,
		GOSSIP_MESSAGE                        =0x017D,
		GOSSIP_COMPLETE                       =0x017E,
		NPC_TEXT_UPDATE                       =0x0180,
		NPC_WONT_TALK                         =0x0181,
		QUESTGIVER_STATUS                     =0x0183,
		QUESTGIVER_QUEST_LIST                 =0x0185,
		QUESTGIVER_QUEST_DETAILS              =0x0188,
		QUESTGIVER_REQUEST_ITEMS              =0x018B,
		QUESTGIVER_OFFER_REWARD               =0x018D,
		QUESTGIVER_QUEST_INVALID              =0x018F,
		QUESTGIVER_QUEST_COMPLETE             =0x0191,
		QUESTGIVER_QUEST_FAILED               =0x0192,
		QUESTLOG_FULL                         =0x0195,
		QUESTUPDATE_FAILED                    =0x0196,
		QUESTUPDATE_FAILEDTIMER               =0x0197,
		QUESTUPDATE_COMPLETE                  =0x0198,
		QUESTUPDATE_ADD_KILL                  =0x0199,
		QUESTUPDATE_ADD_ITEM                  =0x019A,
		QUEST_CONFIRM_ACCEPT                  =0x019C,
		LIST_INVENTORY                        =0x019F,
		SELL_ITEM                             =0x01A1,
		BUY_ITEM                              =0x01A4,
		BUY_FAILED                            =0x01A5,
		SHOWTAXINODES                         =0x01A9,
		TAXINODE_STATUS                       =0x01AB,
		ACTIVATETAXIREPLY                     =0x01AE,
		NEW_TAXI_PATH                         =0x01AF,
		TRAINER_LIST                          =0x01B1,
		TRAINER_BUY_SUCCEEDED                 =0x01B3,
		TRAINER_BUY_FAILED                    =0x01B4,
		PLAYERBINDERROR                       =0x01B6,
		SHOW_BANK                             =0x01B8,
		BUY_BANK_SLOT_RESULT                  =0x01BA,
		PETITION_SHOWLIST                     =0x01BC,
		PETITION_SHOW_SIGNATURES              =0x01BF,
		PETITION_SIGN_RESULTS                 =0x01C1,
		PETITION_DECLINE                      =0x01C2,
		TURN_IN_PETITION_RESULTS              =0x01C5,
		PETITION_QUERY_RESPONSE               =0x01C7,
		FISH_NOT_HOOKED                       =0x01C8,
		FISH_ESCAPED                          =0x01C9,
		NOTIFICATION                          =0x01CB,
		PLAYED_TIME                           =0x01CD,
		QUERY_TIME_RESPONSE                   =0x01CF,
		LOG_XPGAIN                            =0x01D0,
		SPLIT_MONEY                           =0x01D1,
		LEVELUP_INFO                          =0x01D4,
		MINIMAP_PING                          =0x01D5,
		RESISTLOG                             =0x01D6,
		ENCHANTMENTLOG                        =0x01D7,
		START_MIRROR_TIMER                    =0x01D9,
		PAUSE_MIRROR_TIMER                    =0x01DA,
		STOP_MIRROR_TIMER                     =0x01DB,
		PONG                                  =0x01DD,
		CLEAR_COOLDOWN                        =0x01DE,
		GAMEOBJECT_PAGETEXT                   =0x01DF,
		COOLDOWN_CHEAT                        =0x01E1,
		SPELL_DELAYED                         =0x01E2,
		PLAYER_MACRO                          =0x01E4,
		GM_BIND_OTHER                         =0x01E8,
		GM_SUMMON                             =0x01E9,
		ITEM_TIME_UPDATE                      =0x01EA,
		ITEM_ENCHANT_TIME_UPDATE              =0x01EB,
		AUTH_CHALLENGE                        =0x01EC,
		AUTH_RESPONSE                         =0x01EE,
		GM_SHOWLABEL                          =0x01EF,
		ADD_DYNAMIC_TARGET                    =0x01F0,
		SAVE_GUILD_EMBLEM                     =0x01F1,
		TABARDVENDOR_ACTIVATE                 =0x01F2,
		PLAY_SPELL_VISUAL                     =0x01F3,
		PARTYKILLLOG                          =0x01F5,
		COMPRESSED_UPDATE_OBJECT              =0x01F6,
		OBSOLETE                              =0x01F7,
		EXPLORATION_EXPERIENCE                =0x01F8,
		RANDOM_ROLL                           =0x01FB,
		ENVIRONMENTALDAMAGELOG                =0x01FC,
		RWHOIS                                =0x01FE,
		LOOKING_FOR_GROUP                     =0x01FF,
		REMOVED_SPELL                         =0x0203,
		GMTICKET_CREATE                       =0x0206,
		GMTICKET_UPDATETEXT                   =0x0208,
		ACCOUNT_DATA_MD5                      =0x0209,
		UPDATE_ACCOUNT_DATA                   =0x020C,
		CLEAR_FAR_SIGHT_IMMEDIATE             =0x020D,
		POWERGAINLOG_OBSOLETE                 =0x020E,
		GMTICKET_GETTICKET                    =0x0212,
		GAMEOBJECT_SPAWN_ANIM                 =0x0214,
		GAMEOBJECT_DESPAWN_ANIM               =0x0215,
		CORPSE_QUERY                          =0x0216,
		GMTICKET_DELETETICKET                 =0x0218,
		CHAT_WRONG_FACTION                    =0x0219,
		GMTICKET_SYSTEMSTATUS                 =0x021B,
		SET_REST_START                        =0x021E,
		SPIRIT_HEALER_CONFIRM                 =0x0222,
		GOSSIP_POI                            =0x0224,
		GM_PLAYER_INFO                        =0x0230,
		LOGIN_VERIFY_WORLD                    =0x0236,
		SEND_MAIL_RESULT                      =0x0239,
		MAIL_LIST_RESULT                      =0x023B,
		BATTLEFIELD_LIST                      =0x023D,
		BATTLEFIELD_WIN                       =0x023F,
		BATTLEFIELD_LOSE                      =0x0240,
		ITEM_TEXT_QUERY_RESPONSE              =0x0244,
		SPELLLOGMISS                          =0x024B,
		SPELLLOGEXECUTE                       =0x024C,
		DEBUGAURAPROC                         =0x024D,
		PERIODICAURALOG                       =0x024E,
		SPELLDAMAGESHIELD                     =0x024F,
		SPELLNONMELEEDAMAGELOG                =0x0250,
		RESURRECT_FAILED                      =0x0252,
		ZONE_UNDER_ATTACK                     =0x0254,
		AUCTION_HELLO                         =0x0255,
		AUCTION_COMMAND_RESULT                =0x025B,
		AUCTION_LIST_RESULT                   =0x025C,
		AUCTION_OWNER_LIST_RESULT             =0x025D,
		AUCTION_BIDDER_NOTIFICATION           =0x025E,
		AUCTION_OWNER_NOTIFICATION            =0x025F,
		PROCRESIST                            =0x0260,
		STANDSTATE_CHANGE_FAILURE             =0x0261,
		DISPEL_FAILED                         =0x0262,
		SPELLORDAMAGE_IMMUNE                  =0x0263,
		AUCTION_BIDDER_LIST_RESULT            =0x0265,
		SET_FLAT_SPELL_MODIFIER               =0x0266,
		SET_PCT_SPELL_MODIFIER                =0x0267,
		CORPSE_RECLAIM_DELAY                  =0x0269,
		GM_ACCOUNT_ONLINE                     =0x026E,
		LIST_STABLED_PETS                     =0x026F,
		STABLE_RESULT                         =0x0273,
		QUEST_PUSH_RESULT                     =0x0276,
		PLAY_MUSIC                            =0x0277,
		PLAY_OBJECT_SOUND                     =0x0278,
		SPELLDISPELLOG                        =0x027B,
		DAMAGE_CALC_LOG                       =0x027C,
		RAID_MEMBER_STATS                     =0x027F,
		QUERY_NEXT_MAIL_TIME                  =0x0284,
		RECEIVED_MAIL                         =0x0285,
		RAID_GROUP_ONLY                       =0x0286,
		PVP_CREDIT                            =0x028C,
		AUCTION_REMOVED_NOTIFICATION          =0x028D,
		SERVER_MESSAGE                        =0x0291,
		CANCEL_AUTO_REPEAT                    =0x0294,
		STANDSTATE_CHANGE_ACK                 =0x0295,
		LOOT_ALL_PASSED                       =0x0296,
		LOOT_ROLL_WON                         =0x0297,
		LOOT_START_ROLL                       =0x0299,
		LOOT_ROLL                             =0x029A,
		LOOT_MASTER_LIST                      =0x029C,
		SET_FORCED_REACTIONS                  =0x029D,
		SPELL_FAILED_OTHER                    =0x029E,
		GAMEOBJECT_RESET_STATE                =0x029F,
		CHAT_PLAYER_NOT_FOUND                 =0x02A1,
		TALENT_WIPE_CONFIRM                   =0x02A2,
		SUMMON_REQUEST                        =0x02A3,
		MOVE_TOGGLE_GRAVITY_CHEAT             =0x02A5,
		MONSTER_MOVE_TRANSPORT                =0x02A6,
		PET_BROKEN                            =0x02A7,
		MSG_MOVE_FEATHER_FALL				= 0x02A8,
		MSG_MOVE_WATER_WALK                 = 0x02A9,
		FEIGN_DEATH_RESISTED                = 0x02AC,
		SCRIPT_MESSAGE                      = 0x02AE,
		DUEL_COUNTDOWN						= 0x02B7,
		AREA_TRIGGER_MESSAGE				= 0x02B8,
		SPELL_REFLECTED						= 0x02BB,
		PLAYER_SKINNED						= 0x02BC,
		DURABILITY_DAMAGE_DEATH				= 0x02BD,
		DELETE_GUILD_CHARTER				= 0x02C0,
		PETITION_RENAME						= 0x02C1,
		INIT_WORLD_STATES					= 0x02C2,
		UPDATE_WORLD_STATE					= 0x02C3,
		ITEM_NAME_QUERY_RESPONSE			= 0x02C5,
		PET_ACTION_FEEDBACK					= 0x02C6,

		MAX  //=0x400
		/*		CREATE_DBOBJECT,
				CREATE_DBOBJECT_REPLY,
				DELETE_DBOBJECT,
				OBJECT_DESTROY,  //From the old list, not sure why
				OBJECT_UPDATE,
		*/	}

	#endregion

	#region enum WORLDMSG
	public enum WORLDMSG : int
	{
		INIT_WORLD, // only from loginserver
		WORLD_SHUTDOWN,
		INIT_MAPS,
		CHANGE_MAP,
		ADD_MAP, // for future use
		REMOVE_MAP, // for future use
		CREATE_DBOBJECT,
		CREATE_DBOBJECT_REPLY,
		DELETE_DBOBJECT,
		DESERIALIZE_OBJ, // maybe sent from both
		PLAYER_ENTER_WORLD, // only from loginserver
		PLAYER_LEAVE_WORLD, // could be sent from both
		CLIENT_MESSAGE, // CMSG
		SERVER_MESSAGE, // SMSG
		INIT_GUIDS, // from login server
		ACQUIRE_GUIDS, // only from a worldserver
		ACQUIRE_GUIDS_REPLY, // only from loginserver
		SCRIPT_MESSAGE,
		REGISTERVENDOR,
		INIT_SPELLS,
		GROUPCREATE,
		TAKETAXI,
		MAX,
	}

	#endregion

	#region enum RESTEDSTATE
	public enum RESTEDSTATE : byte
	{
		WELLRESTED = 1,
		RESTED = 2,
		NORMAL = 3,
		TIRED  = 4,
		EXHAUSTED = 5,
	}
	#endregion

	#region enum CHATMESSAGETYPE
	public enum CHATMESSAGETYPE : int
	{
		SAY,
		PARTY,
		RAID,
		GUILD,
		OFFICER,
		YELL,
		WHISPER,
		WHISPER_INFORM,
		EMOTE,
		TEXT_EMOTE,
		SYSTEM,
		MONSTER_SAY,
		MONSTER_YELL,
		MONSTER_EMOTE,
		CHANNEL,
		CHANNEL_JOIN,
		CHANNEL_LEAVE,
		CHANNEL_LIST,
		CHANNEL_NOTICE,
		CHANNEL_NOTICE_USER,
		AFK,
		DND,
		COMBAT_LOG,
		IGNORED,
		SKILL,
		LOOT,
		COMBAT_LOG_ENEMY,
		COMBAT_LOG_SELF,
		COMBAT_LOG_PARTY,
		COMBAT_LOG_ERROR,
		COMBAT_LOG_MISC_INFO,
		MAX
	};
	#endregion

	#region enum INVSLOT
	public enum INVSLOT : byte
	{
		EQUIPPEDFIRST = 0,
		HEAD = 0,
		NECK = 1,
		SHOULDER = 2,
		BODY = 3,
		CHEST = 4,
		WAIST = 5,
		LEGS = 6,
		FEET = 7,
		WRIST = 8,
		HAND = 9,
		FINGER1 = 10,
		FINGER2 = 11,
		TRINKET1 = 12,
		TRINKET2 = 13,
		BACK = 14,
		MAINHAND = 15,
		OFFHAND = 16,
		RANGED = 17,
		TABARD = 18,
		EQUIPPEDLAST = 0x12,
		NONE_EQUIPFIRST = 0x13,
		BAG0 = 0x13,
		BAGFIRST = 0x13,
		BAG1 = 0x14,
		BAG2 = 0x15,
		BAG3 = 0x16,
		BAGLAST = 0x16,
		BACKPACK_START = 0x17,
		BACKPACK_SLOT = 0x17,
		BACKPACK_SLOT00 = 0x17,
		BACKPACK_FIRST = 0x17,
		BACKPACK_SLOT01 = 0x18,
		BACKPACK_SLOT02 = 0x19,
		BACKPACK_SLOT03 = 0x1A,
		BACKPACK_SLOT04 = 0x1B,
		BACKPACK_SLOT05 = 0x1C,
		BACKPACK_SLOT06 = 0x1D,
		BACKPACK_SLOT07 = 0x1E,
		BACKPACK_SLOT08 = 0x1F,
		BACKPACK_SLOT09 = 0x20,
		BACKPACK_SLOT10 = 0x21,
		BACKPACK_SLOT11 = 0x22,
		BACKPACK_SLOT12 = 0x23,
		BACKPACK_SLOT13 = 0x24,
		BACKPACK_SLOT14 = 0x25,
		BACKPACK_SLOT15 = 0x26,
		BACKPACK_LAST = 0x26,
		BANKGENERIC_SLOT = 0x27,
		BANKGENERIC_SLOT00 = 0x27,
		BANKGENERIC_FIRST = 0x27,
		BANKGENERIC_SLOT01 = 0x28,
		BANKGENERIC_SLOT02 = 0x29,
		BANKGENERIC_SLOT03 = 0x2A,
		BANKGENERIC_SLOT04 = 0x2B,
		BANKGENERIC_SLOT05 = 0x2C,
		BANKGENERIC_SLOT06 = 0x2D,
		BANKGENERIC_SLOT07 = 0x2E,
		BANKGENERIC_SLOT08 = 0x2F,
		BANKGENERIC_SLOT09 = 0x30,
		BANKGENERIC_SLOT10 = 0x31,
		BANKGENERIC_SLOT11 = 0x32,
		BANKGENERIC_SLOT12 = 0x33,
		BANKGENERIC_SLOT13 = 0x34,
		BANKGENERIC_SLOT14 = 0x35,
		BANKGENERIC_SLOT15 = 0x36,
		BANKGENERIC_SLOT16 = 0x37,
		BANKGENERIC_SLOT17 = 0x38,
		BANKGENERIC_SLOT18 = 0x39,
		BANKGENERIC_SLOT19 = 0x3A,
		BANKGENERIC_SLOT20 = 0x3B,
		BANKGENERIC_SLOT21 = 0x3C,
		BANKGENERIC_SLOT22 = 0x3D,
		BANKGENERIC_SLOT23 = 0x3E,
		BANKPURCHASABLE_SLOT1 = 0x3F,
		BANKPURCHASABLE_SLOT2 = 0x40,
		BANKPURCHASABLE_SLOT3 = 0x41,
		BANKPURCHASABLE_SLOT4 = 0x42,
		BANKPURCHASABLE_SLOT5 = 0x43,
		BANKPURCHASABLE_SLOT6 = 0x44,
		BANKGENERIC_LAST = 0x3E,
		BANKBAG_FIRST = 0x3F,
		BANKBAG_LAST = 0x44,
		MAX = 0x45,
		PLAYER_INVENTORY_SLOTS  =0x45,
		NUM_INVENTORY_SLOTS =0x17,
		NUM_BAG_SLOTS  = 0x4,
		MIN_BACKPACK_SLOTS =0x10,
		BANK_NUM_GEMERIC_SLOTS =0x18,
		NUM_BANKBAG_SLOTS = 0x6,
		TOTAL_BAG_SLOTS = 0xA,
	}
	#endregion

	#region enum ITEMCLASS
	public enum ITEMCLASS
	{
		CONSUMABLE = 0x00,
		CONTAINER = 0x01,
		WEAPON = 0x02,
		NOTVALID3 = 0x03, // JEWELRY OBSOLETE?
		ARMOUR = 0x04,
		REGEANT = 0x05,
		PROJECTILE = 0x06, // MAYBE
		TRADEGOODS = 0x07,
		NOTVALID8 = 0x08, // GENERIC OBSOLETE?
		BOOK = 0x09,
		MONEY = 0x0A,
		QUIVER = 0x0B,
		QUEST = 0x0C,
		KEYLOCKPICK = 0x0D,
		PERMANENT = 0x0E,
		JUNK = 0x0F,
		MAX
	}
	#endregion

	#region enum WEAPONSUBCLASS
	public enum WEAPONSUBCLASS
	{
		ONEHANDAXE = 0,
		TWOHANDAXE = 1,
		BOW = 2,
		GUN = 3,
		ONEHANDBLUNT = 4,
		TWOHANDBLUNT = 5,
		POLEARM = 6,
		ONEHANDSWORD = 7,
		TWOHANDSWORD = 8,
		NOTVALID9,
		STAFF = 10,
		ONEHANDEXOTIC = 11,
		TWOHANDEXOTIC = 12,
		UNARMED = 13,
		GENERIC = 14,
		DAGGER = 15,
		THROWN = 16,
		SPEAR = 17,
		CROSSBOW = 18,
		WAND = 19,
	}
	#endregion

	#region enum ARMOURSUBCLASS
	public enum ARMOURSUBCLASS
	{
		GENERIC,
		CLOTH,
		LEATHER,
		MAIL,
		PLATE,
		BUCKLER,
		SHIELD
	}
	#endregion

	#region enum QUIVERSUBCLASS
	public enum QUIVERSUBCLASS
	{
		OBSOLETE_QUIVER,
		BOLT_QUIVER,
		ARROW_QUIVER,
		AMMO_POUCH,
	}
	#endregion

	#region enum PROJECTILESUBCLASS
	public enum PROJECTILESUBCLASS
	{
		WAND,
		BOLT,
		ARROW,
		BULLET,
		THROWN,
	}
	#endregion

	#region enum INVTYPE
	public enum INVTYPE
	{
		NONE_EQUIP = 0x00,
		HEAD = 0x01,
		NECK = 0x02,
		SHOULDER = 0x03,
		BODY = 0x04,
		CHEST = 0x05,
		WAIST = 0x06,
		LEGS = 0x07,
		FEET = 0x08,
		WRIST = 0x09,
		HAND = 0x0A,
		FINGER = 0x0B,
		TRINKET = 0x0C,
		WEAPON = 0x0D,
		SHIELD = 0x0E,
		RANGED = 0x0F,
		CLOAK = 0x10,
		TWOHANDEDWEAPON = 0x11,
		BAG = 0x12,
		TABARD = 0x13,
		ROBE = 0x14,
		WEAPONMAINHAND = 0x15,
		WEAPONOFFHAND = 0x16,
		HOLDABLE = 0x17,
		AMMO = 0x18,
		THROWN = 0x19,
		RANGEDRIGHT = 0x1A,
		NUM_TYPES = 0x1B
	}
	#endregion

	#region enum OBJECTTYPE
	public enum OBJECTTYPE
	{
		OBJECT,
		ITEM,
		CONTAINER,
		UNIT,
		PLAYER,
		GAMEOBJECT,
		DYNAMICOBJECT,
		CORPSEOBJECT,
		MAX,
	}
	#endregion

	#region enum HIER_OBJECTTYPE
	public enum HIER_OBJECTTYPE : int
	{
		OBJECT			= 0x01,
		ITEM			= 0x03,
		CONTAINER		= 0x07,
		UNIT			= 0x09,
		PLAYER			= 0x19,
		GAMEOBJECT		= 0x21,
		DYNAMICOBJECT	= 0x41,
		CORPSEOBJECT	= 0x81,
		MAX
	}
	#endregion

	#region enum OBJECTFIELDS
	public enum OBJECTFIELDS
	{

		GUID		=	0x0000	,	
		GUID1		=	0x0001	,	
		HIER_TYPE	=	0x0002	,	
		ENTRY		=	0x0003	,	
		SCALE		=	0x0004	,	
		PADDING		=	0x0005	,	
		MAX			=	0x0006	,
	}
	#endregion

	#region enum ITEMFIELDS
	public enum ITEMFIELDS
	{
		OWNER = 6,
		CONTAINED = 8,
		CREATOR = 10,
		GIFTCREATOR = 12,
		STACK_COUNT = 14,
		DURATION = 15,
		SPELL_CHARGES = 16,
		FLAGS = 21,
		ENCHANTMENTS = 22,
		PROPERTY_SEED = 43,
		RANDOM_PROPERTIES_ID = 44,
		ITEMPADDING = 45,
		DURABILITY = 46,
		MAXDURABILITY= 47,
		MAX = 48,
	}
	#endregion

	#region enum CONTAINERFIELDS
	public enum CONTAINERFIELDS
	{		
		NUM_SLOTS	= 48,
		ALIGN_PAD	= 49,
		SLOTS		= 50, //64?  (Slots uses an array)
		MAX			= 90,
	}
	#endregion

	#region enum UNITFIELDS
	public enum UNITFIELDS
	{
		CHARM0				=	6	,
		CHARM1				=	7	,
		SUMMON0				=	8	,
		SUMMON1				=	9	,
		CHARMEDBY0			=	10	,
		CHARMEDBY1			=	11	,
		SUMMONEDBY0			=	12	,
		SUMMONEDBY1			=	13	,
		CREATEDBY0			=	14	,
		CREATEDBY1			=	15	,
		TARGET				=	16	,
		TARGET1				=	17	,
		PERSUADED0			=   18	,
		PERSUADED1			=	19	,
		CHANNEL_OBJECT0		=	20	,
		CHANNEL_OBJECT1		=	21	,
		HEALTH				=	22	,
		POWER0				=	23	,//POWER 1
		MANA				=	24	,
		RAGE				=	25	,
		FOCUS				=	26	,
		ENERGY				=	27	,
		MAX_HEALTH			=	28	,
		MAX_POWER0			=	29	,
		MAX_MANA			=	30	,
		MAX_RAGE			=	31	,
		MAX_FOCUS			=	32	,
		MAX_ENERGY			=	33	,
		LEVEL				=	34	,
		FACTION				=	35	,
		BYTES_0				=	36	,
		VIRTUAL_ITEM_SLOT_DISPLAY0	=	37	,
		VIRTUAL_ITEM_SLOT_DISPLAY1	=	38	,
		VIRTUAL_ITEM_SLOT_DISPLAY2	=	39	,
		VIRTUAL_ITEM_INFO0	=	40	,
		VIRTUAL_ITEM_INFO1	=	41	,
		VIRTUAL_ITEM_INFO2	=	42	,
		VIRTUAL_ITEM_INFO3	=	43	,
		VIRTUAL_ITEM_INFO4	=	44	,
		VIRTUAL_ITEM_INFO5	=	45	,
		FLAGS				=	46	,
		AURA00				=	47	,
		AURA55				=	102	,
		AURALEVELS0			=	103	,
		AURALEVELS1			=	104	,
		AURALEVELS2			=	105	,
		AURALEVELS3			=	106	,
		AURALEVELS4			=	107	,
		AURALEVELS5			=	108	,
		AURALEVELS6			=	109	,
		AURALEVELS7			=	110	,
		AURALEVELS8			=	111	,
		AURALEVELS9			=	112	,
		AURAAPPLICATIONS0	=	113	,
		AURAAPPLICATIONS1	=	114	,
		AURAAPPLICATIONS2	=	115	,
		AURAAPPLICATIONS3	=	116	,
		AURAAPPLICATIONS4	=	117	,
		AURAAPPLICATIONS5	=	118	,
		AURAAPPLICATIONS6	=	119	,
		AURAAPPLICATIONS7	=	120	,
		AURAAPPLICATIONS8	=	121	,
		AURAAPPLICATIONS9	=	122	,
		AURAFLAGS0			=	123	,
		AURAFLAGS1			=	124	,
		AURAFLAGS2			=	125	,
		AURAFLAGS3			=	126	,
		AURAFLAGS4			=	127	,
		AURAFLAGS5			=	128	,
		AURAFLAGS6			=	129	,
		AURASTATE			=	130	,
		BASEATTACKTIME		=	131	,
		BASEATTACKTIME1		=	132	,
		RANGEDATTACKTIME0	=	133	,
		BOUNDINGRADIUS		=	134	,
		COMBATREACH			=	135	,
		DISPLAYID			=	136	,
		NATIVE_DISPLAYID	=	137 ,
		MOUNT_DISPLAYID		=	138	,
		MIN_DAMAGE			=	139	,
		MAX_DAMAGE			=	140	,
		UNIT_FIELD_MINOFFHANDDAMAGE = 141 ,
		UNIT_FIELD_MAXOFFHANDDAMAGE = 142 ,
		BYTES_1				=	143	,
		PETNUMBER			=	144	,
		PET_NAME_TIMESTAMP	=	145	,
		PETEXPERIENCE		=	146	,
		PETNEXTLEVELEXP		=	147	,
		DYNAMIC_FLAGS		=	148	,
		CHANNEL_SPELL		=	149	,
		MOD_CAST_SPEED		=	150	,
		CREATED_BY_SPELL	=	151	,
		NPC_FLAGS			=	152	,
		NPC_EMOTE_STATE		=	153	,
		TRAINING_POINTS		=	154 ,
		BASE_STRENGTH		=	155 ,
		BASE_AGILITY		=	156	,
		BASE_STAMINA		=	157	,
		BASE_INTELLECT		=	158	,
		BASE_SPIRIT			=	159	,
		RESIST_PHYSICAL		=	160	,
		RESIST_HOLY			=	161 ,
		RESIST_FIRE			=	162 ,
		RESIST_NATURE		=	163 ,
		RESIST_FROST		=	164 ,
		RESIST_SHADOW		=	165 ,
		RESIST_ARCANE		=	166 ,
		ATTACKPOWER			=	167 ,
		BASE_MANA			=	168 ,
		ATTACKPOWERMODIFIER	=	169 ,
		BYTES_2				=	170 ,
		RANGEDATTACKPOWER	=	171 ,
		MINRANGEDDAMAGE		=	172 ,
		MAXRANGEDDAMAGE		=	173 ,
		RANGED_ATTACK_POWER_MODS = 174 ,
		PADDING				=	175	,
		MAX = 176,
	}
	#endregion

	#region enum PLAYERFIELDS
	public enum PLAYERFIELDS
	{
		SELECTION			=	176	,
		SELECTION1			=	177	, // was commented
		DUEL_ARBITER0		=	178	,
		DUEL_ARBITER1		=	179	,
		FLAGS				=	180	,
		GUILD_ID			=	181	,
		GUILD_RANK			=	182	,
		BYTES_1				=	183	,
		BYTES_2				=	184	,
		BYTES_3				=	185	,
		DUEL_TEAM			=	186	,
		GUILD_TIMESTAMP		=	187	,
		QUEST_LOG_1_1		=	188 ,
		QUEST_LOG_1_2		=	189 ,
		QUEST_LOG_2_1		=	191 ,
		QUEST_LOG_2_2		=	192	,
		QUEST_LOG_3_1		=	194 ,
		QUEST_LOG_3_2		=	195 ,
		QUEST_LOG_4_1		=	197 ,
		QUEST_LOG_4_2		=	198 ,
		QUEST_LOG_5_1		=	200 ,
		QUEST_LOG_5_2		=	201 ,
		QUEST_LOG_6_1		=	203 ,
		QUEST_LOG_6_2		=	204 ,
		QUEST_LOG_7_1		=	206 ,
		QUEST_LOG_7_2		=	207 ,
		QUEST_LOG_8_1		=	209 ,
		QUEST_LOG_8_2		=	210 ,
		QUEST_LOG_9_1		=	212 ,
		QUEST_LOG_9_2		=	213 ,
		QUEST_LOG_10_1		=	215 ,
		QUEST_LOG_10_2		=	216 ,
		QUEST_LOG_11_1		=	218 ,
		QUEST_LOG_11_2		=	219 ,
		QUEST_LOG_12_1		=	221	,
		QUEST_LOG_12_2		=	222	,
		QUEST_LOG_13_1		=	224	,
		QUEST_LOG_13_2		=	225	,
		QUEST_LOG_14_1		=	227	,
		QUEST_LOG_14_2		=	228	,
		QUEST_LOG_15_1		=	230	,
		QUEST_LOG_15_2		=	231	,
		QUEST_LOG_16_1		=	233	,
		QUEST_LOG_16_2		=	234	,
		QUEST_LOG_17_1		=	236	,
		QUEST_LOG_17_2		=	237	,
		QUEST_LOG_18_1		=	239	,
		QUEST_LOG_18_2		=	240	,
		QUEST_LOG_19_1		=	242	,
		QUEST_LOG_19_2		=	243	,
		QUEST_LOG_20_1		=	245	,
		QUEST_LOG_20_2		=	246	,
		VISIBLE_ITEM_1_0	= 248 ,
		VISIBLE_ITEM_1_PROPERTIES = 256 ,
		VISIBLE_ITEM_2_0	= 257 , 
		VISIBLE_ITEM_2_PROPERTIES = 265 ,
		VISIBLE_ITEM_3_0	= 266 ,
		VISIBLE_ITEM_3_PROPERTIES = 274 ,
		VISIBLE_ITEM_4_0	= 275 ,
		VISIBLE_ITEM_4_PROPERTIES = 283 ,
		VISIBLE_ITEM_5_0	= 284 ,
		VISIBLE_ITEM_5_PROPERTIES = 292 ,
		VISIBLE_ITEM_6_0	= 293 ,
		VISIBLE_ITEM_6_PROPERTIES = 301 ,
		VISIBLE_ITEM_7_0	= 302 ,
		VISIBLE_ITEM_7_PROPERTIES = 310 ,
		VISIBLE_ITEM_8_0	= 311 ,
		VISIBLE_ITEM_8_PROPERTIES = 319 ,
		VISIBLE_ITEM_9_0	= 320 ,
		VISIBLE_ITEM_9_PROPERTIES = 328 ,
		VISIBLE_ITEM_10_0	= 329 ,
		VISIBLE_ITEM_10_PROPERTIES = 337,
		VISIBLE_ITEM_11_0	= 338 ,
		VISIBLE_ITEM_11_PROPERTIES = 346,
		VISIBLE_ITEM_12_0	= 347 ,
		VISIBLE_ITEM_12_PROPERTIES = 355,
		VISIBLE_ITEM_13_0	= 356 ,
		VISIBLE_ITEM_13_PROPERTIES = 364,
		VISIBLE_ITEM_14_0	= 365 ,
		VISIBLE_ITEM_14_PROPERTIES = 373,
		VISIBLE_ITEM_15_0	= 374 ,
		VISIBLE_ITEM_15_PROPERTIES = 382,
		VISIBLE_ITEM_16_0	= 383 ,
		VISIBLE_ITEM_16_PROPERTIES = 391,
		VISIBLE_ITEM_17_0	= 392 ,
		VISIBLE_ITEM_17_PROPERTIES = 400,
		VISIBLE_ITEM_18_0	= 401 ,
		VISIBLE_ITEM_18_PROPERTIES = 409,
		VISIBLE_ITEM_19_0	= 410 ,
		VISIBLE_ITEM_19_PROPERTIES = 418,
		PAD_0				=	419	,
		INV_SLOTS			=	420	,
		PACK_SLOTS			=	466	,
		BANK_SLOTS			=	498	,
		BANKBAG_SLOTS		=	546	,
		VENDORBUYBACK_SLOT	=	558 ,
		FARSIGHT			=	560	,
		FARSIGHT1			=	561	,
		COMBO_TARGET0		=	562	,
		COMBO_TARGET1		=	563	,
		BUYBACK_NPC			=	564	,
		XP					=	566	,	
		NEXTLEVEL_XP		=	567 ,
		SKILL_INFO			=	568	,
		//		SKILL_INFO383		=	689	,
		//QUEST_INFO			=	720	, moved up
		//		QUEST_LOG79			=	769	,
		SKILL_POINTS		=	952	,
		TALENT_POINTS		=	953	,
		TRACK_CREATURES		=	954	,
		TRACK_RESOURCES		=	955	,
		CHAT_FILTERS		=	956	,
		BLOCK_PERCENTAGE	=	957	,
		DODGE_PERCENTAGE	=	958	,
		PARRY_PERCENTAGE	=	959	,
		CRIT_PERCENTAGE		=	960	,
		EXPLORED_ZONES		=	961	,
		REST_STATE_EXPERIENCE=	993 ,
		COINAGE				=	994	,
		STRENGTH			=	995	,
		AGILITY				=	996	,
		STAMINA				=	997	,
		INTELLECT			=	998	,
		SPIRIT				=	999	,
		BASE_STRENGTH_NEG	=	1000,
		BASE_AGILITY_NEG	=	1001,
		BASE_STAMINA_NEG	=	1002,
		BASE_INTELLECT_NEG	=	1003,
		BASE_SPIRIT_NEG		=	1004,
		RESISTANCEBUFFMODSPOSITIVE0	=	1005,
		RESISTANCEBUFFMODSPOSITIVE1	=	1006,
		RESISTANCEBUFFMODSPOSITIVE2	=	1007,
		RESISTANCEBUFFMODSPOSITIVE3	=	1008,
		RESISTANCEBUFFMODSPOSITIVE4	=	1009,
		RESISTANCEBUFFMODSPOSITIVE5	=	1010,
		RESISTANCEBUFFMODSPOSITIVE6	=	1011,
		RESISTANCEBUFFMODSNEGATIVE0	=	1012,
		RESISTANCEBUFFMODSNEGATIVE1	=	1013,
		RESISTANCEBUFFMODSNEGATIVE2	=	1014,
		RESISTANCEBUFFMODSNEGATIVE3	=	1015,
		RESISTANCEBUFFMODSNEGATIVE4	=	1016,
		RESISTANCEBUFFMODSNEGATIVE5	=	1017,
		RESISTANCEBUFFMODSNEGATIVE6	=	1018,
		MOD_DAMAGE_DONE_POS			=	1019, 
		MOD_DAMAGE_DONE_NEG			=	1026,
		MOD_DAMAGE_DONE_PCT			=	1033,
		BYT							=	1040,
		AMMO_ID						=	1041,
		PVP_MEDALS					=	1042,
		BUYBACK_ITEM_ID				=	1043,
		BUYBACK_RANDOM_PROPERTIES_ID=	1044,
		BUYBACK_SEED				=	1045,
		BUYBACK_PRICE				=	1046,
		BUYBACK_DURABILITY			=	1047,
		BUYBACK_COUNT				=	1048,
		PADDING						=	1049,
		MAX							=	1050,
		MAX_NOTCLIENT=200
	}
	#endregion

	#region enum GAMEOBJECTFIELDS
	public enum GAMEOBJECTFIELDS
	{
		DISPLAYID	=	6	,
		FLAGS		=	7	,
		ROTATION	=	8	,
		//		ROTATION01	=	9	,
		//		ROTATION02	=	10	,
		//		ROTATION03	=	11	,
		STATE		=	12	,
		TIMESTAMP	=	13	,
		POS_X		=	14	,
		POS_Y		=	15	,
		POS_Z		=	16	,
		FACING		=	17	,
		DYN_FLAGS	=	18	,
		FACTION		=	19	,
		TYPE_ID		=	20	,
		LEVEL		=	21	,

		MAX = 22,  //worth a shot - Phaze
	}
	#endregion

	#region enum DYNAMICOBJECTFIELDS
	public enum DYNAMICOBJECTFIELDS
	{	/*
		CASTER = 6,
		BYTES = 8,
		SPELLID = 9,
		RADIUS = 10,
		POS_X = 11,
		POS_Y = 12,
		POS_Z = 13,
		FACING = 14,
		PADDING = 15,
		MAX = 16,
		*/
		CASTER = 22,
		BYTES = 24,
		SPELLID = 25,
		RADIUS = 26,
		POS_X = 27,
		POS_Y = 28,
		POS_Z = 29,
		FACING = 30,
		PADDING = 31,
		MAX = 32,

	}
	#endregion

	#region enum CORPSEFIELDS
	public enum CORPSEFIELDS
	{/*
		OWNER = 6,
		FACING = 8,
		POS_X = 9,
		POS_Y = 10,
		POS_Z = 11,
		DISPLAYID = 12,
		ITEM0 = 13,
		BYTES_1 = 32,
		BYTES_2 = 33,
		GUILD = 34,
		FLAGS = 35,
		MAX = 36
		*/
		OWNER	= 22,
		FACING	= 24,
		POS_X	= 25,
		POS_Y	= 26,
		POS_Z	= 27,
		DISPLAYID = 28,
		ITEM0	= 29,
		ITEM1	= 30,
		ITEM2	= 31,
		ITEM3	= 32,
		ITEM4	= 33,
		BYTES_1 = 48,
		BYTES_2 = 49,
		GUILD	= 50,
		FLAGS	= 51,
		MAX		= 52

	}
	#endregion

	#region enum POWERTYPE
	public enum POWERTYPE : byte
	{
		MANA,
		RAGE,
		FOCUS,
		ENERGY,
	}
	#endregion

	#region enum RACE
	public enum RACE : byte
	{
		HUMAN = 1,
		ORC = 2,
		DWARF = 3,
		NIGHTELF = 4,
		UNDEAD = 5,
		TAUREN = 6,
		GNOME = 7,
		TROLL = 8,
		GOBLIN = 0,
		MAX = 9
	}
	#endregion

	#region enum CLASS
	public enum CLASS : byte
	{
		WARRIOR = 1,
		PALADIN = 2,
		HUNTER = 3,
		ROGUE = 4,
		PRIEST = 5,
		SHAMAN = 7,
		MAGE = 8,
		WARLOCK = 9,
		DRUID = 11,
	}
	#endregion

	#region enum GUILDRANK
	public enum GUILDRANK : uint
	{
		GM,
		OFFICER,
		VETERAN,
		MEMBER,
		INITIATE
	}
	#endregion
	
	#region enum ACCESSLEVEL
	public enum ACCESSLEVEL : byte
	{
		BANNED=0,
		NORMAL=2,
		TEMPGM=5,
		GM=6,
		ADMIN=9,
	}
	#endregion

	#region enum FRIEND
	public enum FRIEND : int
	{

		DB_ERROR = 0,  
		LIST_FULL = 1, 
		ONLINE = 2, 
		OFFLINE = 3, 
		NOT_FOUND = 4,  
		REMOVED =5, 
		ADDED_ONLINE = 6, 
		ADDED_OFFLINE = 7,
		ALREADY = 8, 
		SELF = 9, 
		ENEMY = 0xA, 
		IGNORE_FULL = 0xB, 
		IGNORE_SELF = 0xC, 
		IGNORE_NOT_FOUND = 0xD, 
		IGNORE_ALREADY = 0xE, 
		IGNORE_ADDED = 0xF, 
		IGNORE_REMOVED = 0x10

	}
	#endregion

	#region enum FACTION
	public enum FACTION : int
	{
		NEUTRAL = 0,
		HUMAN = 1,
		ORC = 2,
		DWARF = 3,
		NIGHTELF = 4,
		UNDEAD = 5,
		TAUREN = 6,
		CREATURE = 7,
		GNOME = 8,
		TROLL = 9,
		MONSTER = 14
	}
	#endregion

	#region enum SCRMSG
	public enum SCRMSG : int
	{
		SPAWN			=	0x01,
		SPAWNCIRCLE		=	0x02,
		ACCESSUPDATE	=	0x03,
		ZONEUPDATE		=	0X04,
		BUYITEM			=	0X05,
		SELECTION		=	0X06,
		GUILDUPDATE		=	0X07,
		GROUPCREATE		=	0X08,
		TRADEMONEY		=	0x09,
		TAKETAXI		=	0x10
	}
	#endregion

	#region enum WORLDTEXTTYPE
	public enum WORLDTEXTTYPE : int
	{
		WT_DAMAGE                        =0x0,
		WT_ABSORB                        =0x1,
		WT_CRIT                          =0x2,
		WT_HEALSPELL                     =0x3,
		WT_MISS                          =0x4,
		WT_XPGAIN                        =0x5,
		WT_QUEST                         =0x6,
	}
	#endregion

	#region enum GERR
	public enum GERR : int
	{
		GERR_INV_FULL                   = 0x0,
		GERR_CANT_EQUIP_LEVEL_I         = 0x1,
		GERR_CANT_EQUIP_SKILL           = 0x2,
		GERR_CANT_EQUIP_EVER            = 0x3,
		GERR_PROFICIENCY_NEEDED         = 0x4,
		GERR_WRONG_SLOT                 = 0x5,
		GERR_BAG_FULL                   = 0x6,
		GERR_DESTROY_NONEMPTY_BAG       = 0x7,
		GERR_BAG_IN_BAG                 = 0x8,
		GERR_AMMO_ONLY                  = 0x9,
		GERR_NO_SLOT_AVAILABLE          = 0xA,
		GERR_WRONG_BAG_TYPE             = 0xB,
		GERR_ITEM_MAX_COUNT             = 0xC,
		GERR_NOT_EQUIPPABLE             = 0xD,
		GERR_CANT_STACK                 = 0xE,
		GERR_CANT_SWAP                  = 0xF,
		GERR_SLOT_EMPTY                  =0x10,
		GERR_ITEM_NOT_FOUND              =0x11,
		GERR_TOO_FEW_TO_SPLIT            =0x12,
		GERR_SPLIT_FAILED                =0x13,
		GERR_NOT_ENOUGH_GOLD             =0x14,
		GERR_NOT_A_BAG                   =0x15,
		GERR_NOT_OWNER                   =0x16,
		GERR_ONLY_ONE_QUIVER             =0x17,
		GERR_NO_BANK_SLOT                =0x18,
		GERR_NO_BANK_HERE                =0x19,
		GERR_ITEM_LOCKED                 =0x1A,
		GERR_2HANDED_EQUIPPED            =0x1B,
		GERR_VENDOR_NOT_INTERESTED       =0x1C,
		GERR_VENDOR_HATES_YOU            =0x1D,
		GERR_VENDOR_SOLD_OUT             =0x1E,
		GERR_VENDOR_TOO_FAR              =0x1F,
		GERR_NOT_ENOUGH_MONEY            =0x20,
		GERR_RECEIVE_ITEM_S              =0x21,
		GERR_DROP_BOUND_ITEM             =0x22,
		GERR_TRADE_BOUND_ITEM            =0x23,
		GERR_TRADE_QUEST_ITEM            =0x24,
		GERR_TRADE_GROUND_ITEM           =0x25,
		GERR_TRADE_BAG                   =0x26,
		GERR_SPELL_FAILED_S              =0x27,
		GERR_ITEM_COOLDOWN               =0x28,
		GERR_POTION_COOLDOWN             =0x29,
		GERR_FOOD_COOLDOWN               =0x2A,
		GERR_SPELL_COOLDOWN              =0x2B,
		GERR_ABILITY_COOLDOWN            =0x2C,
		GERR_SPELL_ALREADY_KNOWN_S       =0x2D,
		GERR_SKILL_GAINED_S              =0x2E,
		GERR_SKILL_UP_SI                 =0x2F,
		GERR_LEARN_SPELL_S               =0x30,
		GERR_LEARN_ABILITY_S             =0x31,
		GERR_LEARN_RECIPE_S              =0x32,
		GERR_INVITE_PLAYER_S             =0x33,
		GERR_INVITED_TO_GROUP_S          =0x34,
		GERR_ALREADY_IN_GROUP_S          =0x35,
		GERR_PLAYER_BUSY_S               =0x36,
		GERR_NEW_LEADER_S                =0x37,
		GERR_NEW_LEADER_YOU              =0x38,
		GERR_LEFT_GROUP_S                =0x39,
		GERR_LEFT_GROUP_YOU              =0x3A,
		GERR_GROUP_DISBANDED             =0x3B,
		GERR_DECLINE_GROUP_S             =0x3C,
		GERR_JOINED_GROUP_S              =0x3D,
		GERR_UNINVITE_YOU                =0x3E,
		GERR_BAD_PLAYER_NAME_S           =0x3F,
		GERR_NOT_IN_GROUP                =0x40,
		GERR_TARGET_NOT_IN_GROUP_S       =0x41,
		GERR_GROUP_FULL                  =0x42,
		GERR_NOT_LEADER                  =0x43,
		GERR_PLAYER_DIED_S               =0x44,
		GERR_GUILD_CREATE_S              =0x45,
		GERR_GUILD_INVITE_S              =0x46,
		GERR_INVITED_TO_GUILD_SS         =0x47,
		GERR_ALREADY_IN_GUILD_S          =0x48,
		GERR_ALREADY_INVITED_TO_GUILD_S  =0x49,
		GERR_INVITED_TO_GUILD            =0x4A,
		GERR_ALREADY_IN_GUILD            =0x4B,
		GERR_GUILD_ACCEPT                =0x4C,
		GERR_GUILD_DECLINE_S             =0x4D,
		GERR_GUILD_PERMISSIONS           =0x4E,
		GERR_GUILD_JOIN_S                =0x4F,
		GERR_GUILD_FOUNDER_S             =0x50,
		GERR_GUILD_PROMOTE_SS            =0x51,
		GERR_GUILD_DEMOTE_SS             =0x52,
		GERR_GUILD_QUIT_S                =0x53,
		GERR_GUILD_LEAVE_S               =0x54,
		GERR_GUILD_REMOVE_SS             =0x55,
		GERR_GUILD_REMOVE_SELF           =0x56,
		GERR_GUILD_DISBAND_S             =0x57,
		GERR_GUILD_DISBAND_SELF          =0x58,
		GERR_GUILD_LEADER_S              =0x59,
		GERR_GUILD_LEADER_SELF           =0x5A,
		GERR_GUILD_MOTD_S                =0x5B,
		GERR_GUILD_PLAYER_NOT_FOUND_S    =0x5C,
		GERR_GUILD_PLAYER_NOT_IN_GUILD_S =0x5D,
		GERR_GUILD_PLAYER_NOT_IN_GUILD   =0x5E,
		GERR_GUILD_CANT_PROMOTE_S        =0x5F,
		GERR_GUILD_CANT_DEMOTE_S         =0x60,
		GERR_GUILD_NOT_IN_A_GUILD        =0x61,
		GERR_GUILD_INTERNAL              =0x62,
		GERR_GUILD_LEADER_IS_S           =0x63,
		GERR_GUILD_LEADER_CHANGED_SS     =0x64,
		GERR_GUILD_DISBANDED             =0x65,
		GERR_GUILD_NOT_ALLIED            =0x66,
		GERR_GUILD_LEADER_LEAVE          =0x67,
		GERR_GUILD_NAME_INVALID          =0x68,
		GERR_GUILD_NAME_EXISTS_S         =0x69,
		GERR_GUILD_ENTER_NAME            =0x6A,
		GERR_GUILD_NAME_TOO_SHORT        =0x6B,
		GERR_GUILD_NAME_MIXED_LANGUAGES  =0x6C,
		GERR_GUILD_NAME_PROFANE          =0x6D,
		GERR_GUILD_NAME_RESERVED         =0x6E,
		GERR_NO_GUILD_CHARTER            =0x6F,
		GERR_OUT_OF_RANGE                =0x70,
		GERR_PLAYER_DEAD                 =0x71,
		GERR_CLIENT_LOCKED_OUT           =0x72,
		GERR_KILLED_BY_S                 =0x73,
		GERR_LOOT_LOCKED                 =0x74,
		GERR_LOOT_TOO_FAR                =0x75,
		GERR_LOOT_DIDNT_KILL             =0x76,
		GERR_LOOT_BAD_FACING             =0x77,
		GERR_LOOT_NOTSTANDING            =0x78,
		GERR_LOOT_STUNNED                =0x79,
		GERR_LOOT_NO_UI                  =0x7A,
		GERR_QUEST_ACCEPTED_S            =0x7B,
		GERR_QUEST_COMPLETE_S            =0x7C,
		GERR_QUEST_FAILED_S              =0x7D,
		GERR_QUEST_FAILED_BAG_FULL_S     =0x7E,
		GERR_QUEST_FAILED_MAX_COUNT_S    =0x7F,
		GERR_QUEST_FAILED_LOW_LEVEL      =0x80,
		GERR_QUEST_FAILED_MISSING_ITEMS  =0x81,
		GERR_QUEST_REWARD_EXP_I          =0x82,
		GERR_QUEST_REWARD_ITEM_S         =0x83,
		GERR_QUEST_REWARD_MONEY_S        =0x84,
		GERR_QUEST_MUST_CHOOSE           =0x85,
		GERR_QUEST_LOG_FULL              =0x86,
		GERR_COMBAT_DAMAGE_SSI           =0x87,
		GERR_INSPECT_S                   =0x88,
		GERR_CANT_USE_ITEM               =0x89,
		GERR_MUST_EQUIP_ITEM             =0x8A,
		GERR_PASSIVE_ABILITY             =0x8B,
		GERR_2HSKILLNOTFOUND             =0x8C,
		GERR_NO_ATTACK_TARGET            =0x8D,
		GERR_INVALID_ATTACK_TARGET       =0x8E,
		GERR_ATTACK_PACIFIED             =0x8F,
		GERR_ATTACK_DEAD                 =0x90,
		GERR_HUNGER_VERY_LOW             =0x91,
		GERR_HUNGER_LOW                  =0x92,
		GERR_HUNGER_MED                  =0x93,
		GERR_HUNGER_HIGH                 =0x94,
		GERR_HUNGER_SATIATED             =0x95,
		GERR_THIRST_VERY_LOW             =0x96,
		GERR_THIRST_LOW                  =0x97,
		GERR_THIRST_MED                  =0x98,
		GERR_THIRST_HIGH                 =0x99,
		GERR_THIRST_SATIATED             =0x9A,
		GERR_TAXISAMENODE                =0x9B,
		GERR_TAXINOSUCHPATH              =0x9C,
		GERR_TAXIUNSPECIFIEDSERVERERROR  =0x9D,
		GERR_TAXINOTENOUGHMONEY          =0x9E,
		GERR_TAXITOOFARAWAY              =0x9F,
		GERR_TAXINOVENDORNEARBY          =0xA0,
		GERR_TAXINOTVISITED              =0xA1,
		GERR_TAXIPLAYERBUSY              =0xA2,
		GERR_TAXIPLAYERALREADYMOUNTED    =0xA3,
		GERR_TAXIPLAYERSHAPESHIFTED      =0xA4,
		GERR_TAXIPLAYERMOVING            =0xA5,
		GERR_TAXINOPATHS                 =0xA6,
		GERR_NO_REPLY_TARGET             =0xA7,
		GERR_GENERIC_NO_TARGET           =0xA8,
		GERR_INITIATE_TRADE_S            =0xA9,
		GERR_TRADE_REQUEST_S             =0xAA,
		GERR_TRADE_TOO_FAR               =0xAB,
		GERR_TRADE_CANCELLED             =0xAC,
		GERR_TRADE_COMPLETE              =0xAD,
		GERR_TRADE_BAG_FULL              =0xAE,
		GERR_TRADE_TARGET_BAG_FULL       =0xAF,
		GERR_TRADE_MAX_COUNT_EXCEEDED    =0xB0,
		GERR_TRADE_TARGET_MAX_COUNT_EXCEEDED= 0xB1,
		GERR_MOUNT_INVALIDMOUNTEE        =0xB2,
		GERR_MOUNT_TOOFARAWAY            =0xB3,
		GERR_MOUNT_ALREADYMOUNTED        =0xB4,
		GERR_MOUNT_NOTMOUNTABLE          =0xB5,
		GERR_MOUNT_NOTYOURPET            =0xB6,
		GERR_MOUNT_OTHER                 =0xB7,
		GERR_MOUNT_LOOTING               =0xB8,
		GERR_MOUNT_RACECANTMOUNT         =0xB9,
		GERR_MOUNT_SHAPESHIFTED          =0xBA,
		GERR_DISMOUNT_NOPET              =0xBB,
		GERR_DISMOUNT_NOTMOUNTED         =0xBC,
		GERR_DISMOUNT_NOTYOURPET         =0xBD,
		GERR_SPELL_FAILED_TOTEMS         =0xBE,
		GERR_SPELL_FAILED_REAGENTS       =0xBF,
		GERR_SPELL_FAILED_EQUIPPED_ITEM  =0xC0,
		GERR_SPELL_FAILED_EQUIPPED_ITEM_CLASS_S= 0xC1,
		GERR_SPELL_FAILED_SHAPESHIFT_FORM_S =0xC2,
		GERR_BADATTACKFACING             =0xC3,
		GERR_BADATTACKPOS                =0xC4,
		GERR_CHEST_IN_USE                =0xC5,
		GERR_USE_CANT_OPEN               =0xC6,
		GERR_USE_LOCKED                  =0xC7,
		GERR_USE_LOCKED_WITH_ITEM_S      =0xC8,
		GERR_USE_LOCKED_WITH_SPELL_S     =0xC9,
		GERR_USE_LOCKED_WITH_SPELL_KNOWN_SI= 0xCA,
		GERR_USE_TOO_FAR                 =0xCB,
		GERR_USE_BAD_ANGLE               =0xCC,
		GERR_USE_OBJECT_MOVING           =0xCD,
		GERR_USE_SPELL_FOCUS             =0xCE,
		GERR_USE_DESTROYED               =0xCF,
		GERR_CANTATTACK_NOTSTANDING      =0xD0,
		GERR_SET_LOOT_FREEFORALL         =0xD1,
		GERR_SET_LOOT_ROUNDROBIN         =0xD2,
		GERR_SET_LOOT_MASTER             =0xD3,
		GERR_NEW_LOOT_MASTER_S           =0xD4,
		GERR_SPECIFY_MASTER_LOOTER       =0xD5,
		GERR_TAME_FAILED                 =0xD6,
		GERR_CHAT_WHILE_DEAD             =0xD7,
		GERR_NEWTAXIPATH                 =0xD8,
		GERR_NO_PET                      =0xD9,
		GERR_NOTYOURPET                  =0xDA,
		GERR_PET_NOT_RENAMEABLE          =0xDB,
		GERR_NULL_PETNAME                =0xDC,
		GERR_INVALID_PETNAME             =0xDD,
		GERR_QUEST_OBJECTIVE_COMPLETE_S  =0xDE,
		GERR_QUEST_UNKNOWN_COMPLETE      =0xDF,
		GERR_QUEST_ADD_KILL_SII          =0xE0,
		GERR_QUEST_ADD_FOUND_SII         =0xE1,
		GERR_QUEST_ADD_ITEM_SII          =0xE2,
		GERR_CANNOTCREATEDIRECTORY       =0xE3,
		GERR_CANNOTCREATEFILE            =0xE4,
		GERR_PLAYER_WRONG_FACTION        =0xE5,
		GERR_BANKSLOT_FAILED_TOO_MANY    =0xE6,
		GERR_BANKSLOT_INSUFFICIENT_FUNDS =0xE7,
		GERR_BANKSLOT_NOTBANKER          =0xE8,
		GERR_FRIEND_DB_ERROR             =0xE9,
		GERR_FRIEND_LIST_FULL            =0xEA,
		GERR_FRIEND_ADDED_S              =0xEB,
		GERR_FRIEND_ONLINE_S             =0xEC,
		GERR_FRIEND_OFFLINE_S            =0xED,
		GERR_FRIEND_NOT_FOUND            =0xEE,
		GERR_FRIEND_WRONG_FACTION        =0xEF,
		GERR_FRIEND_REMOVED_S            =0xF0,
		GERR_FRIEND_ERROR                =0xF1,
		GERR_FRIEND_ALREADY_S            =0xF2,
		GERR_FRIEND_SELF                 =0xF3,
		GERR_IGNORE_FULL                 =0xF4,
		GERR_IGNORE_SELF                 =0xF5,
		GERR_IGNORE_NOT_FOUND            =0xF6,
		GERR_IGNORE_ALREADY_S            =0xF7,
		GERR_IGNORE_ADDED_S              =0xF8,
		GERR_IGNORE_REMOVED_S            =0xF9,
		GERR_ONLY_ONE_BOLT               =0xFA,
		GERR_ONLY_ONE_AMMO               =0xFB,
		GERR_SPELL_FAILED_EQUIPPED_SPECIFIC_ITEM =0xFC,
		GERR_WRONG_BAG_TYPE_SUBCLASS     =0xFD,
		GERR_CANT_WRAP_STACKABLE         =0xFE,
		GERR_CANT_WRAP_EQUIPPED          =0xFF,
		GERR_CANT_WRAP_WRAPPED           =0x100,
		GERR_CANT_WRAP_BOUND             =0x101,
		GERR_CANT_WRAP_UNIQUE            =0x102,
		GERR_CANT_WRAP_BAGS              =0x103,
		GERR_OUT_OF_MANA                 =0x104,
		GERR_OUT_OF_RAGE                 =0x105,
		GERR_OUT_OF_FOCUS                =0x106,
		GERR_OUT_OF_ENERGY               =0x107,
		GERR_OUT_OF_HEALTH               =0x108,
		GERR_LOOT_GONE                   =0x109,
		GERR_MOUNT_FORCEDDISMOUNT        =0x10A,
		GERR_AUTOFOLLOW_TOO_FAR          =0x10B,
		GERR_UNIT_NOT_FOUND              =0x10C,
		GERR_INVALID_FOLLOW_TARGET       =0x10D,
		GERR_GUILDEMBLEM_SUCCESS         =0x10E,
		GERR_GUILDEMBLEM_INVALID_TABARD_COLORS =0x10F,
		GERR_GUILDEMBLEM_NOGUILD         =0x110,
		GERR_GUILDEMBLEM_COLORSPRESENT   =0x111,
		GERR_GUILDEMBLEM_NOTGUILDMASTER  =0x112,
		GERR_GUILDEMBLEM_NOTENOUGHMONEY  =0x113,
		GERR_GUILDEMBLEM_INVALIDVENDOR   =0x114,
		GERR_SPELL_OUT_OF_RANGE          =0x115,
		GERR_COMMAND_NEEDS_TARGET        =0x116,
		GERR_NOAMMO_S                    =0x117,
		GERR_TOOBUSYTOFOLLOW             =0x118,
		GERR_DUEL_REQUESTED              =0x119,
		GERR_DUEL_CANCELLED              =0x11A,
		GERR_DEATHBINDALREADYBOUND       =0x11B,
		GERR_NOEMOTEWHILERUNNING         =0x11C,
		GERR_ZONE_EXPLORED               =0x11D,
		GERR_ZONE_EXPLORED_XP            =0x11E,
		GERR_INVALID_ITEM_TARGET         =0x11F,
		GERR_IGNORING_YOU_S              =0x120,
		GERR_FISH_NOT_HOOKED             =0x121,
		GERR_FISH_ESCAPED                =0x122,
		GERR_SPELL_FAILED_NOTUNSHEATHED  =0x123,
		GERR_PETITION_SIGNED             =0x124,
		GERR_PETITION_ALREADY_SIGNED     =0x125,
		GERR_PETITION_IN_GUILD           =0x126,
		GERR_PETITION_CREATOR            =0x127,
		GERR_PETITION_NOT_ENOUGH_SIGNATURES =0x128,
		GERR_NONE                        =0x129,
	}
	#endregion

	#region enum NPCSOUND
	public enum NPCSOUND : int
	{
		HELLO                   =0x0,
		GOODBYE                 =0x1,
		PISSED                  =0x2,
		ACK                     =0x3,
	}
	#endregion
	
	#region enum VICTIMSTATE
	public enum VICTIMSTATE : uint
	{ 
		NONE = 0x0, 
		WOUND = 0x1, 
		DODGE = 0x2, 
		PARRY = 0x3, 
		INTERRUPT = 0x4, 
		BLOCK = 0x5, 
		EVADE = 0x6, 
		IMMUNE = 0x7, 
		DEFLECT = 0x8, 
		MAX, 
	}
	#endregion

	#region enum CHANNEL
	public enum CHANNEL : uint
	{ 
		JOIN1 = 0x00,
		LEFT1 = 0x01,
		JOIN2 = 0x02,
		LEFT2 = 0x03,
		WRONGPASS = 0x04,
		NOTON = 0x05,
		NOTMOD = 0x06,
		SETPASS = 0x07,
		OWNER = 0x08,
		ISNOT = 0x09,
		NOTOWNER = 0x0A,
		ISOWNER = 0x0B,
		CHANGEMODE = 0x0C,
		ANNOUNCEON = 0x0D,
		ANNOUNCEOFF = 0x0E,
		MODERATE = 0x0F,
		UNMODERATE = 0x10,
		CANNOTSPEAK = 0x11,
		ISKICKED = 0x12,
		YOUBANNED = 0x13,
		BANNED = 0x14,
		UNBANNED = 0x15,
		ALREADYON = 0x17,
		INVITE = 0x18,
		WRONGALLIANCE = 0x19,
	}
	#endregion

	#region enum CAST_FAILED
	public enum CAST_FAILED : uint
	{
		AFFECTING_COMBAT,
		ALREADY_HAVE_CHARM,
		ALREADY_HAVE_SUMMON, 
		ALREADY_OPEN,
		AURA_BOUNCED,
		BAD_IMPLICIT_TARGETS ,
		BAD_TARGETS ,
		CANT_BE_CHARMED ,
		CANT_STEALTH ,
		CASTER_AURASTATE ,
		CASTER_DEAD ,
		DONT_REPORT ,
		EQUIPPED_ITEM ,
		EQUIPPED_ITEM_CLASS ,
		ERROR ,
		FIZZLE ,
		HUNGER_SATIATED ,
		INTERRUPTED ,
		INTERRUPTED_COMBAT ,
		ITEM_ALREADY_ENCHANTED ,
		ITEM_NOT_FOUND ,
		ITEM_NOT_READY ,
		LEVEL_REQUIREMENT ,
		LINE_OF_SIGHT ,
		LOWLEVEL ,
		LOW_CASTLEVEL ,
		MOVING ,
		NEED_AMMO ,
		NEED_AMMO_POUCH ,
		NEED_EXOTIC_AMMO ,
		NOPATH ,
		NOTSTANDING ,
		NOT_BEHIND ,
		NOT_BEHIND_OR_SIDE ,
		NOT_HERE ,
		NOT_KNOWN ,
		NOT_MOUNTED ,
		NOT_READY ,
		NOT_SHAPESHIFT ,
		NOT_TRADING ,
		NO_AMMO ,
		NO_CHARGES_REMAIN ,
		NO_ENDURANCE ,
		NO_PET ,
		NO_POWER ,
		ONLY_ABOVEWATER ,
		ONLY_DAYTIME ,
		ONLY_INDOORS ,
		ONLY_MOUNTED ,
		ONLY_NIGHTTIME ,
		ONLY_OUTDOORS ,
		ONLY_SHAPESHIFT ,
		ONLY_STEALTHED ,
		ONLY_UNDERWATER ,
		OUT_OF_RANGE ,
		PACIFIED ,
		REAGENTS ,
		REQUIRES_SPELL_FOCUS ,
		SILENCED ,
		SPELL_IN_PROGRESS ,
		SPELL_LEARNED ,
		SPELL_UNAVAILABLE ,
		STUNNED ,
		TARGETS_DEAD ,
		TARGET_AFFECTING_COMBAT ,
		TARGET_AURASTATE ,
		TARGET_ENEMY ,
		TARGET_ENRAGED ,
		TARGET_FRIENDLY ,
		TARGET_IS_PLAYER ,
		TARGET_NOT_DEAD ,
		TARGET_NOT_IN_PARTY ,
		TARGET_NO_POCKETS ,
		THIRST_SATIATED ,
		TOO_CLOSE ,
		TOTEMS ,
		TRY_AGAIN ,
		UNIT_NOT_ATSIDE ,
		UNIT_NOT_BEHIND ,
		UNIT_NOT_INFRONT ,
		NO_MOUNTS_ALLOWED ,
		CHEST_IN_USE ,
		NO_COMBO_POINTS ,
		TARGET_NOT_PLAYER ,
		TARGET_DUELING ,
		NOTUNSHEATHED ,
		NOT_FISHABLE ,
		NUMREASONS ,
	}
	#endregion

	#region enum GUILDRESULT
	public enum GUILDRESULT : int
	{
		SUCCESS						=	0,
		INTERNAL					=	1,
		ALREADY_IN_GUILD			=	2,
		ALREADY_IN_GUILD_S			=	3,
		ALREADY_INVITED_TO_GUILD	=	4,
		ALREADY_INVITED_TO_GUILD_S	=	5,
		NAME_INVALID				=	6,
		NAME_EXISTS					=	7,
		PERMISSIONS					=	8,
		PLAYER_NOT_IN_GUILD			=	9,
		PLAYER_NOT_IN_GUILD_S		=	10,
		PLAYER_NOT_FOUND			=	11,
		NOT_ALLIED					=	12,
		RANK_TO_HIGH				=	13,
		RANK_TO_LOW					=	14,
		TEMP_GUILD_ERROR			=	17,
		RANK_IN_USE					=	18
	}
	#endregion

	#region enum GUILDFLAGS
	public enum GUILDFLAGS : uint
	{
		LISTEN						=	1,
		SAY							=	2,
		OFFICER_LISTEN				=	4,
		OFFICER_SAY					=	8,
		INVITE						=	16,
		REMOVE						=	32,
		PROMOTE						=	128,
		DEMOTE						=	256,
		SET_MOTD					=	4096,
		PUBLIC_NOTE_EDIT			=	8192,
		OFFICER_NOTE_VIEW			=	16384,
		OFFICER_NOTE_EDIT			=	32768
	}
	#endregion
}


