//  Script Made by BRDDY311 on 7/28/05

using Server;
namespace Server.Items
{
public class CatFamilyLoots
	{
		public static Loot[] Araga = new Loot[] {  new Loot( typeof( KnightsCloak ), 5.3f )
								, new Loot( typeof( DurableTunic ), 5.3f )
								, new Loot( typeof( PhalanxLeggings ), 5.3f )
								, new Loot( typeof( LargeFang ), 10.7f )
								, new Loot( typeof( BristlyWhisker ), 16f )
								, new Loot( typeof( RetractableClaw ), 5.3f )
								};
		public static Loot[] Bhagthera = new Loot[] {  new Loot( typeof( FangOfBhagthera ), 60.8f )
								, new Loot( typeof( LargeFang ), 2.55f )
								, new Loot( typeof( TigerMeat ), 25.5f )
								, new Loot( typeof( BristlyWhisker ), 5.5f )
								, new Loot( typeof( LongSoftTail ), 20.1f )
								};
		public static Loot[] BloodscalpTiger = new Loot[] {  new Loot( typeof( BloodscalpEar ), 0.01f )
								, new Loot( typeof( BloodscalpTusk ), 0.01f )
								, new Loot( typeof( BloodyBoneNecklace ), 0.01f )
								, new Loot( typeof( TheFourthTrollLegend ), 0.01f )
								, new Loot( typeof( TigerMeat ), 0.01f )
								};
		public static Loot[] BrokenTooth = new Loot[] {  new Loot( typeof( ConjurersVest ), 4.2f )
								, new Loot( typeof( TwilightGloves ), 4.2f )
								, new Loot( typeof( WickedClaw ), 3f )
								, new Loot( typeof( LongSoftTail ), 19.7f )
								, new Loot( typeof( SabertoothFang ), 9.6f )
								};
		public static Loot[] CragStalker = new Loot[] {  new Loot( typeof( SharpClaw ), 3.9f )
								, new Loot( typeof( BrightEyeball ), 39.4f )
								, new Loot( typeof( TornFurryEar ), 5.4f )
								};
		public static Loot[] Dishu = new Loot[] {  new Loot( typeof( CadetLeggings ), 4.2f )
								, new Loot( typeof( DisciplesVest ), 5.2f )
								, new Loot( typeof( InfantryTunic ), 4.5f )
								, new Loot( typeof( BardsCloak ), 3.1f )
								, new Loot( typeof( CadetBelt ), 2.6f )
								, new Loot( typeof( CadetBoots ), 4f )
								, new Loot( typeof( CadetGauntlets ), 4.4f )
								, new Loot( typeof( GypsyGloves ), 4.4f )
								, new Loot( typeof( SavannahLionTusk ), 4.2f )
								, new Loot( typeof( SimpleGloves ), 3.5f )
								, new Loot( typeof( SmallFurryPaw ), 14.8f )
								, new Loot( typeof( SmallLeatherCollar ), 8f )
								};
		public static Loot[] DurotarTiger = new Loot[] {  new Loot( typeof( DurotarTigerFur ), 34f )
								, new Loot( typeof( DiscoloredFang ), 42.2f )
								, new Loot( typeof( SmallLeatherCollar ), 14.1f )
								};
		public static Loot[] Duskstalker = new Loot[] {  new Loot( typeof( InfantryCloak ), 12.3f )
								, new Loot( typeof( PioneerBelt ), 3f )
								, new Loot( typeof( PioneerCloak ), 17.4f )
								, new Loot( typeof( DiscoloredFang ), 48f )
								, new Loot( typeof( SmallLeatherCollar ), 20f )
								};
		public static Loot[] Echeyakee = new Loot[] {  new Loot( typeof( EcheyakeesHide ), 80.2f )
								, new Loot( typeof( LionMeat ), 19.4f )
								, new Loot( typeof( SmallFurryPaw ), 5.4f )
								, new Loot( typeof( ThinBlackClaw ), 17.3f )
								};
		public static Loot[] ElderNightsaber = new Loot[] {  new Loot( typeof( DiscoloredFang ), 50f )
								, new Loot( typeof( SmallLeatherCollar ), 16.7f )
								};
		public static Loot[] ElderShadowmawPanther = new Loot[] {  new Loot( typeof( LongSoftTail ), 23.8f )
								, new Loot( typeof( SabertoothFang ), 10.2f )
								};
		public static Loot[] ElderStranglethornTiger = new Loot[] {  new Loot( typeof( LargeFang ), 2.8f )
								, new Loot( typeof( TigerMeat ), 30.9f )
								, new Loot( typeof( BristlyWhisker ), 24.9f )
								, new Loot( typeof( RetractableClaw ), 7.1f )
								};
		public static Loot[] EnragedPanther = new Loot[] {  new Loot( typeof( HypercapacitorGizmo ), 71.9f )
								, new Loot( typeof( SharpClaw ), 3.3f )
								, new Loot( typeof( BrightEyeball ), 31.8f )
								, new Loot( typeof( TornFurryEar ), 5f )
								};
		public static Loot[] FeralMountainLion = new Loot[] {  new Loot( typeof( FreshCarcass ), 4.3f )
								, new Loot( typeof( LionMeat ), 35.2f )
								, new Loot( typeof( MountainLionBlood ), 4.6f )
								, new Loot( typeof( SharpClaw ), 4.7f )
								, new Loot( typeof( BrightEyeball ), 30.2f )
								, new Loot( typeof( TornFurryEar ), 4.5f )
								};
		public static Loot[] FeralNightsaber = new Loot[] {  new Loot( typeof( DiscoloredFang ), 56.4f )
								, new Loot( typeof( SmallLeatherCollar ), 18.5f )
								};
		public static Loot[] FlatlandCougar = new Loot[] {  new Loot( typeof( CougarClaws ), 16.1f )
								, new Loot( typeof( DiscoloredFang ), 37.5f )
								, new Loot( typeof( SmallLeatherCollar ), 12.3f )
								};
		public static Loot[] FlatlandProwler = new Loot[] {  new Loot( typeof( FlatlandProwlerClaw ), 12.7f )
								, new Loot( typeof( DiscoloredFang ), 52.1f )
								, new Loot( typeof( SmallLeatherCollar ), 17.4f )
								};
		public static Loot[] Frostsaber = new Loot[] {  new Loot( typeof( TigerMeat ), 29.8f )
								, new Loot( typeof( WickedClaw ), 3.9f )
								, new Loot( typeof( LongSoftTail ), 26.2f )
								, new Loot( typeof( PatchOfFineFur ), 8f )
								, new Loot( typeof( SabertoothFang ), 30.6f )
								, new Loot( typeof( FrostsaberEko ), 1.5f )
								};
		public static Loot[] FrostsaberCub = new Loot[] {  new Loot( typeof( FrostsaberEko ), 2f )
								, new Loot( typeof( TigerMeat ), 28.2f )
								, new Loot( typeof( WickedClaw ), 3.7f )
								, new Loot( typeof( LongSoftTail ), 25f )
								, new Loot( typeof( PatchOfFineFur ), 7.3f )
								, new Loot( typeof( SabertoothFang ), 27.8f )
								};
		public static Loot[] FrostsaberHuntress = new Loot[] {  new Loot( typeof( FrostsaberEko ), 1.8f )
								, new Loot( typeof( TigerMeat ), 29f )
								, new Loot( typeof( WickedClaw ), 3.7f )
								, new Loot( typeof( LongSoftTail ), 25.4f )
								, new Loot( typeof( PatchOfFineFur ), 7.5f )
								, new Loot( typeof( SabertoothFang ), 28.9f )
								};
		public static Loot[] FrostsaberPrideWatcher = new Loot[] {  new Loot( typeof( FrostsaberEko ), 1.9f )
								, new Loot( typeof( SacredFrostsaberMeat ), 1f )
								, new Loot( typeof( TigerMeat ), 28.7f )
								, new Loot( typeof( WickedClaw ), 3.3f )
								, new Loot( typeof( LongSoftTail ), 24.9f )
								, new Loot( typeof( PatchOfFineFur ), 7.6f )
								, new Loot( typeof( SabertoothFang ), 28.4f )
								};
		public static Loot[] FrostsaberStalker = new Loot[] {  new Loot( typeof( FrostsaberEko ), 1.8f )
								, new Loot( typeof( SacredFrostsaberMeat ), 0.7f )
								, new Loot( typeof( TigerMeat ), 29.6f )
								, new Loot( typeof( WickedClaw ), 3.7f )
								, new Loot( typeof( LongSoftTail ), 26.2f )
								, new Loot( typeof( PatchOfFineFur ), 7.95f )
								, new Loot( typeof( SabertoothFang ), 29.4f )
								};
		public static Loot[] HulkingMountainLion = new Loot[] {  new Loot( typeof( FreshCarcass ), 2.2f )
								, new Loot( typeof( LargeFang ), 2.9f )
								, new Loot( typeof( LionMeat ), 41.7f )
								, new Loot( typeof( BristlyWhisker ), 22.8f )
								, new Loot( typeof( RetractableClaw ), 6.4f )
								};
		public static Loot[] HumarThePridelord = new Loot[] {  new Loot( typeof( DefenderBoots ), 3.1f )
								, new Loot( typeof( DefenderBracers ), 3.1f )
								, new Loot( typeof( DefenderGauntlets ), 5f )
								, new Loot( typeof( DefenderLeggings ), 5.6f )
								, new Loot( typeof( FortifiedBelt ), 3.1f )
								, new Loot( typeof( GreenweaveMantle ), 5f )
								, new Loot( typeof( GreenweaveRobe ), 3.1f )
								, new Loot( typeof( GreenweaveVest ), 4.3f )
								, new Loot( typeof( ScoutingGloves ), 5f )
								, new Loot( typeof( LinenCloth ), 6.8f )
								, new Loot( typeof( LionMeat ), 24.8f )
								, new Loot( typeof( SavannahLionTusk ), 2.5f )
								, new Loot( typeof( ScoutingSpaulders ), 4.3f )
								, new Loot( typeof( ShimmeringAmice ), 3.1f )
								, new Loot( typeof( SilkCloth ), 1.2f )
								, new Loot( typeof( WoolCloth ), 15.5f )
								, new Loot( typeof( ThinBlackClaw ), 15.5f )
								, new Loot( typeof( TornFurryEar ), 61.5f )
								};
		public static Loot[] JagueroStalker = new Loot[] {  new Loot( typeof( PatchOfFineFur ), 13.5f )
								, new Loot( typeof( WickedClaw ), 4.1f )
								, new Loot( typeof( SabertoothFang ), 32f )
								};
		public static Loot[] JuvenileSnowLeopard = new Loot[] {  new Loot( typeof( DiscoloredFang ), 36.8f )
								, new Loot( typeof( SmallLeatherCollar ), 12.3f )
								};
		public static Loot[] KingBangalash = new Loot[] {  new Loot( typeof( HeadOfBangalash ), 54.2f )
								, new Loot( typeof( TigerMeat ), 24.4f )
								, new Loot( typeof( PatchOfFineFur ), 10f )
								, new Loot( typeof( SabertoothFang ), 23.6f )
								};
		public static Loot[] KurzenWarPanther = new Loot[] {  new Loot( typeof( LargeFang ), 2.8f )
								, new Loot( typeof( BristlyWhisker ), 28.9f )
								, new Loot( typeof( RetractableClaw ), 9f )
								};
		public static Loot[] KurzenWarTiger = new Loot[] {  new Loot( typeof( LargeFang ), 2.7f )
								, new Loot( typeof( TigerMeat ), 30.5f )
								, new Loot( typeof( BristlyWhisker ), 25.9f )
								, new Loot( typeof( RetractableClaw ), 8.6f )
								};
		public static Loot[] MangyNightsaber = new Loot[] {  new Loot( typeof( BrokenFang ), 41.8f )
								, new Loot( typeof( ChippedClaw ), 41.7f )
								, new Loot( typeof( RuinedPelt ), 41f )
								, new Loot( typeof( BatteredBuckler ), 1.2f )
								, new Loot( typeof( BentLargeShield ), 1.2f )
								, new Loot( typeof( FlimsyChainBelt ), 1f )
								, new Loot( typeof( FlimsyChainBoots ), 1f )
								, new Loot( typeof( FlimsyChainBracers ), 1f )
								, new Loot( typeof( FlimsyChainCloak ), 1.1f )
								, new Loot( typeof( FlimsyChainGloves ), 1f )
								, new Loot( typeof( FlimsyChainPants ), 1.1f )
								, new Loot( typeof( FlimsyChainVest ), 1f )
								, new Loot( typeof( FrayedBelt ), 1.5f )
								, new Loot( typeof( FrayedBracers ), 1.5f )
								, new Loot( typeof( FrayedCloak ), 1.5f )
								, new Loot( typeof( FrayedGloves ), 1.5f )
								, new Loot( typeof( FrayedPants ), 1.6f )
								, new Loot( typeof( FrayedRobe ), 1.5f )
								, new Loot( typeof( FrayedShoes ), 1.4f )
								, new Loot( typeof( RaggedCloak ), 1.3f )
								, new Loot( typeof( RaggedLeatherBelt ), 1.3f )
								, new Loot( typeof( RaggedLeatherBoots ), 1.3f )
								, new Loot( typeof( RaggedLeatherBracers ), 1.2f )
								, new Loot( typeof( RaggedLeatherGloves ), 1.3f )
								, new Loot( typeof( RaggedLeatherPants ), 1.4f )
								, new Loot( typeof( RaggedLeatherVest ), 1.4f )
								};
		public static Loot[] Moonstalker = new Loot[] {  new Loot( typeof( MoonstalkerFang ), 11.8f )
								, new Loot( typeof( SmallFurryPaw ), 25.8f )
								, new Loot( typeof( SmallLeatherCollar ), 7.4f )
								};
		public static Loot[] MoonstalkerMatriarch = new Loot[] {  new Loot( typeof( FineMoonstalkerPelt ), 22.5f )
								, new Loot( typeof( MoonstalkerFang ), 1.3f )
								, new Loot( typeof( SharpClaw ), 2.5f )
								, new Loot( typeof( SmallFurryPaw ), 9.4f )
								, new Loot( typeof( ThinBlackClaw ), 32.8f )
								};
		public static Loot[] MoonstalkerRunt = new Loot[] {  new Loot( typeof( MoonstalkerFang ), 6.1f )
								, new Loot( typeof( SmallFurryPaw ), 15.1f )
								, new Loot( typeof( SmallLeatherCollar ), 4.2f )
								};
		public static Loot[] MoonstalkerSire = new Loot[] {  new Loot( typeof( FineMoonstalkerPelt ), 22.6f )
								, new Loot( typeof( MoonstalkerFang ), 0.9f )
								, new Loot( typeof( SharpClaw ), 1.8f )
								, new Loot( typeof( SmallFurryPaw ), 7f )
								, new Loot( typeof( ThinBlackClaw ), 25f )
								};
		public static Loot[] MountainCougar = new Loot[] {  new Loot( typeof( MountainCougarPelt ), 66.7f )
								, new Loot( typeof( BatteredBuckler ), 1.2f )
								, new Loot( typeof( BentLargeShield ), 1.3f )
								, new Loot( typeof( BrokenFang ), 41.5f )
								, new Loot( typeof( ChippedClaw ), 41.3f )
								, new Loot( typeof( FlimsyChainBelt ), 1.1f )
								, new Loot( typeof( FlimsyChainBoots ), 1.1f )
								, new Loot( typeof( FlimsyChainBracers ), 1f )
								, new Loot( typeof( FlimsyChainCloak ), 1.1f )
								, new Loot( typeof( FlimsyChainGloves ), 1.1f )
								, new Loot( typeof( FlimsyChainPants ), 1.1f )
								, new Loot( typeof( FlimsyChainVest ), 1.1f )
								, new Loot( typeof( FrayedBelt ), 1.4f )
								, new Loot( typeof( FrayedBracers ), 1.5f )
								, new Loot( typeof( FrayedCloak ), 1.5f )
								, new Loot( typeof( FrayedGloves ), 1.6f )
								, new Loot( typeof( FrayedPants ), 1.5f )
								, new Loot( typeof( FrayedRobe ), 1.5f )
								, new Loot( typeof( FrayedShoes ), 1.5f )
								, new Loot( typeof( RaggedCloak ), 1.3f )
								, new Loot( typeof( RaggedLeatherBelt ), 1.3f )
								, new Loot( typeof( RaggedLeatherBoots ), 1.3f )
								, new Loot( typeof( RaggedLeatherBracers ), 1.3f )
								, new Loot( typeof( RaggedLeatherGloves ), 1.4f )
								, new Loot( typeof( RaggedLeatherPants ), 1.4f )
								, new Loot( typeof( RaggedLeatherVest ), 1.3f )
								, new Loot( typeof( RuinedPelt ), 41.2f )
								};
		public static Loot[] MountainLion = new Loot[] {  new Loot( typeof( FreshCarcass ), 2.5f )
								, new Loot( typeof( LargeFang ), 2.8f )
								, new Loot( typeof( LionMeat ), 40.1f )
								, new Loot( typeof( BristlyWhisker ), 19f )
								, new Loot( typeof( RetractableClaw ), 5.3f )
								};
		public static Loot[] MountainLionMother = new Loot[] {};
		public static Loot[] NeedlesCougar = new Loot[] {  new Loot( typeof( SharpClaw ), 4.7f )
								, new Loot( typeof( BrightEyeball ), 49.3f )
								, new Loot( typeof( TornFurryEar ), 7.2f )
								};
		public static Loot[] Nightsaber = new Loot[] {  new Loot( typeof( NightsaberFang ), 12.6f )
								, new Loot( typeof( DiscoloredFang ), 31f )
								, new Loot( typeof( SmallLeatherCollar ), 10.4f )
								};
		public static Loot[] NightsaberStalker = new Loot[] {  new Loot( typeof( NightsaberFang ), 0.75f )
								, new Loot( typeof( DiscoloredFang ), 37.2f )
								, new Loot( typeof( SmallLeatherCollar ), 11.9f )
								};
		public static Loot[] Panther = new Loot[] {  new Loot( typeof( LargeFang ), 3f )
								, new Loot( typeof( WickedClaw ), 1.1f )
								, new Loot( typeof( BristlyWhisker ), 28.2f )
								, new Loot( typeof( RetractableClaw ), 8f )
								};
		public static Loot[] Rakshiri = new Loot[] {  new Loot( typeof( TigerMeat ), 32.6f )
								, new Loot( typeof( LongSoftTail ), 30.4f )
								, new Loot( typeof( PatchOfFineFur ), 9.2f )
								, new Loot( typeof( SabertoothFang ), 32.3f )
								};
		public static Loot[] RidgeHuntress = new Loot[] {  new Loot( typeof( LargeFang ), 4.8f )
								, new Loot( typeof( TigerMeat ), 36.4f )
								, new Loot( typeof( WickedClaw ), 1.9f )
								, new Loot( typeof( BristlyWhisker ), 7.2f )
								, new Loot( typeof( LongSoftTail ), 26f )
								};
		public static Loot[] RidgeStalker = new Loot[] {  new Loot( typeof( LargeFang ), 4f )
								, new Loot( typeof( TigerMeat ), 35f )
								, new Loot( typeof( WickedClaw ), 1f )
								, new Loot( typeof( BristlyWhisker ), 5.4f )
								, new Loot( typeof( LongSoftTail ), 19.4f )
								};
		public static Loot[] RidgeStalkerPatriarch = new Loot[] {  new Loot( typeof( TigerMeat ), 39f )
								, new Loot( typeof( WickedClaw ), 3.1f )
								, new Loot( typeof( LongSoftTail ), 27.7f )
								, new Loot( typeof( SabertoothFang ), 11.6f )
								};
		public static Loot[] SavannahCub = new Loot[] {};
		public static Loot[] SavannahHighmane = new Loot[] {  new Loot( typeof( SavannahLionTusk ), 4.7f )
								, new Loot( typeof( SharpClaw ), 1f )
								, new Loot( typeof( SmallFurryPaw ), 16.3f )
								, new Loot( typeof( SmallLeatherCollar ), 4.6f )
								};
		public static Loot[] SavannahHuntress = new Loot[] {  new Loot( typeof( SavannahLionTusk ), 4.7f )
								, new Loot( typeof( SharpClaw ), 1f )
								, new Loot( typeof( SmallFurryPaw ), 16.3f )
								, new Loot( typeof( SmallLeatherCollar ), 4.6f )
								};
		public static Loot[] SavannahMatriarch = new Loot[] {  new Loot( typeof( SavannahLionTusk ), 1.8f )
								, new Loot( typeof( SharpClaw ), 2.1f )
								, new Loot( typeof( SmallFurryPaw ), 7.7f )
								, new Loot( typeof( ThinBlackClaw ), 27.6f )
								};
		public static Loot[] SavannahPatriarch = new Loot[] {  new Loot( typeof( SavannahLionTusk ), 2.9f )
								, new Loot( typeof( SharpClaw ), 1.9f )
								, new Loot( typeof( SmallFurryPaw ), 24f )
								, new Loot( typeof( SmallLeatherCollar ), 6.3f )
								};
		public static Loot[] SavannahProwler = new Loot[] {  new Loot( typeof( SavannahLionTusk ), 6.6f )
								, new Loot( typeof( SharpClaw ), 0.8f )
								, new Loot( typeof( SmallFurryPaw ), 18.2f )
								, new Loot( typeof( SmallLeatherCollar ), 5.3f )
								};
		public static Loot[] ShadowPanther = new Loot[] {  new Loot( typeof( LargeFang ), 5f )
								, new Loot( typeof( ShadowPantherHeart ), 6.4f )
								, new Loot( typeof( WickedClaw ), 1.7f )
								, new Loot( typeof( BristlyWhisker ), 8f )
								, new Loot( typeof( LongSoftTail ), 27.8f )
								};
		public static Loot[] Shadowclaw = new Loot[] {  new Loot( typeof( CadetLeggings ), 2.9f )
								, new Loot( typeof( DisciplesPants ), 2.2f )
								, new Loot( typeof( DisciplesRobe ), 5.1f )
								, new Loot( typeof( DisciplesVest ), 3.9f )
								, new Loot( typeof( InfantryTunic ), 3.2f )
								, new Loot( typeof( PioneerTunic ), 3.0f )
								, new Loot( typeof( BardsCloak ), 2.5f )
								, new Loot( typeof( CadetBelt ), 2.1f )
								, new Loot( typeof( CadetBoots ), 4.3f )
								, new Loot( typeof( CadetGauntlets ), 6.6f )
								, new Loot( typeof( GypsyBands ), 1.5f )
								, new Loot( typeof( GypsyGloves ), 3.8f )
								, new Loot( typeof( GypsySandals ), 2.2f )
								, new Loot( typeof( GypsySash ), 2.2f )
								, new Loot( typeof( MoonstalkerFang ), 7.4f )
								, new Loot( typeof( SimpleBands ), 1.4f )
								, new Loot( typeof( SimpleCord ), 2.8f )
								, new Loot( typeof( SimpleGloves ), 4f )
								, new Loot( typeof( SimpleShoes ), 2.1f )
								, new Loot( typeof( SoldiersCloak ), 3.1f )
								, new Loot( typeof( SmallFurryPaw ), 27f )
								, new Loot( typeof( SmallLeatherCollar ), 6.1f )
								};
		public static Loot[] ShadowmawPanther = new Loot[] {  new Loot( typeof( LargeFang ), 3.8f )
								, new Loot( typeof( ShadowmawClaw ), 13.1f )
								, new Loot( typeof( BristlyWhisker ), 6.3f )
								, new Loot( typeof( LongSoftTail ), 22f )
								};
		public static Loot[] ShyRotam = new Loot[] {  new Loot( typeof( TigerMeat ), 31.5f )
								, new Loot( typeof( WickedClaw ), 2.9f )
								, new Loot( typeof( LongSoftTail ), 25.2f )
								, new Loot( typeof( PatchOfFineFur ), 9.7f )
								, new Loot( typeof( SabertoothFang ), 27.2f )
								};
		public static Loot[] SianRotam = new Loot[] {  new Loot( typeof( SabertoothFang ), 28.9f )
								, new Loot( typeof( PatchOfFineFur ), 8f )
								, new Loot( typeof( LongSoftTail ), 20.5f )
								, new Loot( typeof( WickedClaw ), 3.5f )
								, new Loot( typeof( TigerMeat ), 35.1f )
								};
		public static Loot[] SinDall = new Loot[] {  new Loot( typeof( LargeFang ), 3.2f )
								, new Loot( typeof( TigerMeat ), 28f )
								, new Loot( typeof( WickedClaw ), 0.8f )
								, new Loot( typeof( BristlyWhisker ), 5f )
								, new Loot( typeof( LongSoftTail ), 18.6f )
								};
		public static Loot[] SkullsplitterPanther = new Loot[] {  new Loot( typeof( LargeFang ), 3f )
								, new Loot( typeof( SkullsplitterTusk ), 3f )
								, new Loot( typeof( LongSoftTail ), 10f )
								};
		public static Loot[] SnowLeopard = new Loot[] {  new Loot( typeof( Malachite ), 0.6f )
								, new Loot( typeof( DiscoloredFang ), 46f )
								, new Loot( typeof( SmallLeatherCollar ), 15.3f )
								};
		public static Loot[] StarvingMountainLion = new Loot[] {  new Loot( typeof( FreshCarcass ), 2.5f )
								, new Loot( typeof( LionMeat ), 29.4f )
								, new Loot( typeof( MountainLionBlood ), 16.6f )
								, new Loot( typeof( SharpClaw ), 3.5f )
								, new Loot( typeof( ThinBlackClaw ), 9.9f )
								, new Loot( typeof( TornFurryEar ), 35f )
								};
		public static Loot[] StranglethornTiger = new Loot[] {  new Loot( typeof( LargeFang ), 2.9f )
								, new Loot( typeof( TigerMeat ), 30f )
								, new Loot( typeof( WickedClaw ), 1f )
								, new Loot( typeof( BristlyWhisker ), 26.2f )
								, new Loot( typeof( RetractableClaw ), 7.5f )
								};
		public static Loot[] StranglethornTigress = new Loot[] {  new Loot( typeof( LargeFang ), 3.6f )
								, new Loot( typeof( TigerMeat ), 32.9f )
								, new Loot( typeof( WickedClaw ), 0.9f )
								, new Loot( typeof( BristlyWhisker ), 5.9f )
								, new Loot( typeof( LongSoftTail ), 20.8f )
								};
		public static Loot[] SwampJaguar = new Loot[] {  new Loot( typeof( LargeFang ), 4.7f )
								, new Loot( typeof( WickedClaw ), 1.2f )
								, new Loot( typeof( BristlyWhisker ), 6.6f )
								, new Loot( typeof( LongSoftTail ), 23.1f )
								};
		public static Loot[] TheRake = new Loot[] {  new Loot( typeof( LionfurArmor ), 56.6f )
								, new Loot( typeof( DiscoloredFang ), 54.7f )
								, new Loot( typeof( SmallLeatherCollar ), 18.7f )
								};
		public static Loot[] TwilightRunner = new Loot[] {  new Loot( typeof( SharpClaw ), 3.6f )
								, new Loot( typeof( TwilightWhisker ), 24.7f )
								, new Loot( typeof( ThinBlackClaw ), 10.8f )
								, new Loot( typeof( TornFurryEar ), 37.1f )
								};
		public static Loot[] YoungNightsaber = new Loot[] {  new Loot( typeof( BatteredBuckler ), 1.3f )
								, new Loot( typeof( BentLargeShield ), 1.3f )
								, new Loot( typeof( BrokenFang ), 41.6f )
								, new Loot( typeof( ChippedClaw ), 41.6f )
								, new Loot( typeof( FlimsyChainBelt ), 1.1f )
								, new Loot( typeof( FlimsyChainBoots ), 1.1f )
								, new Loot( typeof( FlimsyChainBracers ), 1.1f )
								, new Loot( typeof( FlimsyChainCloak ), 1.1f )
								, new Loot( typeof( FlimsyChainGloves ), 1.1f )
								, new Loot( typeof( FlimsyChainPants ), 1.1f )
								, new Loot( typeof( FlimsyChainVest ), 1.1f )
								, new Loot( typeof( FrayedBelt ), 1.4f )
								, new Loot( typeof( FrayedBracers ), 1.6f )
								, new Loot( typeof( FrayedCloak ), 1.6f )
								, new Loot( typeof( FrayedGloves ), 1.6f )
								, new Loot( typeof( FrayedPants ), 1.6f )
								, new Loot( typeof( FrayedRobe ), 1.6f )
								, new Loot( typeof( FrayedShoes ), 1.6f )
								, new Loot( typeof( RaggedCloak ), 1.3f )
								, new Loot( typeof( RaggedLeatherBelt ), 1.3f )
								, new Loot( typeof( RaggedLeatherBoots ), 1.3f )
								, new Loot( typeof( RaggedLeatherBracers ), 1.3f )
								, new Loot( typeof( RaggedLeatherGloves ), 1.3f )
								, new Loot( typeof( RaggedLeatherPants ), 1.3f )
								, new Loot( typeof( RaggedLeatherVest ), 1.3f )
								, new Loot( typeof( RuinedPelt ), 41.5f )
								};
		public static Loot[] YoungPanther = new Loot[] {  new Loot( typeof( LargeFang ), 2.2f )
								, new Loot( typeof( BristlyWhisker ), 24.2f )
								, new Loot( typeof( RetractableClaw ), 6.9f )
								};
		public static Loot[] YoungStranglethornTiger = new Loot[] {  new Loot( typeof( LargeFang ), 1.8f )
								, new Loot( typeof( TigerMeat ), 27.6f )
								, new Loot( typeof( BristlyWhisker ), 18.3f )
								, new Loot( typeof( RetractableClaw ), 5.2f )
								};

	}
}
