//////////////////////////////////////////////////////////
// DrNexus Advanced RingsAndJewels Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class AdvancedRingsAndJewelsDrops
	{
		public static Loot[]AdvancedRingsAndJewels = new Loot[]
		{
			new Loot( typeof( RingOfPureSilver ), 50f )
				, new Loot( typeof( MinorChannelingRing ), 25f )
				, new Loot( typeof( RingOfTheShadow ), 47.75f )
				, new Loot( typeof( RingOfPrecision ), 11.7f )
				, new Loot( typeof( OgremindRing ), 16f )
				, new Loot( typeof( VoodooBand ), 31.2f )
				, new Loot( typeof( RingOfForlornSpirits ), 40f )
				, new Loot( typeof( BlazingEmblem ), 35f )
				, new Loot( typeof( BlackRose ), 50f )
				, new Loot( typeof( StylishBlackShirt ), 40f )
				, new Loot( typeof( SkullRing ), 50f )
				, new Loot( typeof( BandOfTheUndercity ), 40f )
				, new Loot( typeof( SmottsCompass ), 13.15f )
				, new Loot( typeof( RichPurpleSilkShirt ), 40f )
				, new Loot( typeof( BlackSwashbucklersShirt ), 40f )
				, new Loot( typeof( SeafireBand ), 16.3f )
				, new Loot( typeof( ColdwaterRing ), 16.3f )
				, new Loot( typeof( FireproofOrb ), 19.98f )
				, new Loot( typeof( StrengthOfWill ), 19.98f )
				, new Loot( typeof( OrbOfPower ), 19.98f )
				, new Loot( typeof( GlowingGreenTalisman ), 38.6f )
				, new Loot( typeof( CrystalStarfireMedallion ), 31.45f )
				, new Loot( typeof( MarkOfTheKirinTor ), 27.75f )
				, new Loot( typeof( EmbersparkPendant ), 26.4f )
				, new Loot( typeof( BandOfThorns ), 34.7f )
				, new Loot( typeof( QuicksilverRing ), 38.15f )
				, new Loot( typeof( MindbenderLoop ), 32.15f )
				, new Loot( typeof( InscribedGoldRing ), 27.85f )
				, new Loot( typeof( WelkenRing ), 23.5f )
				, new Loot( typeof( PulsatingHydraHeart ), 37f )
				, new Loot( typeof( EverglowLantern ), 34.7f )
				, new Loot( typeof( SilverlainesFamilySeal ), 34f )
				, new Loot( typeof( SealOfSylvanas ), 17.8f )
				, new Loot( typeof( DeepFathomRing ), 38.9f )
				, new Loot( typeof( SacredBand ), 44.85f )
				, new Loot( typeof( AgamaggansClutch ), 27.35f )
				, new Loot( typeof( SustainingRing ), 41.5f )
				, new Loot( typeof( RingOfCalm ), 38.4f )
				, new Loot( typeof( VermilionBand ), 23.15f )
				, new Loot( typeof( IvoryBand ), 20.65f )
				, new Loot( typeof( ShimmeringStave ), 35.62f )
				, new Loot( typeof( BandOfTheGreatTortoise ), 16.3f )
				, new Loot( typeof( GreenweaveBranch ), 34.52f )
				, new Loot( typeof( IvyOrb ), 18.9f )
				, new Loot( typeof( TuxedoShirt ), 20f )
				, new Loot( typeof( OrangeMartialShirt ), 40f )
				, new Loot( typeof( OrangeMageweaveShirt ), 40f )
				, new Loot( typeof( SmokingHeartOfTheMountain ), 40f )
				, new Loot( typeof( JacinthCircle ), 31.13f )
				, new Loot( typeof( SpinelRing ), 31.59f )
				, new Loot( typeof( CobaltRing ), 12.44f )
				, new Loot( typeof( ThalliumHoop ), 30.19f )
				, new Loot( typeof( BasaltRing ), 31.46f )
				, new Loot( typeof( TundraRing ), 13.02f )
				, new Loot( typeof( FenRing ), 1.239997f )
				, new Loot( typeof( MarshRing ), 1.47f )
				, new Loot( typeof( BandOfPurification ), 38.9f )
				, new Loot( typeof( OrbOfMistmantle ), 43.95f )
				, new Loot( typeof( ThunderbrowRing ), 13.42f )
				, new Loot( typeof( BrightSphere ), 25.42f )
				, new Loot( typeof( SilverThreadRod ), 4.519999f )
				, new Loot( typeof( SanguineStar ), 24.52f )
				, new Loot( typeof( WatchersStar ), 7.459998f )
				, new Loot( typeof( PaganRod ), 41.54f )
				, new Loot( typeof( RaincallerScepter ), 3.16f )
				, new Loot( typeof( WitchsFinger ), 20.46f )
		};
	}
}
