//////////////////////////////////////////////////////////
// DrNexus Advanced MailArmors Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class AdvancedMailArmorsDrops
	{
		public static Loot[]AdvancedMailArmors = new Loot[]
		{
			new Loot( typeof( ForestChain ), 17.18f )
				, new Loot( typeof( DeputyChainCoat ), 16.58f )
				, new Loot( typeof( DragonmawChainBoots ), 21.32f )
				, new Loot( typeof( DustyChainArmor ), 11.53f )
				, new Loot( typeof( PolishedScaleLeggings ), 40.94f )
				, new Loot( typeof( PolishedScaleVest ), 40.73f )
				, new Loot( typeof( AugmentedChainBelt ), 21.06f )
				, new Loot( typeof( AugmentedChainBracers ), 20.48f )
				, new Loot( typeof( AugmentedChainGloves ), 20.19f )
				, new Loot( typeof( MalleableChainLeggings ), 10.16f )
				, new Loot( typeof( SilveredBronzeBreastplate ), 8.450002f )
				, new Loot( typeof( DarkshireMailLeggings ), 9.490002f )
				, new Loot( typeof( GoldMilitiaBoots ), 37.14f )
				, new Loot( typeof( BurnishedTunic ), 49.91f )
				, new Loot( typeof( LambentScaleBoots ), 21.31f )
				, new Loot( typeof( LambentScaleGloves ), 47.4f )
				, new Loot( typeof( LambentScaleLegguards ), 4.02f )
				, new Loot( typeof( JimmiedHandcuffs ), 45.08f )
				, new Loot( typeof( CutthroatPauldrons ), 36.68f )
				, new Loot( typeof( GauntletsOfOgreStrength ), 18.92f )
				, new Loot( typeof( SilveredBronzeShoulders ), 35.78f )
				, new Loot( typeof( SilveredBronzeBoots ), 34.12f )
				, new Loot( typeof( GreenIronBoots ), 11.63f )
				, new Loot( typeof( GreenIronGauntlets ), 35.23f )
				, new Loot( typeof( OrcishWarChain ), 36.53f )
				, new Loot( typeof( CrusaderBelt ), 9.140003f )
				, new Loot( typeof( DoubleMailBracers ), 42.72f )
				, new Loot( typeof( DoubleMailPants ), 11.38f )
				, new Loot( typeof( DoubleMailShoulderpads ), 5.430001f )
				, new Loot( typeof( DoubleMailVest ), 26.23f )
				, new Loot( typeof( GreenIronBracers ), 44.68f )
				, new Loot( typeof( OverlinkedChainBelt ), 10.14f )
				, new Loot( typeof( GlimmeringMailGauntlets ), 32.96f )
				, new Loot( typeof( MailCombatGauntlets ), 0.7600009f )
				, new Loot( typeof( PugilistBracers ), 15.36f )
				, new Loot( typeof( HuskOfNaraxis ), 0.4100025f )
				, new Loot( typeof( BonefistGauntlets ), 20.72f )
				, new Loot( typeof( SteelClaspedBracers ), 41.32f )
				, new Loot( typeof( LambentScalePauldrons ), 27.52f )
				, new Loot( typeof( GlimmeringMailGirdle ), 38.6f )
				, new Loot( typeof( MightyChainPants ), 38.91f )
				, new Loot( typeof( LegionnairesLeggings ), 24.82f )
				, new Loot( typeof( GloriousShoulders ), 13.42f )
				, new Loot( typeof( GoldenScaleBracers ), 17.53f )
				, new Loot( typeof( ChaussesOfWestfall ), 13.61f )
				, new Loot( typeof( GarnegsWarBelt ), 38.83f )
				, new Loot( typeof( GlimmeringMailBracers ), 38.59f )
				, new Loot( typeof( MailCombatArmguards ), 11.41f )
				, new Loot( typeof( VioletScaleArmor ), 42.99f )
				, new Loot( typeof( DefenderLeggings ), 34.86f )
				, new Loot( typeof( DefenderTunic ), 34.38f )
				, new Loot( typeof( BattleforgeBoots ), 8.469999f )
				, new Loot( typeof( BattleforgeWristguards ), 49.61f )
				, new Loot( typeof( BattleforgeGirdle ), 43.96f )
				, new Loot( typeof( BattleforgeGauntlets ), 43.76f )
				, new Loot( typeof( BattleforgeShoulderguards ), 14.64f )
				, new Loot( typeof( PhantomArmor ), 5.980003f )
				, new Loot( typeof( TemperedBracers ), 47.56f )
				, new Loot( typeof( ChestplateOfKor ), 29.06f )
				, new Loot( typeof( BeastialManacles ), 33.43f )
				, new Loot( typeof( AlgaeFists ), 36.23f )
				, new Loot( typeof( TortoiseArmor ), 6.360001f )
				, new Loot( typeof( FireHardenedGauntlets ), 25.15f )
				, new Loot( typeof( BeltOfTheStars ), 7.069999f )
				, new Loot( typeof( BrutalGauntlets ), 22.66f )
				, new Loot( typeof( WildwoodChain ), 24.52f )
				, new Loot( typeof( PhalanxBracers ), 27.87f )
				, new Loot( typeof( PhalanxGauntlets ), 11.09f )
				, new Loot( typeof( PhalanxGirdle ), 18.87f )
				, new Loot( typeof( FireWeldedBracers ), 29.66f )
				, new Loot( typeof( FortifiedBoots ), 38.45f )
				, new Loot( typeof( FortifiedLeggings ), 16.8f )
				, new Loot( typeof( FortifiedSpaulders ), 28.66f )
				, new Loot( typeof( FortifiedChain ), 15.9f )
				, new Loot( typeof( BandedBracers ), 35.64f )
				, new Loot( typeof( BandedGauntlets ), 28.66f )
				, new Loot( typeof( BandedGirdle ), 28.39f )
				, new Loot( typeof( RenegadeBracers ), 2.890003f )
				, new Loot( typeof( QuagmireGaloshes ), 37.52f )
				, new Loot( typeof( BrightscaleGirdle ), 15.19f )
				, new Loot( typeof( YorgenBracers ), 37.92f )
				, new Loot( typeof( WarPaintChestpiece ), 38.81f )
				, new Loot( typeof( HulkingBoots ), 44.08f )
				, new Loot( typeof( HulkingLeggings ), 22.48f )
				, new Loot( typeof( HulkingSpaulders ), 33.75f )
				, new Loot( typeof( SlayersCuffs ), 46.6f )
				, new Loot( typeof( SlayersGloves ), 40.35f )
				, new Loot( typeof( SlayersSash ), 44.1f )
				, new Loot( typeof( SlayersSlippers ), 6.999999f )
				, new Loot( typeof( GrimtollWristguards ), 42.88f )
				, new Loot( typeof( OutrunnersChestguard ), 31.11f )
				, new Loot( typeof( OutrunnersLegguards ), 45.43f )
				, new Loot( typeof( GruntsLegguards ), 26.29f )
				, new Loot( typeof( GruntsPauldrons ), 36.8f )
				, new Loot( typeof( GruntsChestpiece ), 4.860002f )
				, new Loot( typeof( SpikedChainSlippers ), 20.61f )
				, new Loot( typeof( SpikedChainLeggings ), 2.880001f )
				, new Loot( typeof( SpikedChainShoulderPads ), 26.27f )
				, new Loot( typeof( SentrysSlippers ), 18.29f )
				, new Loot( typeof( SentrysGloves ), 48.99f )
				, new Loot( typeof( WickedChainBracers ), 36.48f )
				, new Loot( typeof( WickedChainGauntlets ), 29.37f )
				, new Loot( typeof( WickedChainWaistband ), 35.87f )
				, new Loot( typeof( ThickScaleBracelets ), 32.6f )
				, new Loot( typeof( ThickScaleGauntlets ), 17.55f )
				, new Loot( typeof( ThickScaleBelt ), 24.77f )
				, new Loot( typeof( PillagersGirdle ), 7.33f )
				, new Loot( typeof( PillagersBracers ), 15.15f )
				, new Loot( typeof( PillagersGloves ), 3.140002f )
				, new Loot( typeof( WarsongGauntlets ), 42.06f )
				, new Loot( typeof( CobaltLegguards ), 1.69f )
		};
	}
}
