//////////////////////////////////////////////////////////
// DrNexus Advanced PlansAndRecipes Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class AdvancedPlansAndRecipesDrops
	{
		public static Loot[]AdvancedPlansAndRecipes = new Loot[]
		{
			new Loot( typeof( PlansFrostTigerBlade ), 50f )
				, new Loot( typeof( PlansShadowCrescentAxe ), 50f )
				, new Loot( typeof( PlansGoldenScaleBoots ), 50f )
				, new Loot( typeof( RecipeGiantClamScorcho ), 50f )
				, new Loot( typeof( PatternCrimsonSilkRobe ), 50f )
				, new Loot( typeof( PlansHeavyMithrilPants ), 40f )
				, new Loot( typeof( PlansMithrilShieldSpike ), 20f )
				, new Loot( typeof( PlansOrnateMithrilPants ), 20f )
				, new Loot( typeof( PlansOrnateMithrilGloves ), 20f )
				, new Loot( typeof( PlansOrnateMithrilShoulder ), 20f )
				, new Loot( typeof( PlansBlueGlitteringAxe ), 20f )
				, new Loot( typeof( PlansMithrilScaleBracers ), 40f )
				, new Loot( typeof( PlansWickedMithrilBlade ), 20f )
				, new Loot( typeof( PatternBigVoodooPants ), 50f )
				, new Loot( typeof( PatternBigVoodooCloak ), 50f )
				, new Loot( typeof( PatternToughScorpidBoots ), 50f )
				, new Loot( typeof( PatternToughScorpidShoulders ), 50f )
				, new Loot( typeof( PatternToughScorpidLeggings ), 45f )
				, new Loot( typeof( PatternToughScorpidHelm ), 45f )
				, new Loot( typeof( RecipeMagicResistancePotion ), 50f )
				, new Loot( typeof( RecipeWildvinePotion ), 20f )
				, new Loot( typeof( RecipeInvisibilityPotion ), 20f )
				, new Loot( typeof( RecipeGiftOfArthas ), 20f )
				, new Loot( typeof( RecipeElixirOfGiants ), 10f )
				, new Loot( typeof( RecipeGhostDye ), 10f )
				, new Loot( typeof( RecipePhilosophersStone ), 20f )
				, new Loot( typeof( RecipeTransmuteIronToGold ), 20f )
				, new Loot( typeof( RecipeTransmuteMithrilToTruesilver ), 20f )
				, new Loot( typeof( PlansGoldenScaleGauntlets ), 50f )
				, new Loot( typeof( PatternRedMageweaveVest ), 50f )
				, new Loot( typeof( PatternWhiteBanditMask ), 50f )
				, new Loot( typeof( PatternRedMageweavePants ), 50f )
				, new Loot( typeof( PatternRedMageweaveGloves ), 40f )
				, new Loot( typeof( PatternRedMageweaveShoulders ), 30f )
				, new Loot( typeof( PatternAdmiralsHat ), 30f )
				, new Loot( typeof( PatternRedMageweaveHeadband ), 30f )
				, new Loot( typeof( PatternTuxedoJacket ), 50f )
				, new Loot( typeof( PatternShadoweaveMask ), 30f )
				, new Loot( typeof( FormulaEnchantGlovesAdvancedHerbalism ), 50f )
				, new Loot( typeof( FormulaEnchantCloakLesserAgility ), 50f )
				, new Loot( typeof( FormulaEnchantWeaponFieryWeapon ), 25f )
				, new Loot( typeof( FormulaEnchantWeaponDemonslaying ), 46f )
				, new Loot( typeof( FormulaEnchantBracerDeflection ), 42f )
				, new Loot( typeof( FormulaEnchantShieldFrostResistance ), 42f )
				, new Loot( typeof( FormulaEnchantBracerGreaterStamina ), 38f )
				, new Loot( typeof( FormulaEnchantGlovesRidingSkill ), 38f )
				, new Loot( typeof( RecipeRoastRaptor ), 50f )
				, new Loot( typeof( RecipeHotWolfRibs ), 50f )
				, new Loot( typeof( RecipeCarrionSurprise ), 50f )
				, new Loot( typeof( RecipeDragonbreathChili ), 30f )
				, new Loot( typeof( RecipeHeavyKodoStew ), 30f )
				, new Loot( typeof( ManualMageweaveBandage ), 50f )
				, new Loot( typeof( GrimoireOfFireboltRank4 ), 50f )
				, new Loot( typeof( GrimoireOfFireShieldRank3 ), 20f )
				, new Loot( typeof( GrimoireOfTormentRank3 ), 40f )
				, new Loot( typeof( GrimoireOfSacrificeRank3 ), 30f )
				, new Loot( typeof( GrimoireOfConsumeShadowsRank3 ), 20f )
				, new Loot( typeof( GrimoireOfSufferingRank2 ), 10f )
				, new Loot( typeof( GrimoireOfLashOfPainRank2 ), 50f )
				, new Loot( typeof( GrimoireOfLashOfPainRank3 ), 10f )
				, new Loot( typeof( GrimoireOfSoothingKissRank2 ), 20f )
				, new Loot( typeof( GrimoireOfLesserInvisibility ), 30f )
				, new Loot( typeof( GrimoireOfTaintedBloodRank1 ), 30f )
				, new Loot( typeof( GrimoireOfSpellLockRank1 ), 10f )
		};
	}
}
