//////////////////////////////////////////////////////////
// DrNexus High StavesAndWands Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class HighStavesAndWandsDrops
	{
		public static Loot[]HighStavesAndWands = new Loot[]
		{
			new Loot( typeof( GnarledAshStaff ), 29.306f )
				, new Loot( typeof( StaffOfHorrors ), 73.08f )
				, new Loot( typeof( TwistedChantersStaff ), 64.824f )
				, new Loot( typeof( RodOfTheSleepwalker ), 40.46f )
				, new Loot( typeof( HardenedRootStaff ), 64.998f )
				, new Loot( typeof( WitchingStave ), 70.776f )
				, new Loot( typeof( BloodscalpChannelingStaff ), 27.602f )
				, new Loot( typeof( CryptboneStaff ), 63.556f )
				, new Loot( typeof( StaffOfWestfall ), 63.61f )
				, new Loot( typeof( DwarvenMagestaff ), 55.86f )
				, new Loot( typeof( MagicianStaff ), 49.41f )
				, new Loot( typeof( OgremageStaff ), 58.822f )
				, new Loot( typeof( StaffOfTheBlessedSeer ), 67.444f )
				, new Loot( typeof( KamsWalkingStick ), 59.766f )
				, new Loot( typeof( BattleStaff ), 41.288f )
				, new Loot( typeof( StaffOfTheShade ), 49.836f )
				, new Loot( typeof( IcicleRod ), 65.232f )
				, new Loot( typeof( AcrobaticStaff ), 19.12f )
				, new Loot( typeof( NightbaneStaff ), 73.662f )
				, new Loot( typeof( StaffOfTheFriar ), 64.014f )
				, new Loot( typeof( CeraniumRod ), 76.78f )
				, new Loot( typeof( MetalStave ), 57.916f )
				, new Loot( typeof( HeavyWarStaff ), 1.782f )
				, new Loot( typeof( EmberstoneStaff ), 68.382f )
				, new Loot( typeof( StaffOfThePurifier ), 73.646f )
				, new Loot( typeof( OdosLeyStaff ), 51.972f )
				, new Loot( typeof( CrescentStaff ), 63.198f )
				, new Loot( typeof( LivingRoot ), 59.468f )
				, new Loot( typeof( WindSpiritStaff ), 17.328f )
				, new Loot( typeof( Hydrocane ), 17.898f )
				, new Loot( typeof( StaffOfSoranruk ), 66.554f )
				, new Loot( typeof( PolishedWalkingStaff ), 69.066f )
				, new Loot( typeof( GnomishZapper ), 16.808f )
				, new Loot( typeof( ScorchingWand ), 47.814f )
				, new Loot( typeof( WandOfEventide ), 60.646f )
				, new Loot( typeof( EmberWand ), 13.44f )
				, new Loot( typeof( CombustibleWand ), 71.212f )
				, new Loot( typeof( PitchwoodWand ), 28.546f )
				, new Loot( typeof( BlackboneWand ), 22.538f )
				, new Loot( typeof( ConsecratedWand ), 65.35f )
				, new Loot( typeof( SummonersWand ), 49.086f )
				, new Loot( typeof( ExcavationRod ), 65.102f )
				, new Loot( typeof( RodOfSorrow ), 20.388f )
				, new Loot( typeof( FlashWand ), 31.51f )
				, new Loot( typeof( BurningSliver ), 13.416f )
				, new Loot( typeof( CharredWand ), 73.536f )
				, new Loot( typeof( GoblinIgniter ), 20.48f )
				, new Loot( typeof( PestilentWand ), 68.574f )
				, new Loot( typeof( BrandingRod ), 74.058f )
				, new Loot( typeof( MoonbeamWand ), 67.608f )
				, new Loot( typeof( SpellcrafterWand ), 75.99f )
				, new Loot( typeof( FizzlesZippyLighter ), 28.124f )
				, new Loot( typeof( Eyepoker ), 36.376f )
				, new Loot( typeof( DancingFlame ), 14.922f )
				, new Loot( typeof( GravestoneScepter ), 64.64799f )
				, new Loot( typeof( RagefireWand ), 18.288f )
				, new Loot( typeof( IcefuryWand ), 17.982f )
				, new Loot( typeof( NecroticWand ), 33.502f )
				, new Loot( typeof( Firestarter ), 70.528f )
				, new Loot( typeof( DireWand ), 77.69f )
				, new Loot( typeof( EarthenRod ), 13.714f )
				, new Loot( typeof( GyromaticIcemaker ), 63.10001f )
				, new Loot( typeof( FreezingShard ), 4.079998f )
				, new Loot( typeof( PlaguerotSprig ), 3.391999f )
				, new Loot( typeof( NetherForceWand ), 15.806f )
				, new Loot( typeof( LesserMysticWand ), 78.514f )
				, new Loot( typeof( GreaterMysticWand ), 68.422f )
				, new Loot( typeof( Thunderwood ), 70.086f )
				, new Loot( typeof( Starfaller ), 41.484f )
				, new Loot( typeof( StingshotWand ), 72.87f )
				, new Loot( typeof( KodoBrander ), 32.37f )
				, new Loot( typeof( CaptainRackmoresTiller ), 43.072f )
		};
	}
}
