//////////////////////////////////////////////////////////
// DrNexus High Shields Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class HighShieldsDrops
	{
		public static Loot[]HighShields = new Loot[]
		{
			new Loot( typeof( FireHardenedBuckler ), 77.798f )
				, new Loot( typeof( ShieldOfTheFaith ), 72.04401f )
				, new Loot( typeof( MetalBuckler ), 65.83f )
				, new Loot( typeof( OrnateBuckler ), 6.066f )
				, new Loot( typeof( HeavyPavise ), 67.684f )
				, new Loot( typeof( CrestedHeaterShield ), 12.742f )
				, new Loot( typeof( GoldLionShield ), 55.944f )
				, new Loot( typeof( LambentScaleShield ), 78.832f )
				, new Loot( typeof( SentryBuckler ), 75.488f )
				, new Loot( typeof( DeadskullShield ), 66.934f )
				, new Loot( typeof( LunarBuckler ), 32.39f )
				, new Loot( typeof( ReflectiveHeater ), 78.978f )
				, new Loot( typeof( ProtectivePavise ), 46.672f )
				, new Loot( typeof( DeflectingTower ), 31.63f )
				, new Loot( typeof( BlockingTarge ), 68.456f )
				, new Loot( typeof( CrestedBuckler ), 17.628f )
				, new Loot( typeof( EmblazonedBuckler ), 70.124f )
				, new Loot( typeof( CombatShield ), 46.884f )
				, new Loot( typeof( InsigniaBuckler ), 51.546f )
				, new Loot( typeof( GlyphedBuckler ), 36.182f )
				, new Loot( typeof( ChiefBrigadierShield ), 30.816f )
				, new Loot( typeof( JoustersCrest ), 24.724f )
				, new Loot( typeof( GromgolBuckler ), 42.17f )
				, new Loot( typeof( CollectionPlate ), 5.558002f )
				, new Loot( typeof( NefariousBuckler ), 56.094f )
				, new Loot( typeof( PitFightersShield ), 17.178f )
				, new Loot( typeof( VigilantBuckler ), 35.222f )
				, new Loot( typeof( WardOfTheVale ), 77.786f )
				, new Loot( typeof( CrestOfDarkshire ), 52.028f )
				, new Loot( typeof( CommandersCrest ), 72.888f )
				, new Loot( typeof( GlimmeringShield ), 69.11f )
				, new Loot( typeof( DervishBuckler ), 75.738f )
				, new Loot( typeof( BattleforgeShield ), 73.214f )
				, new Loot( typeof( SeedcloudBuckler ), 79.326f )
				, new Loot( typeof( ConstableBuckler ), 77.542f )
				, new Loot( typeof( HeartOfAgamaggan ), 36.908f )
				, new Loot( typeof( MarbledBuckler ), 38.944f )
				, new Loot( typeof( BasaltBuckler ), 29.242f )
				, new Loot( typeof( VisionaryBuckler ), 37.32f )
				, new Loot( typeof( ArcticBuckler ), 69.718f )
				, new Loot( typeof( InfiltratorBuckler ), 60.77f )
				, new Loot( typeof( PhalanxShield ), 56.69201f )
				, new Loot( typeof( SentinelBuckler ), 37.974f )
				, new Loot( typeof( KnightsCrest ), 32.53f )
				, new Loot( typeof( CaptainsBuckler ), 4.416001f )
				, new Loot( typeof( FieldPlateShield ), 11.176f )
				, new Loot( typeof( VileProtector ), 22.452f )
				, new Loot( typeof( ResplendentGuardian ), 60.396f )
				, new Loot( typeof( BatteredVikingShield ), 55.632f )
				, new Loot( typeof( OlafsAllPurposeShield ), 6.018001f )
				, new Loot( typeof( ThermapluggsCentralCore ), 30.822f )
				, new Loot( typeof( EnergizedStoneCircle ), 50.612f )
				, new Loot( typeof( EarthclaspBarrier ), 9.486002f )
				, new Loot( typeof( ThargsDisk ), 7.876003f )
				, new Loot( typeof( ScaledShield ), 65.11f )
				, new Loot( typeof( BandedShield ), 62.608f )
				, new Loot( typeof( ArchersBuckler ), 51.172f )
				, new Loot( typeof( RenegadeShield ), 41.718f )
				, new Loot( typeof( ElvenProtector ), 15.886f )
				, new Loot( typeof( JazeraintShield ), 20.8f )
				, new Loot( typeof( SavageBoarsGuard ), 3.479999f )
				, new Loot( typeof( ShieldOfThorsen ), 66.404f )
				, new Loot( typeof( SkullanceShield ), 28.766f )
				, new Loot( typeof( HawkeyesBuckler ), 44.188f )
				, new Loot( typeof( DokebiBuckler ), 68.38f )
				, new Loot( typeof( RavagersShield ), 2.898002f )
				, new Loot( typeof( SymbolicCrest ), 14.046f )
				, new Loot( typeof( SaltstoneShield ), 25.174f )
				, new Loot( typeof( RobustBuckler ), 75.362f )
				, new Loot( typeof( CutthroatsBuckler ), 61.732f )
				, new Loot( typeof( GhostwalkerBuckler ), 50.566f )
				, new Loot( typeof( WranglersBuckler ), 77.362f )
				, new Loot( typeof( PathfinderGuard ), 70.92599f )
				, new Loot( typeof( HeadhuntersBuckler ), 58.986f )
				, new Loot( typeof( TrickstersProtector ), 37.534f )
				, new Loot( typeof( ClinkShield ), 76.76199f )
				, new Loot( typeof( SpikedChainShield ), 74.832f )
				, new Loot( typeof( SentrysShield ), 67.78f )
				, new Loot( typeof( WickedChainShield ), 58.204f )
				, new Loot( typeof( ThickScaleShield ), 47.74f )
				, new Loot( typeof( PillagersShield ), 44.372f )
				, new Loot( typeof( MaraudersCrest ), 28.374f )
				, new Loot( typeof( SparkleshellShield ), 24.054f )
				, new Loot( typeof( SteadfastBuckler ), 15.344f )
				, new Loot( typeof( StuddedRingShield ), 42.288f )
				, new Loot( typeof( AnchorholdBuckler ), 34.378f )
				, new Loot( typeof( HulkingShield ), 79.852f )
				, new Loot( typeof( SlayersShield ), 64.178f )
				, new Loot( typeof( EnduringShield ), 31.496f )
				, new Loot( typeof( DriftmireShield ), 77.992f )
				, new Loot( typeof( CaptainRackmoresWheel ), 49.048f )
		};
	}
}
