//////////////////////////////////////////////////////////
// DrNexus High SwordsAndDaggers Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class HighSwordsAndDaggersDrops
	{
		public static Loot[]HighSwordsAndDaggers = new Loot[]
		{
			new Loot( typeof( Vendetta ), 42.348f )
				, new Loot( typeof( Tigerbane ), 1.752001f )
				, new Loot( typeof( AssassinsBlade ), 70.252f )
				, new Loot( typeof( Blackfang ), 66.138f )
				, new Loot( typeof( MainGauche ), 61.328f )
				, new Loot( typeof( Rondel ), 9.138f )
				, new Loot( typeof( EvocatorsBlade ), 74.908f )
				, new Loot( typeof( CrossDagger ), 61.696f )
				, new Loot( typeof( ClawOfTheShadowmancer ), 32.688f )
				, new Loot( typeof( PrisonShank ), 64.478f )
				, new Loot( typeof( FleshPiercer ), 60.134f )
				, new Loot( typeof( Doomspike ), 67.706f )
				, new Loot( typeof( DeadlyBronzePoniard ), 72.68401f )
				, new Loot( typeof( ShinyDirk ), 60.43f )
				, new Loot( typeof( FinePointedDagger ), 37.842f )
				, new Loot( typeof( BlackvenomBlade ), 64.056f )
				, new Loot( typeof( NaraxisFang ), 66.67599f )
				, new Loot( typeof( TalonOfVultros ), 61.998f )
				, new Loot( typeof( PearlHandledDagger ), 78.922f )
				, new Loot( typeof( WyvernTailspike ), 68.904f )
				, new Loot( typeof( MeteorShard ), 51.064f )
				, new Loot( typeof( HowlingBlade ), 5.334002f )
				, new Loot( typeof( Thornspike ), 68.756f )
				, new Loot( typeof( SwinetuskShank ), 11.336f )
				, new Loot( typeof( BiteOfSerrakis ), 53.348f )
				, new Loot( typeof( TorturingPoker ), 23.216f )
				, new Loot( typeof( StonevaultShiv ), 2.105999f )
				, new Loot( typeof( ToxicRevenger ), 34.078f )
				, new Loot( typeof( DiabolistsBlade ), 73.466f )
				, new Loot( typeof( BroadBladedKnife ), 43.256f )
				, new Loot( typeof( DaringDirk ), 35.942f )
				, new Loot( typeof( GlintingSteelDagger ), 19.274f )
				, new Loot( typeof( BattleKnife ), 69.88f )
				, new Loot( typeof( HonedStiletto ), 55.734f )
				, new Loot( typeof( DeadlyKris ), 21.286f )
				, new Loot( typeof( DragonmawShortsword ), 61.578f )
				, new Loot( typeof( KnightlyLongsword ), 2.84f )
				, new Loot( typeof( BlackMetalShortsword ), 70.506f )
				, new Loot( typeof( Shadowfang ), 70.356f )
				, new Loot( typeof( HeavyMarauderScimitar ), 60.78f )
				, new Loot( typeof( SwordOfDecay ), 54.372f )
				, new Loot( typeof( TwistedSabre ), 61.6f )
				, new Loot( typeof( SkeletalLongsword ), 67.31f )
				, new Loot( typeof( SwordOfTheNightSky ), 76.994f )
				, new Loot( typeof( BluegillKukri ), 75.386f )
				, new Loot( typeof( Phytoblade ), 73.804f )
				, new Loot( typeof( Broadsword ), 50.744f )
				, new Loot( typeof( VikingSword ), 55.64f )
				, new Loot( typeof( LucineLongsword ), 72.388f )
				, new Loot( typeof( Talonstrike ), 77.164f )
				, new Loot( typeof( DecapitatingSword ), 75.47601f )
				, new Loot( typeof( LightScimitar ), 69.512f )
				, new Loot( typeof( HardenedIronShortsword ), 45.32f )
				, new Loot( typeof( JadeSerpentblade ), 26.954f )
				, new Loot( typeof( SharpShortsword ), 30.9f )
				, new Loot( typeof( CruelBarb ), 70.356f )
				, new Loot( typeof( Wingblade ), 70.666f )
				, new Loot( typeof( ButchersSlicer ), 78.682f )
				, new Loot( typeof( SilithidRipper ), 23.444f )
				, new Loot( typeof( TaintedPierce ), 7.778001f )
				, new Loot( typeof( TheButcher ), 42.526f )
				, new Loot( typeof( ElectrocutionerLeg ), 24.36f )
				, new Loot( typeof( DarkwaterTalwar ), 70.59f )
				, new Loot( typeof( TheBlackKnight ), 38.95f )
				, new Loot( typeof( SwordOfCorruption ), 58.614f )
				, new Loot( typeof( ZealotBlade ), 19.056f )
				, new Loot( typeof( FighterBroadsword ), 65.496f )
				, new Loot( typeof( MercenaryBlade ), 18.342f )
				, new Loot( typeof( OutlawSabre ), 45.076f )
				, new Loot( typeof( SlatemetalCutlass ), 75.168f )
		};
	}
}
