//////////////////////////////////////////////////////////
// DrNexus High TwoHandedWeapons Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class HighTwoHandedWeaponsDrops
	{
		public static Loot[]HighTwoHandedWeapons = new Loot[]
		{
			new Loot( typeof( TunnelPick ), 50.364f )
				, new Loot( typeof( Rockslicer ), 79.884f )
				, new Loot( typeof( NightReaver ), 69.336f )
				, new Loot( typeof( BlackrockChampionsAxe ), 70.686f )
				, new Loot( typeof( SlayersBattleAxe ), 66.12801f )
				, new Loot( typeof( BlackMetalWarAxe ), 55.562f )
				, new Loot( typeof( ShadowhideBattleAxe ), 73.16801f )
				, new Loot( typeof( HeavyOgreWarAxe ), 58.666f )
				, new Loot( typeof( BurningWarAxe ), 12.432f )
				, new Loot( typeof( Bullova ), 43.43f )
				, new Loot( typeof( ArcedWarAxe ), 61.422f )
				, new Loot( typeof( BattleSlayer ), 77.38f )
				, new Loot( typeof( BarbarianWarAxe ), 55.034f )
				, new Loot( typeof( BrutalWarAxe ), 43.732f )
				, new Loot( typeof( HeftyWarAxe ), 71.65f )
				, new Loot( typeof( TaskmasterAxe ), 69.202f )
				, new Loot( typeof( BoahnsFang ), 79.158f )
				, new Loot( typeof( ScytheAxe ), 73.358f )
				, new Loot( typeof( Corpsemaker ), 0.6959975f )
				, new Loot( typeof( ReefAxe ), 59.892f )
				, new Loot( typeof( Bloodspiller ), 21.258f )
				, new Loot( typeof( BronzeBattleAxe ), 75.644f )
				, new Loot( typeof( SuperchargerBattleAxe ), 45.166f )
				, new Loot( typeof( MercilessAxe ), 39.61f )
				, new Loot( typeof( MidnightAxe ), 19.318f )
				, new Loot( typeof( ProspectorAxe ), 77.948f )
				, new Loot( typeof( Killmaim ), 52.29f )
				, new Loot( typeof( MassiveBattleAxe ), 69.634f )
				, new Loot( typeof( IronwoodTreebranch ), 66.756f )
				, new Loot( typeof( Maul ), 78.056f )
				, new Loot( typeof( HeavyGnollWarClub ), 79.358f )
				, new Loot( typeof( Headbasher ), 63.286f )
				, new Loot( typeof( ShadowhideMaul ), 73.766f )
				, new Loot( typeof( KorgBat ), 3.645998f )
				, new Loot( typeof( Slaghammer ), 36.594f )
				, new Loot( typeof( GoblinPowerShovel ), 16.424f )
				, new Loot( typeof( KazonsMaul ), 58.028f )
				, new Loot( typeof( WarHammer ), 47.022f )
				, new Loot( typeof( OakMallet ), 79.278f )
				, new Loot( typeof( BlackMalice ), 75.042f )
				, new Loot( typeof( BatteringHammer ), 72.582f )
				, new Loot( typeof( DenseTriangleMace ), 45.632f )
				, new Loot( typeof( TroggBeater ), 78.814f )
				, new Loot( typeof( LargeWarClub ), 65.486f )
				, new Loot( typeof( SolidIronMaul ), 37.412f )
				, new Loot( typeof( GoldenIronDestroyer ), 16.392f )
				, new Loot( typeof( DemolitionHammer ), 59.838f )
				, new Loot( typeof( GlacialStone ), 41.29f )
				, new Loot( typeof( OrcCrusher ), 55.818f )
				, new Loot( typeof( VerigansFist ), 25.406f )
				, new Loot( typeof( SmitesMightyHammer ), 68.97f )
				, new Loot( typeof( ManualCrowdPummeler ), 4.356003f )
				, new Loot( typeof( MechanicsPipehammer ), 43.68f )
				, new Loot( typeof( RakzurClub ), 76.374f )
				, new Loot( typeof( HeftyBattlehammer ), 66.934f )
				, new Loot( typeof( BruteHammer ), 54.954f )
				, new Loot( typeof( HugeOgreSword ), 49.624f )
				, new Loot( typeof( DacianFalx ), 75.924f )
				, new Loot( typeof( PysansOldGreatsword ), 42.558f )
				, new Loot( typeof( Archeus ), 11.728f )
				, new Loot( typeof( BlackMetalGreatsword ), 51.308f )
				, new Loot( typeof( DarksteelBastardSword ), 42.906f )
				, new Loot( typeof( Duskbringer ), 60.388f )
				, new Loot( typeof( Flamberge ), 38.208f )
				, new Loot( typeof( CombatantClaymore ), 14.754f )
				, new Loot( typeof( StonecutterClaymore ), 7.044f )
				, new Loot( typeof( CavalierTwoHander ), 54.18f )
				, new Loot( typeof( AncientWarSword ), 32.166f )
				, new Loot( typeof( OnyxClaymore ), 53.708f )
				, new Loot( typeof( BroadClaymore ), 68.744f )
				, new Loot( typeof( RunicDarkblade ), 35.19f )
				, new Loot( typeof( WhettedClaymore ), 36.274f )
				, new Loot( typeof( BlessedClaymore ), 75.378f )
				, new Loot( typeof( ExecutionersSword ), 71.454f )
				, new Loot( typeof( SeraphsStrike ), 38.53f )
				, new Loot( typeof( EmilsBrand ), 29.122f )
				, new Loot( typeof( HauntingBlade ), 63.248f )
				, new Loot( typeof( OrcishWarSword ), 69.856f )
				, new Loot( typeof( StrikeOfTheHydra ), 28.446f )
				, new Loot( typeof( BronzeGreatsword ), 77.944f )
				, new Loot( typeof( GizmotronMegachopper ), 38.782f )
				, new Loot( typeof( SearingBlade ), 67.396f )
				, new Loot( typeof( GuardianBlade ), 54.836f )
				, new Loot( typeof( DeanshipClaymore ), 38.084f )
				, new Loot( typeof( PolishedZweihander ), 61.224f )
				, new Loot( typeof( GlimmeringFlamberge ), 31.052f )
		};
	}
}
