unit SpellConst;

interface

const

// SKILL_ID
SKILL_TAILORING         = 197;
SKILL_ALCHEMY           = 171;
SKILL_LEATHERWORKING    = 165;
SKILL_ENGINERING        = 202;
SKILL_FIRST_AID         = 129;
SKILL_MINING            = 186;
SKILL_COOKING           = 185;
SKILL_POISONS           = 40;
SKILL_SKINNING          = 393;
SKILL_ENCHANTING        = 333;
SKILL_BLACKSMITHING     = 164;
SKILL_HERBALISM         = 182;
SKILL_FISHING           = 356;
SKILL_OPENLOCK          = 242;

// SPELL_CAST_TARGET_FLAGS
TARGET_FLAG_SELF             = $0000;
TARGET_FLAG_UNIT             = $0002;
TARGET_FLAG_OBJECT           = $0800;
TARGET_FLAG_ITEM             = $1010;
TARGET_FLAG_SOURCE_LOCATION  = $0020;
TARGET_FLAG_DEST_LOCATION    = $0040;
TARGET_FLAG_STRING           = $2000;

// TARGETS
TARGET_SELF         = 1;
TARGET_PET          = 5;
TARGET_S_E          = 6;
TARGET_AE_E         = 15;
TARGET_AE_E_INSTANT = 16;
TARGET_AC_P         = 20;
TARGET_S_F          = 21;
TARGET_AC_E         = 22;
TARGET_S_GO         = 23;
TARGET_INFRONT      = 24;
TARGET_DUELVSPLAYER = 25;
TARGET_GOITEM       = 26;
TARGET_AE_E_CHANNEL = 28;
TARGET_MINION       = 32;
TARGET_S_P          = 35;
TARGET_SELF_FISHING = 39;
TARGET_TOTEM_EARTH  = 41;
TARGET_TOTEM_WATER  = 42;
TARGET_TOTEM_AIR    = 43;
TARGET_TOTEM_FIRE   = 44;
TARGET_CHAIN        = 45;
TARGET_DY_OBJ       = 47;                               //DynamicObject
TARGET_AE_SELECTED  = 53;
TARGET_S_F_2        = 57;                               //single friend

// SPELL_CAST_FLAGS
CAST_FLAG_UNKNOWN1           = $02;
CAST_FLAG_UNKNOWN2           = $10;
CAST_FLAG_AMMO               = $20;

// SHEPESHIFT_FORM
FORM_CAT              = 1;
FORM_TREE             = 2;
FORM_TRAVEL           = 3;
FORM_AQUA             = 4;
FORM_BEAR             = 5;
FORM_AMBIENT          = 6;
FORM_GHOUL            = 7;
FORM_DIREBEAR         = 8;
FORM_CREATUREBEAR     = 14;
FORM_GHOSTWOLF        = 16;
FORM_BATTLESTANCE     = 17;
FORM_DEFENSIVESTANCE  = 18;
FORM_BERSERKERSTANCE  = 19;
FORM_SHADOW           = 28;
FORM_STEALTH          = 30;

// SPELL_FAIL_RESASONS
CAST_FAIL_ALREADY_FULL_HEALTH = 1;
CAST_FAIL_ALREADY_FULL_MANA = 2;
    //CAST_FAIL_ALREADY_FULL_RAGE = 2;
CAST_FAIL_CREATURE_ALREADY_TAMING = 3;
CAST_FAIL_ALREADY_HAVE_CHARMED = 4;
CAST_FAIL_ALREADY_HAVE_SUMMON = 5;
CAST_FAIL_ALREADY_OPEN = 6;
CAST_FAIL_MORE_POWERFUL_SPELL_ACTIVE = 7;
CAST_FAIL_FAILED = 8;
CAST_FAIL_NO_TARGET = 9;
CAST_FAIL_INVALID_TARGET = 10;
CAST_FAIL_CANT_BE_CHARMED = 11;
CAST_FAIL_CANT_BE_DISENCHANTED = 12;
CAST_FAIL_TARGET_IS_TAPPED = 13;
CAST_FAIL_CANT_START_DUEL_INVISIBLE = 14;
CAST_FAIL_CANT_START_DUEL_STEALTHED = 15;
CAST_FAIL_TOO_CLOSE_TO_ENEMY = 16;
CAST_FAIL_CANT_DO_THAT_YET = 17;
CAST_FAIL_YOU_ARE_DEAD = 18;
CAST_FAIL_OBJECT_ALREADY_BEING_USED = 19;
CAST_FAIL_CANT_DO_WHILE_CONFUSED = 20;
CAST_FAIL_MUST_HAVE_ITEM_EQUIPPED = 22;
CAST_FAIL_MUST_HAVE_XXXX_EQUIPPED = 23;
CAST_FAIL_MUST_HAVE_XXXX_IN_MAINHAND = 24;
CAST_FAIL_INTERNAL_ERROR = 25;
CAST_FAIL_FIZZLED = 26;
CAST_FAIL_YOU_ARE_FLEEING = 27;
CAST_FAIL_FOOD_TOO_LOWLEVEL_FOR_PET = 28;
CAST_FAIL_TARGET_IS_TOO_HIGH = 29;
CAST_FAIL_IMMUNE = 32;                                  // was 31 in pre 1.7
CAST_FAIL_INTERRUPTED = 33;                             // was 32 in pre 1.7
    //CAST_FAIL_INTERRUPTED_COMBAT = 31;
CAST_FAIL_ITEM_ALREADY_ENCHANTED = 34;
CAST_FAIL_ITEM_IS_GONE = 35;
CAST_FAIL_ENCHANT_NOT_EXISTING_ITEM = 36;
CAST_FAIL_ITEM_NOT_READY = 37;
CAST_FAIL_YOU_ARE_NOT_HIGH_ENOUGH = 38;
CAST_FAIL_NOT_IN_LINE_OF_SIGHT = 39;
CAST_FAIL_TARGET_TOO_LOW = 40;
CAST_FAIL_SKILL_NOT_HIGH_ENOUGH = 41;
CAST_FAIL_WEAPON_HAND_IS_EMPTY = 42;
CAST_FAIL_CANT_DO_WHILE_MOVING = 43;
CAST_FAIL_NEED_AMMO_IN_PAPERDOLL_SLOT = 44;
CAST_FAIL_REQUIRES_SOMETHING = 45;
CAST_FAIL_NEED_EXOTIC_AMMO = 46;
CAST_FAIL_NO_PATH_AVAILABLE = 47;
CAST_FAIL_NOT_BEHIND_TARGET = 48;
CAST_FAIL_DIDNT_LAND_IN_FISHABLE_WATER = 49;
CAST_FAIL_CANT_BE_CAST_HERE = 50;
CAST_FAIL_NOT_IN_FRONT_OF_TARGET = 51;
CAST_FAIL_NOT_IN_CONTROL_OF_ACTIONS = 52;
CAST_FAIL_SPELL_NOT_LEARNED = 53;
CAST_FAIL_CANT_USE_WHEN_MOUNTED = 54;
CAST_FAIL_YOU_ARE_IN_FLIGHT = 55;
CAST_FAIL_YOU_ARE_ON_TRANSPORT = 56;
CAST_FAIL_SPELL_NOT_READY_YET = 57;
CAST_FAIL_CANT_DO_IN_SHAPESHIFT = 58;
CAST_FAIL_HAVE_TO_BE_STANDING = 59;
CAST_FAIL_CAN_USE_ONLY_ON_OWN_OBJECT = 60;              // rogues trying "enchant" other's weapon with poison
CAST_FAIL_CANT_ENCHANT_TRADE_ITEM = 61;
CAST_FAIL_HAVE_TO_BE_UNSHEATHED = 62;                   // yellow text
CAST_FAIL_CANT_CAST_AS_GHOST = 63;
CAST_FAIL_NO_AMMO = 64;
CAST_FAIL_NO_CHARGES_REMAIN = 65;
CAST_FAIL_COMBO_POINTS_REQUIRED = 66;
CAST_FAIL_NO_DUELING_HERE = 67;
CAST_FAIL_NOT_ENOUGH_ENDURANCE = 68;
CAST_FAIL_THERE_ARENT_ANY_FISH_HERE = 69;
CAST_FAIL_CANT_USE_WHILE_SHAPESHIFTED = 70;
CAST_FAIL_CANT_MOUNT_HERE = 71;
CAST_FAIL_YOU_DO_NOT_HAVE_PET = 72;
CAST_FAIL_NOT_ENOUGH_MANA = 73;
CAST_FAIL_CANT_USE_WHILE_SWIMMING = 74;
CAST_FAIL_CAN_ONLY_USE_AT_DAY = 75;
CAST_FAIL_CAN_ONLY_USE_INDOORS = 76;
CAST_FAIL_CAN_ONLY_USE_MOUNTED = 77;
CAST_FAIL_CAN_ONLY_USE_AT_NIGHT = 78;
CAST_FAIL_CAN_ONLY_USE_OUTDOORS = 79;
    //CAST_FAIL_ONLY_SHAPESHIFTED = 80;			// didn't display
CAST_FAIL_CAN_ONLY_USE_STEALTHED  = 81;
CAST_FAIL_CAN_ONLY_USE_WHILE_SWIMMING = 82;
CAST_FAIL_OUT_OF_RANGE = 83;
CAST_FAIL_CANT_USE_WHILE_PACIFIED = 84;
CAST_FAIL_YOU_ARE_POSSESSED = 85;
CAST_FAIL_YOU_NEED_TO_BE_IN_XXX = 87;
CAST_FAIL_REQUIRES_XXX = 88;
CAST_FAIL_UNABLE_TO_MOVE = 89;
CAST_FAIL_SILENCED = 90;
CAST_FAIL_ANOTHER_ACTION_IS_IN_PROGRESS = 91;
CAST_FAIL_ALREADY_LEARNED_THAT_SPELL = 92;
CAST_FAIL_SPELL_NOT_AVAILABLE_TO_YOU = 93;
CAST_FAIL_CANT_DO_WHILE_STUNNED = 94;
CAST_FAIL_YOUR_TARGET_IS_DEAD = 95;
CAST_FAIL_TARGET_IS_IN_COMBAT = 96;
CAST_FAIL_CANT_DO_THAT_YET_2 = 97;
CAST_FAIL_TARGET_IS_DUELING = 98;
CAST_FAIL_TARGET_IS_HOSTILE = 99;
CAST_FAIL_TARGET_IS_TOO_ENRAGED_TO_CHARM = 100;
CAST_FAIL_TARGET_IS_FRIENDLY = 101;
CAST_FAIL_TARGET_CANT_BE_IN_COMBAT = 102;
CAST_FAIL_CANT_TARGET_PLAYERS = 103;
CAST_FAIL_TARGET_IS_ALIVE = 104;
CAST_FAIL_TARGET_NOT_IN_YOUR_PARTY = 104;
CAST_FAIL_CREATURE_MUST_BE_LOOTED_FIRST = 106;
CAST_FAIL_TARGET_IS_NOT_A_PLAYER = 107;
CAST_FAIL_NO_POCKETS_TO_PICK = 108;
CAST_FAIL_TARGET_HAS_NO_WEAPONS_EQUIPPED = 109;
CAST_FAIL_NOT_SKINNABLE = 110;
CAST_FAIL_TOO_CLOSE = 112;
CAST_FAIL_TOO_MANY_OF_THAT_ITEM_ALREADY = 113;
CAST_FAIL_NOT_ENOUGH_TRAINING_POINTS = 115;
CAST_FAIL_FAILED_ATTEMPT = 116;
CAST_FAIL_TARGET_NEED_TO_BE_BEHIND = 117;
CAST_FAIL_TARGET_NEED_TO_BE_INFRONT = 118;
CAST_FAIL_PET_DOESNT_LIKE_THAT_FOOD = 119;
CAST_FAIL_CANT_CAST_WHILE_FATIGUED = 120;
CAST_FAIL_TARGET_MUST_BE_IN_THIS_INSTANCE = 121;
CAST_FAIL_CANT_CAST_WHILE_TRADING = 122;
CAST_FAIL_TARGET_IS_NOT_PARTY_OR_RAID = 123;
CAST_FAIL_CANT_DISENCHANT_WHILE_LOOTING = 124;
CAST_FAIL_TARGET_IS_IN_FFA_PVP_COMBAT = 125;
CAST_FAIL_NO_NEARBY_CORPSES_TO_EAT = 126;
CAST_FAIL_CAN_ONLY_USE_IN_BATTLEGROUNDS = 127;
CAST_FAIL_TARGET_IS_NOT_A_GHOST = 128;
CAST_FAIL_YOUR_PET_CANT_LEARN_MORE_SKILLS = 129;
CAST_FAIL_UNKNOWN_REASON = 130;

// SPELL EFFECTS
SPELL_EFFECT_INSTAKILL	=	1	;                       //
SPELL_EFFECT_SCHOOL_DAMAGE	=	2	;                   //
SPELL_EFFECT_DUMMY	=	3	;                           // NOT TO BE IMPLEMENTED
SPELL_EFFECT_PORTAL_TELEPORT	=	4	;                 //
SPELL_EFFECT_TELEPORT_UNITS	=	5	;                   //
SPELL_EFFECT_APPLY_AURA	=	6	;                       //
SPELL_EFFECT_ENVIRONMENTAL_DAMAGE	=	7	;             //
SPELL_EFFECT_MANA_DRAIN	=	8	;                       //
SPELL_EFFECT_HEALTH_LEECH	=	9	;                     //
SPELL_EFFECT_HEAL	=	10	;                           //
SPELL_EFFECT_BIND	=	11	;                           //
SPELL_EFFECT_PORTAL	=	12	;                         //
SPELL_EFFECT_RITUAL_BASE	=	13	;                   //
SPELL_EFFECT_RITUAL_SPECIALIZE	=	14	;             //
SPELL_EFFECT_RITUAL_ACTIVATE_PORTAL	=	15	;         //
SPELL_EFFECT_QUEST_COMPLETE	=	16	;                 //
SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL	=	17	;         //
SPELL_EFFECT_RESURRECT	=	18	;                     //
SPELL_EFFECT_ADD_EXTRA_ATTACKS	=	19	;             //
SPELL_EFFECT_DODGE	=	20	;                         //
SPELL_EFFECT_EVADE	=	21	;                         //
SPELL_EFFECT_PARRY	=	22	;                         //
SPELL_EFFECT_BLOCK	=	23	;                         //
SPELL_EFFECT_CREATE_ITEM	=	24	;                   //
SPELL_EFFECT_WEAPON	=	25	;                         //
SPELL_EFFECT_DEFENSE	=	26	;                       //
SPELL_EFFECT_PERSISTENT_AREA_AURA	=	27	;           //
SPELL_EFFECT_SUMMON	=	28	;                         //
SPELL_EFFECT_LEAP	=	29	;                           //
SPELL_EFFECT_ENERGIZE	=	30	;                       //
SPELL_EFFECT_WEAPON_PERCENT_DAMAGE	=	31	;         //
SPELL_EFFECT_TRIGGER_MISSILE	=	32	;               //
SPELL_EFFECT_OPEN_LOCK	=	33	;                     //
SPELL_EFFECT_SUMMON_MOUNT_OBSOLETE	=	34	;         //
SPELL_EFFECT_APPLY_AREA_AURA	=	35	;               //
SPELL_EFFECT_LEARN_SPELL	=	36	;                   //
SPELL_EFFECT_SPELL_DEFENSE	=	37	;                 //
SPELL_EFFECT_DISPEL	=	38	;                         //
SPELL_EFFECT_LANGUAGE	=	39	;                       //
SPELL_EFFECT_DUAL_WIELD	=	40	;                     //
SPELL_EFFECT_SUMMON_WILD	=	41	;                   //
SPELL_EFFECT_SUMMON_GUARDIAN	=	42	;               //
SPELL_EFFECT_TELEPORT_UNITS_FACE_CASTER	=	43	;     //
SPELL_EFFECT_SKILL_STEP	=	44	;                     //
SPELL_EFFECT_UNDEFINED_45	=	45	;                   //
SPELL_EFFECT_SPAWN	=	46	;                         //
SPELL_EFFECT_TRADE_SKILL	=	47	;                   //
SPELL_EFFECT_STEALTH	=	48	;                       //
SPELL_EFFECT_DETECT	=	49	;                         //
SPELL_EFFECT_SUMMON_OBJECT	=	50	;                 //
SPELL_EFFECT_TRANS_DOOR	=	50	;                     //
SPELL_EFFECT_FORCE_CRITICAL_HIT	=	51	;             //
SPELL_EFFECT_GUARANTEE_HIT	=	52	;                 //
SPELL_EFFECT_ENCHANT_ITEM	=	53	;                   //
SPELL_EFFECT_ENCHANT_ITEM_TEMPORARY	=	54	;         //
SPELL_EFFECT_TAMECREATURE	=	55	;                   //
SPELL_EFFECT_SUMMON_PET	=	56	;                     //
SPELL_EFFECT_LEARN_PET_SPELL	=	57	;               //
SPELL_EFFECT_WEAPON_DAMAGE	=	58	;                 //
SPELL_EFFECT_OPEN_LOCK_ITEM	=	59	;                 //
SPELL_EFFECT_PROFICIENCY	=	60	;                   //
SPELL_EFFECT_SEND_EVENT	=	61	;                     //
SPELL_EFFECT_POWER_BURN	=	62	;                     //
SPELL_EFFECT_THREAT	=	63	;                         //
SPELL_EFFECT_TRIGGER_SPELL	=	64	;                 //
SPELL_EFFECT_HEALTH_FUNNEL	=	65	;                 //
SPELL_EFFECT_POWER_FUNNEL	=	66	;                   //
SPELL_EFFECT_HEAL_MAX_HEALTH	=	67	;               //
SPELL_EFFECT_INTERRUPT_CAST	=	68	;                 //
SPELL_EFFECT_DISTRACT	=	69	;                       //
SPELL_EFFECT_PULL	=	70	;                           //
SPELL_EFFECT_PICKPOCKET	=	71	;                     //
SPELL_EFFECT_ADD_FARSIGHT	=	72	;                   //
SPELL_EFFECT_SUMMON_POSSESSED	=	73	;               //
SPELL_EFFECT_SUMMON_TOTEM	=	74	;                   //
SPELL_EFFECT_HEAL_MECHANICAL	=	75	;               //
SPELL_EFFECT_SUMMON_OBJECT_WILD	=	76	;             //
SPELL_EFFECT_SCRIPT_EFFECT	=	77	;                 //
SPELL_EFFECT_ATTACK	=	78	;                         //
SPELL_EFFECT_SANCTUARY	=	79	;                     //
SPELL_EFFECT_ADD_COMBO_POINTS	=	80	;               //
SPELL_EFFECT_CREATE_HOUSE	=	81	;                   //
SPELL_EFFECT_BIND_SIGHT	=	82	;                     //
SPELL_EFFECT_DUEL	=	83	;                           //
SPELL_EFFECT_STUCK	=	84	;                         //
SPELL_EFFECT_SUMMON_PLAYER	=	85	;                 //
SPELL_EFFECT_ACTIVATE_OBJECT	=	86	;               //
SPELL_EFFECT_SUMMON_TOTEM_SLOT1	=	87	;             //
SPELL_EFFECT_SUMMON_TOTEM_SLOT2	=	88	;             //
SPELL_EFFECT_SUMMON_TOTEM_SLOT3	=	89	;             //
SPELL_EFFECT_SUMMON_TOTEM_SLOT4	=	90	;             //
SPELL_EFFECT_THREAT_ALL	=	91	;                     //
SPELL_EFFECT_ENCHANT_HELD_ITEM	=	92	;             //
SPELL_EFFECT_SUMMON_PHANTASM	=	93	;               //
SPELL_EFFECT_SELF_RESURRECT	=	94	;                 //
SPELL_EFFECT_SKINNING	=	95	;                       //
SPELL_EFFECT_CHARGE	=	96	;                         //
SPELL_EFFECT_SUMMON_CRITTER	=	97	;                 //
SPELL_EFFECT_KNOCK_BACK	=	98	;                     //
SPELL_EFFECT_DISENCHANT	=	99	;                     //
SPELL_EFFECT_INEBRIATE	=	100	;                     //
SPELL_EFFECT_FEED_PET	=	101	;                       //
SPELL_EFFECT_DISMISS_PET	=	102	;                   //
SPELL_EFFECT_REPUTATION	=	103	;                     //
SPELL_EFFECT_SUMMON_OBJECT_SLOT1	=	104	;           //
SPELL_EFFECT_SUMMON_OBJECT_SLOT2	=	105	;           //
SPELL_EFFECT_SUMMON_OBJECT_SLOT3	=	106	;           //
SPELL_EFFECT_SUMMON_OBJECT_SLOT4	=	107	;           //
SPELL_EFFECT_DISPEL_MECHANIC	=	108	;               //
SPELL_EFFECT_SUMMON_DEAD_PET	=	109	;               //
SPELL_EFFECT_DESTROY_ALL_TOTEMS	=	110	;             //
SPELL_EFFECT_DURABILITY_DAMAGE	=	111	;             //
SPELL_EFFECT_SUMMON_DEMON	=	112	;                   //
SPELL_EFFECT_RESURRECT_NEW	=	113	;                 //
SPELL_EFFECT_ATTACK_ME	=	114	;                     //
SPELL_EFFECT_DURABILITY_DAMAGE_PCT	=	115	;         //
SPELL_EFFECT_SKIN_PLAYER_CORPSE	=	116	;             //
SPELL_EFFECT_SPIRIT_HEAL	=	117	;                   //
SPELL_EFFECT_SKILL	=	118	;                         //
SPELL_EFFECT_APPLY_AURA_NEW	=	119	;                 //
SPELL_EFFECT_TELEPORT_GRAVEYARD	=	120	;             //
SPELL_EFFECT_ADICIONAL_DMG	=	121	;                 //

// CHANNELING
SPELL_SPELL_CHANNEL_UPDATE_INTERVAL = 1000;

// AURA MODIFIERS
SPELL_AURA_NONE = 0;                                // None
SPELL_AURA_BIND_SIGHT = 1;                          // Bind Sight
SPELL_AURA_MOD_THREAT = 10;                         // Mod Threat
SPELL_AURA_AURAS_VISIBLE = 100;                     // Auras Visible
SPELL_AURA_MOD_RESISTANCE_PCT = 101;                // Mod Resistance %
SPELL_AURA_MOD_CREATURE_ATTACK_POWER = 102;         // Mod Creature Attack Power
SPELL_AURA_MOD_TOTAL_THREAT = 103;                  // Mod Total Threat (Fade)
SPELL_AURA_WATER_WALK = 104;                        // Water Walk
SPELL_AURA_FEATHER_FALL = 105;                      // Feather Fall
SPELL_AURA_HOVER = 106;                             // Hover
SPELL_AURA_ADD_FLAT_MODIFIER = 107;                 // Add Flat Modifier
SPELL_AURA_ADD_PCT_MODIFIER = 108;                  // Add % Modifier
SPELL_AURA_ADD_TARGET_TRIGGER = 109;                // Add Class Target Trigger
SPELL_AURA_MOD_TAUNT = 11;                          // Taunt
SPELL_AURA_MOD_POWER_REGEN_PERCENT = 110;           // Mod Power Regen %
SPELL_AURA_ADD_CASTER_HIT_TRIGGER = 111;            // Add Class Caster Hit Trigger
SPELL_AURA_OVERRIDE_CLASS_SCRIPTS = 112;            // Override Class Scripts
SPELL_AURA_MOD_RANGED_DAMAGE_TAKEN = 113;           // Mod Ranged Dmg Taken
SPELL_AURA_MOD_RANGED_DAMAGE_TAKEN_PCT = 114;       // Mod Ranged % Dmg Taken
SPELL_AURA_MOD_HEALING = 115;                       // Mod Healing
SPELL_AURA_IGNORE_REGEN_INTERRUPT = 116;            // Regen During Combat
SPELL_AURA_MOD_MECHANIC_RESISTANCE = 117;           // Mod Mechanic Resistance
SPELL_AURA_MOD_HEALING_PCT = 118;                   // Mod Healing %
SPELL_AURA_SHARE_PET_TRACKING = 119;                // Share Pet Tracking
SPELL_AURA_MOD_STUN = 12;                           // Stun
SPELL_AURA_UNTRACKABLE = 120;                       // Untrackable
SPELL_AURA_EMPATHY = 121;                           // Empathy (Lore; whatever)
SPELL_AURA_MOD_OFFHAND_DAMAGE_PCT = 122;            // Mod Offhand Dmg %
SPELL_AURA_MOD_POWER_COST_PCT = 123;                // Mod Power Cost %
SPELL_AURA_MOD_RANGED_ATTACK_POWER = 124;           // Mod Ranged Attack Power
SPELL_AURA_MOD_MELEE_DAMAGE_TAKEN = 125;            // Mod Melee Dmg Taken
SPELL_AURA_MOD_MELEE_DAMAGE_TAKEN_PCT = 126;        // Mod Melee % Dmg Taken
SPELL_AURA_RANGED_ATTACK_POWER_ATTACKER_BONUS = 127;// Rngd Atk Pwr Attckr Bonus
SPELL_AURA_MOD_POSSESS_PET = 128;                   // Mod Possess Pet
SPELL_AURA_MOD_INCREASE_SPEED_ALWAYS = 129;         // Mod Speed Always
SPELL_AURA_MOD_DAMAGE_DONE = 13;                    // Mod Damage Done
SPELL_AURA_MOD_MOUNTED_SPEED_ALWAYS = 130;          // Mod Mounted Speed Always
SPELL_AURA_MOD_CREATURE_RANGED_ATTACK_POWER = 131;  // Mod Creature Ranged Attack Power
SPELL_AURA_MOD_INCREASE_ENERGY_PERCENT = 132;       // Mod Increase Energy %
SPELL_AURA_MOD_INCREASE_HEALTH_PERCENT = 133;       // Mod Max Health %
SPELL_AURA_MOD_MANA_REGEN_INTERRUPT = 134;          // Mod Interrupted Mana Regen
SPELL_AURA_MOD_HEALING_DONE = 135;                  // Mod Healing Done
SPELL_AURA_MOD_HEALING_DONE_PERCENT = 136;          // Mod Healing Done %
SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE = 137;         // Mod Total Stat %
SPELL_AURA_MOD_HASTE = 138;                         // Haste - Melee
SPELL_AURA_FORCE_REACTION = 139;                    // Force Reaction
SPELL_AURA_MOD_DAMAGE_TAKEN = 14;                   // Mod Damage Taken
SPELL_AURA_MOD_RANGED_HASTE = 140;                  // Haste - Ranged
SPELL_AURA_MOD_RANGED_AMMO_HASTE = 141;             // Haste - Ranged (Ammo Only)
SPELL_AURA_MOD_BASE_RESISTANCE_PCT = 142;           // Mod Base Resistance %
SPELL_AURA_MOD_RESISTANCE_EXCLUSIVE = 143;          // Mod Resistance Exclusive
SPELL_AURA_SAFE_FALL = 144;                         // Safe Fall
SPELL_AURA_CHARISMA = 145;                          // Charisma
SPELL_AURA_PERSUADED = 146;                         // Persuaded
SPELL_AURA_ADD_CREATURE_IMMUNITY = 147;             // Add Creature Immunity
SPELL_AURA_RETAIN_COMBO_POINTS = 148;               // Retain Combo Points
SPELL_AURA_DAMAGE_SHIELD = 15;                      // Damage Shield
SPELL_AURA_MOD_STEALTH = 16;                        // Mod Stealth
SPELL_AURA_MOD_DETECT = 17;                         // Mod Detect
SPELL_AURA_MOD_INVISIBILITY = 18;                   // Mod Invisibility
SPELL_AURA_MOD_INVISIBILITY_DETECTION = 19;         // Mod Invisibility Detection
SPELL_AURA_MOD_POSSESS = 2;                         // Mod Possess
SPELL_AURA_MOD_RESISTANCE = 22;                     // Mod Resistance
SPELL_AURA_PERIODIC_TRIGGER_SPELL = 23;             // Periodic Trigger
SPELL_AURA_PERIODIC_ENERGIZE = 24;                  // Periodic Energize
SPELL_AURA_MOD_PACIFY = 25;                         // Pacify
SPELL_AURA_MOD_ROOT = 26;                           // Root
SPELL_AURA_MOD_SILENCE = 27;                        // Silence
SPELL_AURA_REFLECT_SPELLS = 28;                     // Reflect Spells %
SPELL_AURA_MOD_STAT = 29;                           // Mod Stat
SPELL_AURA_PERIODIC_DAMAGE = 3;                     // Periodic Damage
SPELL_AURA_MOD_SKILL = 30;                          // Mod Skill
SPELL_AURA_MOD_INCREASE_SPEED = 31;                 // Mod Speed
SPELL_AURA_MOD_INCREASE_MOUNTED_SPEED = 32;         // Mod Speed Mounted
SPELL_AURA_MOD_DECREASE_SPEED = 33;                 // Mod Speed Slow
SPELL_AURA_MOD_INCREASE_HEALTH = 34;                // Mod Increase Health
SPELL_AURA_MOD_INCREASE_ENERGY = 35;                // Mod Increase Energy
SPELL_AURA_MOD_SHAPESHIFT = 36;                     // Shapeshift
SPELL_AURA_EFFECT_IMMUNITY = 37;                    // Immune Effect
SPELL_AURA_STATE_IMMUNITY = 38;                     // Immune State
SPELL_AURA_SCHOOL_IMMUNITY = 39;                    // Immune School
SPELL_AURA_DAMAGE_IMMUNITY = 40;                    // Immune Damage
SPELL_AURA_DISPEL_IMMUNITY = 41;                    // Immune Dispel Type
SPELL_AURA_PROC_TRIGGER_SPELL = 42;                 // Proc Trigger Spell
SPELL_AURA_PROC_TRIGGER_DAMAGE = 43;                // Proc Trigger Damage
SPELL_AURA_TRACK_CREATURES = 44;                    // Track Creatures
SPELL_AURA_TRACK_RESOURCES = 45;                    // Track Resources
SPELL_AURA_MOD_PARRY_SKILL = 46;                    // Mod Parry Skill
SPELL_AURA_MOD_PARRY_PERCENT = 47;                  // Mod Parry Percent
SPELL_AURA_MOD_DODGE_SKILL = 48;                    // Mod Dodge Skill
SPELL_AURA_MOD_DODGE_PERCENT = 49;                  // Mod Dodge Percent
SPELL_AURA_MOD_CONFUSE = 5;                         // Mod Confuse
SPELL_AURA_MOD_BLOCK_SKILL = 50;                    // Mod Block Skill
SPELL_AURA_MOD_BLOCK_PERCENT = 51;                  // Mod Block Percent
SPELL_AURA_MOD_CRIT_PERCENT = 52;                   // Mod Crit Percent
SPELL_AURA_PERIODIC_LEECH = 53;                     // Periodic Leech
SPELL_AURA_MOD_HIT_CHANCE = 54;                     // Mod Hit Chance
SPELL_AURA_MOD_SPELL_HIT_CHANCE = 55;               // Mod Spell Hit Chance
SPELL_AURA_TRANSFORM = 56;                          // Transform
SPELL_AURA_MOD_SPELL_CRIT_CHANCE = 57;              // Mod Spell Crit Chance
SPELL_AURA_MOD_INCREASE_SWIM_SPEED = 58;            // Mod Speed Swim
SPELL_AURA_MOD_DAMAGE_DONE_CREATURE = 59;           // Mod Creature Dmg Done
SPELL_AURA_MOD_CHARM = 6;                           // Mod Charm
SPELL_AURA_MOD_PACIFY_SILENCE = 60;                 // Pacify & Silence
SPELL_AURA_MOD_SCALE = 61;                          // Mod Scale
SPELL_AURA_PERIODIC_HEALTH_FUNNEL = 62;             // Periodic Health Funnel
SPELL_AURA_PERIODIC_MANA_FUNNEL = 63;               // Periodic Mana Funnel
SPELL_AURA_PERIODIC_MANA_LEECH = 64;                // Periodic Mana Leech
SPELL_AURA_MOD_CASTING_SPEED = 65;                  // Haste - Spells
SPELL_AURA_FEIGN_DEATH = 66;                        // Feign Death
SPELL_AURA_MOD_DISARM = 67;                         // Disarm
SPELL_AURA_MOD_STALKED = 68;                        // Mod Stalked
SPELL_AURA_SCHOOL_ABSORB = 69;                      // School Absorb
SPELL_AURA_MOD_FEAR = 7;                            // Mod Fear
SPELL_AURA_EXTRA_ATTACKS = 70;                      // Extra Attacks
SPELL_AURA_MOD_SPELL_CRIT_CHANCE_SCHOOL = 71;       // Mod School Spell Crit Chance
SPELL_AURA_MOD_POWER_COST = 72;                     // Mod Power Cost
SPELL_AURA_MOD_POWER_COST_SCHOOL = 73;              // Mod School Power Cost
SPELL_AURA_REFLECT_SPELLS_SCHOOL = 74;              // Reflect School Spells %
SPELL_AURA_MOD_LANGUAGE = 75;                       // Mod Language
SPELL_AURA_FAR_SIGHT = 76;                          // Far Sight
SPELL_AURA_MECHANIC_IMMUNITY = 77;                  // Immune Mechanic
SPELL_AURA_MOUNTED = 78;                            // Mounted
SPELL_AURA_MOD_DAMAGE_PERCENT_DONE = 79;            // Mod Dmg %
SPELL_AURA_PERIODIC_HEAL = 8;                       // Periodic Heal
SPELL_AURA_MOD_PERCENT_STAT = 80;                   // Mod Stat %
SPELL_AURA_SPLIT_DAMAGE = 81;                       // Split Damage
SPELL_AURA_WATER_BREATHING = 82;                    // Water Breathing
SPELL_AURA_MOD_BASE_RESISTANCE = 83;                // Mod Base Resistance
SPELL_AURA_MOD_REGEN = 84;                          // Mod Health Regen
SPELL_AURA_MOD_POWER_REGEN = 85;                    // Mod Power Regen
SPELL_AURA_CHANNEL_DEATH_ITEM = 86;                 // Create Death Item
SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN = 87;           // Mod Dmg % Taken
SPELL_AURA_MOD_PERCENT_REGEN = 88;                  // Mod Health Regen Percent
SPELL_AURA_PERIODIC_DAMAGE_PERCENT = 89;            // Periodic Damage Percent
SPELL_AURA_MOD_ATTACKSPEED = 9;                     // Mod Attack Speed
SPELL_AURA_MOD_RESIST_CHANCE = 90;                  // Mod Resist Chance
SPELL_AURA_MOD_DETECT_RANGE = 91;                   // Mod Detect Range
SPELL_AURA_PREVENTS_FLEEING = 92;                   // Prevent Fleeing
SPELL_AURA_MOD_UNATTACKABLE = 93;                   // Mod Uninteractible
SPELL_AURA_INTERRUPT_REGEN = 94;                    // Interrupt Regen
SPELL_AURA_GHOST = 95;                              // Ghost
SPELL_AURA_SPELL_MAGNET = 96;                       // Spell Magnet
SPELL_AURA_MANA_SHIELD = 97;                        // Mana Shield
SPELL_AURA_MOD_SKILL_TALENT = 98;                   // Mod Skill Talent
SPELL_AURA_MOD_ATTACK_POWER = 99;                   // Mod Attack Power

// AURA FLAGS

AFLAG_EMPTY = $0;
AFLAG_SET = $9;

MAX_POSITIVE_AURA = 32;
MAX_AURAS = 56;

type
  SpellState = (
              SPELL_STATE_NULL      = 0,
              SPELL_STATE_PREPARING = 1,
              SPELL_STATE_CASTING   = 2,
              SPELL_STATE_FINISHED  = 3,
              SPELL_STATE_IDLE      = 4
              );

implementation

end.
