unit UpdateConst;

interface

type
  TUpdateType = (
    UPDATETYPE_VALUES                       = 0, //  8 bytes - GUID Goto Update Block
    UPDATETYPE_MOVEMENT                     = 1, //  8 bytes - GUID  Goto Position Update
    UPDATETYPE_CREATE_OBJECT                = 2, //  *UpdateFull; 8 bytes - GUID 1 byte - Object Type (*);Goto Position Update;Goto Update Block
    UPDATETYPE_OUT_OF_RANGE_OBJECTS         = 3, //  4 bytes - Count;Loop Count Times:;8 bytes - GUID
    UPDATETYPE_NEAR_OBJECTS                 = 4  // looks like 3 & 4 do the same thing;4 bytes - Count;Loop Count Times:;8 bytes - GUID
  );

const
    TYPE_OBJECT                             = 1;
    TYPE_ITEM                               = 2;
    TYPE_CONTAINER                          = 6;
    TYPE_UNIT                               = 8;
    TYPE_PLAYER                             = 16;
    TYPE_GAMEOBJECT                         = 32;
    TYPE_DYNAMICOBJECT                      = 64;
    TYPE_CORPSE                             = 128;
    TYPE_AIGROUP                            = 256;
    TYPE_AREATRIGGER                        = 512;

    SPEED_STOP                              = 0.0;
    SPEED_WALK                              = 2.5;
    SPEED_RUN                               = 7.0;
    SPEED_WALKBACK                          = 2.5;
    SPEED_SWIM                              = 4.722222;
    SPEED_SWIMBACK                          = 4.5;
    SPEED_TURN                              = PI;

    MOVE_STOP                               = 0;
    MOVE_WALK                               = 1;
    MOVE_RUN                                = 2;
    MOVE_WALKBACK                           = 3;
    MOVE_SWIM                               = 4;
    MOVE_SWIMBACK                           = 5;
    MOVE_TURN                               = 6;

	  OBJECT_FIELD_GUID                       =    0;  //  2  UINT64
	  OBJECT_FIELD_TYPE                       =    2;  //  1  UINT32
	  OBJECT_FIELD_ENTRY                      =    3;  //  1  UINT32
	  OBJECT_FIELD_SCALE_X                    =    4;  //  1  UINT32
	  OBJECT_FIELD_PADDING                    =    5;  //  1  UINT32
	  OBJECT_END                              =    6;  //  0  INTERNALMARKER

    ITEM_FIELD_OWNER                        =    6;  //  2  UINT64
	  ITEM_FIELD_CONTAINED                    =    8;  //  2  UINT64
	  ITEM_FIELD_CREATOR                      =   10;  //  2  UINT64
	  ITEM_FIELD_GIFTCREATOR                  =   12;  //  2  UINT64
	  ITEM_FIELD_STACK_COUNT                  =   14;  //  1  UINT32
	  ITEM_FIELD_DURATION                     =   15;  //  1  UINT32
	  ITEM_FIELD_SPELL_CHARGES                =   16;  //  5  SPELLCHARGES
	  ITEM_FIELD_FLAGS                        =   21;  //  1  UINT32
	  ITEM_FIELD_ENCHANTMENT                  =   22;  //  21 ENCHANTMENT
	  ITEM_FIELD_PROPERTY_SEED                =   43;  //  1  UINT32
	  ITEM_FIELD_RANDOM_PROPERTIES_ID         =   44;  //  1  UINT32
	  ITEM_FIELD_ITEM_TEXT_ID                 =   45;  //  1  UINT32
	  ITEM_FIELD_DURABILITY                   =   46;  //  1  UINT32
	  ITEM_FIELD_MAXDURABILITY                =   47;  //  1  UINT32
	  ITEM_END                                =   48;  //  0  INTERNALMARKER

	  CONTAINER_FIELD_NUM_SLOTS               =   48;  //  1  UINT32
	  CONTAINER_ALIGN_PAD                     =   49;  //  1  UINT32
	  CONTAINER_FIELD_SLOT_1                  =   50;  //  72 CONTAINERSLOTS
	  CONTAINER_END                           =   122;  //  0  INTERNALMARKER

    UNIT_FIELD_CHARM                              = 6; // 2 4 1
	  UNIT_FIELD_SUMMON                             = 8; // 2 4 1
	  UNIT_FIELD_CHARMEDBY                          = 10; // 2 4 1
	  UNIT_FIELD_SUMMONEDBY                         = 12; // 2 4 1
	  UNIT_FIELD_CREATEDBY                          = 14; // 2 4 1
	  UNIT_FIELD_TARGET                             = 16; // 2 4 1
	  UNIT_FIELD_PERSUADED                          = 18; // 2 4 1
	  UNIT_FIELD_CHANNEL_OBJECT                     = 20; // 2 4 1
	  UNIT_FIELD_HEALTH                             = 22; // 1 1 256
	  UNIT_FIELD_POWER1                             = 23; // 1 1 1
	  UNIT_FIELD_POWER2                             = 24; // 1 1 1
	  UNIT_FIELD_POWER3                             = 25; // 1 1 1
	  UNIT_FIELD_POWER4                             = 26; // 1 1 1
	  UNIT_FIELD_POWER5                             = 27; // 1 1 1
	  UNIT_FIELD_MAXHEALTH                          = 28; // 1 1 256
    UNIT_FIELD_MAXPOWER1                          = 29; // 1 1 1
	  UNIT_FIELD_MAXPOWER2                          = 30; // 1 1 1
	  UNIT_FIELD_MAXPOWER3                          = 31; // 1 1 1
	  UNIT_FIELD_MAXPOWER4                          = 32; // 1 1 1
	  UNIT_FIELD_MAXPOWER5                          = 33; // 1 1 1 
	  UNIT_FIELD_LEVEL                              = 34; // 1 1 1
	  UNIT_FIELD_FACTIONTEMPLATE                    = 35; // 1 1 1 
	  UNIT_FIELD_BYTES_0                            = 36; // 1 5 1
	  UNIT_VIRTUAL_ITEM_SLOT_DISPLAY                = 37; // 3 1 1
	  UNIT_VIRTUAL_ITEM_INFO                        = 40; // 6 5 1 
	  UNIT_FIELD_FLAGS                              = 46; // 1 1 1
	  UNIT_FIELD_AURA                               = 47; // 48 1 1
	  UNIT_FIELD_AURAFLAGS                          = 95; // 6 5 1 
	  UNIT_FIELD_AURALEVELS                         = 101; // 12 5 1 
	  UNIT_FIELD_AURAAPPLICATIONS                   = 113; // 12 5 1
    UNIT_FIELD_AURASTATE                          = 125; // 1 1 1 
	  UNIT_FIELD_BASEATTACKTIME                     = 126; // 2 1 1 
	  UNIT_FIELD_RANGEDATTACKTIME                   = 128; // 1 1 2 
	  UNIT_FIELD_BOUNDINGRADIUS                     = 129; // 1 3 1
	  UNIT_FIELD_COMBATREACH                        = 130; // 1 3 1 
	  UNIT_FIELD_DISPLAYID                          = 131; // 1 1 1
	  UNIT_FIELD_NATIVEDISPLAYID                    = 132; // 1 1 1 
	  UNIT_FIELD_MOUNTDISPLAYID                     = 133; // 1 1 1 
	  UNIT_FIELD_MINDAMAGE                          = 134; // 1 3 38
	  UNIT_FIELD_MAXDAMAGE                          = 135; // 1 3 38 
	  UNIT_FIELD_MINOFFHANDDAMAGE                   = 136; // 1 3 38 
	  UNIT_FIELD_MAXOFFHANDDAMAGE                   = 137; // 1 3 38
	  UNIT_FIELD_BYTES_1                            = 138; // 1 5 1
	  UNIT_FIELD_PETNUMBER                          = 139; // 1 1 1
	  UNIT_FIELD_PET_NAME_TIMESTAMP                 = 140; // 1 1 1
    UNIT_FIELD_PETEXPERIENCE                      = 141; // 1 1 4 
	  UNIT_FIELD_PETNEXTLEVELEXP                    = 142; // 1 1 4
	  UNIT_DYNAMIC_FLAGS                            = 143; // 1 1 256
	  UNIT_CHANNEL_SPELL                            = 144; // 1 1 1
	  UNIT_MOD_CAST_SPEED                           = 145; // 1 1 1
	  UNIT_CREATED_BY_SPELL                         = 146; // 1 1 1
	  UNIT_NPC_FLAGS                                = 147; // 1 1 1
	  UNIT_NPC_EMOTESTATE                           = 148; // 1 1 1
	  UNIT_TRAINING_POINTS                          = 149; // 1 2 4
	  UNIT_FIELD_STAT0                              = 150; // 1 1 6    UNIT_FIELD_STRENGTH
	  UNIT_FIELD_STAT1                              = 151; // 1 1 6    UNIT_FIELD_AGILITY   
	  UNIT_FIELD_STAT2                              = 152; // 1 1 6    UNIT_FIELD_STAMINA   
	  UNIT_FIELD_STAT3                              = 153; // 1 1 6    UNIT_FIELD_SPIRIT    
	  UNIT_FIELD_STAT4                              = 154; // 1 1 6    UNIT_FIELD_INTELLECT 
	  UNIT_FIELD_RESISTANCES                        = 155; // 7 1 38   UNIT_FIELD_ARMOR
    UNIT_FIELD_BASE_MANA                          = 162; // 1 1 6
	  UNIT_FIELD_BASE_HEALTH                        = 163; // 1 1 6
	  UNIT_FIELD_BYTES_2                            = 164; // 1 5 1
	  UNIT_FIELD_ATTACK_POWER                       = 165; // 1 1 6
	  UNIT_FIELD_ATTACK_POWER_MODS                  = 166; // 1 2 6
	  UNIT_FIELD_ATTACK_POWER_MULTIPLIER            = 167; // 1 3 6
	  UNIT_FIELD_RANGED_ATTACK_POWER                = 168; // 1 1 6
	  UNIT_FIELD_RANGED_ATTACK_POWER_MODS           = 169; // 1 2 6
	  UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER     = 170; // 1 3 6
	  UNIT_FIELD_MINRANGEDDAMAGE                    = 171; // 1 3 6
	  UNIT_FIELD_MAXRANGEDDAMAGE                    = 172; // 1 3 6
	  UNIT_FIELD_POWER_COST_MODIFIER                = 173; // 7 1 6
	  UNIT_FIELD_POWER_COST_MULTIPLIER              = 180; // 7 3 6
	  UNIT_FIELD_PADDING                            = 187; // 1 1 0
    UNIT_END                                      = 188;

    PLAYER_SELECTION                                         = 188;
    PLAYER_DUEL_ARBITER                                      = 190;
    PLAYER_FLAGS                                             = 192;
    PLAYER_GUILDID                                           = 193;
    PLAYER_GUILDRANK                                         = 194;
    PLAYER_BYTES                                             = 195;
    PLAYER_BYTES_2                                           = 196;
    PLAYER_BYTES_3                                           = 197;
    PLAYER_DUEL_TEAM                                         = 198;
    PLAYER_GUILD_TIMESTAMP                                   = 199;
    PLAYER_QUEST_LOG_1_1                                     = 200;
    PLAYER_QUEST_LOG_1_2                                     = 201;
    PLAYER_QUEST_LOG_2_1                                     = 203;
    PLAYER_QUEST_LOG_2_2                                     = 204;
    PLAYER_QUEST_LOG_3_1                                     = 206;
    PLAYER_QUEST_LOG_3_2                                     = 207;
    PLAYER_QUEST_LOG_4_1                                     = 209;
    PLAYER_QUEST_LOG_4_2                                     = 210;
    PLAYER_QUEST_LOG_5_1                                     = 212;
    PLAYER_QUEST_LOG_5_2                                     = 213;
    PLAYER_QUEST_LOG_6_1                                     = 215;
    PLAYER_QUEST_LOG_6_2                                     = 216;
    PLAYER_QUEST_LOG_7_1                                     = 218;
    PLAYER_QUEST_LOG_7_2                                     = 219;
    PLAYER_QUEST_LOG_8_1                                     = 221;
    PLAYER_QUEST_LOG_8_2                                     = 222;
    PLAYER_QUEST_LOG_9_1                                     = 224;
    PLAYER_QUEST_LOG_9_2                                     = 225;
    PLAYER_QUEST_LOG_10_1                                    = 227;
    PLAYER_QUEST_LOG_10_2                                    = 228;
    PLAYER_QUEST_LOG_11_1                                    = 230;
    PLAYER_QUEST_LOG_11_2                                    = 231;
    PLAYER_QUEST_LOG_12_1                                    = 233;
    PLAYER_QUEST_LOG_12_2                                    = 234;
    PLAYER_QUEST_LOG_13_1                                    = 236;
    PLAYER_QUEST_LOG_13_2                                    = 237;
    PLAYER_QUEST_LOG_14_1                                    = 239;
    PLAYER_QUEST_LOG_14_2                                    = 240;
    PLAYER_QUEST_LOG_15_1                                    = 242;
    PLAYER_QUEST_LOG_15_2                                    = 243;
    PLAYER_QUEST_LOG_16_1                                    = 245;
    PLAYER_QUEST_LOG_16_2                                    = 246;
    PLAYER_QUEST_LOG_17_1                                    = 248;
    PLAYER_QUEST_LOG_17_2                                    = 249;
    PLAYER_QUEST_LOG_18_1                                    = 251;
    PLAYER_QUEST_LOG_18_2                                    = 252;
    PLAYER_QUEST_LOG_19_1                                    = 254;
    PLAYER_QUEST_LOG_19_2                                    = 255;
    PLAYER_QUEST_LOG_20_1                                    = 257;
    PLAYER_QUEST_LOG_20_2                                    = 258;
    PLAYER_VISIBLE_ITEM_1_CREATOR                            = 260;
    PLAYER_VISIBLE_ITEM_1_0                                  = 262;
    PLAYER_VISIBLE_ITEM_1_PROPERTIES                         = 270;
    PLAYER_VISIBLE_ITEM_1_PAD                                = 271;
    PLAYER_VISIBLE_ITEM_2_CREATOR                            = 272;
    PLAYER_VISIBLE_ITEM_2_0                                  = 274;
    PLAYER_VISIBLE_ITEM_2_PROPERTIES                         = 282;
    PLAYER_VISIBLE_ITEM_2_PAD                                = 283;
    PLAYER_VISIBLE_ITEM_3_CREATOR                            = 284;
    PLAYER_VISIBLE_ITEM_3_0                                  = 286;
    PLAYER_VISIBLE_ITEM_3_PROPERTIES                         = 294;
    PLAYER_VISIBLE_ITEM_3_PAD                                = 295;
    PLAYER_VISIBLE_ITEM_4_CREATOR                            = 296;
    PLAYER_VISIBLE_ITEM_4_0                                  = 298;
    PLAYER_VISIBLE_ITEM_4_PROPERTIES                         = 306;
    PLAYER_VISIBLE_ITEM_4_PAD                                = 307;
    PLAYER_VISIBLE_ITEM_5_CREATOR                            = 308;
    PLAYER_VISIBLE_ITEM_5_0                                  = 310;
    PLAYER_VISIBLE_ITEM_5_PROPERTIES                         = 318;
    PLAYER_VISIBLE_ITEM_5_PAD                                = 319;
    PLAYER_VISIBLE_ITEM_6_CREATOR                            = 320;
    PLAYER_VISIBLE_ITEM_6_0                                  = 322;
    PLAYER_VISIBLE_ITEM_6_PROPERTIES                         = 330;
    PLAYER_VISIBLE_ITEM_6_PAD                                = 331;
    PLAYER_VISIBLE_ITEM_7_CREATOR                            = 332;
    PLAYER_VISIBLE_ITEM_7_0                                  = 334;
    PLAYER_VISIBLE_ITEM_7_PROPERTIES                         = 342;
    PLAYER_VISIBLE_ITEM_7_PAD                                = 343;
    PLAYER_VISIBLE_ITEM_8_CREATOR                            = 344;
    PLAYER_VISIBLE_ITEM_8_0                                  = 346;
    PLAYER_VISIBLE_ITEM_8_PROPERTIES                         = 354;
    PLAYER_VISIBLE_ITEM_8_PAD                                = 355;
    PLAYER_VISIBLE_ITEM_9_CREATOR                            = 356;
    PLAYER_VISIBLE_ITEM_9_0                                  = 358;
    PLAYER_VISIBLE_ITEM_9_PROPERTIES                         = 366;
    PLAYER_VISIBLE_ITEM_9_PAD                                = 367;
    PLAYER_VISIBLE_ITEM_10_CREATOR                           = 368;
    PLAYER_VISIBLE_ITEM_10_0                                 = 370;
    PLAYER_VISIBLE_ITEM_10_PROPERTIES                        = 378;
    PLAYER_VISIBLE_ITEM_10_PAD                               = 379;
    PLAYER_VISIBLE_ITEM_11_CREATOR                           = 380;
    PLAYER_VISIBLE_ITEM_11_0                                 = 382;
    PLAYER_VISIBLE_ITEM_11_PROPERTIES                        = 390;
    PLAYER_VISIBLE_ITEM_11_PAD                               = 391;
    PLAYER_VISIBLE_ITEM_12_CREATOR                           = 392;
    PLAYER_VISIBLE_ITEM_12_0                                 = 394;
    PLAYER_VISIBLE_ITEM_12_PROPERTIES                        = 402;
    PLAYER_VISIBLE_ITEM_12_PAD                               = 403;
    PLAYER_VISIBLE_ITEM_13_CREATOR                           = 404;
    PLAYER_VISIBLE_ITEM_13_0                                 = 406;
    PLAYER_VISIBLE_ITEM_13_PROPERTIES                        = 414;
    PLAYER_VISIBLE_ITEM_13_PAD                               = 415;
    PLAYER_VISIBLE_ITEM_14_CREATOR                           = 416;
    PLAYER_VISIBLE_ITEM_14_0                                 = 418;
    PLAYER_VISIBLE_ITEM_14_PROPERTIES                        = 426;
    PLAYER_VISIBLE_ITEM_14_PAD                               = 427;
    PLAYER_VISIBLE_ITEM_15_CREATOR                           = 428;
    PLAYER_VISIBLE_ITEM_15_0                                 = 430;
    PLAYER_VISIBLE_ITEM_15_PROPERTIES                        = 438;
    PLAYER_VISIBLE_ITEM_15_PAD                               = 439;
    PLAYER_VISIBLE_ITEM_16_CREATOR                           = 440;
    PLAYER_VISIBLE_ITEM_16_0                                 = 442;
    PLAYER_VISIBLE_ITEM_16_PROPERTIES                        = 450;
    PLAYER_VISIBLE_ITEM_16_PAD                               = 451;
    PLAYER_VISIBLE_ITEM_17_CREATOR                           = 452;
    PLAYER_VISIBLE_ITEM_17_0                                 = 454;
    PLAYER_VISIBLE_ITEM_17_PROPERTIES                        = 462;
    PLAYER_VISIBLE_ITEM_17_PAD                               = 463;
    PLAYER_VISIBLE_ITEM_18_CREATOR                           = 464;
    PLAYER_VISIBLE_ITEM_18_0                                 = 466;
    PLAYER_VISIBLE_ITEM_18_PROPERTIES                        = 474;
    PLAYER_VISIBLE_ITEM_18_PAD                               = 475;
    PLAYER_VISIBLE_ITEM_19_CREATOR                           = 476;
    PLAYER_VISIBLE_ITEM_19_0                                 = 478;
    PLAYER_VISIBLE_ITEM_19_PROPERTIES                        = 486;
    PLAYER_VISIBLE_ITEM_19_PAD                               = 487;
    PLAYER_FIELD_INV_SLOT_HEAD                               = 488;
    PLAYER_FIELD_PACK_SLOT_1                                 = 534;
    PLAYER_FIELD_BANK_SLOT_1                                 = 566;
    PLAYER_FIELD_BANKBAG_SLOT_1                              = 614;
    PLAYER_FIELD_VENDORBUYBACK_SLOT_1                        = 626;
    PLAYER_FARSIGHT                                          = 650;
    PLAYER__FIELD_COMBO_TARGET                               = 652;
    PLAYER_XP                                                = 654;
    PLAYER_NEXT_LEVEL_XP                                     = 655;
    PLAYER_SKILL_INFO_1_1                                    = 656;
    PLAYER_CHARACTER_POINTS1                                 = 1040;
    PLAYER_CHARACTER_POINTS2                                 = 1041;
    PLAYER_TRACK_CREATURES                                   = 1042;
    PLAYER_TRACK_RESOURCES                                   = 1043;
    PLAYER_BLOCK_PERCENTAGE                                  = 1044;
    PLAYER_DODGE_PERCENTAGE                                  = 1045;
    PLAYER_PARRY_PERCENTAGE                                  = 1046;
    PLAYER_CRIT_PERCENTAGE                                   = 1047;
    PLAYER_RANGED_CRIT_PERCENTAGE                            = 1048;
    PLAYER_EXPLORED_ZONES_1                                  = 1049;
    PLAYER_REST_STATE_EXPERIENCE                             = 1113;
    PLAYER_FIELD_COINAGE                                     = 1114;
    PLAYER_FIELD_POSSTAT0                                    = 1115;
    PLAYER_FIELD_POSSTAT1                                    = 1116;
    PLAYER_FIELD_POSSTAT2                                    = 1117;
    PLAYER_FIELD_POSSTAT3                                    = 1118;
    PLAYER_FIELD_POSSTAT4                                    = 1119;
    PLAYER_FIELD_NEGSTAT0                                    = 1120;
    PLAYER_FIELD_NEGSTAT1                                    = 1121;
    PLAYER_FIELD_NEGSTAT2                                    = 1122;
    PLAYER_FIELD_NEGSTAT3                                    = 1123;
    PLAYER_FIELD_NEGSTAT4                                    = 1124;
    PLAYER_FIELD_RESISTANCEBUFFMODSPOSITIVE                  = 1125;
    PLAYER_FIELD_RESISTANCEBUFFMODSNEGATIVE                  = 1132;
    PLAYER_FIELD_MOD_DAMAGE_DONE_POS                         = 1139;
    PLAYER_FIELD_MOD_DAMAGE_DONE_NEG                         = 1146;
    PLAYER_FIELD_MOD_DAMAGE_DONE_PCT                         = 1153;
    PLAYER_FIELD_BYTES                                       = 1160;
    PLAYER_AMMO_ID                                           = 1161;
    PLAYER_SELF_RES_SPELL                                    = 1162;
    PLAYER_FIELD_PVP_MEDALS                                  = 1163;
    PLAYER_FIELD_BUYBACK_PRICE_1                             = 1164;
    PLAYER_FIELD_BUYBACK_TIMESTAMP_1                         = 1176;
    PLAYER_FIELD_SESSION_KILLS                               = 1188;
    PLAYER_FIELD_YESTERDAY_KILLS                             = 1189;
    PLAYER_FIELD_LAST_WEEK_KILLS                             = 1190;
    PLAYER_FIELD_THIS_WEEK_KILLS                             = 1191;
    PLAYER_FIELD_THIS_WEEK_CONTRIBUTION                      = 1192;
    PLAYER_FIELD_LIFETIME_HONORBALE_KILLS                    = 1193;
    PLAYER_FIELD_LIFETIME_DISHONORBALE_KILLS                 = 1194;
    PLAYER_FIELD_YESTERDAY_CONTRIBUTION                      = 1195;
    PLAYER_FIELD_LAST_WEEK_CONTRIBUTION                      = 1196;
    PLAYER_FIELD_LAST_WEEK_RANK                              = 1197;
    PLAYER_FIELD_BYTES2                                      = 1198;
    PLAYER_FIELD_WATCHED_FACTION_INDEX                       = 1199;
    PLAYER_END                                               = 1200;  //  0  INTERNALMARKER

	  OBJECT_FIELD_CREATED_BY                 =    6;  //  2  UINT64
	  GAMEOBJECT_DISPLAYID                    =    8;  //  1  UINT32
	  GAMEOBJECT_FLAGS                        =    9;  //  1  UINT32
	  GAMEOBJECT_ROTATION                     =   10;  //  4  ROTATION
	  GAMEOBJECT_STATE                        =   14;  //  1  UINT32
	  GAMEOBJECT_TIMESTAMP                    =   15;  //  1  UINT32
	  GAMEOBJECT_POS_X                        =   16;  //  1  FLOAT
	  GAMEOBJECT_POS_Y                        =   17;  //  1  FLOAT
	  GAMEOBJECT_POS_Z                        =   18;  //  1  FLOAT
	  GAMEOBJECT_FACING                       =   19;  //  1  FLOAT
	  GAMEOBJECT_DYN_FLAGS                    =   20;  //  1  UINT32
	  GAMEOBJECT_FACTION                      =   21;  //  1  UINT32
	  GAMEOBJECT_TYPE_ID                      =   22;  //  1  UINT32
	  GAMEOBJECT_LEVEL                        =   23;  //  1  UINT32
	  GAMEOBJECT_END                          =   24;  //  0  INTERNALMARKER

	  DYNAMICOBJECT_CASTER                    =    6;  //  2  UINT64
	  DYNAMICOBJECT_BYTES                     =    8;  //  1  UINT32
	  DYNAMICOBJECT_SPELLID                   =    9;  //  1  UINT32
	  DYNAMICOBJECT_RADIUS                    =   10;  //  1  UINT32
	  DYNAMICOBJECT_POS_X                     =   11;  //  1  UINT32
	  DYNAMICOBJECT_POS_Y                     =   12;  //  1  UINT32
	  DYNAMICOBJECT_POS_Z                     =   13;  //  1  UINT32
	  DYNAMICOBJECT_FACING                    =   14;  //  1  UINT32
	  DYNAMICOBJECT_PAD                       =   15;  //  1  UINT32
	  DYNAMICOBJECT_END                       =   16;  //  0  INTERNALMARKER

	  CORPSE_FIELD_OWNER                      =    6;  //  2  UINT64
	  CORPSE_FIELD_FACING                     =    8;  //  1  FLOAT
	  CORPSE_FIELD_POS_X                      =    9;  //  1  FLOAT
	  CORPSE_FIELD_POS_Y                      =   10;  //  1  FLOAT
	  CORPSE_FIELD_POS_Z                      =   11;  //  1  FLOAT
	  CORPSE_FIELD_DISPLAY_ID                 =   12;  //  1  UINT32
	  CORPSE_FIELD_ITEM                       =   13;  //  19 CORPSEITEMS
	  CORPSE_FIELD_BYTES_1                    =   32;  //  1  UINT32
	  CORPSE_FIELD_BYTES_2                    =   33;  //  1  UINT32
	  CORPSE_FIELD_GUILD                      =   34;  //  1  UINT32
	  CORPSE_FIELD_FLAGS                      =   35;  //  1  UINT32
	  CORPSE_FIELD_DYNAMIC_FLAGS              =   36;  //  1  UINT32
	  CORPSE_FIELD_PAD                        =   37;  //  1  UINT32
	  CORPSE_END                              =   38;  //  0  INTERNALMARKER

    UNIT_DYNFLAG_LOOTABLE			              = $0001;
    // Shows marked unit as small red dot on radar
    UNIT_DYNFLAG_TRACK_UNIT			            = $0002;
    // Gray mob title marks that mob is tagged by another player
    UNIT_DYNFLAG_OTHER_TAGGER		            = $0004;
    // Blocks player character from moving
    UNIT_DYNFLAG_ROOTED				              = $0008;
    // Shows infos like Damage and Health of the enemy
    UNIT_DYNFLAG_SPECIALINFO		            = $0010;
    // Unit falls on the ground and shows like dead
    UNIT_DYNFLAG_DEAD				                = $0020;

//    PLAYER_FLAGS

    PLAYER_FLAGS_GROUPLEADER                = 1;
    PLAYER_FLAGS_AFK                        = 2;
    PLAYER_FLAGS_DND                        = 4;
    PLAYER_FLAGS_GM                         = 8;
    PLAYER_FLAGS_DEAD                       = $10;
    PLAYER_FLAGS_RESTING                    = $20;
    PLAYER_FLAGS_FFAPVP                     = $80;

    BUYBACK_SLOT_END                        = 12;

    // PLAYER STATE TYPE

    PLAYER_STATE_NONE             = 0;
    PLAYER_STATE_SIT              = 1;
    PLAYER_STATE_SIT_CHAIR        = 2;
    PLAYER_STATE_SLEEP            = 3;
    PLAYER_STATE_SIT_LOW_CHAIR    = 4;
    PLAYER_STATE_SIT_MEDIUM_CHAIR = 5;
    PLAYER_STATE_SIT_HIGH_CHAIR   = 6;
    PLAYER_STATE_DEAD             = 7;
    PLAYER_STATE_KNEEL            = 8;

implementation

end.
