//////////////////////////////////////////////////////////
// DrNexus Incredible TwoHandedWeapons Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class IncredibleTwoHandedWeaponsDrops
	{
		public static Loot[]IncredibleTwoHandedWeapons = new Loot[]
		{
			new Loot( typeof( FieryWarAxe ), 78.472f )
				, new Loot( typeof( GrinningAxe ), 71.5398f )
				, new Loot( typeof( KangTheDecapitator ), 55.42f )
				, new Loot( typeof( Bonebiter ), 76.5238f )
				, new Loot( typeof( PendulumOfDoom ), 78.5108f )
				, new Loot( typeof( TheMinotaur ), 65.933f )
				, new Loot( typeof( WillOfTheMountainGiant ), 67.7222f )
				, new Loot( typeof( DarkIronSunderer ), 48.775f )
				, new Loot( typeof( AngerforgesBattleAxe ), 59.2644f )
				, new Loot( typeof( Beastslayer ), 58.95f )
				, new Loot( typeof( DreadforgeRetaliator ), 41.8968f )
				, new Loot( typeof( LimbCleaver ), 58.94621f )
				, new Loot( typeof( LordAlexandersBattleAxe ), 50.35941f )
				, new Loot( typeof( ExecutionersCleaver ), 68.033f )
				, new Loot( typeof( TheNicker ), 45.0752f )
				, new Loot( typeof( GravestoneWarAxe ), 33.2456f )
				, new Loot( typeof( GiganticWarAxe ), 77.2246f )
				, new Loot( typeof( ColossalGreatAxe ), 56.29881f )
				, new Loot( typeof( RazorAxe ), 48.2596f )
				, new Loot( typeof( DeathStriker ), 42.8914f )
				, new Loot( typeof( GatorbiteAxe ), 57.0482f )
				, new Loot( typeof( TaranIcebreaker ), 44.7106f )
				, new Loot( typeof( ConkHammer ), 74.62141f )
				, new Loot( typeof( MograinesMight ), 77.4328f )
				, new Loot( typeof( TheRockpounder ), 67.7512f )
				, new Loot( typeof( TheJackhammer ), 74.5362f )
				, new Loot( typeof( Ragehammer ), 63.2678f )
				, new Loot( typeof( DarkIronPulverizer ), 54.2394f )
				, new Loot( typeof( ForceOfMagma ), 58.1852f )
				, new Loot( typeof( ImperviousGiant ), 45.8328f )
				, new Loot( typeof( TheJudgesGavel ), 62.167f )
				, new Loot( typeof( EnchantedBattlehammer ), 51.8752f )
				, new Loot( typeof( HammerOfTheTitans ), 29.0872f )
				, new Loot( typeof( SeepingWillow ), 29.116f )
				, new Loot( typeof( BlanchardsStout ), 64.95741f )
				, new Loot( typeof( TwigOfTheWorldTree ), 43.4116f )
				, new Loot( typeof( FistOfOmokk ), 40.5896f )
				, new Loot( typeof( MalownsSlam ), 37.6192f )
				, new Loot( typeof( FrightskullShaft ), 40.1084f )
				, new Loot( typeof( GreaterMaul ), 78.4474f )
				, new Loot( typeof( RoyalMallet ), 71.1104f )
				, new Loot( typeof( Backbreaker ), 58.4822f )
				, new Loot( typeof( Painbringer ), 53.1768f )
				, new Loot( typeof( FierceMauler ), 45.5948f )
				, new Loot( typeof( PrincessTheradrasScepter ), 55.1366f )
				, new Loot( typeof( Destiny ), 29.9758f )
				, new Loot( typeof( Nightblade ), 70.4864f )
				, new Loot( typeof( TruesilverChampion ), 61.4514f )
				, new Loot( typeof( BattlefieldDestroyer ), 75.3388f )
				, new Loot( typeof( SulthrazeTheLasher ), 38.0638f )
				, new Loot( typeof( Stoneslayer ), 67.1484f )
				, new Loot( typeof( Deathblow ), 70.755f )
				, new Loot( typeof( Xcaliboar ), 79.8554f )
				, new Loot( typeof( StoneOfTheEarth ), 49.2602f )
				, new Loot( typeof( DrakefangButcher ), 57.5538f )
				, new Loot( typeof( Corruption ), 43.1916f )
				, new Loot( typeof( ArcaniteChampion ), 25.3804f )
				, new Loot( typeof( BladeOfTheTitans ), 67.61021f )
				, new Loot( typeof( Demonslayer ), 47.2f )
				, new Loot( typeof( Witchfury ), 77.0886f )
				, new Loot( typeof( Warmonger ), 58.3224f )
				, new Loot( typeof( Doombringer ), 40.8134f )
				, new Loot( typeof( RelentlessScythe ), 30.4624f )
				, new Loot( typeof( Demonshear ), 27.2302f )
				, new Loot( typeof( RunebladeOfBaronRivendare ), 8.655f )
				, new Loot( typeof( WarbladeOfCaerDarrow ), 30.174f )
				, new Loot( typeof( BarovianFamilySword ), 31.5736f )
				, new Loot( typeof( TuskerSword ), 72.094f )
				, new Loot( typeof( BeheadingBlade ), 68.4526f )
				, new Loot( typeof( DarkEspadon ), 64.4156f )
				, new Loot( typeof( GallantFlamberge ), 57.4544f )
				, new Loot( typeof( MassacreSword ), 52.4688f )
				, new Loot( typeof( ShinBlade ), 44.7656f )
				, new Loot( typeof( TaKierthanSongblade ), 46.402f )
		};
	}
}
