//////////////////////////////////////////////////////////
// DrNexus Incredible SwordsAndDaggers Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class IncredibleSwordsAndDaggersDrops
	{
		public static Loot[]IncredibleSwordsAndDaggers = new Loot[]
		{
			new Loot( typeof( Shadowblade ), 53.29f )
				, new Loot( typeof( GutRipper ), 72.9682f )
				, new Loot( typeof( Widowmaker ), 77.5204f )
				, new Loot( typeof( ScarletKris ), 40.149f )
				, new Loot( typeof( Gutwrencher ), 77.262f )
				, new Loot( typeof( JuliesDagger ), 63.8424f )
				, new Loot( typeof( EbonShiv ), 75.108f )
				, new Loot( typeof( Stealthblade ), 72.6338f )
				, new Loot( typeof( EnchantedAzshariteFelbaneDagger ), 57.9558f )
				, new Loot( typeof( LifeforceDirk ), 64.6846f )
				, new Loot( typeof( DireNail ), 59.5728f )
				, new Loot( typeof( HookfangShanker ), 64.54881f )
				, new Loot( typeof( BloodEtchedBlade ), 56.5086f )
				, new Loot( typeof( SkilledFightingBlade ), 59.6346f )
				, new Loot( typeof( SearingNeedle ), 71.1168f )
				, new Loot( typeof( KerisOfZulSerak ), 48.8006f )
				, new Loot( typeof( DeathStriker ), 24.3752f )
				, new Loot( typeof( FinklesSkinner ), 42.0088f )
				, new Loot( typeof( BarmanShanker ), 60.5882f )
				, new Loot( typeof( FangOfTheCrystalSpider ), 46.6116f )
				, new Loot( typeof( GiftOfTheElvenMagi ), 43.483f )
				, new Loot( typeof( Bonescraper ), 44.562f )
				, new Loot( typeof( Witchblade ), 47.6934f )
				, new Loot( typeof( Darrowspike ), 42.1932f )
				, new Loot( typeof( Frightalon ), 47.5778f )
				, new Loot( typeof( AlcorsSunrazor ), 21.2274f )
				, new Loot( typeof( VorpalDagger ), 76.7154f )
				, new Loot( typeof( DemonBlade ), 54.2952f )
				, new Loot( typeof( BloodstrikeDagger ), 49.424f )
				, new Loot( typeof( HuntTrackerBlade ), 66.1692f )
				, new Loot( typeof( BeasthunterDagger ), 56.708f )
				, new Loot( typeof( CharstoneDirk ), 64.5166f )
				, new Loot( typeof( SatyrsLash ), 71.2144f )
				, new Loot( typeof( BladeOfEternalDarkness ), 53.2034f )
				, new Loot( typeof( ShortswordOfVengeance ), 76.4432f )
				, new Loot( typeof( Bloodrazor ), 60.875f )
				, new Loot( typeof( KrolBlade ), 48.1422f )
				, new Loot( typeof( DazzlingMithrilRapier ), 79.9074f )
				, new Loot( typeof( PhantomBlade ), 74.4918f )
				, new Loot( typeof( HanzoSword ), 62.7134f )
				, new Loot( typeof( SangthrazeTheDeflector ), 78.8602f )
				, new Loot( typeof( JangthrazeTheProtector ), 71.6658f )
				, new Loot( typeof( BloodletterScalpel ), 78.93999f )
				, new Loot( typeof( EnchantedAzshariteFelbaneSword ), 58.1092f )
				, new Loot( typeof( Firebreather ), 64.9306f )
				, new Loot( typeof( BladeOfTheWretched ), 70.55859f )
				, new Loot( typeof( DragonsCall ), 43.0784f )
				, new Loot( typeof( ArbitersBlade ), 66.1646f )
				, new Loot( typeof( LordGeneralsSword ), 60.7454f )
				, new Loot( typeof( LinkensSwordOfMastery ), 65.8054f )
				, new Loot( typeof( BladeOfReckoning ), 59.788f )
				, new Loot( typeof( DoomforgedStraightedge ), 65.0742f )
				, new Loot( typeof( BlazingRapier ), 61.3516f )
				, new Loot( typeof( Frostguard ), 43.0568f )
				, new Loot( typeof( DalRendsTribalGuardian ), 39.6364f )
				, new Loot( typeof( DalRendsSacredCharge ), 45.1874f )
				, new Loot( typeof( SerpentSlicer ), 74.8588f )
				, new Loot( typeof( AssassinationBlade ), 59.0114f )
				, new Loot( typeof( PhaseBlade ), 69.1142f )
				, new Loot( typeof( ArgentAvenger ), 46.3772f )
				, new Loot( typeof( SkullforgeReaver ), 43.27f )
				, new Loot( typeof( SilentFang ), 43.1196f )
				, new Loot( typeof( EbonHiltOfMarduk ), 54.8156f )
				, new Loot( typeof( RuneSword ), 74.0678f )
				, new Loot( typeof( WidowBlade ), 69.004f )
				, new Loot( typeof( CrystalSword ), 62.9522f )
				, new Loot( typeof( DimensionalBlade ), 58.6236f )
				, new Loot( typeof( BattlefellSabre ), 56.507f )
				, new Loot( typeof( HolyWarSword ), 48.0536f )
				, new Loot( typeof( TidecrestBlade ), 66.1692f )
				, new Loot( typeof( BeaststalkerBlade ), 56.8572f )
				, new Loot( typeof( IntrepidShortsword ), 63.9174f )
				, new Loot( typeof( ValiantShortsword ), 64.1394f )
				, new Loot( typeof( MirahsSong ), 48.7268f )
				, new Loot( typeof( HameyasSlayer ), 58.0884f )
				, new Loot( typeof( JoonhosMercy ), 71.2116f )
				, new Loot( typeof( ThrashBlade ), 67.1456f )
				, new Loot( typeof( InventorsFocalSword ), 67.894f )
		};
	}
}
