//////////////////////////////////////////////////////////
// DrNexus Incredible MailArmors Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class IncredibleMailArmorsDrops
	{
		public static Loot[]IncredibleMailArmors = new Loot[]
		{
			new Loot( typeof( HelmOfNarv ), 72.3634f )
				, new Loot( typeof( EbonholdLeggings ), 79.642f )
				, new Loot( typeof( HerosBreastplate ), 73.0104f )
				, new Loot( typeof( HerosLeggings ), 73.7212f )
				, new Loot( typeof( OrnateBreastplate ), 76.6182f )
				, new Loot( typeof( OrnateLegguards ), 79.6036f )
				, new Loot( typeof( MercurialGreaves ), 79.8316f )
				, new Loot( typeof( MercurialBreastplate ), 68.7838f )
				, new Loot( typeof( MercurialLegguards ), 71.8624f )
				, new Loot( typeof( MercurialPauldrons ), 79.736f )
				, new Loot( typeof( EngravedBreastplate ), 74.3134f )
				, new Loot( typeof( EngravedLeggings ), 77.3842f )
				, new Loot( typeof( MasterworkBreastplate ), 67.6896f )
				, new Loot( typeof( MasterworkBoots ), 77.6036f )
				, new Loot( typeof( MasterworkCirclet ), 79.1344f )
				, new Loot( typeof( MasterworkLegplates ), 70.67619f )
				, new Loot( typeof( MasterworkPauldrons ), 78.8812f )
				, new Loot( typeof( PrismscaleHauberk ), 79.5952f )
				, new Loot( typeof( SavageGladiatorChain ), 66.4668f )
				, new Loot( typeof( SavageGladiatorLeggings ), 74.6638f )
				, new Loot( typeof( SearingscaleLeggings ), 79.8584f )
				, new Loot( typeof( RoyalDecoratedArmor ), 77.6986f )
				, new Loot( typeof( OutriderLeggings ), 79.47939f )
				, new Loot( typeof( DeathdealerBreastplate ), 75.40961f )
				, new Loot( typeof( BasaltscaleArmor ), 76.9452f )
				, new Loot( typeof( RadiantLeggings ), 74.6692f )
				, new Loot( typeof( BonespikeShoulder ), 74.5534f )
				, new Loot( typeof( WildthornMail ), 79.3576f )
				, new Loot( typeof( InvulnerableMail ), 56.1636f )
				, new Loot( typeof( LegguardsOfTheChromaticDefier ), 54.5176f )
				, new Loot( typeof( LegplatesOfTheChromaticDefier ), 57.435f )
				, new Loot( typeof( DragoneyeCoif ), 78.4154f )
				, new Loot( typeof( TristamLegguards ), 66.6116f )
				, new Loot( typeof( BreastplateOfTheChosen ), 64.0446f )
				, new Loot( typeof( WindrunnerLegguards ), 74.9342f )
				, new Loot( typeof( DrakesfireEpaulets ), 76.9168f )
				, new Loot( typeof( WindDancerBoots ), 77.4386f )
				, new Loot( typeof( CrownOfTyranny ), 74.6634f )
				, new Loot( typeof( WoolliesOfThePrancingMinstrel ), 73.1354f )
				, new Loot( typeof( TimmysGaloshes ), 78.8316f )
				, new Loot( typeof( WindreaverGreaves ), 76.6618f )
				, new Loot( typeof( MaelstromLeggings ), 68.6818f )
				, new Loot( typeof( BonebraceHauberk ), 66.1154f )
				, new Loot( typeof( RoyalCapSpaulders ), 79.33939f )
				, new Loot( typeof( BloodmailHauberk ), 67.4906f )
				, new Loot( typeof( BloodmailLegguards ), 72.815f )
				, new Loot( typeof( BloodlustBreastplate ), 75.963f )
				, new Loot( typeof( BloodlustBritches ), 79.4228f )
				, new Loot( typeof( GreenDragonscaleLeggings ), 77.518f )
				, new Loot( typeof( BlueDragonscaleBreastplate ), 75.59081f )
				, new Loot( typeof( BlueDragonscaleShoulders ), 79.4568f )
				, new Loot( typeof( BlackDragonscaleBreastplate ), 73.9286f )
				, new Loot( typeof( BlackDragonscaleShoulders ), 78.2634f )
				, new Loot( typeof( BlackDragonscaleLeggings ), 68.0666f )
				, new Loot( typeof( HeavyScorpidLeggings ), 78.2394f )
				, new Loot( typeof( IronhideBreastplate ), 79.7664f )
				, new Loot( typeof( MercilessSurcoat ), 77.7692f )
				, new Loot( typeof( ImpenetrableLegguards ), 74.48f )
				, new Loot( typeof( MagnificentLeggings ), 74.0712f )
				, new Loot( typeof( TriumphantSabatons ), 78.3064f )
				, new Loot( typeof( WillowBandHauberk ), 77.4078f )
				, new Loot( typeof( JadescaleBreastplate ), 77.4078f )
				, new Loot( typeof( VestOfElements ), 64.0376f )
				, new Loot( typeof( CoifOfElements ), 74.2212f )
				, new Loot( typeof( KiltOfElements ), 69.4586f )
				, new Loot( typeof( PauldronsOfElements ), 78.0048f )
				, new Loot( typeof( BootsOfElements ), 78.973f )
				, new Loot( typeof( BeaststalkersTunic ), 65.5648f )
				, new Loot( typeof( BeaststalkersBoots ), 78.57899f )
				, new Loot( typeof( BeaststalkersCap ), 75.1318f )
				, new Loot( typeof( BeaststalkersPants ), 68.3054f )
				, new Loot( typeof( BeaststalkersMantle ), 77.1774f )
		};
	}
}
