//////////////////////////////////////////////////////////
// DrNexus Medium PrimMaterials Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class MediumPrimMaterialsDrops
	{
		public static Loot[]MediumPrimMaterials = new Loot[]
		{
			new Loot( typeof( BloodOfTheMountain ), 40f )
				, new Loot( typeof( MossAgate ), 68f )
				, new Loot( typeof( Shadowgem ), 80f )
				, new Loot( typeof( LargeVenomSac ), 85.2f )
				, new Loot( typeof( Jade ), 44f )
				, new Loot( typeof( LesserMoonstone ), 52f )
				, new Loot( typeof( BlackDye ), 80f )
				, new Loot( typeof( IronOre ), 88f )
				, new Loot( typeof( GoldOre ), 60f )
				, new Loot( typeof( SpidersSilk ), 69f )
				, new Loot( typeof( KhadgarsWhisker ), 86f )
				, new Loot( typeof( BuzzardWing ), 85.5f )
				, new Loot( typeof( StrongFlux ), 60f )
				, new Loot( typeof( IronBar ), 84f )
				, new Loot( typeof( GoldBar ), 52f )
				, new Loot( typeof( Fadeleaf ), 90f )
				, new Loot( typeof( Goldthorn ), 88f )
				, new Loot( typeof( Coal ), 90f )
				, new Loot( typeof( MithrilOre ), 80f )
				, new Loot( typeof( MithrilBar ), 68f )
				, new Loot( typeof( Citrine ), 36f )
				, new Loot( typeof( MediumHide ), 90f )
				, new Loot( typeof( CuredMediumHide ), 84f )
				, new Loot( typeof( HeavyLeather ), 88f )
				, new Loot( typeof( HeavyHide ), 84f )
				, new Loot( typeof( CuredHeavyHide ), 82f )
				, new Loot( typeof( SilkenThread ), 90f )
				, new Loot( typeof( ThickLeather ), 76f )
				, new Loot( typeof( BoltOfSilkCloth ), 52f )
				, new Loot( typeof( SilkCloth ), 88f )
				, new Loot( typeof( ThickSpidersSilk ), 40f )
				, new Loot( typeof( MageweaveCloth ), 80f )
				, new Loot( typeof( YellowDye ), 90f )
				, new Loot( typeof( PurpleDye ), 50f )
				, new Loot( typeof( SmallFlameSac ), 80f )
				, new Loot( typeof( RaptorHide ), 83.3f )
				, new Loot( typeof( Firebloom ), 80f )
				, new Loot( typeof( ThievesTools ), 70f )
				, new Loot( typeof( SmallLustrousPearl ), 84f )
				, new Loot( typeof( IridescentPearl ), 40f )
				, new Loot( typeof( ThickMurlocScale ), 60f )
				, new Loot( typeof( IronShieldSpike ), 80f )
				, new Loot( typeof( IronCounterweight ), 60f )
				, new Loot( typeof( OrangeDye ), 80f )
				, new Loot( typeof( SilverRod ), 90f )
				, new Loot( typeof( EnchantedPowder ), 90f )
				, new Loot( typeof( ShadowcatHide ), 80f )
				, new Loot( typeof( Aquamarine ), 20f )
				, new Loot( typeof( TruesilverOre ), 60f )
				, new Loot( typeof( SolidGrindingStone ), 84f )
				, new Loot( typeof( MithrilShieldSpike ), 80f )
				, new Loot( typeof( MithrilSpurs ), 80f )
				, new Loot( typeof( BlackPearl ), 20f )
				, new Loot( typeof( WickedClaw ), 60f )
				, new Loot( typeof( DeeprockSalt ), 80f )
				, new Loot( typeof( FlaskOfMojo ), 80f )
				, new Loot( typeof( FlaskOfBigMojo ), 60f )
				, new Loot( typeof( ThickHide ), 60f )
				, new Loot( typeof( RuggedLeather ), 60f )
				, new Loot( typeof( RuggedHide ), 60f )
				, new Loot( typeof( CuredThickHide ), 60f )
				, new Loot( typeof( HeavySilkenThread ), 60f )
				, new Loot( typeof( ThickWolfhide ), 20f )
				, new Loot( typeof( PurpleLotus ), 76f )
				, new Loot( typeof( Blindweed ), 70f )
				, new Loot( typeof( GhostMushroom ), 70f )
				, new Loot( typeof( Gromsblood ), 80f )
				, new Loot( typeof( CrystalVial ), 50f )
				, new Loot( typeof( PhilosophersStone ), 80f )
				, new Loot( typeof( GhostDye ), 40f )
				, new Loot( typeof( LeadOre ), 80f )
				, new Loot( typeof( BlackVitriol ), 20f )
				, new Loot( typeof( ShadowSilk ), 20f )
				, new Loot( typeof( PinkDye ), 50f )
				, new Loot( typeof( ThoriumOre ), 80f )
				, new Loot( typeof( EngineersInk ), 60f )
				, new Loot( typeof( BlankParchment ), 90f )
				, new Loot( typeof( LesserMagicEssence ), 84f )
				, new Loot( typeof( GreaterMagicEssence ), 52f )
				, new Loot( typeof( StrangeDust ), 84f )
				, new Loot( typeof( SmallGlimmeringShard ), 20f )
				, new Loot( typeof( LesserAstralEssence ), 40f )
				, new Loot( typeof( SoulDust ), 52f )
				, new Loot( typeof( GoldenRod ), 60f )
				, new Loot( typeof( RunedGoldenRod ), 60f )
				, new Loot( typeof( VisionDust ), 20f )
				, new Loot( typeof( TruesilverRod ), 20f )
				, new Loot( typeof( DarkIronOre ), 60f )
				, new Loot( typeof( DarkIronBar ), 52f )
				, new Loot( typeof( GiantEgg ), 88f )
				, new Loot( typeof( TenderWolfMeat ), 88f )
				, new Loot( typeof( ThoriumBar ), 52f )
				, new Loot( typeof( DenseStone ), 80f )
				, new Loot( typeof( DenseGrindingStone ), 84f )
				, new Loot( typeof( EnchantedThoriumBar ), 60f )
				, new Loot( typeof( DemonicRune ), 52f )
				, new Loot( typeof( EnchantedLeather ), 60f )
				, new Loot( typeof( MountainSilversage ), 88f )
				, new Loot( typeof( Plaguebloom ), 80f )
				, new Loot( typeof( Icecap ), 80f )
				, new Loot( typeof( Runecloth ), 68f )
				, new Loot( typeof( CuredRuggedHide ), 60f )
				, new Loot( typeof( RefinedDeeprockSalt ), 20f )
				, new Loot( typeof( DevilsaurLeather ), 60f )
				, new Loot( typeof( WarbearLeather ), 52f )
				, new Loot( typeof( FrostsaberLeather ), 60f )
				, new Loot( typeof( ChimeraLeather ), 60f )
				, new Loot( typeof( GoldenSkeletonKey ), 76f )
				, new Loot( typeof( TruesilverSkeletonKey ), 50f )
				, new Loot( typeof( ArcaniteRod ), 20f )
				, new Loot( typeof( CoreLeather ), 20f )
		};
	}
}
