//////////////////////////////////////////////////////////
// DrNexus Medium MiscelenaousItems Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class MediumMiscelenaousItemsDrops
	{
		public static Loot[]MediumMiscelenaousItems = new Loot[]
		{
			new Loot( typeof( PointyCrocoliskTooth ), 74.7f )
				, new Loot( typeof( DireWolfFang ), 89f )
				, new Loot( typeof( HardSpiderLegTip ), 60.7f )
				, new Loot( typeof( BristlyWhisker ), 41.3f )
				, new Loot( typeof( RetractableClaw ), 80.5f )
				, new Loot( typeof( LongSoftTail ), 35.5f )
				, new Loot( typeof( CurvedRaptorTalon ), 51.5f )
				, new Loot( typeof( KeenRaptorTooth ), 64.4f )
				, new Loot( typeof( CurvedBasiliskClaw ), 69.9f )
				, new Loot( typeof( IntactBasiliskSpine ), 74.39999f )
				, new Loot( typeof( CrackedDragonMolting ), 90f )
				, new Loot( typeof( FleckedRaptorScale ), 86.5f )
				, new Loot( typeof( SoftPatchOfFur ), 51.8f )
				, new Loot( typeof( IvoryBoarTusk ), 74.3f )
				, new Loot( typeof( GelatinousGoo ), 84.4f )
				, new Loot( typeof( LifelessSkull ), 83.9f )
				, new Loot( typeof( BearGallBladder ), 60.1f )
				, new Loot( typeof( FamiliarHide ), 82.9f )
				, new Loot( typeof( FamiliarHorn ), 86.68f )
				, new Loot( typeof( PoisonedSpiderFang ), 85.2f )
				, new Loot( typeof( LargeBasiliskTail ), 42.9f )
				, new Loot( typeof( CoarseGorillaHair ), 51.3f )
				, new Loot( typeof( ChippedGorillaTooth ), 75.6f )
				, new Loot( typeof( TuftOfGorillaHair ), 9.500003f )
				, new Loot( typeof( SpiderPalp ), 73.5f )
				, new Loot( typeof( BrittleDragonBone ), 88f )
				, new Loot( typeof( RippedWingWebbing ), 86f )
				, new Loot( typeof( SmoothStoneChip ), 57.6f )
				, new Loot( typeof( JaggedPieceOfStone ), 67.1f )
				, new Loot( typeof( ShinyPolishedStone ), 43.3f )
				, new Loot( typeof( ThickScalyTail ), 87.6f )
				, new Loot( typeof( SpeckledShellFragment ), 27.7f )
				, new Loot( typeof( FieryGland ), 82f )
				, new Loot( typeof( SabertoothFang ), 37f )
				, new Loot( typeof( PatchOfFineFur ), 31f )
				, new Loot( typeof( SoftBushyTail ), 40.4f )
				, new Loot( typeof( ThickFurryMane ), 35f )
				, new Loot( typeof( LargeTrophyPaw ), 25f )
				, new Loot( typeof( DrippingSpiderMandible ), 53.3f )
				, new Loot( typeof( SmoothRaptorSkin ), 42.9f )
				, new Loot( typeof( TribalRaptorFeathers ), 35.4f )
				, new Loot( typeof( PristineRaptorSkull ), 28f )
				, new Loot( typeof( LongElegantFeather ), 57.6f )
				, new Loot( typeof( CurvedYellowBill ), 47.6f )
				, new Loot( typeof( EagleEye ), 66.9f )
				, new Loot( typeof( SteelLockbox ), 88f )
				, new Loot( typeof( ReinforcedSteelLockbox ), 84f )
				, new Loot( typeof( LifelessStone ), 71.2f )
				, new Loot( typeof( BurningPitch ), 53.8f )
				, new Loot( typeof( GlisteningFrenzyScale ), 40.7f )
				, new Loot( typeof( MarkOfTheSyndicate ), 80f )
				, new Loot( typeof( VibrantPlume ), 34f )
				, new Loot( typeof( LongTailHair ), 84.5f )
				, new Loot( typeof( DirtyKodoScale ), 87f )
				, new Loot( typeof( ThickKodoHair ), 77f )
				, new Loot( typeof( ChargedScale ), 87.6f )
				, new Loot( typeof( ShedLizardSkin ), 83.8f )
				, new Loot( typeof( SeepingGizzard ), 76f )
				, new Loot( typeof( ThinBlackClaw ), 88.6f )
				, new Loot( typeof( TornFurryEar ), 85.8f )
				, new Loot( typeof( BrightEyeball ), 82.6f )
				, new Loot( typeof( CrackedSilithidShell ), 82.5f )
				, new Loot( typeof( CrudePocketWatch ), 88.2f )
				, new Loot( typeof( AnExoticCookbook ), 74.2f )
				, new Loot( typeof( APrettyRock ), 89f )
				, new Loot( typeof( IntricateBauble ), 77.8f )
				, new Loot( typeof( EmptyHipFlask ), 87.6f )
				, new Loot( typeof( HickoryPipe ), 73.6f )
				, new Loot( typeof( Seaweed ), 83.7f )
				, new Loot( typeof( MithrilLockbox ), 80f )
				, new Loot( typeof( ThoriumLockbox ), 70f )
				, new Loot( typeof( EterniumLockbox ), 60f )
				, new Loot( typeof( RazorSharpBeak ), 35.68f )
				, new Loot( typeof( LargeHoof ), 74.5f )
				, new Loot( typeof( BloodyBatFang ), 89.60001f )
				, new Loot( typeof( HuskFragment ), 64.5f )
				, new Loot( typeof( DelicateInsectWing ), 49.7f )
				, new Loot( typeof( _19PoundCatfish ), 88f )
				, new Loot( typeof( _22PoundCatfish ), 85f )
				, new Loot( typeof( SturdyLockedChest ), 80f )
				, new Loot( typeof( _26PoundCatfish ), 80f )
				, new Loot( typeof( _32PoundCatfish ), 70f )
				, new Loot( typeof( DullElementalBracer ), 71f )
				, new Loot( typeof( BrokenBindingBracer ), 81f )
				, new Loot( typeof( ForkedTongue ), 81.7f )
				, new Loot( typeof( BrilliantScale ), 56.1f )
				, new Loot( typeof( BoxOfSupplies ), 88f )
				, new Loot( typeof( GreenWhelpScale ), 84f )
				, new Loot( typeof( ScorpidScale ), 80f )
				, new Loot( typeof( WornDragonscale ), 60f )
				, new Loot( typeof( WastewanderWaterPouch ), 86.3f )
				, new Loot( typeof( CatCarrierBombay ), 20f )
				, new Loot( typeof( CatCarrierCornishRex ), 20f )
				, new Loot( typeof( CatCarrierOrangeTabby ), 20f )
				, new Loot( typeof( CatCarrierSilverTabby ), 20f )
				, new Loot( typeof( ParrotCageGreenWingMacaw ), 20f )
				, new Loot( typeof( ParrotCageHyacinthMacaw ), 20f )
				, new Loot( typeof( ParrotCageSenegal ), 20f )
				, new Loot( typeof( ParrotCageCockatiel ), 20f )
				, new Loot( typeof( RabbitCrateSnowshoe ), 60f )
				, new Loot( typeof( SecurityDELTADataAccessCard ), 50f )
				, new Loot( typeof( HoopEarring ), 69.9f )
				, new Loot( typeof( AWoodenLeg ), 82.6f )
				, new Loot( typeof( AParrotSkeleton ), 81.8f )
				, new Loot( typeof( AHeadRag ), 81.7f )
				, new Loot( typeof( MechanicalChicken ), 20f )
				, new Loot( typeof( UnGoroSoil ), 88.3f )
				, new Loot( typeof( BasiliskScale ), 88.4f )
				, new Loot( typeof( SquishyBasiliskEye ), 45.9f )
				, new Loot( typeof( BasiliskHeart ), 18.9f )
				, new Loot( typeof( SpinedBatWing ), 83.6f )
				, new Loot( typeof( SeveredBatClaw ), 67.76f )
				, new Loot( typeof( SmallBatSkull ), 37.6f )
				, new Loot( typeof( BatHeart ), 53.6f )
				, new Loot( typeof( BatEar ), 33.6f )
				, new Loot( typeof( SleekBatPelt ), 3.600001f )
				, new Loot( typeof( RottingBearCarcass ), 86.5f )
				, new Loot( typeof( BearJaw ), 28.1f )
				, new Loot( typeof( BearFlank ), 59.7f )
				, new Loot( typeof( SavageBearClaw ), 53.7f )
				, new Loot( typeof( DelicateRibcage ), 73.7f )
				, new Loot( typeof( FeatheryWing ), 3.680003f )
				, new Loot( typeof( HollowWingBone ), 51.68f )
				, new Loot( typeof( ShinyBracelet ), 46.32f )
				, new Loot( typeof( _70PoundMightfish ), 90f )
				, new Loot( typeof( HeavyScorpidScale ), 60f )
				, new Loot( typeof( GreenDragonscale ), 60f )
				, new Loot( typeof( BlueDragonscale ), 60f )
				, new Loot( typeof( BlackDragonscale ), 20f )
		};
	}
}
