//////////////////////////////////////////////////////////
// DrNexus Medium NoCategory Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class MediumNoCategoryDrops
	{
		public static Loot[]MediumNoCategory = new Loot[]
		{
			new Loot( typeof( HakkariBlood ), 49.64f )
				, new Loot( typeof( SkinOfSweetRum ), 86.5f )
				, new Loot( typeof( CaskOfMerlot ), 83.7f )
				, new Loot( typeof( BottleOfMoonshine ), 74.7f )
				, new Loot( typeof( GreenHillsOfStranglethornPage1 ), 70f )
				, new Loot( typeof( GreenHillsOfStranglethornPage4 ), 70f )
				, new Loot( typeof( GreenHillsOfStranglethornPage6 ), 70f )
				, new Loot( typeof( GreenHillsOfStranglethornPage8 ), 70f )
				, new Loot( typeof( GreenHillsOfStranglethornPage10 ), 70f )
				, new Loot( typeof( GreenHillsOfStranglethornPage11 ), 70f )
				, new Loot( typeof( GreenHillsOfStranglethornPage14 ), 70f )
				, new Loot( typeof( GreenHillsOfStranglethornPage16 ), 70f )
				, new Loot( typeof( GreenHillsOfStranglethornPage18 ), 70f )
				, new Loot( typeof( GreenHillsOfStranglethornPage20 ), 70f )
				, new Loot( typeof( GreenHillsOfStranglethornPage21 ), 70f )
				, new Loot( typeof( GreenHillsOfStranglethornPage24 ), 70f )
				, new Loot( typeof( GreenHillsOfStranglethornPage25 ), 70f )
				, new Loot( typeof( GreenHillsOfStranglethornPage26 ), 70f )
				, new Loot( typeof( GreenHillsOfStranglethornPage27 ), 70f )
				, new Loot( typeof( EnchantedSeaKelp ), 87f )
				, new Loot( typeof( FieldTestingKit ), 80f )
				, new Loot( typeof( HippogryphEgg ), 84f )
				, new Loot( typeof( OrdinaryEgg ), 40f )
				, new Loot( typeof( BadEgg ), 80f )
				, new Loot( typeof( ShipSchedule ), 56.84f )
				, new Loot( typeof( PacketOfTharlendrisSeeds ), 80f )
				, new Loot( typeof( CrystalRestore ), 20f )
				, new Loot( typeof( CrystalWard ), 20f )
				, new Loot( typeof( CrystalSpire ), 20f )
				, new Loot( typeof( LongTailFeather ), 75.7f )
				, new Loot( typeof( TinyIronKey ), 88f )
				, new Loot( typeof( TombDust ), 90f )
				, new Loot( typeof( BlindingPowder ), 90f )
				, new Loot( typeof( SilkBandage ), 84f )
				, new Loot( typeof( HeavySilkBandage ), 68f )
				, new Loot( typeof( PerfectDeviateScale ), 60f )
				, new Loot( typeof( ElementalEarth ), 68f )
				, new Loot( typeof( ElementalFire ), 68f )
				, new Loot( typeof( ElementalAir ), 68f )
				, new Loot( typeof( ElementalWater ), 68f )
				, new Loot( typeof( NagaScale ), 88f )
				, new Loot( typeof( CoreOfEarth ), 68f )
				, new Loot( typeof( EssenceOfEarth ), 68f )
				, new Loot( typeof( HeartOfFire ), 68f )
				, new Loot( typeof( EssenceOfFire ), 68f )
				, new Loot( typeof( GlobeOfWater ), 68f )
				, new Loot( typeof( EssenceOfWater ), 68f )
				, new Loot( typeof( BreathOfWind ), 68f )
				, new Loot( typeof( EssenceOfAir ), 68f )
				, new Loot( typeof( IchorOfUndeath ), 68f )
				, new Loot( typeof( MageweaveBandage ), 68f )
				, new Loot( typeof( HeavyMageweaveBandage ), 52f )
				, new Loot( typeof( InlaidMithrilCylinder ), 20f )
				, new Loot( typeof( GoblinRocketFuel ), 80f )
				, new Loot( typeof( HeartOfTheWild ), 68f )
				, new Loot( typeof( StarWood ), 10f )
				, new Loot( typeof( LivingEssence ), 60f )
				, new Loot( typeof( EssenceOfUndeath ), 20f )
				, new Loot( typeof( StonescaleOil ), 90f )
				, new Loot( typeof( LightningEel ), 76f )
				, new Loot( typeof( PlatedArmorfish ), 72f )
				, new Loot( typeof( RuneclothBandage ), 60f )
				, new Loot( typeof( HeavyRuneclothBandage ), 20f )
				, new Loot( typeof( ArcaneDust ), 86f )
				, new Loot( typeof( ArcanePowder ), 80f )
				, new Loot( typeof( WildBerries ), 86f )
				, new Loot( typeof( WildRoot ), 86f )
				, new Loot( typeof( WildThornroot ), 80f )
				, new Loot( typeof( HolyCandle ), 86f )
				, new Loot( typeof( SacredCandle ), 80f )
				, new Loot( typeof( Ankh ), 60f )
				, new Loot( typeof( RuneOfTeleportation ), 80f )
				, new Loot( typeof( RuneOfPortals ), 60f )
				, new Loot( typeof( SymbolOfDivinity ), 60f )
				, new Loot( typeof( AshwoodSeed ), 84f )
				, new Loot( typeof( HornbeamSeed ), 72f )
				, new Loot( typeof( IronwoodSeed ), 60f )
		};
	}
}
