//////////////////////////////////////////////////////////
// DrNexus Medium RingsAndJewels Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class MediumRingsAndJewelsDrops
	{
		public static Loot[]MediumRingsAndJewels = new Loot[]
		{
			new Loot( typeof( DefiasRenegadeRing ), 48f )
				, new Loot( typeof( TotemOfInfliction ), 9.100002f )
				, new Loot( typeof( LavishlyJeweledRing ), 35f )
				, new Loot( typeof( GraysonsTorch ), 22.5f )
				, new Loot( typeof( OverseersRing ), 50f )
				, new Loot( typeof( RingOfIronWill ), 63f )
				, new Loot( typeof( PlainsRing ), 40f )
				, new Loot( typeof( BouquetOfScarletBegonias ), 54f )
				, new Loot( typeof( GrayWoolenShirt ), 84f )
				, new Loot( typeof( TranquilRing ), 46.8f )
				, new Loot( typeof( EyeOfPaleth ), 57f )
				, new Loot( typeof( RingOfTheUnderwood ), 47.5f )
				, new Loot( typeof( RingOfScorn ), 66.99999f )
				, new Loot( typeof( CaptainSandersShirt ), 89f )
				, new Loot( typeof( StitchesFemur ), 50f )
				, new Loot( typeof( RedRose ), 90f )
				, new Loot( typeof( BoldYellowShirt ), 20f )
				, new Loot( typeof( NightglowConcoction ), 51.4f )
				, new Loot( typeof( BloodboneBand ), 9.600001f )
				, new Loot( typeof( StylishRedShirt ), 80f )
				, new Loot( typeof( BrightYellowShirt ), 60f )
				, new Loot( typeof( DarkSilkShirt ), 4.000002f )
				, new Loot( typeof( FormalWhiteShirt ), 56f )
				, new Loot( typeof( IronforgeMemorialRing ), 29.4f )
				, new Loot( typeof( BloodRing ), 33f )
				, new Loot( typeof( AzorasWill ), 15.8f )
				, new Loot( typeof( CoralBand ), 23f )
				, new Loot( typeof( HeartRing ), 16.9f )
				, new Loot( typeof( DeckhandsShirt ), 86.04f )
				, new Loot( typeof( TotemicClanRing ), 48f )
				, new Loot( typeof( BountyHuntersRing ), 67.7f )
				, new Loot( typeof( TearOfGrief ), 63.8f )
				, new Loot( typeof( ClergyRing ), 55.5f )
				, new Loot( typeof( BlackWidowBand ), 48f )
				, new Loot( typeof( BlackPearlRing ), 7.700002f )
				, new Loot( typeof( EerieStableLantern ), 46.7f )
				, new Loot( typeof( StylishBlueShirt ), 80f )
				, new Loot( typeof( StylishGreenShirt ), 80f )
				, new Loot( typeof( ViridianBand ), 15.5f )
				, new Loot( typeof( BandOfElvenGrace ), 45.8f )
				, new Loot( typeof( MonkeyRing ), 28.2f )
				, new Loot( typeof( TigerBand ), 28.2f )
				, new Loot( typeof( SnakeHoop ), 28.2f )
				, new Loot( typeof( WhiteSwashbucklersShirt ), 60f )
				, new Loot( typeof( RedSwashbucklersShirt ), 40f )
				, new Loot( typeof( CeruleanRing ), 0.4999995f )
				, new Loot( typeof( ArcaneOrb ), 68f )
				, new Loot( typeof( LeyOrb ), 68f )
				, new Loot( typeof( WillowBranch ), 16.84f )
				, new Loot( typeof( RunicCane ), 46.7f )
				, new Loot( typeof( SeersFineStein ), 11.5f )
				, new Loot( typeof( The1Ring ), 9.600001f )
				, new Loot( typeof( GnomereganBand ), 0.4999995f )
				, new Loot( typeof( TorkWrench ), 37.4f )
				, new Loot( typeof( QuartzRing ), 62.84f )
				, new Loot( typeof( ZirconBand ), 12.98f )
				, new Loot( typeof( AmberHoop ), 20.24f )
				, new Loot( typeof( LeadBand ), 60.3f )
				, new Loot( typeof( ChromeRing ), 9.579998f )
				, new Loot( typeof( ClayRing ), 30.04f )
				, new Loot( typeof( MeadowRing ), 14.84f )
				, new Loot( typeof( PrairieRing ), 14.84f )
				, new Loot( typeof( SavannahRing ), 28.38f )
				, new Loot( typeof( RingOfTheMoon ), 33f )
				, new Loot( typeof( VolcanicRockRing ), 33f )
				, new Loot( typeof( DemonBand ), 33f )
				, new Loot( typeof( RingOfDefense ), 7.700002f )
				, new Loot( typeof( WhiteTraditionalHanbok ), 40.48f )
				, new Loot( typeof( JadefingerBaton ), 31.4f )
				, new Loot( typeof( VeildustMedicineBag ), 55f )
				, new Loot( typeof( BuccaneersOrb ), 8.120001f )
				, new Loot( typeof( JourneymansStave ), 64.84f )
				, new Loot( typeof( SpellbinderOrb ), 35.8f )
				, new Loot( typeof( DisciplesStein ), 57.8f )
				, new Loot( typeof( SimpleBranch ), 50.4f )
				, new Loot( typeof( AncestralOrb ), 58.98f )
				, new Loot( typeof( RunicStave ), 32.98f )
				, new Loot( typeof( MysticsSphere ), 10.1f )
				, new Loot( typeof( BeadedOrb ), 66f )
				, new Loot( typeof( NativeBranch ), 53.04f )
				, new Loot( typeof( AboriginalRod ), 14.84f )
				, new Loot( typeof( RitualStein ), 6.300002f )
				, new Loot( typeof( HornRing ), 29.5f )
				, new Loot( typeof( BandOfTheFist ), 29.5f )
				, new Loot( typeof( GreenHolidayShirt ), 40f )
				, new Loot( typeof( BlessedRelic ), 90f )
				, new Loot( typeof( SpiritRelic ), 80f )
				, new Loot( typeof( RelicOfTheDead ), 90f )
				, new Loot( typeof( RelicOfTruth ), 80f )
				, new Loot( typeof( BeautifulWildflowers ), 60f )
				, new Loot( typeof( RedSparkler ), 80f )
				, new Loot( typeof( WhiteSparkler ), 80f )
				, new Loot( typeof( BlueSparkler ), 80f )
		};
	}
}
