//////////////////////////////////////////////////////////
// DrNexus Medium SwordsAndDaggers Treasure list
//////////////////////////////////////////////////////////
using Server;
namespace Server.Items
{
	public class MediumSwordsAndDaggersDrops
	{
		public static Loot[]MediumSwordsAndDaggers = new Loot[]
		{
			new Loot( typeof( SmallHandBlade ), 69.46f )
				, new Loot( typeof( SlicerBlade ), 5.239999f )
				, new Loot( typeof( GiantTarantulaFang ), 29.64f )
				, new Loot( typeof( JeweledDagger ), 74.88f )
				, new Loot( typeof( LongCrawlerLimb ), 27.04f )
				, new Loot( typeof( CarvingKnife ), 67.68f )
				, new Loot( typeof( BuzzerBlade ), 5.659997f )
				, new Loot( typeof( Jambiya ), 52.2f )
				, new Loot( typeof( Poniard ), 27f )
				, new Loot( typeof( CraftsmansDagger ), 49.9f )
				, new Loot( typeof( SharpKitchenKnife ), 81.68f )
				, new Loot( typeof( StonesplinterDagger ), 52.08f )
				, new Loot( typeof( CurvedDagger ), 39.42f )
				, new Loot( typeof( FishermanKnife ), 75.94f )
				, new Loot( typeof( SmallDagger ), 55.96f )
				, new Loot( typeof( HuntingKnife ), 18.86f )
				, new Loot( typeof( CeremonialKnife ), 77.34f )
				, new Loot( typeof( SmallGreenDagger ), 85.36f )
				, new Loot( typeof( WarKnife ), 2.079999f )
				, new Loot( typeof( LongBayonet ), 85.74f )
				, new Loot( typeof( JaggedDagger ), 67.46f )
				, new Loot( typeof( CompactFightingKnife ), 61.2f )
				, new Loot( typeof( RazormaneBackstabber ), 75.24f )
				, new Loot( typeof( RitualBlade ), 26.98f )
				, new Loot( typeof( ThreshadonFang ), 68.22f )
				, new Loot( typeof( PruningKnife ), 85f )
				, new Loot( typeof( EluniteDagger ), 29.88f )
				, new Loot( typeof( HaggardsDagger ), 32.22f )
				, new Loot( typeof( UmbralDagger ), 31.96f )
				, new Loot( typeof( HeirloomDagger ), 31.44f )
				, new Loot( typeof( CopperDagger ), 80.54f )
				, new Loot( typeof( BladeOfCunning ), 53.12f )
				, new Loot( typeof( ThungrimsDagger ), 30.14f )
				, new Loot( typeof( CurvewoodDagger ), 41.74f )
				, new Loot( typeof( NotchedShortsword ), 75.52f )
				, new Loot( typeof( Cutlass ), 59.54f )
				, new Loot( typeof( WellUsedSword ), 85.6f )
				, new Loot( typeof( RedridgeMachete ), 17.62f )
				, new Loot( typeof( CommonersSword ), 80.62f )
				, new Loot( typeof( StockShortsword ), 49.86f )
				, new Loot( typeof( WarpedBlade ), 1.200002f )
				, new Loot( typeof( DefiasRapier ), 21.24f )
				, new Loot( typeof( Scimitar ), 23.7f )
				, new Loot( typeof( RockjawBlade ), 88.62f )
				, new Loot( typeof( StonesplinterBlade ), 85.36f )
				, new Loot( typeof( RodentiaShortsword ), 86.08f )
				, new Loot( typeof( Gladius ), 89.28f )
				, new Loot( typeof( CopperShortsword ), 88.98f )
				, new Loot( typeof( ShortSabre ), 89f )
				, new Loot( typeof( DeathstalkerShortsword ), 81.18f )
				, new Loot( typeof( DarylsShortsword ), 2.780002f )
				, new Loot( typeof( EnamelledBroadsword ), 42.46f )
				, new Loot( typeof( FeralBlade ), 51.86f )
				, new Loot( typeof( HarpyWingClipper ), 82.02f )
				, new Loot( typeof( PaleSkinner ), 61.34f )
				, new Loot( typeof( EluniteSword ), 30.38f )
				, new Loot( typeof( UmbralSword ), 31.18f )
				, new Loot( typeof( HaggardsSword ), 30.92f )
				, new Loot( typeof( HeirloomSword ), 30.92f )
				, new Loot( typeof( ThungrimsSword ), 29.62f )
				, new Loot( typeof( BriarsteelShortsword ), 41.92f )
		};
	}
}
