#ifndef SPELL_H
#define SPELL_H

#include "stdafx.h"
#include "WoWObject.h"
#include "DataBuffer.h"
#include "Client.h"
#include "dbc_structs.h"
#include "Packets.h"

enum SpellFailureReasons
{
	SPELL_FAIL_ABILITY_IS_NOT_READY_YET = 0x39,
	SPELL_FAIL_ALREADY_AT_FULL_HEALTH = 1,
	SPELL_FAIL_ALREADY_AT_FULL_RAGE = 2,
	SPELL_FAIL_ALREADY_BEEN_TAMED = 3,
	SPELL_FAIL_ALREADY_CONTROL_A_CREATURE = 4,
	SPELL_FAIL_ALREADY_CONTROL_A_SUMMONED_CREATURE = 5,
	SPELL_FAIL_ALREADY_OPEN = 6,
	SPELL_FAIL_AMNO_NEEDED = 0x2C,
	SPELL_FAIL_A_MORE_POWERFUL_SPELL_ALREADY_ACTIVE = 7,
	SPELL_FAIL_ANOTHER_ACTION_IS_IN_PROGRESS = 0x5B,
	SPELL_FAIL_CANNOT_DO_WHILE_SILENCED = 90,
	SPELL_FAIL_CANNOT_DISENCHANT_WHILE_LOOTING = 0x7C,
	SPELL_FAIL_CANNOT_USED_WHILE_MOUNTED = 0x36,
	SPELL_FAIL_CAN_ONLY_BE_USED_DURING_THE_DAY = 0x4B,
	SPELL_FAIL_CAN_ONLY_BE_USED_DURING_THE_NIGHT = 0x4C,
	SPELL_FAIL_CAN_ONLY_USE_IN_BATTLEGROUND = 0x7F,
	SPELL_FAIL_CAN_ONLY_USE_INDOOR = 0x4C,
	SPELL_FAIL_CAN_ONLY_USE_MOUNTED = 0x4D,
	SPELL_FAIL_CAN_ONLY_USE_OUTSIDE = 0x4F,
	SPELL_FAIL_CAN_ONLY_USE_WHILE_SWIMMING = 0x52,
	SPELL_FAIL_CANNOT_BE_CHARMED = 11,
	SPELL_FAIL_CANNOT_USE_SHAPESHIFT_FORM = 0x3A,
	SPELL_FAIL_CANNOT_CAST_AS_GHOST = 0x3F,
	SPELL_FAIL_CANNOT_CAST_WHILE_FATIGUED = 120,
	SPELL_FAIL_CANNOT_CAST_WHILE_TRADING = 0x7A,
	SPELL_FAIL_CANNOT_DO_THAT_WHILE_CONFUSED = 20,
	SPELL_FAIL_CANNOT_DO_THAT_WHILE_FLEEING = 0x1B,
	SPELL_FAIL_CANNOT_DO_WHILE_MOVING = 0x2B,
	SPELL_FAIL_CANNOT_DO_WHILE_STUNED = 0x5E,
	SPELL_FAIL_CANNOT_TARGET_PLAYER = 0x67,
	SPELL_FAIL_CANNOT_USE_ITEM_WHILE_SHAPESHIFT = 70,
	SPELL_FAIL_CANNOT_USE_WHILE_SWIMMING = 0x4A,
	SPELL_FAIL_CANNOT_USE_THIS_ABILITY_WHILE_PACIFIED = 0x54,
	SPELL_FAIL_CREATURE_IS_NOT_SKINNABLE = 110,
	SPELL_FAIL_CREATURE_MUST_BE_LOOTED_FIRST = 0x6A,
	SPELL_FAIL_DONT_HAVE_A_TARGET = 9,
	SPELL_FAIL_DUELING_ISNT_ALLOWED_HERE = 0x43,
	SPELL_FAIL_FAILED = 8,
	SPELL_FAIL_FAILED_ATTEMPT = 0x74,
	SPELL_FAIL_FIZZLED = 0x1A,
	SPELL_FAIL_IMMUNE = 0x1F,
	SPELL_FAIL_INTERNAL_ERROR = 0x19,
	SPELL_FAIL_INTERRUPTED = 0x20,
	SPELL_FAIL_INTERRUPTED2 = 0x21,
	SPELL_FAIL_INVALID_TARGET = 10,
	SPELL_FAIL_ITEM_CANNOT_BE_DISENCHANTED = 12,
	SPELL_FAIL_ITEM_IS_ALREADY_ENCHANTED = 0x22,
	SPELL_FAIL_ITEM_IS_GONE = 0x23,
	SPELL_FAIL_ITEM_IS_NOT_READY_YET = 0x25,
	SPELL_FAIL_MUST_HAVE_A_NEW_ITEM_EQUIPPED = 0x18,
	SPELL_FAIL_MUST_HAVE_A_NEW_ITEM_EQUIPPED_IN_MAIN_HAND = 0x17,
	SPELL_FAIL_MUST_HAVE_A_PROPER_ITEM_EQUIPPED = 0x16,
	SPELL_FAIL_NO_CHARGE_REMAINS = 0x41,
	SPELL_FAIL_NO_PATH_AVAILABLE = 0x2F,
	SPELL_FAIL_NO_POCKET_TO_PICK = 0x6C,
	SPELL_FAIL_NOT_ENOUGH_ENDURANCE = 0x44,
	SPELL_FAIL_NOT_ENOUGH_MANA = 0x49,
	SPELL_FAIL_NOT_ENOUGH_TRAINING_POINTS = 0x73,
	SPELL_FAIL_NOT_IN_COMBAT = 0,
	SPELL_FAIL_OUT_OF_AMNO = 0x40,
	SPELL_FAIL_OUT_OF_RANGE = 0x53,
	SPELL_FAIL_REQUIRE = 0x58,
	SPELL_FAIL_REQUIRED = 0x2D,
	SPELL_FAIL_REQUIRED_EXOTIC_AMNO = 0x2E,
	SPELL_FAIL_SKILL_NOT_HIGH_ENOUGH = 0x29,
	SPELL_FAIL_SPELL_CANNOT_CAST_HERE = 50,
	SPELL_FAIL_SPELL_NOT_LEARNED = 0x35,
	SPELL_FAIL_SUCCESS = -1,
	SPELL_FAIL_TARGET_HAS_NOT_WEAPON_EQUIPED = 0x6D,
	SPELL_FAIL_TARGET_IS_ALIVE = 0x68,
	SPELL_FAIL_TARGET_IS_CURRENTLY_DUELING = 0x62,
	SPELL_FAIL_TARGET_IS_CURRENTLY_IN_FREE_FOR_ALL_PVP_COMBAT = 0x7D,
	SPELL_FAIL_TARGET_IS_FRIENDLY = 0x65,
	SPELL_FAIL_TARGET_IS_HOSTILE = 0x63,
	SPELL_FAIL_TARGET_IS_IN_COMBAT = 0x60,
	SPELL_FAIL_TARGET_IS_NOT_IN_YOUR_PARTY = 0x69,
	SPELL_FAIL_TARGET_IS_NOT_IN_YOUR_PARTY2 = 0x7B,
	SPELL_FAIL_TARGET_IS_TAPPED = 13,
	SPELL_FAIL_TARGET_IS_TOO_ENRAGED_TO_BE_CHARMED = 100,
	SPELL_FAIL_TARGET_IS_TOO_HIGH_LEVEL = 0x1D,
	SPELL_FAIL_TARGET_IS_TOO_LOW_LEVEL = 40,
	SPELL_FAIL_TARGET_MUST_BE_IN_THIS_INSTANCE = 0x79,
	SPELL_FAIL_TARGET_NEEDS_TO_BE_BEHIND_YOU = 0x75,
	SPELL_FAIL_TARGET_NEEDS_TO_BE_FRONT_OF_YOU = 0x76,
	SPELL_FAIL_TARGET_NOT_IN_LINE_OF_SIGHT = 0x27,
	SPELL_FAIL_TARGET_TOO_CLOSE = 0x70,
	SPELL_FAIL_THAT_FOOD_LEVEL_IS_NOT_ENOUGH_FOR_YOUR_PET = 0x1C,
	SPELL_FAIL_THERE_ARE_NO_NEARBY_CORPSES_TO_EAT = 0x7E,
	SPELL_FAIL_THE_SPELL_IS_NOT_AVAILABLE_FOR_YOU = 0x5D,
	SPELL_FAIL_THE_TARGET_CANNOT_BE_IN_COMBAT = 0x66,
	SPELL_FAIL_THE_TARGET_IS_DEAD = 0x5F,
	SPELL_FAIL_THERE_ARENT_ANY_FISH_HERE = 0x45,
	SPELL_FAIL_THIS_ABILITY_REQUIRE_COMBO_POINT = 0x42,
	SPELL_FAIL_THIS_IS_ALREADY_BEING_USED = 0x13,
	SPELL_FAIL_TOO_CLOSE_TO_ENEMIES = 0x10,
	SPELL_FAIL_TRIED_TO_ENCHANT_AN_ITEM_THAT_DOESNT_EXIST = 0x24,
	SPELL_FAIL_TRY_TO_ENCHANT_A_TRADE_ITEM_BUT_NOT_TRADING = 0x3D,
	SPELL_FAIL_UNKNOWN3 = 0x56,
	SPELL_FAIL_UNKNOWN4 = 0x6B,
	SPELL_FAIL_UNKNOWN = 0x15,
	SPELL_FAIL_UNKNOWN2 = 0x4E,
	SPELL_FAIL_UNKNOWN_REASON = 0x80,
	SPELL_FAIL_UNKNOWN_SUCCESS112 = 0x72,
	SPELL_FAIL_YOO_ARE_TOO_FULL_TO_EAT = 30,
	SPELL_FAIL_YOU_ARE_DEAD = 0x12,
	SPELL_FAIL_YOU_ARE_NOT_ENOUGH_LEVEL = 0x26,
	SPELL_FAIL_YOU_ARE_POSSESSED = 0x55,
	SPELL_FAIL_YOU_ARE_UNABLE_TO_MOVE = 0x59,
	SPELL_FAIL_YOU_CAN_ONLY_USE_THIS_ON_A_OBJECT_YOU_OWN = 60,
	SPELL_FAIL_YOU_CANNOT_DO_THAT_YET = 0x11,
	SPELL_FAIL_YOU_CANNOT_DO_THAT_YET2 = 0x61,
	SPELL_FAIL_YOU_CANNOT_MOUNT_HERE = 0x47,
	SPELL_FAIL_YOU_CANNOT_START_A_DUEL_WHILE_INVISIBLE = 14,
	SPELL_FAIL_YOU_CANNOT_START_A_DUEL_WHILE_STEALTH = 15,
	SPELL_FAIL_YOU_DO_NOT_HAVE_A_PET = 0x48,
	SPELL_FAIL_YOU_HAVE_ALREADY_LEARNED_THAT_SPELL = 0x5C,
	SPELL_FAIL_YOU_HAVE_TO_BE_UNSHEATHED_TO_DO_THAT = 0x3E,
	SPELL_FAIL_YOU_HAVE_TOO_MANY_OF_THAT_ITEM = 0x71,
	SPELL_FAIL_YOU_HAVE_TO_BE_STANDING_TO_DO_THAT = 0x3B,
	SPELL_FAIL_YOU_MUST_BE_BEHIND_YOUR_TARGET = 0x30,
	SPELL_FAIL_YOU_MUST_BE_IN_FRONT_OF_YOUR_TARGET = 0x33,
	SPELL_FAIL_YOU_MUST_BE_IN_STEALTH_MODE = 0x51,
	SPELL_FAIL_YOU_NEED_TO_BE_IN = 0x57,
	SPELL_FAIL_YOU_ARE_IN_FLIGHT = 0x37,
	SPELL_FAIL_YOU_ARE_NOT_IN_CONTROL_OF_YOUR_ACTIONS = 0x34,
	SPELL_FAIL_YOU_ARE_ON_TRANSPORT = 0x38,
	SPELL_FAIL_YOUR_CAST_DIDNT_FALL_IN_WATER = 0x31,
	SPELL_FAIL_YOUR_THIRST_IS_ALREADY_QUENCHED = 0x6F,
	SPELL_FAIL_YOUR_PET_DOESNT_LIKE_THAT_FOOD = 0x77,
	SPELL_FAIL_YOUR_WEAPON_HAND_IS_EMPTY = 0x2A
};

enum SPELLSTATES
{
	SPELL_STATE_NULL      = 0,
	SPELL_STATE_PREPARING = 1,
	SPELL_STATE_CASTING   = 2,
	SPELL_STATE_FINISHED  = 3,
	SPELL_STATE_IDLE      = 4
};

enum SPELLTARGETS
{
	TARGET_FLAG_SELF             = 0x0,
	TARGET_FLAG_UNIT             = 0x0002,
	TARGET_FLAG_OBJECT           = 0x0800,
	TARGET_FLAG_ITEM             = 0x1010,
	TARGET_FLAG_SOURCE_LOCATION  = 0x20,
	TARGET_FLAG_DEST_LOCATION    = 0x40,
	TARGET_FLAG_STRING           = 0x2000
};

class CSpell: public CWoWObject
{
public:
	CSpell(unsigned long SpellID);
	~CSpell(void);

	unsigned long Caster;
	unsigned long CastTime;
	unsigned long SpellID;
	unsigned long Target;
	unsigned long TargetType;
	unsigned short TargetFlag;
	unsigned long TargetMap[200][2]; // maximum of 8*25 targets
	unsigned char TargetCount;
	long NextAttackBaseDmg;
	_Location SrcLoc;
	_Location DestLoc;
	string strTarget;
	SpellRec SpellInfo;

	CClient *pClient;

	void Clear();
	void New();

	void CastSpellStart(CDataBuffer &Data);
	void CastSpell();

	void SendStartSpell(CDataBuffer &Data);
	void SendSpellResult();
	void SendSpellGo();
	void SendSpellLog();
	void SpellFail();
	void SpellFail(unsigned char reason);
	void SpellFail(unsigned char reason, char *msg);
	void SendSpellEffects(unsigned long target);
	long SendChannelStart();
	void SendNonMeleeDamageLog(long damage);

	void Cancel();
	void ProcessEvent(WoWEvent &Event);
	int GetTargets(_Location &Loc);

	long getPower(unsigned long spell, unsigned long effect);
	long getComboPower(unsigned long spell, unsigned long effect,unsigned long combopts);
	bool ValidateAction();
	void SpellDelay(void);
};

#endif // SPELL_H
