//------------------------------------------------------------------------------
//
//     This source code was auto-generated by biasha's tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     Time stamp: 13.10.2005 22:52:04
//
//------------------------------------------------------------------------------

#pragma once

#ifndef _UPDATEFIELDS_AUTO_H
#define _UPDATEFIELDS_AUTO_H

enum EObjectFields
{
	OBJECT_FIELD_GUID                       =    0,  //  2  UINT64
	OBJECT_FIELD_TYPE                       =    2,  //  1  UINT32
	OBJECT_FIELD_ENTRY                      =    3,  //  1  UINT32
	OBJECT_FIELD_SCALE_X                    =    4,  //  1  UINT32
	OBJECT_FIELD_PADDING                    =    5,  //  1  UINT32
	OBJECT_END                              =    6,  //  0  INTERNALMARKER
};

enum EItemFields
{
	ITEM_FIELD_OWNER                        =    6,  //  2  UINT64
	ITEM_FIELD_CONTAINED                    =    8,  //  2  UINT64
	ITEM_FIELD_CREATOR                      =   10,  //  2  UINT64
	ITEM_FIELD_GIFTCREATOR                  =   12,  //  2  UINT64
	ITEM_FIELD_STACK_COUNT                  =   14,  //  1  UINT32
	ITEM_FIELD_DURATION                     =   15,  //  1  UINT32
	ITEM_FIELD_SPELL_CHARGES                =   16,  //  5  SPELLCHARGES
	ITEM_FIELD_FLAGS                        =   21,  //  1  UINT32
	ITEM_FIELD_ENCHANTMENT                  =   22,  //  21 ENCHANTMENT
	ITEM_FIELD_PROPERTY_SEED                =   43,  //  1  UINT32
	ITEM_FIELD_RANDOM_PROPERTIES_ID         =   44,  //  1  UINT32
	ITEM_FIELD_ITEM_TEXT_ID                 =   45,  //  1  UINT32
	ITEM_FIELD_DURABILITY                   =   46,  //  1  UINT32
	ITEM_FIELD_MAXDURABILITY                =   47,  //  1  UINT32
	ITEM_END                                =   48,  //  0  INTERNALMARKER
};

enum EContainerFields
{
	CONTAINER_FIELD_NUM_SLOTS               =   48,  //  1  UINT32
	CONTAINER_ALIGN_PAD                     =   49,  //  1  UINT32
	CONTAINER_FIELD_SLOT_1                  =   50,  //  40 CONTAINERSLOTS
	CONTAINER_END                           =   90,  //  0  INTERNALMARKER
};

enum EUnitFields
{
	UNIT_FIELD_CHARM                        =    6,  //  2  UINT64
	UNIT_FIELD_SUMMON                       =    8,  //  2  UINT64
	UNIT_FIELD_CHARMEDBY                    =   10,  //  2  UINT64
	UNIT_FIELD_SUMMONEDBY                   =   12,  //  2  UINT64
	UNIT_FIELD_CREATEDBY                    =   14,  //  2  UINT64
	UNIT_FIELD_TARGET                       =   16,  //  2  UINT64
	UNIT_FIELD_PERSUADED                    =   18,  //  2  UINT64
	UNIT_FIELD_CHANNEL_OBJECT               =   20,  //  2  UINT64
	UNIT_FIELD_HEALTH                       =   22,  //  1  UINT32
	UNIT_FIELD_POWER1                       =   23,  //  1  UINT32
	UNIT_FIELD_POWER2                       =   24,  //  1  UINT32
	UNIT_FIELD_POWER3                       =   25,  //  1  UINT32
	UNIT_FIELD_POWER4                       =   26,  //  1  UINT32
	UNIT_FIELD_POWER5                       =   27,  //  1  UINT32
	UNIT_FIELD_MAXHEALTH                    =   28,  //  1  UINT32
	UNIT_FIELD_MAXPOWER1                    =   29,  //  1  UINT32
	UNIT_FIELD_MAXPOWER2                    =   30,  //  1  UINT32
	UNIT_FIELD_MAXPOWER3                    =   31,  //  1  UINT32
	UNIT_FIELD_MAXPOWER4                    =   32,  //  1  UINT32
	UNIT_FIELD_MAXPOWER5                    =   33,  //  1  UINT32
	UNIT_FIELD_LEVEL                        =   34,  //  1  UINT32
	UNIT_FIELD_FACTIONTEMPLATE              =   35,  //  1  UINT32
	UNIT_FIELD_BYTES_0                      =   36,  //  1  UINT32
	UNIT_VIRTUAL_ITEM_SLOT_DISPLAY          =   37,  //  3  SLOT
	UNIT_VIRTUAL_ITEM_INFO                  =   40,  //  6  ITEMINFO
	UNIT_FIELD_FLAGS                        =   46,  //  1  UINT32
	UNIT_FIELD_AURA                         =   47,  //  64 AURA
	UNIT_FIELD_AURAFLAGS                    =  111,  //  8  AURAFLAGS
	UNIT_FIELD_AURALEVELS                   =  119,  //  8  AURALEVELS
	UNIT_FIELD_AURAAPPLICATIONS             =  127,  //  16 AURAAPPLICATIONS
	UNIT_FIELD_AURASTATE                    =  143,  //  1  UINT32
	UNIT_FIELD_BASEATTACKTIME               =  144,  //  2  UINT64
	UNIT_FIELD_RANGEDATTACKTIME             =  146,  //  1  UINT32
	UNIT_FIELD_BOUNDINGRADIUS               =  147,  //  1  FLOAT
	UNIT_FIELD_COMBATREACH                  =  148,  //  1  FLOAT
	UNIT_FIELD_DISPLAYID                    =  149,  //  1  UINT32
	UNIT_FIELD_NATIVEDISPLAYID              =  150,  //  1  UINT32
	UNIT_FIELD_MOUNTDISPLAYID               =  151,  //  1  UINT32
	UNIT_FIELD_MINDAMAGE                    =  152,  //  1  FLOAT
	UNIT_FIELD_MAXDAMAGE                    =  153,  //  1  FLOAT
	UNIT_FIELD_MINOFFHANDDAMAGE             =  154,  //  1  FLOAT
	UNIT_FIELD_MAXOFFHANDDAMAGE             =  155,  //  1  FLOAT
	UNIT_FIELD_BYTES_1                      =  156,  //  1  UINT32
	UNIT_FIELD_PETNUMBER                    =  157,  //  1  UINT32
	UNIT_FIELD_PET_NAME_TIMESTAMP           =  158,  //  1  UINT32
	UNIT_FIELD_PETEXPERIENCE                =  159,  //  1  UINT32
	UNIT_FIELD_PETNEXTLEVELEXP              =  160,  //  1  UINT32
	UNIT_DYNAMIC_FLAGS                      =  161,  //  1  UINT32
	UNIT_CHANNEL_SPELL                      =  162,  //  1  UINT32
	UNIT_MOD_CAST_SPEED                     =  163,  //  1  UINT32
	UNIT_CREATED_BY_SPELL                   =  164,  //  1  UINT32
	UNIT_NPC_FLAGS                          =  165,  //  1  UINT32
	UNIT_NPC_EMOTESTATE                     =  166,  //  1  UINT32
	UNIT_TRAINING_POINTS                    =  167,  //  1  UINT32
	UNIT_FIELD_STAT0                        =  168,  //  1  UINT32
	UNIT_FIELD_STAT1                        =  169,  //  1  UINT32
	UNIT_FIELD_STAT2                        =  170,  //  1  UINT32
	UNIT_FIELD_STAT3                        =  171,  //  1  UINT32
	UNIT_FIELD_STAT4                        =  172,  //  1  UINT32
	UNIT_FIELD_RESISTANCES                  =  173,  //  7  RESISTANCES
	UNIT_FIELD_ATTACKPOWER                  =  180,  //  1  UINT32
	UNIT_FIELD_BASE_MANA                    =  181,  //  1  UINT32
	UNIT_FIELD_BASE_HEALTH                  =  182,  //  1  UINT32
	UNIT_FIELD_ATTACK_POWER_MODS            =  183,  //  1  UINT32
	UNIT_FIELD_BYTES_2                      =  184,  //  1  UINT32
	UNIT_FIELD_RANGEDATTACKPOWER            =  185,  //  1  UINT32
	UNIT_FIELD_RANGED_ATTACK_POWER_MODS     =  186,  //  1  UINT32
	UNIT_FIELD_MINRANGEDDAMAGE              =  187,  //  1  UINT32
	UNIT_FIELD_MAXRANGEDDAMAGE              =  188,  //  1  UINT32
	UNIT_FIELD_POWER_COST_MODIFIER          =  189,  //  1  UINT32
	UNIT_FIELD_POWER_COST_MULTIPLIER        =  190,  //  1  UINT32
	UNIT_FIELD_PADDING                      =  191,  //  1  UINT32
	UNIT_FIELD_UNKNOWN180                   =  192,  //  12 UNIT_UNKNOWN180
	UNIT_END                                =  204,  //  0  INTERNALMARKER
};

enum EPlayerFields
{
	PLAYER_SELECTION                        =  204,  //  2  UINT64
	PLAYER_DUEL_ARBITER                     =  206,  //  2  UINT64
	PLAYER_FLAGS                            =  208,  //  1  UINT32
	PLAYER_GUILDID                          =  209,  //  1  UINT32
	PLAYER_GUILDRANK                        =  210,  //  1  UINT32
	PLAYER_BYTES                            =  211,  //  1  UINT32
	PLAYER_BYTES_2                          =  212,  //  1  UINT32
	PLAYER_BYTES_3                          =  213,  //  1  UINT32
	PLAYER_DUEL_TEAM                        =  214,  //  1  UINT32
	PLAYER_GUILD_TIMESTAMP                  =  215,  //  1  UINT32
	PLAYER_QUEST_LOG_1_1                    =  216,  //  1  UINT32
	PLAYER_QUEST_LOG_1_2                    =  217,  //  2  UINT64
	PLAYER_QUEST_LOG_2_1                    =  219,  //  1  UINT32
	PLAYER_QUEST_LOG_2_2                    =  220,  //  2  UINT64
	PLAYER_QUEST_LOG_3_1                    =  222,  //  1  UINT32
	PLAYER_QUEST_LOG_3_2                    =  223,  //  2  UINT64
	PLAYER_QUEST_LOG_4_1                    =  225,  //  1  UINT32
	PLAYER_QUEST_LOG_4_2                    =  226,  //  2  UINT64
	PLAYER_QUEST_LOG_5_1                    =  228,  //  1  UINT32
	PLAYER_QUEST_LOG_5_2                    =  229,  //  2  UINT64
	PLAYER_QUEST_LOG_6_1                    =  231,  //  1  UINT32
	PLAYER_QUEST_LOG_6_2                    =  232,  //  2  UINT64
	PLAYER_QUEST_LOG_7_1                    =  234,  //  1  UINT32
	PLAYER_QUEST_LOG_7_2                    =  235,  //  2  UINT64
	PLAYER_QUEST_LOG_8_1                    =  237,  //  1  UINT32
	PLAYER_QUEST_LOG_8_2                    =  238,  //  2  UINT64
	PLAYER_QUEST_LOG_9_1                    =  240,  //  1  UINT32
	PLAYER_QUEST_LOG_9_2                    =  241,  //  2  UINT64
	PLAYER_QUEST_LOG_10_1                   =  243,  //  1  UINT32
	PLAYER_QUEST_LOG_10_2                   =  244,  //  2  UINT64
	PLAYER_QUEST_LOG_11_1                   =  246,  //  1  UINT32
	PLAYER_QUEST_LOG_11_2                   =  247,  //  2  UINT64
	PLAYER_QUEST_LOG_12_1                   =  249,  //  1  UINT32
	PLAYER_QUEST_LOG_12_2                   =  250,  //  2  UINT64
	PLAYER_QUEST_LOG_13_1                   =  252,  //  1  UINT32
	PLAYER_QUEST_LOG_13_2                   =  253,  //  2  UINT64
	PLAYER_QUEST_LOG_14_1                   =  255,  //  1  UINT32
	PLAYER_QUEST_LOG_14_2                   =  256,  //  2  UINT64
	PLAYER_QUEST_LOG_15_1                   =  258,  //  1  UINT32
	PLAYER_QUEST_LOG_15_2                   =  259,  //  2  UINT64
	PLAYER_QUEST_LOG_16_1                   =  261,  //  1  UINT32
	PLAYER_QUEST_LOG_16_2                   =  262,  //  2  UINT64
	PLAYER_QUEST_LOG_17_1                   =  264,  //  1  UINT32
	PLAYER_QUEST_LOG_17_2                   =  265,  //  2  UINT64
	PLAYER_QUEST_LOG_18_1                   =  267,  //  1  UINT32
	PLAYER_QUEST_LOG_18_2                   =  268,  //  2  UINT64
	PLAYER_QUEST_LOG_19_1                   =  270,  //  1  UINT32
	PLAYER_QUEST_LOG_19_2                   =  271,  //  2  UINT64
	PLAYER_QUEST_LOG_20_1                   =  273,  //  1  UINT32
	PLAYER_QUEST_LOG_20_2                   =  274,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_1_CREATOR           =  276,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_1_0                 =  278,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_1_PROPERTIES        =  286,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_1_PAD               =  287,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_2_CREATOR           =  288,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_2_0                 =  290,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_2_PROPERTIES        =  298,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_2_PAD               =  299,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_3_CREATOR           =  300,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_3_0                 =  302,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_3_PROPERTIES        =  310,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_3_PAD               =  311,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_4_CREATOR           =  312,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_4_0                 =  314,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_4_PROPERTIES        =  322,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_4_PAD               =  323,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_5_CREATOR           =  324,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_5_0                 =  326,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_5_PROPERTIES        =  334,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_5_PAD               =  335,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_6_CREATOR           =  336,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_6_0                 =  338,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_6_PROPERTIES        =  346,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_6_PAD               =  347,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_7_CREATOR           =  348,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_7_0                 =  350,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_7_PROPERTIES        =  358,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_7_PAD               =  359,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_8_CREATOR           =  360,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_8_0                 =  362,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_8_PROPERTIES        =  370,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_8_PAD               =  371,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_9_CREATOR           =  372,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_9_0                 =  374,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_9_PROPERTIES        =  382,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_9_PAD               =  383,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_10_CREATOR          =  384,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_10_0                =  386,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_10_PROPERTIES       =  394,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_10_PAD              =  395,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_11_CREATOR          =  396,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_11_0                =  398,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_11_PROPERTIES       =  406,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_11_PAD              =  407,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_12_CREATOR          =  408,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_12_0                =  410,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_12_PROPERTIES       =  418,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_12_PAD              =  419,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_13_CREATOR          =  420,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_13_0                =  422,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_13_PROPERTIES       =  430,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_13_PAD              =  431,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_14_CREATOR          =  432,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_14_0                =  434,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_14_PROPERTIES       =  442,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_14_PAD              =  443,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_15_CREATOR          =  444,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_15_0                =  446,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_15_PROPERTIES       =  454,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_15_PAD              =  455,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_16_CREATOR          =  456,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_16_0                =  458,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_16_PROPERTIES       =  466,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_16_PAD              =  467,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_17_CREATOR          =  468,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_17_0                =  470,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_17_PROPERTIES       =  478,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_17_PAD              =  479,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_18_CREATOR          =  480,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_18_0                =  482,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_18_PROPERTIES       =  490,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_18_PAD              =  491,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_19_CREATOR          =  492,  //  2  UINT64
	PLAYER_VISIBLE_ITEM_19_0                =  494,  //  8  VISIBLEITEMOCTET
	PLAYER_VISIBLE_ITEM_19_PROPERTIES       =  502,  //  1  UINT32
	PLAYER_VISIBLE_ITEM_19_PAD              =  503,  //  1  UINT32
	PLAYER_FIELD_INV_SLOT_HEAD              =  504,  //  46 INVSLOTS
	PLAYER_FIELD_PACK_SLOT_1                =  550,  //  32 PACKSLOTS
	PLAYER_FIELD_BANK_SLOT_1                =  582,  //  48 BANKSLOTS
	PLAYER_FIELD_BANKBAG_SLOT_1             =  630,  //  12 BANKBAGSLOTS
	PLAYER_FIELD_VENDORBUYBACK_SLOT_1       =  642,  //  24 VENDORBUYBACKSLOT
	PLAYER_FARSIGHT                         =  666,  //  2  UINT64
	PLAYER__FIELD_COMBO_TARGET              =  668,  //  2  UINT64
	PLAYER_XP                               =  670,  //  1  UINT32
	PLAYER_NEXT_LEVEL_XP                    =  671,  //  1  UINT32
	PLAYER_SKILL_INFO_1_1                   =  672,  //  384 SKILLSINFO
	PLAYER_CHARACTER_POINTS1                = 1056,  //  1  UINT32
	PLAYER_CHARACTER_POINTS2                = 1057,  //  1  UINT32
	PLAYER_TRACK_CREATURES                  = 1058,  //  1  UINT32
	PLAYER_TRACK_RESOURCES                  = 1059,  //  1  UINT32
	PLAYER_BLOCK_PERCENTAGE                 = 1060,  //  1  UINT32
	PLAYER_DODGE_PERCENTAGE                 = 1061,  //  1  UINT32
	PLAYER_PARRY_PERCENTAGE                 = 1062,  //  1  UINT32
	PLAYER_CRIT_PERCENTAGE                  = 1063,  //  1  UINT32
	PLAYER_RANGED_CRIT_PERCENTAGE           = 1064,  //  1  UINT32
	PLAYER_EXPLORED_ZONES_1                 = 1065,  //  64 EXPLOREDZONES
	PLAYER_REST_STATE_EXPERIENCE            = 1129,  //  1  UINT32
	PLAYER_FIELD_COINAGE                    = 1130,  //  1  UINT32
	PLAYER_FIELD_POSSTAT0                   = 1131,  //  1  UINT32
	PLAYER_FIELD_POSSTAT1                   = 1132,  //  1  UINT32
	PLAYER_FIELD_POSSTAT2                   = 1133,  //  1  UINT32
	PLAYER_FIELD_POSSTAT3                   = 1134,  //  1  UINT32
	PLAYER_FIELD_POSSTAT4                   = 1135,  //  1  UINT32
	PLAYER_FIELD_NEGSTAT0                   = 1136,  //  1  UINT32
	PLAYER_FIELD_NEGSTAT1                   = 1137,  //  1  UINT32
	PLAYER_FIELD_NEGSTAT2                   = 1138,  //  1  UINT32
	PLAYER_FIELD_NEGSTAT3                   = 1139,  //  1  UINT32
	PLAYER_FIELD_NEGSTAT4                   = 1140,  //  1  UINT32
	PLAYER_FIELD_RESISTANCEBUFFMODSPOSITIVE = 1141,  //  7  RESISTANCES
	PLAYER_FIELD_RESISTANCEBUFFMODSNEGATIVE = 1148,  //  7  RESISTANCES
	PLAYER_FIELD_MOD_DAMAGE_DONE_POS        = 1155,  //  7  RESISTANCES
	PLAYER_FIELD_MOD_DAMAGE_DONE_NEG        = 1162,  //  7  RESISTANCES
	PLAYER_FIELD_MOD_DAMAGE_DONE_PCT        = 1169,  //  7  RESISTANCES
	PLAYER_FIELD_BYTES                      = 1176,  //  1  UINT32
	PLAYER_AMMO_ID                          = 1177,  //  1  UINT32
	PLAYER_SELF_RES_SPELL                   = 1178,  //  1  UINT32
	PLAYER_FIELD_PVP_MEDALS                 = 1179,  //  1  UINT32
	PLAYER_FIELD_BUYBACK_PRICE_1            = 1180,  //  1  UINT32
	PLAYER_FIELD_BUYBACK_TIMESTAMP_1        = 1181,  //  1  UINT32
	PLAYER_FIELD_SESSION_KILLS              = 1182,  //  1  UINT32
	PLAYER_FIELD_YESTERDAY_KILLS            = 1183,  //  1  UINT32
	PLAYER_FIELD_LAST_WEEK_KILLS            = 1184,  //  1  UINT32
	PLAYER_FIELD_THIS_WEEK_KILLS            = 1185,  //  1  UINT32
	PLAYER_FIELD_THIS_WEEK_CONTRIBUTION     = 1186,  //  1  UINT32
	PLAYER_FIELD_LIFETIME_HONORBALE_KILLS   = 1187,  //  1  UINT32
	PLAYER_FIELD_LIFETIME_DISHONORBALE_KILLS= 1188,  //  1  UINT32
	PLAYER_FIELD_YESTERDAY_CONTRIBUTION     = 1189,  //  1  UINT32
	PLAYER_FIELD_LAST_WEEK_CONTRIBUTION     = 1190,  //  1  UINT32
	PLAYER_FIELD_LAST_WEEK_RANK             = 1191,  //  1  UINT32
	PLAYER_FIELD_BYTES2                     = 1192,  //  1  UINT32
	PLAYER_FIELD_PADDING                    = 1193,  //  1  UINT32
	PLAYER_FIELD_UNKNOWN180                 = 1194,  //  44 PLAYER_UNKNOWN180
	PLAYER_END                              = 1238,  //  0  INTERNALMARKER
};

enum EGameObjectFields
{
	OBJECT_FIELD_CREATED_BY                 =    6,  //  2  UINT64
	GAMEOBJECT_DISPLAYID                    =    8,  //  1  UINT32
	GAMEOBJECT_FLAGS                        =    9,  //  1  UINT32
	GAMEOBJECT_ROTATION                     =   10,  //  4  ROTATION
	GAMEOBJECT_STATE                        =   14,  //  1  UINT32
	GAMEOBJECT_TIMESTAMP                    =   15,  //  1  UINT32
	GAMEOBJECT_POS_X                        =   16,  //  1  FLOAT
	GAMEOBJECT_POS_Y                        =   17,  //  1  FLOAT
	GAMEOBJECT_POS_Z                        =   18,  //  1  FLOAT
	GAMEOBJECT_FACING                       =   19,  //  1  FLOAT
	GAMEOBJECT_DYN_FLAGS                    =   20,  //  1  UINT32
	GAMEOBJECT_FACTION                      =   21,  //  1  UINT32
	GAMEOBJECT_TYPE_ID                      =   22,  //  1  UINT32
	GAMEOBJECT_LEVEL                        =   23,  //  1  UINT32
	GAMEOBJECT_END                          =   24,  //  0  INTERNALMARKER
};

enum EDynamicObjectFields
{
	DYNAMICOBJECT_CASTER                    =    6,  //  2  UINT64
	DYNAMICOBJECT_BYTES                     =    8,  //  1  UINT32
	DYNAMICOBJECT_SPELLID                   =    9,  //  1  UINT32
	DYNAMICOBJECT_RADIUS                    =   10,  //  1  UINT32
	DYNAMICOBJECT_POS_X                     =   11,  //  1  UINT32
	DYNAMICOBJECT_POS_Y                     =   12,  //  1  UINT32
	DYNAMICOBJECT_POS_Z                     =   13,  //  1  UINT32
	DYNAMICOBJECT_FACING                    =   14,  //  1  UINT32
	DYNAMICOBJECT_PAD                       =   15,  //  1  UINT32
	DYNAMICOBJECT_END                       =   16,  //  0  INTERNALMARKER
};

enum ECorpseFields
{
	CORPSE_FIELD_OWNER                      =    6,  //  2  UINT64
	CORPSE_FIELD_FACING                     =    8,  //  1  FLOAT
	CORPSE_FIELD_POS_X                      =    9,  //  1  FLOAT
	CORPSE_FIELD_POS_Y                      =   10,  //  1  FLOAT
	CORPSE_FIELD_POS_Z                      =   11,  //  1  FLOAT
	CORPSE_FIELD_DISPLAY_ID                 =   12,  //  1  UINT32
	CORPSE_FIELD_ITEM                       =   13,  //  19 CORPSEITEMS
	CORPSE_FIELD_BYTES_1                    =   32,  //  1  UINT32
	CORPSE_FIELD_BYTES_2                    =   33,  //  1  UINT32
	CORPSE_FIELD_GUILD                      =   34,  //  1  UINT32
	CORPSE_FIELD_FLAGS                      =   35,  //  1  UINT32
	CORPSE_FIELD_DYNAMIC_FLAGS              =   36,  //  1  UINT32
	CORPSE_FIELD_PAD                        =   37,  //  1  UINT32
	CORPSE_END                              =   38,  //  0  INTERNALMARKER
};

#endif
