import os

Import('lua_env')

lua_srcs = [
    'lapi.c',
    'lcode.c',
    'ldebug.c',
    'ldo.c',
    'ldump.c',
    'lfunc.c',
    'lgc.c',
    'llex.c',
    'lmem.c',
    'lobject.c',
    'lopcodes.c',
    'lparser.c',
    'lstate.c',
    'lstring.c',
    'ltable.c',
    'ltests.c',
    'ltm.c',
    'lundump.c',
    'lvm.c',
    'lzio.c',
    ]

lua_incs = [
    'lapi.h',
    'lauxlib.h',
    'lcode.h',
    'ldebug.h',
    'ldo.h',
    'lfunc.h',
    'lgc.h',
    'llex.h',
    'llimits.h',
    'lmem.h',
    'lobject.h',
    'lopcodes.h',
    'lparser.h',
    'lstate.h',
    'lstring.h',
    'ltable.h',
    'ltm.h',
    'lua.h',
    'lualib.h',
    'lundump.h',
    'lvm.h',
    'lzio.h',
    ]

lua_lib = lua_env.Library('lua', lua_srcs)
lua_env.Default(lua_lib)
lua_env.Alias('lua', lua_lib)
lua_env.Alias('shared', lua_lib)

if lua_env['buildenv'] == 'win32-msvc':
    msvsproj = lua_env.MSVSProject(
        target='lua' + lua_env['MSVSPROJECTSUFFIX'],
        srcs=lua_srcs,
        incs=lua_incs,
        buildtarget=lua_lib,
        variant='SCons')
    lua_env.Default(msvsproj)
    lua_env.Alias('lua', msvsproj)
    pass
