using System;
using System.Collections;
using Server;
using Server.Items;

namespace Server.Items
{
  public class SkullsplitterDrops
  {
   //Creature Id = 696
       public static Loot[] SkullsplitterAxeThrower = new Loot[] {
                                 new Loot( typeof( TrollSweat ), 28.8f )
                               , new Loot( typeof( SkullsplitterTusk ), 17.0f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.72f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.70f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.70f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.70f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.67f )
                               , new Loot( typeof( SplitBoneNecklace ), 8.01f )
                               , new Loot( typeof( SilkCloth ), 28.1f )
                               , new Loot( typeof( MageweaveCloth ), 4.52f )
                               , new Loot( typeof( FlaskOfMojo ), 9.19f )
                                 };
   //Creature Id = 784
       public static Loot[] SkullsplitterBeastmaster = new Loot[] {
                                 new Loot( typeof( TrollSweat ), 28.5f )
                               , new Loot( typeof( SkullsplitterTusk ), 9.47f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.71f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.84f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.58f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.44f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.88f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.53f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.60f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.58f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.71f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.83f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.73f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.76f )
                               , new Loot( typeof( SplitBoneNecklace ), 8.41f )
                               , new Loot( typeof( SilkCloth ), 9.62f )
                               , new Loot( typeof( MageweaveCloth ), 22.1f )
                               , new Loot( typeof( FlaskOfMojo ), 8.67f )
                                 };
   //Creature Id = 783
       public static Loot[] SkullsplitterBerserker = new Loot[] {
                                 new Loot( typeof( TrollSweat ), 28.8f )
                               , new Loot( typeof( SkullsplitterTusk ), 3.93f )
                               , new Loot( typeof( SkullsplitterHelm ), 0.97f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.53f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.80f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.80f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.70f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.58f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.79f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.65f )
                               , new Loot( typeof( SplitBoneNecklace ), 5.03f )
                               , new Loot( typeof( SilkCloth ), 8.75f )
                               , new Loot( typeof( MageweaveCloth ), 21.4f )
                               , new Loot( typeof( FlaskOfMojo ), 8.89f )
                                 };
   //Creature Id = 1059
       public static Loot[] AnathekTheCruel = new Loot[] {
                                 new Loot( typeof( TrollSweat ), 24.3f )
                               , new Loot( typeof( SkullsplitterTusk ), 3.31f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.59f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.59f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.53f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.59f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 1.00f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.94f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.59f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.47f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.94f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.53f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.71f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.41f )
                               , new Loot( typeof( BrokenArmorOfAnathek ), 50.4f )
                               , new Loot( typeof( SplitBoneNecklace ), 5.02f )
                               , new Loot( typeof( SilkCloth ), 7.98f )
                               , new Loot( typeof( MageweaveCloth ), 18.5f )
                               , new Loot( typeof( FlaskOfBigMojo ), 6.27f )
                                 };
   //Creature Id = 1060
       public static Loot[] MoghTheUndying = new Loot[] {
                                 new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.31f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.45f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.41f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.77f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.45f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.72f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.54f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.31f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.72f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.72f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.54f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.50f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.68f )
                               , new Loot( typeof( SilkCloth ), 11.7f )
                               , new Loot( typeof( MageweaveCloth ), 13.4f )
                               , new Loot( typeof( TheLegacyHeart ), 62.2f )
                               , new Loot( typeof( FlaskOfBigMojo ), 7.65f )
                                 };
   //Creature Id = 781
       public static Loot[] SkullsplitterHeadhunter = new Loot[] {
                                 new Loot( typeof( TrollSweat ), 28.3f )
                               , new Loot( typeof( SkullsplitterTusk ), 3.15f )
                               , new Loot( typeof( SkullsplitterHelm ), 0.93f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.82f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.61f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.87f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.62f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.70f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.72f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.62f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.79f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.86f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.61f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.68f )
                               , new Loot( typeof( SplitBoneNecklace ), 4.42f )
                               , new Loot( typeof( SilkCloth ), 9.00f )
                               , new Loot( typeof( MageweaveCloth ), 21.9f )
                               , new Loot( typeof( SolidStone ), 0.02f )
                               , new Loot( typeof( FlaskOfMojo ), 8.72f )
                                 };
   //Creature Id = 669
       public static Loot[] SkullsplitterHunter = new Loot[] {
                                 new Loot( typeof( TrollSweat ), 27.9f )
                               , new Loot( typeof( SkullsplitterTusk ), 8.07f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.80f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.48f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.75f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.79f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 1.02f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.78f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.70f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.72f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.77f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.66f )
                               , new Loot( typeof( SplitBoneNecklace ), 8.05f )
                               , new Loot( typeof( SilkCloth ), 8.59f )
                               , new Loot( typeof( MageweaveCloth ), 21.8f )
                               , new Loot( typeof( ZestyClamMeat ), 0.01f )
                               , new Loot( typeof( FlaskOfMojo ), 9.01f )
                                 };                                 
   //Creature Id = 780
       public static Loot[] SkullsplitterMystic = new Loot[] {
                                 new Loot( typeof( TrollSweat ), 28.8f )
                               , new Loot( typeof( SkullsplitterTusk ), 15.0f )
                               , new Loot( typeof( SkullsplitterFetish ), 7.44f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.61f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.71f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.71f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.65f )
                               , new Loot( typeof( SplitBoneNecklace ), 8.59f )
                               , new Loot( typeof( SilkCloth ), 28.1f )
                               , new Loot( typeof( MageweaveCloth ), 4.54f )
                               , new Loot( typeof( FlaskOfMojo ), 9.14f )
                                 };
   //Creature Id = 756
       public static Loot[] SkullsplitterPanther = new Loot[] {
                                 new Loot( typeof( MageweaveCloth ), 6.66f )
                               , new Loot( typeof( TruesilverBar ), 6.66f )
                               , new Loot( typeof( SolidStone ), 6.66f )
                                 };
   //Creature Id = 782
       public static Loot[] SkullsplitterScout = new Loot[] {
                                 new Loot( typeof( TrollSweat ), 28.6f )
                               , new Loot( typeof( SkullsplitterTusk ), 9.92f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.55f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.61f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.80f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.55f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.59f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.72f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.71f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.71f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.75f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.62f )
                               , new Loot( typeof( ZulMamweTrophy ), 0.01f )
                               , new Loot( typeof( SplitBoneNecklace ), 7.51f )
                               , new Loot( typeof( SilkCloth ), 8.87f )
                               , new Loot( typeof( MageweaveCloth ), 21.8f )
                               , new Loot( typeof( FlaskOfMojo ), 9.21f )
                                 };
/*	please have a look at this*/
   //Creature Id = 11390
       public static Loot[] SkullsplitterSpeaker = new Loot[] {new Loot( typeof( Aquamarine), 0.179946f ) 
,new Loot( typeof( CabalistCloak), 0.029991f ) 
,new Loot( typeof( CaptainsShoulderguards), 0.029991f ) 
,new Loot( typeof( ChromiteBarbute), 0.039988f ) 
,new Loot( typeof( Citrine), 0.029991f ) 
,new Loot( typeof( HematiteLink), 0.029991f ) 
,new Loot( typeof( MistscapeGloves), 0.029991f ) 
,new Loot( typeof( RangerLeggings), 0.039988f ) 
,new Loot( typeof( RecipeWildvinePotion), 0.239928f ) 
,new Loot( typeof( SniperRifle), 0.029991f ) 
,new Loot( typeof( SpiritchaserStaff), 0.049985f ) 
,new Loot( typeof( SteelLockbox), 0.149955f ) 
,new Loot( typeof( TrackersWristguards), 0.039988f ) 
,new Loot( typeof( CuredHamSteak), 4.82855f ) 
,new Loot( typeof( FlaskOfMojo), 9.24723f ) 
,new Loot( typeof( GreaterManaPotion), 0.789763f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage1), 0.689793f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage10), 0.589823f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage11), 0.639808f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage14), 0.59982f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage16), 0.739778f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage18), 0.779766f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage20), 0.619814f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage21), 0.639808f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage24), 0.649805f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage25), 0.739778f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage26), 0.59982f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage27), 0.719784f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage4), 0.749775f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage6), 0.669799f ) 
,new Loot( typeof( GreenHillsOfStranglethornPage8), 0.579826f ) 
,new Loot( typeof( JourneymansBackpack), 0.039988f ) 
,new Loot( typeof( MageweaveCloth), 22.2033f ) 
,new Loot( typeof( MoonberryJuice), 2.22933f ) 
,new Loot( typeof( ScrollOfIntellectIII), 0.19994f ) 
,new Loot( typeof( ScrollOfProtectionIII), 0.309907f ) 
,new Loot( typeof( ScrollOfSpiritIII), 0.19994f ) 
,new Loot( typeof( ScrollOfStaminaIII), 0.139958f ) 
,new Loot( typeof( SilkCloth), 8.96731f ) 
,new Loot( typeof( SkullsplitterTusk), 3.48895f ) 
,new Loot( typeof( SplitBoneNecklace), 4.95851f ) 
,new Loot( typeof( SuperiorHealingPotion), 1.37959f ) 
,new Loot( typeof( Wildvine), 5.94822f ) 
,new Loot( typeof( BalancedLongBow), 0.079976f ) 
,new Loot( typeof( BlockingTarge), 0.029991f ) 
,new Loot( typeof( BluntingMace), 0.049985f ) 
,new Loot( typeof( CrochetBelt), 0.09997f ) 
,new Loot( typeof( CrochetBoots), 0.109967f ) 
,new Loot( typeof( CrochetBracers), 0.089973f ) 
,new Loot( typeof( CrochetHat), 0.039988f ) 
,new Loot( typeof( CrochetPants), 0.029991f ) 
,new Loot( typeof( CrochetShoulderpads), 0.069979f ) 
,new Loot( typeof( CrochetVest), 0.079976f ) 
,new Loot( typeof( CrushingMaul), 0.129961f ) 
,new Loot( typeof( FinePointedDagger), 0.109967f ) 
,new Loot( typeof( HeavyFlintAxe), 0.089973f ) 
,new Loot( typeof( HeavyWarStaff), 0.149955f ) 
,new Loot( typeof( OverlinkedChainArmor), 0.029991f ) 
,new Loot( typeof( OverlinkedChainBelt), 0.049985f ) 
,new Loot( typeof( OverlinkedChainBracers), 0.069979f ) 
,new Loot( typeof( OverlinkedChainCloak), 0.049985f ) 
,new Loot( typeof( OverlinkedChainGloves), 0.039988f ) 
,new Loot( typeof( OverlinkedChainPants), 0.029991f ) 
,new Loot( typeof( OverlinkedCoif), 0.049985f ) 
,new Loot( typeof( ProtectivePavise), 0.039988f ) 
,new Loot( typeof( SentinelMusket), 0.149955f ) 
,new Loot( typeof( SharpShortsword), 0.109967f ) 
,new Loot( typeof( SplinteringBattleAxe), 0.079976f ) 
,new Loot( typeof( ThickCloak), 0.039988f ) 
,new Loot( typeof( ThickLeatherBelt), 0.119964f ) 
,new Loot( typeof( ThickLeatherBoots), 0.029991f ) 
,new Loot( typeof( ThickLeatherBracers), 0.039988f ) 
,new Loot( typeof( ThickLeatherGloves), 0.09997f ) 
,new Loot( typeof( ThickLeatherHat), 0.029991f ) 
,new Loot( typeof( ThickLeatherPants), 0.029991f ) 
,new Loot( typeof( ThickLeatherTunic), 0.09997f ) 
,new Loot( typeof( TrollSweat), 28.9013f ) 
,new Loot( typeof( WhettedClaymore), 0.049985f ) 
};


   //Creature Id = 672
       public static Loot[] SkullsplitterSpiritchaser = new Loot[] {
                                 new Loot( typeof( TrollSweat ), 29.0f )
                               , new Loot( typeof( SkullsplitterTusk ), 3.44f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.70f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.70f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.70f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.61f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.59f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.60f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.81f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.58f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.76f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.56f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.74f )
                               , new Loot( typeof( SplitBoneNecklace ), 4.73f )
                               , new Loot( typeof( SilkCloth ), 9.04f )
                               , new Loot( typeof( MageweaveCloth ), 22.4f )
                               , new Loot( typeof( FlaskOfMojo ), 9.28f )
                                 };
   //Creature Id = 667
       public static Loot[] SkullsplitterWarrior = new Loot[] {
                                 new Loot( typeof( TrollSweat ), 29.0f )
                               , new Loot( typeof( SkullsplitterTusk ), 15.7f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.72f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.75f )
                               , new Loot( typeof( SplitBoneNecklace ), 8.72f )
                               , new Loot( typeof( SilkCloth ), 27.8f )
                               , new Loot( typeof( MageweaveCloth ), 4.42f )
                               , new Loot( typeof( FlaskOfMojo ), 9.07f )
                                 };
   //Creature Id = 670
       public static Loot[] SkullsplitterWitchDoctor = new Loot[] {
                                 new Loot( typeof( TrollSweat ), 29.6f )
                               , new Loot( typeof( SkullsplitterTusk ), 8.09f )
                               , new Loot( typeof( SkullsplitterFetish ), 5.06f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.80f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.80f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.61f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.59f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.53f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.75f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.58f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.80f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.99f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.77f )
                               , new Loot( typeof( SplitBoneNecklace ), 7.45f )
                               , new Loot( typeof( BoltOfSilkCloth ), 0.01f )
                               , new Loot( typeof( SilkCloth ), 8.44f )
                               , new Loot( typeof( MageweaveCloth ), 20.4f )
                               , new Loot( typeof( FlaskOfMojo ), 8.75f )
                                 };
  }
}