#!/bin/bash
# Massive Network Game Object Server
# Monitoring Script

pid=`ps ax | awk '($5 ~ /xewow/) { print $1 }'`
cpu=`top b -n 1 -p $pid | awk '($13 ~ /xewow/) { print $9 }'`
#echo $pid
#echo $cpu
intcpu=${cpu%.*}
#echo $intcpu
if [ "$intcpu" -gt "50" ]
then
	kill -9 $pid
	echo "Killed XeWOW for exceeding it's cpu limit."
	echo `date` ", Killed XeWOW for $intcpu% CPU Usage." >> serverlog
else
	echo "XeWOW Passes the cpu test."
fi
