#!/bin/bash
# Massive Network Game Object Server
# autorestart Script

while :
do
	echo "XeNOW daemon restarted"
	echo `date` >> crash.log &
	./xenow | tail -n 20 >> crash.log 
	echo " " >> crash.log &
	pid=`ps ax | awk '($5 ~ /xenow/) { print $1 }'`
	wait $pid
        echo `date` ", XeNOW daemon crashed and restarted." >> serverlog
done
