using System;
using System.Collections;
using Server;
using Server.Items;

namespace Server.Items
{
  public class BloodscalpDrops
  {
   //Creature Id = 694
       public static Loot[] BloodscalpAxeThrower = new Loot[] {
                                 new Loot( typeof( BloodscalpEar ), 11.9f )
                               , new Loot( typeof( TheFirstTrollLegend ), 0.02f )
                               , new Loot( typeof( WoolCloth ), 3.82f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.72f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.66f )
                               , new Loot( typeof( BloodscalpTusk ), 10.7f )
                               , new Loot( typeof( BloodyBoneNecklace ), 13.7f )
                               , new Loot( typeof( SilkCloth ), 28.5f )
                               , new Loot( typeof( MageweaveCloth ), 0.90f )
                                 };
   //Creature Id = 699
       public static Loot[] BloodscalpBeastmaster = new Loot[] {
                                 new Loot( typeof( BloodscalpEar ), 8.10f )
                               , new Loot( typeof( WoolCloth ), 4.16f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.72f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.62f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.61f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.55f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.86f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.71f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.61f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.81f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.74f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.58f )
                               , new Loot( typeof( BloodscalpTusk ), 5.45f )
                               , new Loot( typeof( BloodyBoneNecklace ), 5.82f )
                               , new Loot( typeof( SilkCloth ), 27.9f )
                               , new Loot( typeof( MageweaveCloth ), 0.99f )
                                 };
   //Creature Id = 597
       public static Loot[] BloodscalpBerserker = new Loot[] {
                                 new Loot( typeof( BloodscalpEar ), 4.94f )
                               , new Loot( typeof( HugeStoneClub ), 0.51f )
                               , new Loot( typeof( TheFourthTrollLegend ), 0.04f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.60f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.70f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.62f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.74f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.75f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.63f )
                               , new Loot( typeof( BloodscalpTusk ), 2.92f )
                               , new Loot( typeof( BloodyBoneNecklace ), 4.85f )
                               , new Loot( typeof( SilkCloth ), 28.4f )
                               , new Loot( typeof( MageweaveCloth ), 4.53f )
                                 };
   //Creature Id = 1061
       public static Loot[] Ganzulah = new Loot[] {
                                 new Loot( typeof( TrollSweat ), 6.41f )
                               , new Loot( typeof( SkullsplitterTusk ), 7.14f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.20f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.98f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.31f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.93f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.31f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.51f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.93f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.41f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.56f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.98f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.46f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.41f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.36f )
                               , new Loot( typeof( GanzulahsHead ), 60.7f )
                               , new Loot( typeof( SilkCloth ), 6.67f )
                               , new Loot( typeof( MageweaveCloth ), 18.1f )
                               , new Loot( typeof( TruesilverBar ), 0.05f )
                               , new Loot( typeof( FlaskOfMojo ), 8.43f )
                                 };
   //Creature Id = 1062
       public static Loot[] NezzliokTheDire = new Loot[] {
                                 new Loot( typeof( TrollSweat ), 24.5f )
                               , new Loot( typeof( SkullsplitterTusk ), 7.34f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.42f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.35f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.24f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.32f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.57f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.53f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.60f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.46f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.53f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.78f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.71f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.71f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.74f )
                               , new Loot( typeof( NezzlioksHead ), 51.2f )
                               , new Loot( typeof( SilkCloth ), 22.5f )
                               , new Loot( typeof( MageweaveCloth ), 3.77f )
                               , new Loot( typeof( ZestyClamMeat ), 0.03f )
                               , new Loot( typeof( FlaskOfMojo ), 8.34f )
                                 };
   //Creature Id = 671
          public static Loot[] BloodscalpHeadhunter = new Loot[] {
                                 new Loot( typeof( BloodscalpEar ), 4.54f )
                               , new Loot( typeof( HeadhuntingSpear ), 1.01f )
                               , new Loot( typeof( ShrunkenHead ), 24.3f )
                               , new Loot( typeof( TheFourthTrollLegend ), 0.03f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.61f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.61f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.61f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.65f )
                               , new Loot( typeof( BloodscalpTusk ), 2.64f )
                               , new Loot( typeof( BloodyBoneNecklace ), 5.13f )
                               , new Loot( typeof( SilkCloth ), 27.6f )
                               , new Loot( typeof( MageweaveCloth ), 4.57f )
                                 };
   //Creature Id = 595
       public static Loot[] BloodscalpHunter = new Loot[] {
                                 new Loot( typeof( BloodscalpEar ), 8.27f )
                               , new Loot( typeof( TheThirdTrollLegend ), 0.06f )
                               , new Loot( typeof( WoolCloth ), 3.90f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.60f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.60f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.62f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.60f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.73f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.64f )
                               , new Loot( typeof( BloodscalpTusk ), 6.03f )
                               , new Loot( typeof( BloodyBoneNecklace ), 5.82f )
                               , new Loot( typeof( SilkCloth ), 27.3f )
                               , new Loot( typeof( MageweaveCloth ), 0.97f )
                                 };
   //Creature Id = 701
       public static Loot[] BloodscalpMystic = new Loot[] {
                                 new Loot( typeof( LesserMysticEssence ), 0.06f )
                               , new Loot( typeof( BloodscalpEar ), 9.15f )
                               , new Loot( typeof( PressedFeltRobe ), 0.53f )
                               , new Loot( typeof( TheThirdTrollLegend ), 0.06f )
                               , new Loot( typeof( WoolCloth ), 3.73f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.71f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.71f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.59f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.65f )
                               , new Loot( typeof( BloodscalpTusk ), 5.43f )
                               , new Loot( typeof( BloodyBoneNecklace ), 5.19f )
                               , new Loot( typeof( SilkCloth ), 27.9f )
                               , new Loot( typeof( MageweaveCloth ), 0.92f )
                                 };
   //Creature Id = 702
       public static Loot[] BloodscalpScavenger = new Loot[] {
                                 new Loot( typeof( BloodscalpEar ), 14.0f )
                               , new Loot( typeof( TrollSweat ), 9.99f )
                               , new Loot( typeof( WoolCloth ), 3.78f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.73f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.61f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.71f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.70f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.59f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.62f )
                               , new Loot( typeof( BloodscalpTusk ), 7.77f )
                               , new Loot( typeof( BloodyBoneNecklace ), 8.34f )
                               , new Loot( typeof( SilkCloth ), 28.9f )
                               , new Loot( typeof( MageweaveCloth ), 1.02f )
                                 };
   //Creature Id = 588
       public static Loot[] BloodscalpScout = new Loot[] {
                                 new Loot( typeof( BloodscalpEar ), 8.43f )
                               , new Loot( typeof( TheThirdTrollLegend ), 0.02f )
                               , new Loot( typeof( WoolCloth ), 3.92f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.60f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.57f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.60f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.76f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.70f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.59f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.70f )
                               , new Loot( typeof( BloodscalpTusk ), 6.00f )
                               , new Loot( typeof( BloodyBoneNecklace ), 5.37f )
                               , new Loot( typeof( SilkCloth ), 27.5f )
                               , new Loot( typeof( MageweaveCloth ), 0.93f )
                                 };
   //Creature Id = 697
       public static Loot[] BloodscalpShaman = new Loot[] {
                                 new Loot( typeof( BloodscalpEar ), 12.4f )
                               , new Loot( typeof( TrollSweat ), 9.76f )
                               , new Loot( typeof( BloodscalpChannelingStaff ), 0.43f )
                               , new Loot( typeof( TheFirstTrollLegend ), 0.01f )
                               , new Loot( typeof( WoolCloth ), 3.76f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.60f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.71f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.70f )
                               , new Loot( typeof( BloodscalpTusk ), 10.3f )
                               , new Loot( typeof( BloodyBoneNecklace ), 12.9f )
                               , new Loot( typeof( SilkCloth ), 28.2f )
                               , new Loot( typeof( MageweaveCloth ), 0.91f )
                                 };
/*	please have a look at this
   //Creature Id = 11389
       public static Loot[] BloodscalpSpeaker = new Loot[] {
       						     new Loot( typeof( SkullsplitterCoin ), 3.10f )
       							 };
*/
   //Creature Id = 698
       public static Loot[] BloodscalpTiger = new Loot[] {
                                 new Loot( typeof( TigerMeat ), 5.00f )
                               , new Loot( typeof( BloodscalpEar ), 5.00f )
                               , new Loot( typeof( TheFourthTrollLegend ), 5.00f )
                               , new Loot( typeof( BloodscalpTusk ), 5.00f )
                               , new Loot( typeof( BloodyBoneNecklace ), 5.00f )
                                 };
   //Creature Id = 587
       public static Loot[] BloodscalpWarrior = new Loot[] {
                                 new Loot( typeof( BloodscalpEar ), 12.9f )
                               , new Loot( typeof( TrollSweat ), 9.60f )
                               , new Loot( typeof( TheFirstTrollLegend ), 0.01f )
                               , new Loot( typeof( WoolCloth ), 3.79f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.73f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.65f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.62f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.70f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.63f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.73f )
                               , new Loot( typeof( BloodscalpTusk ), 10.1f )
                               , new Loot( typeof( BloodyBoneNecklace ), 12.9f )
                               , new Loot( typeof( SilkCloth ), 28.5f )
                               , new Loot( typeof( MageweaveCloth ), 0.92f )
                                 };
   //Creature Id = 660
       public static Loot[] BloodscalpWitchDoctor = new Loot[] {
                                 new Loot( typeof( BloodscalpEar ), 4.43f )
                               , new Loot( typeof( VoodooBand ), 0.56f )
                               , new Loot( typeof( TheFourthTrollLegend ), 0.04f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage1 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage4 ), 0.69f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage6 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage8 ), 0.68f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage10 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage11 ), 0.66f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage14 ), 0.72f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage16 ), 0.72f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage18 ), 0.64f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage20 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage21 ), 0.73f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage24 ), 0.73f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage25 ), 0.73f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage26 ), 0.67f )
                               , new Loot( typeof( GreenHillsOfStranglethornPage27 ), 0.67f )
                               , new Loot( typeof( BloodscalpTusk ), 2.66f )
                               , new Loot( typeof( BloodyBoneNecklace ), 5.03f )
                               , new Loot( typeof( SilkCloth ), 27.9f )
                               , new Loot( typeof( MageweaveCloth ), 4.55f )
                                 };
  }
}